export const SECURITY = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC',
}

export const TOPOLOGY = {
  DEFAULT: 'TOPOLOGY_DEFAULT',
  OVERVIEW: 'TOPOLOGY_OVERVIEW',
  VIEWER: 'TOPOLOGY_VIEWER',
  STATISTIC: 'TOPOLOGY_STATISTIC',
  USER_TASK: 'TOPOLOGY_USER_TASK',
  USER_TASK_DETAIL: 'TOPOLOGY_USER_TASK_DETAIL',
  LOGS: 'TOPOLOGY_LOGS',
}

export const APP_STORE = {
  DEFAULT: 'APP-STORE',
  AVAILABLE_APPS: 'AVAILABLE-APPS',
  INSTALLED_APPS: 'INSTALLED-APPS',
  INSTALLED_APP: 'INSTALLED_APP',
  DETAIL_APP: 'DETAIL_APP',
}

export const ROUTES = {
  HEALTH_CHECK: 'HEALTH_CHECK',
  DASHBOARD: 'DASHBOARD',
  USERS: 'USERS',
  TRASH: 'TRASH',
  TRASH_DETAIL: 'TRASH_DETAIL',
  LOGS: 'LOGS',
  NOTIFICATION: 'NOTIFICATION',
  EDITOR: 'EDITOR',
  USER_TASK: 'USER_TASK',
  SCHEDULED_TASK: 'SCHEDULED_TASK',
  IMPLEMENTATION: 'IMPLEMENTATION',
  USER_PROFILE: 'USER_PROFILE',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SENT: 'FORGOT_PASSWORD_SENT',
  RESTORE_PASSWORD: 'RESTORE_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  NOT_FOUND: 'NOT_FOUND',
  TOPOLOGY,
  APP_STORE,
}
