version: '2'

services:

    # Services
    cm-api:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
          - ${HOME}/.composer:/srv/.composer
        depends_on:
          - mongo
          - rabbitmq

    # Nginx
    nginx:
        image: nginx
        ports:
          - ${DEV_IP}:8000:8000
        volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./:/srv/project
        depends_on:
          - cm-api

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - ${DEV_IP}:15672:15672
        volumes:
          - rabbit-mq:/var/lib/rabbitmq

    # Storage
    mongo:
        image: mongo:3.4
        ports:
          - ${DEV_IP}:27017:27017
        volumes:
          - mongo:/data/db

    # Redis
    redis:
        image: redis:3.2-alpine
        ports:
          - ${DEV_IP}:6379:6379
        volumes:
          - redis:/data

    # Influx DB
    influxdb:
        image: influxdb:1.2-alpine
        ports:
        - ${DEV_IP}:8083:8083
        - ${DEV_IP}:8086:8086
        - ${DEV_IP}:8089:8089/udp
        volumes:
        - influxdb:/var/lib/influxdb
        - ./docker/influx/influxdb.conf:/etc/influxdb/influxdb.conf

volumes:
  mongo: {}
  redis: {}
  rabbit-mq: {}
  influxdb: {}