// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WorkflowService.proto

/*
Package workflowservice is a generated protocol buffer package.

It is generated from these files:
	WorkflowService.proto

It has these top-level messages:
	CreateRequest
	UpdateRequest
	DeleteRequest
	ReadRequest
	WorkflowResponse
	EditorConfig
	WorkflowConfig
*/
package workflowservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkflowConfig_Step_Recommendation_Type int32

const (
	WorkflowConfig_Step_Recommendation_STANDARD WorkflowConfig_Step_Recommendation_Type = 0
	WorkflowConfig_Step_Recommendation_CUSTOM   WorkflowConfig_Step_Recommendation_Type = 1
)

var WorkflowConfig_Step_Recommendation_Type_name = map[int32]string{
	0: "STANDARD",
	1: "CUSTOM",
}
var WorkflowConfig_Step_Recommendation_Type_value = map[string]int32{
	"STANDARD": 0,
	"CUSTOM":   1,
}

func (x WorkflowConfig_Step_Recommendation_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_Recommendation_Type_name, int32(x))
}
func (WorkflowConfig_Step_Recommendation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 0, 0}
}

type WorkflowConfig_Step_Segmentation_Type int32

const (
	WorkflowConfig_Step_Segmentation_BUSINESS WorkflowConfig_Step_Segmentation_Type = 0
	WorkflowConfig_Step_Segmentation_GRAPHICS WorkflowConfig_Step_Segmentation_Type = 1
	WorkflowConfig_Step_Segmentation_BOTH     WorkflowConfig_Step_Segmentation_Type = 2
)

var WorkflowConfig_Step_Segmentation_Type_name = map[int32]string{
	0: "BUSINESS",
	1: "GRAPHICS",
	2: "BOTH",
}
var WorkflowConfig_Step_Segmentation_Type_value = map[string]int32{
	"BUSINESS": 0,
	"GRAPHICS": 1,
	"BOTH":     2,
}

func (x WorkflowConfig_Step_Segmentation_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_Segmentation_Type_name, int32(x))
}
func (WorkflowConfig_Step_Segmentation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 1, 0}
}

type WorkflowConfig_Step_ChannelMap_Schedule int32

const (
	WorkflowConfig_Step_ChannelMap_NOW     WorkflowConfig_Step_ChannelMap_Schedule = 0
	WorkflowConfig_Step_ChannelMap_DELAYED WorkflowConfig_Step_ChannelMap_Schedule = 1
)

var WorkflowConfig_Step_ChannelMap_Schedule_name = map[int32]string{
	0: "NOW",
	1: "DELAYED",
}
var WorkflowConfig_Step_ChannelMap_Schedule_value = map[string]int32{
	"NOW":     0,
	"DELAYED": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Schedule) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Schedule_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Schedule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 0}
}

type WorkflowConfig_Step_ChannelMap_Action_Family int32

const (
	WorkflowConfig_Step_ChannelMap_Action_TAG  WorkflowConfig_Step_ChannelMap_Action_Family = 0
	WorkflowConfig_Step_ChannelMap_Action_LIST WorkflowConfig_Step_ChannelMap_Action_Family = 1
)

var WorkflowConfig_Step_ChannelMap_Action_Family_name = map[int32]string{
	0: "TAG",
	1: "LIST",
}
var WorkflowConfig_Step_ChannelMap_Action_Family_value = map[string]int32{
	"TAG":  0,
	"LIST": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Family) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Family_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Family) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 1, 0}
}

type WorkflowConfig_Step_ChannelMap_Action_Type int32

const (
	WorkflowConfig_Step_ChannelMap_Action_ADD    WorkflowConfig_Step_ChannelMap_Action_Type = 0
	WorkflowConfig_Step_ChannelMap_Action_REMOVE WorkflowConfig_Step_ChannelMap_Action_Type = 1
	WorkflowConfig_Step_ChannelMap_Action_CHECK  WorkflowConfig_Step_ChannelMap_Action_Type = 2
	WorkflowConfig_Step_ChannelMap_Action_UPDATE WorkflowConfig_Step_ChannelMap_Action_Type = 3
)

var WorkflowConfig_Step_ChannelMap_Action_Type_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
	2: "CHECK",
	3: "UPDATE",
}
var WorkflowConfig_Step_ChannelMap_Action_Type_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
	"CHECK":  2,
	"UPDATE": 3,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Type_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 1, 1}
}

type WorkflowConfig_Step_ChannelMap_Action_Time int32

const (
	WorkflowConfig_Step_ChannelMap_Action_NOW     WorkflowConfig_Step_ChannelMap_Action_Time = 0
	WorkflowConfig_Step_ChannelMap_Action_TRIGGER WorkflowConfig_Step_ChannelMap_Action_Time = 1
)

var WorkflowConfig_Step_ChannelMap_Action_Time_name = map[int32]string{
	0: "NOW",
	1: "TRIGGER",
}
var WorkflowConfig_Step_ChannelMap_Action_Time_value = map[string]int32{
	"NOW":     0,
	"TRIGGER": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Time) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Time_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Time) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 1, 2}
}

type WorkflowConfig_Step_ChannelMap_Action_Trigger int32

const (
	WorkflowConfig_Step_ChannelMap_Action_EMPTY     WorkflowConfig_Step_ChannelMap_Action_Trigger = 0
	WorkflowConfig_Step_ChannelMap_Action_CONDITION WorkflowConfig_Step_ChannelMap_Action_Trigger = 1
)

var WorkflowConfig_Step_ChannelMap_Action_Trigger_name = map[int32]string{
	0: "EMPTY",
	1: "CONDITION",
}
var WorkflowConfig_Step_ChannelMap_Action_Trigger_value = map[string]int32{
	"EMPTY":     0,
	"CONDITION": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Trigger) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Trigger_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Trigger) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 1, 3}
}

type CreateRequest struct {
	Json string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type UpdateRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Json string `protobuf:"bytes,2,opt,name=json" json:"json,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WorkflowResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Json    string `protobuf:"bytes,4,opt,name=json" json:"json,omitempty"`
}

func (m *WorkflowResponse) Reset()                    { *m = WorkflowResponse{} }
func (m *WorkflowResponse) String() string            { return proto.CompactTextString(m) }
func (*WorkflowResponse) ProtoMessage()               {}
func (*WorkflowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WorkflowResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkflowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WorkflowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type EditorConfig struct {
	Id       string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ParentId string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Type     string                 `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Settings *EditorConfig_Settings `protobuf:"bytes,4,opt,name=settings" json:"settings,omitempty"`
}

func (m *EditorConfig) Reset()                    { *m = EditorConfig{} }
func (m *EditorConfig) String() string            { return proto.CompactTextString(m) }
func (*EditorConfig) ProtoMessage()               {}
func (*EditorConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EditorConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditorConfig) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *EditorConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EditorConfig) GetSettings() *EditorConfig_Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type EditorConfig_Settings struct {
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Wait     string `protobuf:"bytes,2,opt,name=wait" json:"wait,omitempty"`
	Unit     string `protobuf:"bytes,3,opt,name=unit" json:"unit,omitempty"`
}

func (m *EditorConfig_Settings) Reset()                    { *m = EditorConfig_Settings{} }
func (m *EditorConfig_Settings) String() string            { return proto.CompactTextString(m) }
func (*EditorConfig_Settings) ProtoMessage()               {}
func (*EditorConfig_Settings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *EditorConfig_Settings) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *EditorConfig_Settings) GetWait() string {
	if m != nil {
		return m.Wait
	}
	return ""
}

func (m *EditorConfig_Settings) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type WorkflowConfig struct {
	Id           string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientDomain string                 `protobuf:"bytes,2,opt,name=client_domain,json=clientDomain" json:"client_domain,omitempty"`
	Type         string                 `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ClientId     int32                  `protobuf:"varint,4,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientGuid   string                 `protobuf:"bytes,5,opt,name=client_guid,json=clientGuid" json:"client_guid,omitempty"`
	Filter       *WorkflowConfig_Filter `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	Steps        []*WorkflowConfig_Step `protobuf:"bytes,7,rep,name=steps" json:"steps,omitempty"`
}

func (m *WorkflowConfig) Reset()                    { *m = WorkflowConfig{} }
func (m *WorkflowConfig) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig) ProtoMessage()               {}
func (*WorkflowConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WorkflowConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowConfig) GetClientDomain() string {
	if m != nil {
		return m.ClientDomain
	}
	return ""
}

func (m *WorkflowConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WorkflowConfig) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *WorkflowConfig) GetClientGuid() string {
	if m != nil {
		return m.ClientGuid
	}
	return ""
}

func (m *WorkflowConfig) GetFilter() *WorkflowConfig_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *WorkflowConfig) GetSteps() []*WorkflowConfig_Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type WorkflowConfig_Filter struct {
	InSegment         []string `protobuf:"bytes,1,rep,name=in_segment,json=inSegment" json:"in_segment,omitempty"`
	NotInSegment      []string `protobuf:"bytes,2,rep,name=not_in_segment,json=notInSegment" json:"not_in_segment,omitempty"`
	InTag             []string `protobuf:"bytes,3,rep,name=in_tag,json=inTag" json:"in_tag,omitempty"`
	NotInTag          []string `protobuf:"bytes,4,rep,name=not_in_tag,json=notInTag" json:"not_in_tag,omitempty"`
	Priority          int32    `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
	FilteringVariable string   `protobuf:"bytes,6,opt,name=filtering_variable,json=filteringVariable" json:"filtering_variable,omitempty"`
}

func (m *WorkflowConfig_Filter) Reset()                    { *m = WorkflowConfig_Filter{} }
func (m *WorkflowConfig_Filter) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Filter) ProtoMessage()               {}
func (*WorkflowConfig_Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *WorkflowConfig_Filter) GetInSegment() []string {
	if m != nil {
		return m.InSegment
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetNotInSegment() []string {
	if m != nil {
		return m.NotInSegment
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetInTag() []string {
	if m != nil {
		return m.InTag
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetNotInTag() []string {
	if m != nil {
		return m.NotInTag
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *WorkflowConfig_Filter) GetFilteringVariable() string {
	if m != nil {
		return m.FilteringVariable
	}
	return ""
}

type WorkflowConfig_Step struct {
	Condition      string                              `protobuf:"bytes,1,opt,name=condition" json:"condition,omitempty"`
	Recommendation *WorkflowConfig_Step_Recommendation `protobuf:"bytes,2,opt,name=recommendation" json:"recommendation,omitempty"`
	Segmentation   *WorkflowConfig_Step_Segmentation   `protobuf:"bytes,3,opt,name=segmentation" json:"segmentation,omitempty"`
	Channels       *WorkflowConfig_Step_ChannelMap     `protobuf:"bytes,4,opt,name=channels" json:"channels,omitempty"`
	NextFlow       *WorkflowConfig_Step_NextFlow       `protobuf:"bytes,5,opt,name=next_flow,json=nextFlow" json:"next_flow,omitempty"`
}

func (m *WorkflowConfig_Step) Reset()                    { *m = WorkflowConfig_Step{} }
func (m *WorkflowConfig_Step) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step) ProtoMessage()               {}
func (*WorkflowConfig_Step) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

func (m *WorkflowConfig_Step) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *WorkflowConfig_Step) GetRecommendation() *WorkflowConfig_Step_Recommendation {
	if m != nil {
		return m.Recommendation
	}
	return nil
}

func (m *WorkflowConfig_Step) GetSegmentation() *WorkflowConfig_Step_Segmentation {
	if m != nil {
		return m.Segmentation
	}
	return nil
}

func (m *WorkflowConfig_Step) GetChannels() *WorkflowConfig_Step_ChannelMap {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *WorkflowConfig_Step) GetNextFlow() *WorkflowConfig_Step_NextFlow {
	if m != nil {
		return m.NextFlow
	}
	return nil
}

type WorkflowConfig_Step_Recommendation struct {
	RecommendationType WorkflowConfig_Step_Recommendation_Type `protobuf:"varint,1,opt,name=recommendation_type,json=recommendationType,enum=workflowservice.WorkflowConfig_Step_Recommendation_Type" json:"recommendation_type,omitempty"`
}

func (m *WorkflowConfig_Step_Recommendation) Reset()         { *m = WorkflowConfig_Step_Recommendation{} }
func (m *WorkflowConfig_Step_Recommendation) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Recommendation) ProtoMessage()    {}
func (*WorkflowConfig_Step_Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 0}
}

func (m *WorkflowConfig_Step_Recommendation) GetRecommendationType() WorkflowConfig_Step_Recommendation_Type {
	if m != nil {
		return m.RecommendationType
	}
	return WorkflowConfig_Step_Recommendation_STANDARD
}

type WorkflowConfig_Step_Segmentation struct {
	SegmentationType WorkflowConfig_Step_Segmentation_Type `protobuf:"varint,1,opt,name=segmentation_type,json=segmentationType,enum=workflowservice.WorkflowConfig_Step_Segmentation_Type" json:"segmentation_type,omitempty"`
}

func (m *WorkflowConfig_Step_Segmentation) Reset()         { *m = WorkflowConfig_Step_Segmentation{} }
func (m *WorkflowConfig_Step_Segmentation) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Segmentation) ProtoMessage()    {}
func (*WorkflowConfig_Step_Segmentation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 1}
}

func (m *WorkflowConfig_Step_Segmentation) GetSegmentationType() WorkflowConfig_Step_Segmentation_Type {
	if m != nil {
		return m.SegmentationType
	}
	return WorkflowConfig_Step_Segmentation_BUSINESS
}

type WorkflowConfig_Step_ChannelMap struct {
	Email   *WorkflowConfig_Step_ChannelMap_Email    `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Actions []*WorkflowConfig_Step_ChannelMap_Action `protobuf:"bytes,2,rep,name=actions" json:"actions,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap) Reset()         { *m = WorkflowConfig_Step_ChannelMap{} }
func (m *WorkflowConfig_Step_ChannelMap) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2}
}

func (m *WorkflowConfig_Step_ChannelMap) GetEmail() *WorkflowConfig_Step_ChannelMap_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *WorkflowConfig_Step_ChannelMap) GetActions() []*WorkflowConfig_Step_ChannelMap_Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type WorkflowConfig_Step_ChannelMap_Email struct {
	Template      string                                  `protobuf:"bytes,1,opt,name=template" json:"template,omitempty"`
	DynamicFields string                                  `protobuf:"bytes,2,opt,name=dynamic_fields,json=dynamicFields" json:"dynamic_fields,omitempty"`
	SendTime      WorkflowConfig_Step_ChannelMap_Schedule `protobuf:"varint,3,opt,name=send_time,json=sendTime,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Schedule" json:"send_time,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Email) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Email{} }
func (m *WorkflowConfig_Step_ChannelMap_Email) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Email) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 0}
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetDynamicFields() string {
	if m != nil {
		return m.DynamicFields
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSendTime() WorkflowConfig_Step_ChannelMap_Schedule {
	if m != nil {
		return m.SendTime
	}
	return WorkflowConfig_Step_ChannelMap_NOW
}

type WorkflowConfig_Step_ChannelMap_Action struct {
	ActionFamily  WorkflowConfig_Step_ChannelMap_Action_Family  `protobuf:"varint,1,opt,name=action_family,json=actionFamily,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Family" json:"action_family,omitempty"`
	ActionType    WorkflowConfig_Step_ChannelMap_Action_Type    `protobuf:"varint,2,opt,name=action_type,json=actionType,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Type" json:"action_type,omitempty"`
	ActionTime    WorkflowConfig_Step_ChannelMap_Action_Time    `protobuf:"varint,3,opt,name=action_time,json=actionTime,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Time" json:"action_time,omitempty"`
	ActionTrigger WorkflowConfig_Step_ChannelMap_Action_Trigger `protobuf:"varint,4,opt,name=action_trigger,json=actionTrigger,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Trigger" json:"action_trigger,omitempty"`
	ActionSubject string                                        `protobuf:"bytes,5,opt,name=action_subject,json=actionSubject" json:"action_subject,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Action) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Action{} }
func (m *WorkflowConfig_Step_ChannelMap_Action) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Action) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Action) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 2, 1}
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionFamily() WorkflowConfig_Step_ChannelMap_Action_Family {
	if m != nil {
		return m.ActionFamily
	}
	return WorkflowConfig_Step_ChannelMap_Action_TAG
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionType() WorkflowConfig_Step_ChannelMap_Action_Type {
	if m != nil {
		return m.ActionType
	}
	return WorkflowConfig_Step_ChannelMap_Action_ADD
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionTime() WorkflowConfig_Step_ChannelMap_Action_Time {
	if m != nil {
		return m.ActionTime
	}
	return WorkflowConfig_Step_ChannelMap_Action_NOW
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionTrigger() WorkflowConfig_Step_ChannelMap_Action_Trigger {
	if m != nil {
		return m.ActionTrigger
	}
	return WorkflowConfig_Step_ChannelMap_Action_EMPTY
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionSubject() string {
	if m != nil {
		return m.ActionSubject
	}
	return ""
}

type WorkflowConfig_Step_NextFlow struct {
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *WorkflowConfig_Step_NextFlow) Reset()         { *m = WorkflowConfig_Step_NextFlow{} }
func (m *WorkflowConfig_Step_NextFlow) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_NextFlow) ProtoMessage()    {}
func (*WorkflowConfig_Step_NextFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 3}
}

func (m *WorkflowConfig_Step_NextFlow) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "workflowservice.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "workflowservice.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "workflowservice.DeleteRequest")
	proto.RegisterType((*ReadRequest)(nil), "workflowservice.ReadRequest")
	proto.RegisterType((*WorkflowResponse)(nil), "workflowservice.WorkflowResponse")
	proto.RegisterType((*EditorConfig)(nil), "workflowservice.EditorConfig")
	proto.RegisterType((*EditorConfig_Settings)(nil), "workflowservice.EditorConfig.Settings")
	proto.RegisterType((*WorkflowConfig)(nil), "workflowservice.WorkflowConfig")
	proto.RegisterType((*WorkflowConfig_Filter)(nil), "workflowservice.WorkflowConfig.Filter")
	proto.RegisterType((*WorkflowConfig_Step)(nil), "workflowservice.WorkflowConfig.Step")
	proto.RegisterType((*WorkflowConfig_Step_Recommendation)(nil), "workflowservice.WorkflowConfig.Step.Recommendation")
	proto.RegisterType((*WorkflowConfig_Step_Segmentation)(nil), "workflowservice.WorkflowConfig.Step.Segmentation")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Email)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Email")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Action)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Action")
	proto.RegisterType((*WorkflowConfig_Step_NextFlow)(nil), "workflowservice.WorkflowConfig.Step.NextFlow")
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_Recommendation_Type", WorkflowConfig_Step_Recommendation_Type_name, WorkflowConfig_Step_Recommendation_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_Segmentation_Type", WorkflowConfig_Step_Segmentation_Type_name, WorkflowConfig_Step_Segmentation_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Schedule", WorkflowConfig_Step_ChannelMap_Schedule_name, WorkflowConfig_Step_ChannelMap_Schedule_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Family", WorkflowConfig_Step_ChannelMap_Action_Family_name, WorkflowConfig_Step_ChannelMap_Action_Family_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Type", WorkflowConfig_Step_ChannelMap_Action_Type_name, WorkflowConfig_Step_ChannelMap_Action_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Time", WorkflowConfig_Step_ChannelMap_Action_Time_name, WorkflowConfig_Step_ChannelMap_Action_Time_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Trigger", WorkflowConfig_Step_ChannelMap_Action_Trigger_name, WorkflowConfig_Step_ChannelMap_Action_Trigger_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorkflowService service

type WorkflowServiceClient interface {
	CreateWorkflow(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	UpdateWorkflow(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	DeleteWorkflow(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ReadWorkflow(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ReadConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowConfig, error)
}

type workflowServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowServiceClient(cc *grpc.ClientConn) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) CreateWorkflow(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/CreateWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UpdateWorkflow(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/UpdateWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeleteWorkflow(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/DeleteWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadWorkflow(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/ReadWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowConfig, error) {
	out := new(WorkflowConfig)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/ReadConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkflowService service

type WorkflowServiceServer interface {
	CreateWorkflow(context.Context, *CreateRequest) (*WorkflowResponse, error)
	UpdateWorkflow(context.Context, *UpdateRequest) (*WorkflowResponse, error)
	DeleteWorkflow(context.Context, *DeleteRequest) (*WorkflowResponse, error)
	ReadWorkflow(context.Context, *ReadRequest) (*WorkflowResponse, error)
	ReadConfig(context.Context, *ReadRequest) (*WorkflowConfig, error)
}

func RegisterWorkflowServiceServer(s *grpc.Server, srv WorkflowServiceServer) {
	s.RegisterService(&_WorkflowService_serviceDesc, srv)
}

func _WorkflowService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/CreateWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UpdateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UpdateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/UpdateWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UpdateWorkflow(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/DeleteWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeleteWorkflow(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReadWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/ReadWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReadWorkflow(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/ReadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReadConfig(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workflowservice.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowService_CreateWorkflow_Handler,
		},
		{
			MethodName: "UpdateWorkflow",
			Handler:    _WorkflowService_UpdateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _WorkflowService_DeleteWorkflow_Handler,
		},
		{
			MethodName: "ReadWorkflow",
			Handler:    _WorkflowService_ReadWorkflow_Handler,
		},
		{
			MethodName: "ReadConfig",
			Handler:    _WorkflowService_ReadConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "WorkflowService.proto",
}

func init() { proto.RegisterFile("WorkflowService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xfa, 0x77, 0xf7, 0xf8, 0xa7, 0xdb, 0x41, 0x95, 0x2c, 0x37, 0xa5, 0xc1, 0x2d, 0xa8,
	0x17, 0xd4, 0x08, 0x57, 0x20, 0x04, 0xa2, 0x92, 0x6b, 0x3b, 0x89, 0x49, 0x63, 0x47, 0xb3, 0xeb,
	0x56, 0x15, 0x48, 0xd6, 0x66, 0x77, 0xe2, 0x4e, 0xf1, 0xce, 0x9a, 0xdd, 0x71, 0xd3, 0xbc, 0x06,
	0xf7, 0x5c, 0xf0, 0x02, 0x3c, 0x02, 0x0f, 0x80, 0xc4, 0x5b, 0xf0, 0x10, 0x5c, 0xa2, 0xf9, 0x59,
	0x67, 0x9d, 0x90, 0xd4, 0xcd, 0x95, 0x67, 0xce, 0x9c, 0xef, 0x3b, 0xe7, 0x7c, 0xf3, 0xb3, 0xc7,
	0x70, 0xe7, 0x65, 0x14, 0xff, 0x7c, 0x32, 0x8f, 0x4e, 0x1d, 0x12, 0xbf, 0xa5, 0x3e, 0x69, 0x2f,
	0xe2, 0x88, 0x47, 0xe8, 0xd6, 0xa9, 0x36, 0x27, 0xca, 0xdc, 0x7a, 0x00, 0xb5, 0x5e, 0x4c, 0x3c,
	0x4e, 0x30, 0xf9, 0x65, 0x49, 0x12, 0x8e, 0x10, 0x14, 0xde, 0x24, 0x11, 0x6b, 0x18, 0x3b, 0xc6,
	0x23, 0x0b, 0xcb, 0x71, 0xeb, 0x09, 0xd4, 0x26, 0x8b, 0x20, 0xe3, 0x54, 0x87, 0x1c, 0x0d, 0xb4,
	0x4b, 0x8e, 0x06, 0x2b, 0x50, 0x2e, 0x03, 0xba, 0x0f, 0xb5, 0x3e, 0x99, 0x93, 0x2b, 0x41, 0xad,
	0x7b, 0x50, 0xc1, 0xc4, 0x0b, 0xae, 0x5a, 0x0e, 0xc0, 0x4e, 0x6b, 0xc0, 0x24, 0x59, 0x44, 0x2c,
	0x21, 0x22, 0x8e, 0x1f, 0x05, 0x44, 0x7a, 0x15, 0xb1, 0x1c, 0xa3, 0x06, 0x94, 0x43, 0x92, 0x24,
	0xde, 0x8c, 0xe8, 0xf0, 0xe9, 0x54, 0x33, 0xe6, 0x2f, 0x65, 0x59, 0xc8, 0x64, 0xf9, 0x8f, 0x01,
	0xd5, 0x41, 0x40, 0x79, 0x14, 0xf7, 0x22, 0x76, 0x42, 0x67, 0x97, 0x4a, 0xbb, 0x0b, 0xd6, 0xc2,
	0x8b, 0x09, 0xe3, 0x53, 0x1a, 0xe8, 0x00, 0xa6, 0x32, 0x0c, 0x25, 0x23, 0x3f, 0x5b, 0x10, 0x1d,
	0x43, 0x8e, 0xd1, 0x33, 0x30, 0x13, 0xc2, 0x39, 0x65, 0xb3, 0x44, 0x46, 0xaa, 0x74, 0x3e, 0x6b,
	0x5f, 0x50, 0xbd, 0x9d, 0x8d, 0xd8, 0x76, 0xb4, 0x37, 0x5e, 0xe1, 0x9a, 0x63, 0x30, 0x53, 0xab,
	0x48, 0x20, 0x89, 0x96, 0xb1, 0x4f, 0xa6, 0xab, 0xbc, 0x4c, 0x65, 0x50, 0x09, 0x9c, 0x7a, 0x94,
	0xa7, 0xc2, 0x8b, 0xb1, 0xb0, 0x2d, 0x19, 0xe5, 0x69, 0x52, 0x62, 0xdc, 0xfa, 0xd7, 0x86, 0x7a,
	0xaa, 0xe6, 0x15, 0x85, 0x3e, 0x80, 0x9a, 0x3f, 0xa7, 0xa2, 0xd0, 0x20, 0x0a, 0x3d, 0x9a, 0x6e,
	0x66, 0x55, 0x19, 0xfb, 0xd2, 0xf6, 0xbf, 0x05, 0xdf, 0x05, 0x4b, 0x03, 0x69, 0x20, 0x2b, 0x2e,
	0x62, 0x53, 0x19, 0x86, 0x01, 0xba, 0x0f, 0x15, 0xbd, 0x38, 0x5b, 0xd2, 0xa0, 0x51, 0x94, 0x38,
	0x50, 0xa6, 0xbd, 0x25, 0x0d, 0xd0, 0x53, 0x28, 0x9d, 0xd0, 0x39, 0x27, 0x71, 0xa3, 0x74, 0x85,
	0x58, 0xeb, 0x79, 0xb7, 0x77, 0xa5, 0x37, 0xd6, 0x28, 0xf4, 0x2d, 0x14, 0x13, 0x4e, 0x16, 0x49,
	0xa3, 0xbc, 0x93, 0x7f, 0x54, 0xe9, 0x3c, 0x7c, 0x1f, 0xdc, 0xe1, 0x64, 0x81, 0x15, 0xa4, 0xf9,
	0xb7, 0x01, 0x25, 0x45, 0x87, 0xee, 0x01, 0x50, 0x36, 0x4d, 0xc8, 0x2c, 0x24, 0x8c, 0x37, 0x8c,
	0x9d, 0xfc, 0x23, 0x0b, 0x5b, 0x94, 0x39, 0xca, 0x80, 0x1e, 0x42, 0x9d, 0x45, 0x7c, 0x9a, 0x71,
	0xc9, 0x49, 0x97, 0x2a, 0x8b, 0xf8, 0x70, 0xe5, 0x75, 0x07, 0x4a, 0x94, 0x4d, 0xb9, 0x37, 0x6b,
	0xe4, 0xe5, 0x6a, 0x91, 0x32, 0xd7, 0x9b, 0xa1, 0x6d, 0x00, 0x0d, 0x16, 0x4b, 0x05, 0xb9, 0x64,
	0x4a, 0xa0, 0x58, 0x6d, 0x82, 0xb9, 0x88, 0x69, 0x14, 0x53, 0x7e, 0x26, 0xe5, 0x29, 0xe2, 0xd5,
	0x1c, 0x3d, 0x06, 0xa4, 0xca, 0xa4, 0x6c, 0x36, 0x7d, 0xeb, 0xc5, 0xd4, 0x3b, 0x9e, 0x13, 0x29,
	0x94, 0x85, 0x6f, 0xaf, 0x56, 0x5e, 0xe8, 0x85, 0xe6, 0xaf, 0x35, 0x28, 0x88, 0xfa, 0xd0, 0x36,
	0x58, 0x7e, 0xc4, 0x02, 0xca, 0xe9, 0xea, 0x26, 0x9f, 0x1b, 0xd0, 0x8f, 0x50, 0x8f, 0x89, 0x1f,
	0x85, 0x21, 0x61, 0x81, 0x27, 0x5d, 0x72, 0x52, 0xfa, 0x27, 0x9b, 0x68, 0xd7, 0xc6, 0x6b, 0x50,
	0x7c, 0x81, 0x0a, 0x4d, 0xa0, 0xaa, 0x25, 0x52, 0xd4, 0x79, 0x49, 0xfd, 0xe5, 0x46, 0xd4, 0x4e,
	0x06, 0x88, 0xd7, 0x68, 0xd0, 0x01, 0x98, 0xfe, 0x6b, 0x8f, 0x31, 0x32, 0x4f, 0x6f, 0xd5, 0x17,
	0x1b, 0x51, 0xf6, 0x14, 0xe8, 0xd0, 0x5b, 0xe0, 0x15, 0x01, 0xfa, 0x01, 0x2c, 0x46, 0xde, 0xf1,
	0xa9, 0x70, 0x96, 0x9a, 0x57, 0x3a, 0x8f, 0x37, 0x62, 0x1b, 0x91, 0x77, 0x7c, 0x57, 0x3c, 0x48,
	0x26, 0xd3, 0xa3, 0xe6, 0x6f, 0x06, 0xd4, 0xd7, 0x25, 0x41, 0x14, 0x3e, 0x5a, 0x17, 0x65, 0x2a,
	0xef, 0x8c, 0xd8, 0x87, 0x7a, 0xe7, 0x9b, 0x1b, 0x88, 0xdc, 0x76, 0xcf, 0x16, 0x04, 0xa3, 0x75,
	0x52, 0x61, 0x6b, 0xed, 0x40, 0x41, 0xfc, 0xa2, 0x2a, 0x98, 0x8e, 0xdb, 0x1d, 0xf5, 0xbb, 0xb8,
	0x6f, 0x6f, 0x21, 0x80, 0x52, 0x6f, 0xe2, 0xb8, 0xe3, 0x43, 0xdb, 0x68, 0xfe, 0x6e, 0x40, 0x35,
	0xab, 0x2b, 0xf2, 0xe1, 0x76, 0x56, 0xd9, 0x6c, 0x6e, 0x5f, 0x7f, 0xf0, 0x2e, 0xa9, 0xcc, 0xec,
	0x2c, 0xa1, 0xcc, 0xeb, 0xf3, 0xf3, 0xbc, 0x9e, 0x4d, 0x9c, 0xe1, 0x68, 0xe0, 0x38, 0xf6, 0x96,
	0x98, 0xed, 0xe1, 0xee, 0xd1, 0xfe, 0xb0, 0xe7, 0xd8, 0x06, 0x32, 0xa1, 0xf0, 0x6c, 0xec, 0xee,
	0xdb, 0xb9, 0xe6, 0x9f, 0x65, 0x80, 0xf3, 0x8d, 0x42, 0x07, 0x50, 0x24, 0xa1, 0x47, 0xe7, 0x32,
	0xab, 0x4a, 0xe7, 0xab, 0x0f, 0xdc, 0xe8, 0xf6, 0x40, 0x80, 0xb1, 0xe2, 0x40, 0x47, 0x50, 0xf6,
	0x7c, 0x91, 0x57, 0x22, 0xaf, 0x6c, 0x65, 0xc3, 0x22, 0x33, 0x74, 0x5d, 0x09, 0xc7, 0x29, 0x8d,
	0x50, 0xb4, 0x28, 0x43, 0x88, 0xab, 0xcb, 0x49, 0xb8, 0x98, 0x7b, 0x9c, 0xa4, 0x2f, 0x73, 0x3a,
	0x47, 0x9f, 0x42, 0x3d, 0x38, 0x63, 0x5e, 0x48, 0xfd, 0xe9, 0x09, 0x25, 0xf3, 0x20, 0xd1, 0xef,
	0x69, 0x4d, 0x5b, 0x77, 0xa5, 0x11, 0x4d, 0xc0, 0x4a, 0x08, 0x0b, 0xa6, 0x9c, 0x86, 0xea, 0x55,
	0xdd, 0xf4, 0x84, 0x64, 0x12, 0x74, 0xfc, 0xd7, 0x24, 0x58, 0xce, 0x89, 0xf8, 0x80, 0xb0, 0xc0,
	0xa5, 0x21, 0x69, 0xfe, 0x55, 0x80, 0x92, 0xca, 0x1b, 0x1d, 0x43, 0x4d, 0x65, 0x3e, 0x3d, 0xf1,
	0x42, 0x3a, 0x3f, 0xd3, 0x7b, 0xfd, 0xfd, 0xcd, 0x64, 0x68, 0xef, 0x4a, 0x12, 0x5c, 0x55, 0x9c,
	0x6a, 0x86, 0x7e, 0x82, 0x8a, 0x8e, 0x21, 0x4f, 0x53, 0x4e, 0x46, 0xf8, 0xee, 0x86, 0x11, 0xe4,
	0x91, 0x02, 0xc5, 0x27, 0x0f, 0x51, 0x86, 0xfd, 0x5c, 0xa5, 0x1b, 0xb3, 0xd3, 0xf0, 0x9c, 0x9d,
	0x86, 0x04, 0x11, 0xa8, 0xa7, 0xec, 0x31, 0x9d, 0xcd, 0x48, 0x2c, 0xdf, 0x97, 0x7a, 0xe7, 0xe9,
	0x4d, 0x03, 0x28, 0x16, 0xac, 0x55, 0xd7, 0x53, 0x71, 0x1e, 0x74, 0x98, 0x64, 0x79, 0xfc, 0x86,
	0xf8, 0x5c, 0x7f, 0x0b, 0xb5, 0x9b, 0xa3, 0x8c, 0xad, 0xbb, 0x50, 0xd2, 0x9a, 0x96, 0x21, 0xef,
	0x76, 0xf7, 0xec, 0x2d, 0x71, 0x4f, 0x9e, 0x0f, 0x1d, 0xd7, 0x36, 0x5a, 0x1d, 0x7d, 0xab, 0xca,
	0x90, 0xef, 0xf6, 0xf5, 0x45, 0xc7, 0x83, 0xc3, 0xf1, 0x8b, 0x81, 0x6d, 0x20, 0x0b, 0x8a, 0xbd,
	0xfd, 0x41, 0xef, 0xc0, 0xce, 0x09, 0xf3, 0xe4, 0xa8, 0xdf, 0x75, 0x07, 0x76, 0xbe, 0xb5, 0x0d,
	0x05, 0x59, 0x66, 0x19, 0xf2, 0xa3, 0xf1, 0x4b, 0x7b, 0x0b, 0x55, 0xa0, 0xec, 0xe2, 0xe1, 0xde,
	0xde, 0x00, 0xdb, 0x46, 0xeb, 0x01, 0x94, 0xd3, 0x04, 0x2d, 0x28, 0x0e, 0x0e, 0x8f, 0xdc, 0x57,
	0xf6, 0x16, 0xaa, 0x81, 0xd5, 0x1b, 0x8f, 0xfa, 0x43, 0x77, 0x38, 0x1e, 0xd9, 0x46, 0x6b, 0x07,
	0xcc, 0xf4, 0x88, 0xad, 0xd1, 0xf4, 0x07, 0xcf, 0xbb, 0xaf, 0x06, 0x7d, 0xdb, 0x68, 0x36, 0xc1,
	0x4c, 0x9f, 0x46, 0xdd, 0x57, 0xe4, 0xd2, 0xbe, 0xa2, 0xf3, 0x47, 0x1e, 0x6e, 0x5d, 0x68, 0x46,
	0x91, 0x03, 0x75, 0xd5, 0x75, 0xa6, 0x0b, 0xe8, 0xe3, 0x4b, 0x6a, 0xaf, 0xb5, 0xa5, 0xcd, 0x4f,
	0xae, 0xdc, 0x8d, 0x55, 0x73, 0xe8, 0x40, 0x5d, 0x75, 0xa9, 0xd7, 0x90, 0xae, 0xb5, 0xb1, 0x1b,
	0x92, 0xaa, 0x2e, 0xf6, 0x1a, 0xd2, 0xb5, 0x36, 0x77, 0x13, 0xd2, 0x31, 0x54, 0x45, 0xe7, 0xbb,
	0xa2, 0xdc, 0xbe, 0x04, 0xc9, 0x34, 0xc6, 0x9b, 0x10, 0x1e, 0x00, 0x08, 0x84, 0xee, 0xec, 0xae,
	0xa7, 0xbb, 0xff, 0x9e, 0x73, 0x7d, 0x5c, 0x92, 0x7f, 0x15, 0x9e, 0xfc, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x52, 0xf1, 0x54, 0x7a, 0x43, 0x0c, 0x00, 0x00,
}
