services:
    _defaults:
        public: '%public.services%'

    hbpf.command.send_usage_stats_events_to_usccp_command:
        class: Hanaboso\PipesFramework\HbPFUsageStatsBundle\Command\SendUsageStatsEventsToUSCCPCommand
        arguments:
            - '@hbpf.database_manager_locator'
            - '%alpha_instance_id%'
            - '@hbpf.transport.curl_manager'
        tags:
            - { name: console.command }
