parameters:
    env(ALPHA_INSTANCE_ID): 'orchesty'
    alpha_instance_id: '%env(string:ALPHA_INSTANCE_ID)%'
    env(INSTANCE_URL_PREFIX): ''
    instance_url_prefix: '%env(string:INSTANCE_URL_PREFIX)%'
    env(INSTANCE_TUNNEL_PROXY_URL): ''
    instance_tunnel_proxy_url: '%env(string:INSTANCE_TUNNEL_PROXY_URL)%'
    env(INSTANCE_BACKEND_URL): ''
    instance_backend_url: '%env(string:INSTANCE_BACKEND_URL)%'
    env(INSTANCE_STARTING_POINT_URL): ''
    instance_starting_point_url: '%env(string:INSTANCE_STARTING_POINT_URL)%'
    env(INSTANCE_WORKER_API_URL): ''
    instance_worker_api_url: '%env(string:INSTANCE_WORKER_API_URL)%'
