services:
  app:
    image: hanabosocom/go-base:1.24
    user: ${DEV_UID}:${DEV_GID}
    environment:
        RABBITMQ_URL: ${RABBITMQ_URL}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        RABBITMQ_VHOST: ${RABBITMQ_VHOST}
        MONGO_DSN: ${MONGO_DSN}
        K8S_CLUSTER_CONFIG: ${K8S_CLUSTER_CONFIG}
        K8S_NAMESPACE: ${K8S_NAMESPACE}
        K8S_ENABLED: ${K8S_ENABLED}
        LOKI_URL: ${LOKI_URL}
        APP_DEBUG: ${APP_DEBUG}
        TICK: ${TICK}
    volumes:
        - ./:/app
        - ${GOPATH}/pkg:/go/pkg
#    command: /run.sh -p main.go -c start -l 6666
    command: tail -f /dev/null
    security_opt:
        - 'seccomp:unconfined'

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "15672:15672"

  loki:
    image: grafana/loki:latest
    # ports:
    #   # - "3100:3100"