openapi: 3.0.0

info:
    title: XML Parser
    description: XML Parser API
    version: '1.0'

servers:
    -   url: http://127.0.0.55
        description: Docker Localhost

paths:
    /version:
        get:
            tags: [ Status ]
            responses:
                200:
                    $ref: '#/components/responses/Status'

    /xml-to-json:
        post:
            tags: [ XML Parser ]
            requestBody:
                $ref: '#/components/requestBodies/XmlToJson'
            responses:
                200:
                    $ref: '#/components/responses/XmlToJson'
                400:
                    $ref: '#/components/responses/400'
                500:
                    $ref: '#/components/responses/500'

    /json-to-xml:
        post:
            tags: [ XML Parser ]
            requestBody:
                $ref: '#/components/requestBodies/JsonToXml'
            responses:
                200:
                    $ref: '#/components/responses/JsonToXml'
                400:
                    $ref: '#/components/responses/400'
                500:
                    $ref: '#/components/responses/500'

    /xml-to-json/test:
        get:
            tags: [ XML Parser Test ]
            responses:
                200:
                    $ref: '#/components/responses/Empty'

    /json-to-xml/test:
        get:
            tags: [ XML Parser Test ]
            responses:
                200:
                    $ref: '#/components/responses/Empty'

components:
    requestBodies:
        XmlToJson:
            description: ''
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            data:
                                type: string
                            config:
                                type: object
                                nullable: true
                                properties:
                                    validator:
                                        type: string

        JsonToXml:
            description: ''
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            data:
                                type: object
                            config:
                                type: object
                                nullable: true
                                properties:
                                    validator:
                                        type: string

    responses:
        Empty:
            description: ''
            content:
                application/json:
                    schema:
                        type: object

        Status:
            description: ''
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: boolean
                            version:
                                type: string

        XmlToJson:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/XmlToJson'

        JsonToXml:
            description: ''
            content:
                application/xml:
                    schema:
                        $ref: '#/components/schemas/JsonToXml'

        400:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Message'
                    example:
                        message: Missing 'data' key!

        500:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Message'
                    example:
                        message: Something gone wrong

    schemas:
        XmlToJson:
            type: object
            properties:
                propertyOne:
                    type: string
                propertyTwo:
                    type: string

        JsonToXml:
            type: object
            properties:
                propertyOne:
                    type: string
                propertyTwo:
                    type: string

        Message:
            type: object
            properties:
                message:
                    type: string
