jose:
    jws:
        serializers:
            serializer:
                serializers: [ 'jws_compact' ]

        builders:
            builder:
                signature_algorithms: [ 'HS512' ]

        verifiers:
            verifier:
                signature_algorithms: [ 'HS512' ]

    jwe:
        serializers:
            serializer:
                serializers: [ 'jwe_compact' ]

        builders:
            builder:
                key_encryption_algorithms: [ 'RSA-OAEP-256' ]
                content_encryption_algorithms: [ 'A128GCM' ]
                compression_methods: [ 'DEF' ]

        decrypters:
            decrypter:
                key_encryption_algorithms: [ 'RSA-OAEP-256' ]
                content_encryption_algorithms: [ 'A128GCM' ]
                compression_methods: [ 'DEF' ]
