{{- if .Values.global.backend.postInstall.enabled }}
{{- $componentName := "backend-post-install" -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.global.backend.postInstall.backoffLimit | default 3 }}
  ttlSecondsAfterFinished: {{ .Values.global.backend.postInstall.ttlSecondsAfterFinished | default 600 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      restartPolicy: Never
      containers:
        - name: post-install
          image: {{ include "pipes.imageFullname" (dict "image" "backend" "root" .) }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              {{- range .Values.global.backend.postInstall.commands }}
              {{ . }}
              {{- end }}
              {{- if .Values.global.backend.postInstall.createDefaultUser }}
              {{ .Values.global.backend.postInstall.createDefaultUserCommand }}
              {{- end }}
          env:
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: BACKEND_URL
              value: "{{ .Values.global.backend_url }}"
            - name: STARTING_POINT_URL
              value: "{{ .Values.global.starting_point_url }}"
            - name: ALPHA_INSTANCE_ID
              value: {{ .Values.global.backend.alpha_instance_id }}
            - name: CRON_DSN
              value: cron-api:8080
            - name: TOPOLOGY_API_DSN
              value: "{{ include "pipes.fullname" (dict "suffix" "topology-api" "noPrefix" true "root" .) }}:8080"
            - name: LIMITER_URL
              value: "{{ include "pipes.fullname" (dict "suffix" "limiter" "root" .) }}:80"
            - name: FRONTEND_URL
              value: "{{ .Values.global.frontend_url }}/"
            - name: RABBITMQ_DSN
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_dsn
                  name: {{ include "pipes.secretName" . }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: backend_jwt_key
                  name: {{ include "pipes.secretName" . }}
            - name: MONGODB_DSN
              valueFrom:
                secretKeyRef:
                  key: mongodb_dsn
                  name: {{ include "pipes.secretName" . }}
            - name: MONGODB_DB
              valueFrom:
                secretKeyRef:
                  key: mongodb_db
                  name: {{ include "pipes.secretName" . }}
            - name: METRICS_DB
              valueFrom:
                secretKeyRef:
                  key: metrics_db
                  name: {{ include "pipes.secretName" . }}
            - name: METRICS_DSN
              valueFrom:
                secretKeyRef:
                  key: metrics_dsn
                  name: {{ include "pipes.secretName" . }}
            - name: ORCHESTY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: orchesty_api_key
                  name: {{ include "pipes.secretName" . }}
{{- if .Values.global.backend.postInstall.createDefaultUser }}
            - name: ORCHESTY_USR
              valueFrom:
                secretKeyRef:
                  key: oc_user_name
                  name: {{ include "pipes.secretName" . }}
            - name: ORCHESTY_PWD
              valueFrom:
                secretKeyRef:
                  key: oc_user_password
                  name: {{ include "pipes.secretName" . }}
{{- end }}
          resources:
{{ toYaml .Values.global.backend.postInstall.resources | indent 12 }}
{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
