{{- $componentName := "frontend" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: nginx
          image: {{ include "pipes.imageFullname" (dict "image" "frontend" "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: VITE_TITLE
              value: "{{ .Values.global.frontend.title }}"
            - name: VITE_BACKEND_URL
              value: "{{ .Values.global.backend_url }}"
            - name: VITE_STARTING_POINT_URL
              value: "{{ .Values.global.starting_point_url }}"
{{- if not .Values.global.cloud.enabled }}
            - name: VITE_NOTIFIER_URL
              value: "{{ .Values.global.cloud.instance.notifierUrl }}"
            - name: VITE_TRACE_URL
              value: "{{ .Values.global.cloud.instance.traceUrl }}"
            - name: VITE_AUTH0_DOMAIN
              value: "{{ .Values.global.cloud.auth0.domain }}"
            - name: VITE_AUTH0_CLIENT_ID
              value: "{{ .Values.global.cloud.auth0.clientId }}"
            - name: VITE_AUTH0_AUDIENCE
              value: "{{ .Values.global.cloud.auth0.audience }}"
            - name: VITE_AUTH0_REDIRECT
              value: "{{ .Values.global.cloud.auth0.redirect }}"
{{- end }}
          resources:
{{ toYaml .Values.global.frontend.resources | indent 12 }}

{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
