{{- $componentName := "trace" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: trace
          image: {{ include "pipes.imageFullname" (dict "image" $componentName "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: APP_DEBUG
              value: "false"
            - name: BACKEND_URL
              value: "http://{{ include "pipes.fullname" (dict "suffix" "backend" "root" .) }}:80"
            - name: BACKEND_TIMEOUT
              value: "{{ .Values.global.trace.backendTimeout }}"
          resources:
{{ toYaml .Values.global.trace.resources | indent 12 }}

{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
