{{- $componentName := "tunnel-proxy" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
spec:
  selector:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
