.base-pipes-connectors:
  variables:
    DIR: pipes-connectors

pipes-connectors:test:
  stage: test
  extends:
    - .base-test
    - .base-pipes-connectors

pipes-connectors:git-mirror:
  variables:
    MIRROR_REPOSITORY_NAME: orchesty-php-connectors
    MIRROR_TRIGGER_REPO_VAR: hanaboso-pipes-nodejs-connectors

  when: manual
  needs:
    - job: pipes-connectors:test
      optional: false

  extends:
    - .base-git-mirror
    - .base-pipes-connectors