app:
    resource: '@AppBundle/Controller/'
    type: annotation

hb_pf_authorization:
    resource: "@HbPFAuthorizationBundle"
    type: annotation

hb_pf_commons:
    resource: "@HbPFCommonsBundle"
    type: annotation

hb_pf_user:
    resource: "@HbPFUserBundle"
    type: annotation

hb_pf_api_gateway:
    resource: '@HbPFApiGatewayBundle'
    type:     annotation
    prefix:   /api/gateway
