services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFCustomNodeBundle\Controller\CustomNodeController:
        class: Hanaboso\PipesFramework\HbPFCustomNodeBundle\Controller\CustomNodeController
        arguments:
            - '@hbpf.handler.custom_node'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
            - ['setContainer', ['@service_container']]
