services:
    hbpf.custom.custom_node:
        class: Hanaboso\PipesFramework\HbPFCustomNodeBundle\Controller\CustomNodeController
        arguments:
            - '@hbpf.handler.custom_node'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]