services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $customNodeHandler: '@hbpf.handler.custom_node'
            $logger: '@monolog.logger.commons'

    Hanaboso\PipesFramework\HbPFCustomNodeBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']