services:
    hbpf.loader.custom_node:
        class: Hanaboso\PipesFramework\HbPFCustomNodeBundle\Loader\CustomNodeLoader
        arguments:
            - '@service_container'

    hbpf.custom_node.null:
        class: Hanaboso\PipesFramework\CustomNode\Impl\NullCustomNode
        arguments:
