services:
    hbpf.loader.custom_node:
        class: Hanaboso\PipesFramework\HbPFCustomNodeBundle\Loader\CustomNodeLoader
        arguments:
            - '@service_container'

    hbpf.custom_node.null:
        class: Hanaboso\PipesFramework\CustomNode\Impl\NullCustomNode
        arguments:

    hbpf.custom_node.sleep1:
        class: Hanaboso\PipesFramework\CustomNode\Impl\Sleep1CustomNode
        arguments:

    hbpf.custom_node.microsleep100000:
        class: Hanaboso\PipesFramework\CustomNode\Impl\Sleep01CustomNode
        arguments:

    hbpf.custom_node.microsleep200000:
        class: Hanaboso\PipesFramework\CustomNode\Impl\Sleep02CustomNode
        arguments:

    hbpf.custom_node.microsleep500000:
        class: Hanaboso\PipesFramework\CustomNode\Impl\Sleep05CustomNode
        arguments:

    hbpf.custom_node.microsleep700000:
        class: Hanaboso\PipesFramework\CustomNode\Impl\Sleep07CustomNode
        arguments:

    hbpf.custom_node.rabbit_node:
        class: Hanaboso\PipesFramework\CustomNode\Impl\RabbitCustomNode
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@rabbit-mq.producer.test_batch'
