apiVersion: v1
kind: Secret
metadata:
  name: cluster-telegraf
stringData:
  INFLUXDB_URL: https://monitoring-poc.orchesty.io
  INFLUXDB_ORG: orchesty-cloud-prod
  INFLUXDB_TOKEN: ""

  RABBITMQ_URL: http://some-host:15672
  RABBITMQ_USERNAME: admin
  RABBITMQ_PASSWORD: xxxxxxx
