apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-telegraf.fullname" . }}
stringData:
  INFLUXDB_URL: https://monitoring-poc.orchesty.io
  INFLUXDB_ORG: orchesty-cloud-prod
  INFLUXDB_TOKEN: ""
