.base-cloud-console-api:
  variables:
    DIR: saas/console-api
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}cloud-console-api

  rules:
    - if: '$FORCE_PIPELINE =~ /ALL/ || $FORCE_PIPELINE =~ /cloud-console-api/'
    - if: '$CI_COMMIT_BEFORE_SHA == $_BANNED_RUN_ALL_SHA'
      when: never
    - changes:
      - ${DIR}/**/*


cloud-console-api:test:
  stage: test
  needs: []

  extends:
    - .base-go-test
    - .base-cloud-console-api

cloud-console-api:build:
  stage: build
  needs: []
  extends:
    - .base-kaniko-build
    - .base-cloud-console-api
