.base-cloud-console-api:
  variables:
    DIR: saas/console-api
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}cloud-console-api

cloud-console-api:test:
  stage: test
  extends:
    - .base-test
    - .base-cloud-console-api

cloud-console-api:build:
  stage: build
  needs:
    - job: cloud-console-api:test
      optional: false
  when: manual
  extends:
    - .base-dind-build
    - .base-cloud-console-api
