services:
    _defaults:
        public: '%public.services%'

    Hanaboso\Applinth\Controller\StatisticsController:
        class: Hanaboso\Applinth\Controller\StatisticsController
        arguments:
            - '@hbpf._application.handler.statistics'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]

    Hanaboso\Applinth\Controller\ApplicationController:
        class: Hanaboso\Applinth\Controller\ApplicationController
        arguments:
            - '@Hanaboso\Applinth\Authenticator\EndUserAuthenticator'
            - '@hbpf.usage_stats.handler.usage_stats'
            - '@hbpp.service.locator'
            - '@hbpf.configurator.handler.topology'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
            - [ 'setContainer', [ '@service_container' ] ]

    Hanaboso\Applinth\Controller\TrashController:
        class: Hanaboso\Applinth\Controller\TrashController
        arguments:
            - '@Hanaboso\Applinth\Authenticator\EndUserAuthenticator'
            - '@hbpf.user_task.handler.user_task'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
            - [ 'setContainer', [ '@service_container' ] ]

    Hanaboso\Applinth\Controller\ProcessController:
        class: Hanaboso\Applinth\Controller\ProcessController
        arguments:
            - '@Hanaboso\Applinth\Authenticator\EndUserAuthenticator'
            - '@hbpf.configurator.handler.topology_progress'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
            - [ 'setContainer', [ '@service_container' ] ]

    Hanaboso\Applinth\Controller\AuthorizationController:
        class: Hanaboso\Applinth\Controller\AuthorizationController
        arguments:
            - '@Hanaboso\Applinth\Handler\AuthorizationHandler'
            - '%cookieSameSite%'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
            - [ 'setContainer', [ '@service_container' ] ]

    Hanaboso\Applinth\Controller\SettingsController:
        class: Hanaboso\Applinth\Controller\SettingsController
        arguments:
            - '@Hanaboso\Applinth\Authenticator\EndUserAuthenticator'
            - '@hbpp.service.locator'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
            - [ 'setContainer', [ '@service_container' ] ]

    Hanaboso\Applinth\Controller\LogsController:
        class: Hanaboso\Applinth\Controller\LogsController
        arguments:
            - '@Hanaboso\Applinth\Authenticator\EndUserAuthenticator'
            - '@hbpf.handler.logs'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
            - [ 'setContainer', [ '@service_container' ] ]
