parameters:
    jwe_private_key: '%env(string:JWE_PRIVATE_KEY)%'

services:
    _defaults:
        public: '%public.services%'

    hbpf._application.manager.statistics:
        class: Hanaboso\Applinth\Manager\StatisticsManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    Hanaboso\Applinth\Manager\AuthorizationManager:
        class: Hanaboso\Applinth\Manager\AuthorizationManager
        arguments:
            - '%jwe_private_key%'
            - '%jwt_key%'
