version: '2'

services:
  pipes-cron:
    user: ${DEV_UID}:${DEV_GID}
    image: dkr.hanaboso.net/pipes/pipes/python-cron:dev
    environment:
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - DEV_IP=${DEV_IP}
      - CRON_NAME=${CRON_NAME}
    #restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - ${DEV_IP}:80:5000
    links:
      - mongo
      - syslog-ng
    depends_on:
      - mongo
    command:
      - python
    stdin_open:
      true
    tty:
      true

  mongo:
    image: mongo:jessie
    volumes:
      - mongo:/data/db
    ports:
      - ${DEV_IP}:27017:27017
  syslog-ng:
    image: balabit/syslog-ng
    ports:
      - ${DEV_IP}:514:514
      - ${DEV_IP}:601:601
    volumes:
      - ./syslog-ng-remote.conf:/etc/syslog-ng/conf.d/syslog-ng-remote.conf

volumes:
  mongo: {}
