.base-enterprise-system-worker:
  variables:
    DIR: enterprise-sys-worker
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}enterprise-system-worker

enterprise-system-worker:test:
  stage: test
  extends:
    - .base-test
    - .base-enterprise-system-worker

enterprise-system-worker:build:
  stage: build
  needs:
    - job: enterprise-system-worker:test
      optional: false
  extends:
    - .base-dind-build
    - .base-enterprise-system-worker
