services:
    sdk:
        image: node-sdk:tag
        build: ./docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            APP_ENV: 'debug'
#            CRYPT_SECRET: ThisIsNotSoSecret
#            BACKEND_URL: ${DEV_IP}:8080
#            STARTING_POINT_DSN: ${DEV_IP}:8080
#            WORKER_API_HOST: ${DEV_IP}:8080
#            ORCHESTY_API_KEY: ThisIsNotSoSecret
        command: /bin/sh -c 'pnpm i && pnpm run start'
