parameters:
    mongo_host: mongo

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%mongo_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: pipes
    document_managers:
        default:
            mappings:
                FileDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/Commons/FileStorage/Document"
                    prefix: Hanaboso\PipesFramework\Commons\FileStorage\Document
                FileMongo:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/Commons/FileStorage/Driver"
                    prefix: Hanaboso\PipesFramework\Commons\FileStorage\Driver
                AclDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/Acl/Document"
                    prefix: Hanaboso\PipesFramework\Acl\Document