parameters:

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     'mariadb'
                dbname:   'pipes'
                user:     'root'
                password: 'root'
    orm:
        default_entity_manager: ~
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        connection: default
        mappings:
            HbPFCommonsBundle: ~
            AclEntity:
                type: annotation
                is_bundle: false
                dir: "%src_dir%/Acl/Entity"
                prefix: Hanaboso\PipesFramework\Acl\Entity
        proxy_dir: "%kernel.cache_dir%/doctrine/orm/Proxies"
        proxy_namespace: Proxies
