parameters:
    mongo_host: mongo

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%mongo_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: pipes
    document_managers:
        default:
            mappings:
                HbPFUserBundle: ~
                HbPFAclBundle: ~
                HbPFCommonsBundle: ~
                ApplicationDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/pipes-php-sdk/src/Authorization/Document"
                    prefix: Hanaboso\PipesPhpSdk\Authorization\Document
                WebhookDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/app-store/src/Document"
                    prefix: Hanaboso\PipesFramework\Application\Document
                FileDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/FileStorage/Document"
                    prefix: Hanaboso\CommonsBundle\FileStorage\Document
                CommonsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/Database/Document"
                    prefix: Hanaboso\CommonsBundle\Database\Document
                FileMongo:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/FileStorage/Driver/Impl/Mongo"
                    prefix: Hanaboso\CommonsBundle\FileStorage\Driver\Impl\Mongo
                LongRunningNodeDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/pipes-php-sdk/src/LongRunningNode/Document"
                    prefix: Hanaboso\PipesPhpSdk\LongRunningNode\Document
                LogsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/Logs/Document"
                    prefix: Hanaboso\PipesFramework\Logs\Document
