services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'

    mailer:
        class: EmailServiceBundle\Mailer\Mailer
        arguments:
            - '@EmailServiceBundle\Transport\Impl\SwiftMailerTransport'

swiftmailer:
    url: '%env(string:SMTP_DSN)%'
    spool: { type: memory }
    disable_delivery: false
    logging: true
