fos_rest:
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/topologies/\w+/schema.bpmn', priorities: ['xml'] }
            - { path: '^/topologies/\w+/schema.bpmn', priorities: ['xml'] }
            - { path: '^/api', priorities: ['json'] }
            - { path: '^/', priorities: ['json'] }

    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml