framework:
    secret: "%secret%"
    csrf_protection:
        enabled: false
    default_locale: "%locale%"
    trusted_hosts: ~
    serializer:
    fragments: ~
    http_method_override: true
    test: false
    session:
        storage_id: session.storage.mock_file
    router:
        strict_requirements: ~
