services:
    _defaults:
        public: '%public.services%'

    ##########################
    #    Session Handlers    #
    ##########################
    session.handler.mongodb:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments:
            - "@doctrine_mongodb.odm.default_connection"
            - {database: "%env(string:MONGODB_DB)%", collection: "Session"}

    hbpf.commons.session_handler:
        class: Hanaboso\CommonsBundle\Session\Handler\CachedSessionHandler
        arguments:
            - '@hbpf.commons.redis_session_handler'

    hbpf.commons.redis_session_handler:
        class: Hanaboso\CommonsBundle\Session\Handler\RedisSessionHandler
        arguments:
            - '%redis_dsn%'

    ##########################
    #        Metrics         #
    ##########################

    hbpf.system_metrics_listener:
        class: Hanaboso\CommonsBundle\Listener\SystemMetricsListener
        arguments:
            - '@hbpf.metrics_monolith.loader'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber, event: kernel.terminate }
            - { name: kernel.event_subscriber, event: kernel.controller }

    hbpf.influxdb_sender_connector:
        class: Hanaboso\CommonsBundle\Metrics\Impl\InfluxDbSender
        arguments:
            - '@hbpf.transport.udp_sender'
            - '%kapacitor.host%:%kapacitor.port%'
            - '%influx.connector_table%'

    hbpf.influxdb_sender_monolith:
        class: Hanaboso\CommonsBundle\Metrics\Impl\InfluxDbSender
        arguments:
            - '@hbpf.transport.udp_sender'
            - '%kapacitor.host%:%kapacitor.port%'
            - '%influx.monolith_table%'

    hbpf.metrics.mongodb_connector:
        class: Hanaboso\CommonsBundle\Metrics\Impl\MongoDbSender
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '%mongodb.connector_table%'

    hbpf.metrics.mongodb_monolith:
        class: Hanaboso\CommonsBundle\Metrics\Impl\MongoDbSender
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '%mongodb.monolith_table%'

    hbpf.metrics_connector.loader:
        class: Hanaboso\CommonsBundle\Metrics\MetricsSenderLoader
        arguments:
            - '%metrics_service%'
            - '@hbpf.influxdb_sender_connector'
            - '@hbpf.metrics.mongodb_connector'

    hbpf.metrics_monolith.loader:
        class: Hanaboso\CommonsBundle\Metrics\MetricsSenderLoader
        arguments:
            - '%metrics_service%'
            - '@hbpf.influxdb_sender_monolith'
            - '@hbpf.metrics.mongodb_monolith'

    ##########################
    #      File Storage      #
    ##########################

    hbpf.file_storage.driver.mongo:
        class: Hanaboso\CommonsBundle\FileStorage\Driver\Impl\Mongo\MongoFileDriver
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.path_generator.hash'

    hbpf.path_generator.hash:
        class: Hanaboso\CommonsBundle\FileStorage\PathGenerator\HashPathGenerator
        arguments:

    hbpf.file_storage.locator:
        class: Hanaboso\CommonsBundle\FileStorage\Driver\FileStorageDriverLocator
        arguments:
            - '@hbpf.file_storage.driver.mongo'
            - '@hbpf.file_storage.driver.mongo'
            - '@hbpf.file_storage.driver.mongo'

    hbpf.file_storage:
        class: Hanaboso\CommonsBundle\FileStorage\FileStorage
        arguments:
            - '@hbpf.file_storage.locator'
            - '@hbpf.database_manager_locator'
            - 'Hanaboso\CommonsBundle\FileStorage\Document\File'

    ##########################
    #    Database Locator    #
    ##########################

    hbpf.database_manager_locator:
        class: Hanaboso\CommonsBundle\Database\Locator\DatabaseManagerLocator
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - null
            - '%database_type%'

    ##########################
    #   Transport Services   #
    ##########################

    hbpf.transport.udp_sender:
        class: Hanaboso\CommonsBundle\Transport\Udp\UDPSender

    hbpf.transport.curl_manager:
        class: Hanaboso\CommonsBundle\Transport\Curl\CurlManager
        arguments:
            - '@hbpf.transport.curl_client_factory'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
#            - ['setMetricsSender', ['@hbpf.metrics_connector.loader']] ## Optional metrics sender

    ##########################
    #      ACL Provider      #
    ##########################

    hbpf.acl.provider:
        class: Hanaboso\AclBundle\Provider\Impl\AclProvider
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.provider.resource'
            - '%resource_enum%'
            - '%acl_use_cache%'
            - '%redis_dsn%'
