parameters:
     # InfluxDb
    influx.host: influxdb
    influx.api_port: 8086
    influx.udp_port: 8089
    influx.user: admin
    influx.password: password
    influx.database: pipes
    influx.node_table: pipes_node
    influx.connector_table: connector
    influx.monolith_table: monolith
    influx.rabbit_table: rabbitmq_queue
    influx.counter_table: processes