doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: OdmProxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: OdmHydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "%mongo_connection%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: '%mongo_db%'
    document_managers:
        default:
            mappings:
                AppDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/Document"
                    prefix: Hanaboso\NotificationSender\Document
