parameters:
    stdout_path: "%kernel.logs_dir%/stdout_%kernel.environment%.log"

monolog:
    use_microseconds: false
    channels: [authorization, commons, connector, ftp, mailer, parser_table, user, rabbit-mq, rabbit_mq, test, stdout]
    handlers:
        authorization:
            type: service
            id: udp_handler
            level: info
            channels: [authorization]
        commons:
            type: service
            id: udp_handler
            level: info
            channels: [commons]
        connector:
            type: service
            id: udp_handler
            level: info
            channels: [connector]
        ftp:
            type: service
            id: udp_handler
            level: info
            channels: [ftp]
        mailer:
            type: service
            id: udp_handler
            level: info
            channels: [mailer]
        parser_table:
            type: service
            id: udp_handler
            level: info
            channels: [parser_table]
        user:
            type: service
            id: udp_handler
            level: info
            channels: [user]
        rabbit-mq:
            type: service
            id: udp_handler
            level: info
            channels: [rabbit-mq]
        rabbit_mq:
            type: service
            id: udp_handler
            level: info
            channels: [rabbit_mq]

        # Handler for docker container
        stdout:
            type:  stream
            path:  "%stdout_path%"
            level: info
            formatter: logstash_formatter
            max_files: 10
            channels: '!php'

services:
    _defaults:
        public: '%public.services%'

    logstash_formatter:
        class: Hanaboso\CommonsBundle\Monolog\LogstashFormatter

    udp_sender:
        class: Hanaboso\CommonsBundle\Metrics\UDPSender
        arguments:
            - 'logstash'
            - '5120'

    udp_handler:
        class: Hanaboso\CommonsBundle\Monolog\UdpHandler
        arguments:
            - '@udp_sender'
            - 'info'
        calls:
            - ['setFormatter', ['@logstash_formatter']]