parameters:
    node_services_dirs:
        - '%kernel.project_dir%/src/HbPFConnectorBundle/Resources/config/'
        - '%kernel.project_dir%/src/HbPFCustomNodeBundle/Resources/config/'
        - '%kernel.project_dir%/src/HbPFJoinerBundle/Resources/config/'
        - '%kernel.project_dir%/src/HbPFMapperBundle/Resources/config/'
