rabbit_mq:
    logger: 'monolog.logger.rabbit-mq'

    connections:
        default:
            dsn: '%env(string:RABBITMQ_DSN)%'

    queues:
        pipes.notifications:
            durable: true

    publishers:
        notification-rabbit:

    consumers:
        notification:
            queue: pipes.notifications
            callback: notification.callback.message
