parameters:
    rabbit_host: rabbitmq
    rabbit_port: 5672
    rabbit_vhost: /
    rabbit_user: guest
    rabbit_password: guest
    rabbit_persistent: false
    rabbit_path: /

rabbit_mq:
    connections:
        default:
            host: '%rabbit_host%'
            port: '%rabbit_port%'
            vhost: '%rabbit_vhost%'
            user: '%rabbit_user%'
            password: '%rabbit_password%'
