rest:
    routes:
        ^/: ['json']
    decoders:
        json: 'rest.decoder.json'
    cors:
        ^/:
            origin: ['*']
            methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            headers: ['Content-Type']
            credentials: TRUE
