services:
    _defaults:
        public: '%public.services%'

    hbpf.install.topology.manager:
        class: Hanaboso\PipesFramework\TopologyInstaller\InstallManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@snc_redis.default'
            - '@hbpf.configurator.manager.topology'
            - '@hbpf.topology_generator.bridge'
            - '@hbpf.category.parser'
            - '@rest.decoder.xml'
            - [] #todo: add dirs

    hbpf.category.parser:
        class: Hanaboso\PipesFramework\TopologyInstaller\CategoryParser
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.configurator.manager.category'