version: "3.5"

services:
    applinth-billing-processor:
        image: applinth-billing-processor:tag
        build: ./console-api/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        ports:
            - ${DEV_IP}:3000:3000
        volumes:
            - ./applinth-billing-processor/:/var/www
        environment:
            # Envs for tests are load from .jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: 'debug'
            NODE_ENV: 'dev'
            MONGODB_DSN: mongodb://mongodb
        command: sleep infinity

    console-api:
        image: console-api:tag
        build: ./console-api/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        ports:
            - ${DEV_IP}:3001:3000
        volumes:
            - ./console-api/:/var/www
        environment:
            # Envs for tests are load from .jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: 'debug'
            NODE_ENV: 'dev'
            MONGODB_DSN: mongodb://mongodb
            FIREBASE_API_KEY: AIzaSyANIRePUXX1f8fr-IS2ljSU8FgLkC53a0o
            FIREBASE_AUTH_DOMAIN: 'orchesty-cloud-stage.firebaseapp.com'
        command: sleep infinity

    mongodb:
        image: mongo:5
        ports:
            - ${DEV_IP}:27017:27017

volumes:
    mongodb: { }
