export const TRASH = {
  NAMESPACE: "trash",
  ACTIONS: {
    TRASH_UPDATE: "TRASH_UPDATE",
    TRASH_ACCEPT: "TRASH_ACCEPT",
    TRASH_ACCEPT_LIST: "TRASH_ACCEPT_LIST",
    TRASH_REJECT: "TRASH_REJECT",
    TRASH_REJECT_LIST: "TRASH_REJECT_LIST",
    TRASH_TASK_GET: "TRASH_TASK_GET",
  },
  MUTATIONS: {
    TRASH_GET: "TRASH_GET",
    RESET: "RESET",
  },
}
