services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%service_visibility%'

    Hanaboso\Portal\Controller\PortalController:
        class: Hanaboso\Portal\Controller\PortalController

    Hanaboso\Portal\Controller\InstallerController:
        class: Hanaboso\Portal\Controller\InstallerController
        arguments:
            - '@portal.handler.installer'
