stages:
  - stage1
  - stage2
  - stage3
  - cleanup

before_script:
  - . build/lib/gitlab-ci-helpers.sh
  - export REPO_ROOT=$(pwd)
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/bob_the_builder_hanaboso

include:
  - local: '/portal/.gitlab-ci.yml'
  - local: '/website/.gitlab-ci.yml'

php-dev-image:
  stage: stage1
  script:
    - DIR=pf-bundles
    - cd $REPO_ROOT/$DIR
    - make build-dev
  only:
    - dev
    - master
    - ci

starting-point-dev-image:
  stage: stage1
  script:
    - DIR=starting-point
    - cd $DIR
    - make build-dev TAG=dev
  only:
    - dev
    - master

rabbitmq-telegraf-dev-image:
  stage: stage1
  script:
    - DIR=rabbitmq-telegraf
    - cd $DIR
    - make build-dev-image
  only:
    - dev
    - master

lib-python-dev-build:
  stage: stage1
  script:
    - cd $REPO_ROOT/lib-python
    - make docker-push-dev-all
  only:
    - dev
    - master

njs-build-image:
  stage: stage1
  script:
    - cd $REPO_ROOT/frontend/docker/build
    - IMAGE=dkr.hanaboso.net/pipes/pipes/nodejs-build:${CI_BUILD_REF_NAME}
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}
    - IMAGE=hanabosocom/nodejs-build:${CI_BUILD_REF_NAME}
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}
  only:
    - dev
    - master
    - ci

multi-probe-image:
  stage: stage1
  script:
    - cd $REPO_ROOT/multi-probe
    - IMAGE=dkr.hanaboso.net/pipes/pipes/multi-probe:${CI_BUILD_REF_NAME}
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}
  only:
    - dev
    - master
    - ci

limiter-image:
  stage: stage1
  script:
    - cd $REPO_ROOT/limiter
    - IMAGE=dkr.hanaboso.net/pipes/pipes/limiter:${CI_BUILD_REF_NAME}
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}
  only:
    - dev
    - master
    - ci

notification-sender-image:
  stage: stage1
  script:
    - cd $REPO_ROOT/notification-sender
    - make build TAG=${CI_BUILD_REF_NAME}
  only:
    - dev
    - master
    - ci

logstash-build:
    stage: stage1
    script:
      - cd $REPO_ROOT/logstash
      - make docker-build docker-push DOCKER_TAG=${CI_BUILD_REF_NAME}
    only:
      - dev
      - master

influxdb-build:
    stage: stage1
    script:
      - cd $REPO_ROOT/influxdb
      - make docker-build DOCKER_TAG=${CI_BUILD_REF_NAME} docker-push DOCKER_TAG=${CI_BUILD_REF_NAME}
    only:
      - dev
      - master

kapacitor-build:
    stage: stage1
    script:
      - cd $REPO_ROOT/kapacitor
      - make docker-build DOCKER_TAG=${CI_BUILD_REF_NAME} docker-push DOCKER_TAG=${CI_BUILD_REF_NAME}
    only:
      - dev
      - master

lib-python-build:
  stage: stage1
  script:
    - cd $REPO_ROOT/lib-python
    - make docker-push-all DOCKER_TAG=${CI_BUILD_REF_NAME}
  only:
    - dev
    - master

topology-api:
  stage: stage1
  script:
    -  cd topology-generator && make docker-push DOCKER_DEFAULT_TAG=${CI_BUILD_REF_NAME}
  only:
    - dev
    - master

pf-bridge:
  stage: stage1
  script:
    - DIR=pf-bridge
    - skip_unmodified $DIR
    - ${DIR}/build.sh ${CI_BUILD_REF_NAME}
  only:
    - dev
    - master

# GO LANG
.go_test: &go_test
  script:
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="${CI_JOB_NAME}_${CI_PIPELINE_ID}"
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} ci-test

multi-probe-test:
  <<: *go_test
  variables:
    DIR: multi-probe
  stage: stage2

limiter-test:
  <<: *go_test
  variables:
    DIR: limiter
  stage: stage2

topology-generator-test:
  <<: *go_test
  variables:
   DIR: topology-generator
  stage: stage2

pf-bundles-test:
  stage: stage2
  script:
    - DIR=pf-bundles
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-bundles" # CLEANUP bundles
    - export COMPOSE_FILE=docker-compose.ci.yml                # CLEANUP bundles
    - make ${COMPOSE_FILE} test docker-down-clean

notification-sender-test:
  stage: stage2
  script:
    - DIR=notification-sender
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-notification-sender" # CLEANUP notification-sender
    - export COMPOSE_FILE=docker-compose.ci.yml                            # CLEANUP notification-sender
    - make ${COMPOSE_FILE} test

app-store-test:
  stage: stage2
  script:
    - DIR=app-store
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-app-store" # CLEANUP app-store
    - export COMPOSE_FILE=docker-compose.ci.yml                  # CLEANUP app-store
    - make ${COMPOSE_FILE} test docker-down-clean

pipes-php-sdk-test:
  stage: stage2
  script:
    - DIR=pipes-php-sdk
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-pipes-php-sdk" # CLEANUP pipes-php-sdk
    - export COMPOSE_FILE=docker-compose.ci.yml                      # CLEANUP pipes-php-sdk
    - make ${COMPOSE_FILE} test docker-down-clean

pipes-connectors-test:
  stage: stage2
  script:
    - DIR=pipes-connectors
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-pipes-connectors" # CLEANUP pipes-connectors
    - export COMPOSE_FILE=docker-compose.ci.yml                         # CLEANUP pipes-connectors
    - make ${COMPOSE_FILE} test docker-down-clean

rabbitmq-telegraf-test:
  stage: stage2
  script:
    - DIR=rabbitmq-telegraf
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-rabbitmq-telegraf" # CLEANUP rabbitmq-telegraf
    - export COMPOSE_FILE=docker-compose.ci.yml                          # CLEANUP rabbitmq-telegraf
    - make ${COMPOSE_FILE} test

demo-pipes-api-test:
  stage: stage2
  script:
    - DIR=clients/demo/pipes-api
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-demo-pipes-api" # CLEANUP bundles
    - export COMPOSE_FILE=docker-compose.ci.yml                       # CLEANUP bundles
    - make ${COMPOSE_FILE} test docker-down-clean

pf-bridge-test:
  stage: stage2
  script:
    - DIR=pf-bridge
    - skip_unmodified $DIR
    - cd $REPO_ROOT/$DIR/test
    - export COMPOSE_PROJECT_NAME="p${CI_PIPELINE_ID}-bridge"  # CLEANUP bridge
    - export RABBITMQ_HOST=rabbitmq
    - export METRICS_HOST=influxdb
    - docker-compose pull
    - docker-compose up -d
    - docker-compose exec -T test npm run lint
    - docker-compose exec -T test sh -c 'while [ $(curl -s -o /dev/null -w "%{http_code}" http://guest:guest@rabbitmq:15672/api/overview) == 000 ]; do sleep 1; done'
    - docker-compose exec -T test npm run testunit
    - docker-compose exec -T test npm run testintegration

frontend:
  stage: stage2
  script:
    - DIR=frontend
    - skip_unmodified $DIR
    - cd $DIR
    - make build image push TAG=${CI_BUILD_REF_NAME}
  only:
    - dev
    - master

starting-point:
  stage: stage2
  script:
    - DIR=starting-point
    - skip_unmodified $DIR
    - cd $DIR
    - make build TAG=${CI_BUILD_REF_NAME}
  only:
    - master

rabbitmq-telegraf:
  stage: stage2
  script:
    - DIR=rabbitmq-telegraf
    - skip_unmodified $DIR
    - cd $DIR
    - make build TAG=${CI_BUILD_REF_NAME}
  only:
    - dev
    - master

# Client: demo
stage-demo:
  stage: stage3
  when: manual
  script:
    - rsync -av --delete --exclude '.git' ./ ~/stage_demo
    - cd ~/stage_demo/clients/demo
    - export COMPOSE_PROJECT_NAME=stagedemo
    - export NPM_INSTALL="yes"
    - make docker-pull-dev init-dev DEV_YML=docker-compose.ci.yml
  script:
    - cd clients/demo
    - make docker-compose.ci.yml
    - source <(../../build/bin/map-branch-image-tags.sh ./branch-image-tag-map ${CI_BUILD_REF_NAME} -e)
    - export DEPLOYMENT_PREFIX=demo
    - export PUBLISH_HTTP_PORT=6539
    - export BACKEND_URL=https://pipes-demo.stage.hanaboso.net
    - export DOCKER_HOST=192.168.10.31:2376
    - export DOCKER_TLS_VERIFY=1
    - docker stack deploy --with-registry-auth -c docker-compose.ci.yml ${DEPLOYMENT_PREFIX}

monolith-demo:
  stage: stage2
  script:
    - ": This job is being run all the time because the most changes happen in its dependencies. Can anyone come up with an optimization?"
    - cd clients/demo
    - make build-monolith push-monolith TAG=${CI_BUILD_REF_NAME}
  only:
    - dev
    - master

git-pf-bundles:
  stage: stage3
  when: always
  only:
    - dev
    - master
    - pf-bundle-export
  script:
    - skip_unmodified pf-bundles
    - rm -rf _tmp_pipes_full
    - rm -rf _tmp_pipes
    - git clone -b ${CI_BUILD_REF_NAME} git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes_full
    - git clone --bare git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes
    - cd _tmp_pipes
    - git filter-branch -f --prune-empty --subdirectory-filter pf-bundles -- -q --all
    - git remote add dest git@gitlab.hanaboso.net:pipes/pf-bundles.git
    - git push --mirror dest
    - "[[ ${CI_BUILD_REF_NAME} == 'master' ]] && git push dest ${CI_BUILD_REF_NAME}:refs/tags/$(cat ../_tmp_pipes_full/pf-bundles/composer.json | grep version | grep -oE '[[:digit:]]\\.[[:digit:]]\\.[[:digit:]]') || true"

git-notification-sender:
  stage: stage3
  when: always
  only:
    - dev
    - master
  script:
    - skip_unmodified notification-sender
    - rm -rf _tmp_pipes_full
    - rm -rf _tmp_pipes
    - git clone -b ${CI_BUILD_REF_NAME} git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes_full
    - git clone --bare git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes
    - cd _tmp_pipes
    - git filter-branch -f --prune-empty --subdirectory-filter notification-sender -- -q --all
    - git remote add dest git@gitlab.hanaboso.net:pipes/notification-sender.git
    - git push --mirror dest
    - "[[ ${CI_BUILD_REF_NAME} == 'master' ]] && git push dest ${CI_BUILD_REF_NAME}:refs/tags/$(cat ../_tmp_pipes_full/notification-sender/composer.json | grep version | grep -oE '[[:digit:]]\\.[[:digit:]]\\.[[:digit:]]') || true"

git-app-store:
  stage: stage3
  when: always
  only:
    - dev
    - master
  script:
    - skip_unmodified app-store
    - rm -rf _tmp_pipes_full
    - rm -rf _tmp_pipes
    - git clone -b ${CI_BUILD_REF_NAME} git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes_full
    - git clone --bare git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes
    - cd _tmp_pipes
    - git filter-branch -f --prune-empty --subdirectory-filter app-store -- -q --all
    - git remote add dest git@gitlab.hanaboso.net:pipes/app-store.git
    - git push --mirror dest
    - "[[ ${CI_BUILD_REF_NAME} == 'master' ]] && git push dest ${CI_BUILD_REF_NAME}:refs/tags/$(cat ../_tmp_pipes_full/app-store/composer.json | grep version | grep -oE '[[:digit:]]\\.[[:digit:]]\\.[[:digit:]]') || true"

git-pipes-php-sdk:
  stage: stage3
  when: always
  only:
    - dev
    - master
  script:
    - skip_unmodified pipes-php-sdk
    - rm -rf _tmp_pipes_full
    - rm -rf _tmp_pipes
    - git clone -b ${CI_BUILD_REF_NAME} git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes_full
    - git clone --bare git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes
    - cd _tmp_pipes
    - git filter-branch -f --prune-empty --subdirectory-filter pipes-php-sdk -- -q --all
    - git remote add dest git@gitlab.hanaboso.net:pipes/pipes-php-sdk.git
    - git push --mirror dest
    - "[[ ${CI_BUILD_REF_NAME} == 'master' ]] && git push dest ${CI_BUILD_REF_NAME}:refs/tags/$(cat ../_tmp_pipes_full/pipes-php-sdk/composer.json | grep version | grep -oE '[[:digit:]]\\.[[:digit:]]\\.[[:digit:]]') || true"

git-pipes-connectors:
  stage: stage3
  when: always
  only:
    - dev
    - master
  script:
    - skip_unmodified pipes-connectors
    - rm -rf _tmp_pipes_full
    - rm -rf _tmp_pipes
    - git clone -b ${CI_BUILD_REF_NAME} git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes_full
    - git clone --bare git@gitlab.hanaboso.net:pipes/pipes.git _tmp_pipes
    - cd _tmp_pipes
    - git filter-branch -f --prune-empty --subdirectory-filter pipes-connectors -- -q --all
    - git remote add dest git@gitlab.hanaboso.net:pipes/pipes-connectors.git
    - git push --mirror dest
    - "[[ ${CI_BUILD_REF_NAME} == 'master' ]] && git push dest ${CI_BUILD_REF_NAME}:refs/tags/$(cat ../_tmp_pipes_full/pipes-connectors/composer.json | grep version | grep -oE '[[:digit:]]\\.[[:digit:]]\\.[[:digit:]]') || true"

cleanup:
  stage: cleanup
  when: always
  script:
    - ": TODO: we should do cleanups also in the end of every job that needs them,"
    - ":       this should be only the last resort when a job fails"

    - ": bundles"
    - cd $REPO_ROOT/pf-bundles
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-bundles
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "bundles cleanup phase failed"

    - ": notification-sender"
    - cd $REPO_ROOT/notification-sender
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-notification-sender
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "notification-sender cleanup phase failed"

    - ": app-store"
    - cd $REPO_ROOT/app-store
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-app-store
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "app-store cleanup phase failed"

    - ": pipes-php-sdk"
    - cd $REPO_ROOT/pipes-php-sdk
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-pipes-php-sdk
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "pipes-php-sdk cleanup phase failed"

    - ": pipes-connectors"
    - cd $REPO_ROOT/pipes-connectors
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-pipes-connectors
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "pipes-connectors cleanup phase failed"

    - ": rabbitmq-telegraf"
    - cd $REPO_ROOT/rabbitmq-telegraf
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-rabbitmq-telegraf
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "rabbitmq-telegraf cleanup phase failed"

    - ": demo-pipes-api-test"
    - cd $REPO_ROOT/clients/demo/pipes-api
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-demo-pipes-api
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} docker-down-clean || echo "demo-pipes-api cleanup phase failed"

    - ": bridge"
    - cd $REPO_ROOT/pf-bridge/test
    - export COMPOSE_FILE=docker-compose.yml
    - export COMPOSE_PROJECT_NAME=p${CI_PIPELINE_ID}-bridge
    - docker-compose down -v || echo "bridge cleanup phase failed"

    - ": multi-probe"
    - cd $REPO_ROOT/multi-probe
    - export COMPOSE_PROJECT_NAME="multi-probe-test_${CI_PIPELINE_ID}"
    - export COMPOSE_FILE=docker-compose.ci.yml
    - docker-compose down -v || echo "multi-probe cleanup phase failed"

    - ": limiter"
    - cd $REPO_ROOT/limiter
    - export COMPOSE_PROJECT_NAME="limiter-test_${CI_PIPELINE_ID}"
    - export COMPOSE_FILE=docker-compose.ci.yml
    - docker-compose down -v || echo "limiter cleanup phase failed"

    - ": topology generator"
    - cd $REPO_ROOT/topology-generator
    - export COMPOSE_PROJECT_NAME="topology-generator-test_${CI_PIPELINE_ID}"
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE}
    - docker-compose down -v || echo "topology generator cleanup phase failed"

    - ": starting point"
    - cd $REPO_ROOT/starting-point
    - export COMPOSE_PROJECT_NAME="starting-point-test_${CI_PIPELINE_ID}"
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE}
    - docker-compose down -v || echo "starting point cleanup phase failed"
