include:
  - local: "/.gitlab/ci/essentials.gitlab-ci.yml"
  - local: "/.gitlab/ci/default-workflow.gitlab-ci.yml"

  - local: "/.gitlab/ci/build.gitlab-ci.yml"
  - local: "/.gitlab/ci/deploy.gitlab-ci.yml"
  - local: "/.gitlab/ci/git-mirror.gitlab-ci.yml"
  - local: "/.gitlab/ci/go.gitlab-ci.yml"
  - local: "/.gitlab/ci/release.gitlab-ci.yml"

  - local: "/app-ui/.gitlab-ci.yml"
  - local: "/applinth-admin-ui/.gitlab-ci.yml"
  - local: "/applinth-marketplace-ui/.gitlab-ci.yml"
  - local: "/applinth/.gitlab-ci.yml"
  - local: "/bridge/.gitlab-ci.yml"
  - local: "/counter/.gitlab-ci.yml"
  - local: "/cron/.gitlab-ci.yml"
  - local: "/detector/.gitlab-ci.yml"
  - local: "/docusaurus/documentation/.gitlab-ci.yml"
  - local: "/fluentd/.gitlab-ci.yml"
  - local: "/limiter/.gitlab-ci.yml"
  - local: "/pf-bridge/.gitlab-ci.yml" # legacy, used as repeater
  - local: "/pf-bundles/.gitlab-ci.yml" # aka backend
  - local: "/pipes-connectors/.gitlab-ci.yml"
  - local: "/pipes-php-sdk/.gitlab-ci.yml"
  - local: "/saas/console-api/.gitlab-ci.yml"
  - local: "/starting-point/.gitlab-ci.yml"
  - local: "/topology-generator/.gitlab-ci.yml"
