version: '3.5'

services:
    app:
        image: hanabosocom/php-dev:php-8.1-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached
            - ../pipes-php-sdk:/var/pipes-php-sdk:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 1
            PHP_WEBROOT: /var/www/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            KERNEL_CLASS: Pipes\StatusService\Kernel
            RABBITMQ_DSN: amqp://rabbitmq:5672
            METRICS_SERVICE: mongodb

    rabbitmq:
        image: rabbitmq:management-alpine
