version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-7.4
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:8000:80
        volumes:
            - ./:/var/www
            - ../app-store:/var/app-store
            - ../pipes-php-sdk:/var/pipes-php-sdk
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/dev/.composer:${HOME}/dev/.composer
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=Hanaboso\PipesFramework\Kernel
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - PRELOAD_USER:${DEV_UID}
            - PRELOAD_PATH:/var/www/var/cache/dev/Hanaboso_PipesFramework_KernelDevDebugContainer.preload.php
            - FRONTEND_DSN=${DEV_IP}
            - FRONTEND_HOST=${DEV_IP}
            - BACKEND_DSN=${DEV_IP}
            - NOTIFICATION_DSN=http://notification-sender-api
            - REDIS_DSN=redis://redis:6379/10
            - MULTI_PROBE_DSN=multi-probe:8007
            - TOPOLOGY_API_DSN=topology-api:80
            - MONGODB_DSN=mongodb://mongo
            - MARIADB_DSN=maria
            - STARTING_POINT_DSN=starting-point:80
            - CRON_DSN=http://cron-api:5000
            - ELASTICSEARCH_DSN=elasticsearch://elasticsearch
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - FTP_API_DSN=ftp-api
            - MAILER_API_DSN=mailer-api
            - MAPPER_API_DSN=mapper-api
            - MONOLITH_API_DSN=${DEV_IP}
            - XML_PARSER_API_DSN=xml-parser-api
            - METRICS_SERVICE=influx

    starting-point:
        image: dkr.hanaboso.net/pipes/pipes/starting-point:master
        environment:
            MONGO_DSN: mongodb://mongo/demo?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            MONGO_METRICS_DSN: mongodb://mongo/metrics?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            RABBIT_COUNTER_QUEUE_DURABLE: 'true'
            RABBIT_QUEUE_DURABLE: 'true'
            RABBIT_DELIVERY_MODE: 2
            APP_CLEANUP_TIME: 300
            GOROUTINE_LIMIT: 1000

    cron-api:
        user: ${DEV_UID}:${DEV_GID}
        image: dkr.hanaboso.net/pipes/pipes/python-cron:dev
        environment:
            - DEV_UID={DEV_UID}
            - DEV_GID={DEV_GID}
        ports:
            - ${DEV_IP}:8050:5000

    notification-sender-api:
        image: dkr.hanaboso.net/pipes/notification-sender:master
        working_dir: /var/www
        environment:
            MONGO_HOST: mongo

    mongo:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongo:/data/db

    rabbitmq:
        image: rabbitmq:management-alpine
        volumes:
            - rabbit-mq:/var/lib/rabbitmq
        ports:
            - ${DEV_IP}:15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    redis:
        image: redis:alpine
        ports:
            - ${DEV_IP}:6379:6379
        volumes:
            - redis:/data

    elasticsearch:
        image: elasticsearch:7.4.2
        environment:
            LS_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data

    influxdb:
        image: dkr.hanaboso.net/pipes/pipes/influxdb:dev
        ports:
            - ${DEV_IP}:8083:8083
            - ${DEV_IP}:8086:8086
            - ${DEV_IP}:8089:8089/udp
        volumes:
            - influxdb:/var/lib/influxdb

volumes:
    mongo: {}
    rabbit-mq: {}
    redis: {}
    influxdb: {}
    elasticsearch: {}