version: '3.5'

services:
    app:
        image: dkr.hanaboso.net/pipes/pipes/topology-api-v2:dev
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            GITLAB_CI: ${GITLAB_CI}
            MONGO_DSN: mongodb://mongodb/topology-api?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
        volumes:
            - ./:/topology-generator
            - ${GOPATH}/pkg:/go/pkg
        ports:
            - ${DEV_IP}:8080:8080

    mongodb:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - ${DEV_IP}:8080:8080
        volumes:
            - ./openapi.yaml:/api.yaml
        environment:
            SWAGGER_JSON: /api.yaml

volumes:
    mongodb:
