version: '2'
services:
  php-dev:
    image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/srv/project
      - ../:/srv/libs
      - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
    environment:
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - COMPOSER_HOME=/home/dev/.composer
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    depends_on:
      - mongo
      - rabbitmq
      - smtp
    links:
      - mongo
      - rabbitmq
      - smtp

  nginx:
    image: nginx
    ports:
      - ${DEV_IP}:8000:8000
    depends_on:
      - php-dev
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/srv/project

  smtp:
    image: mailhog/mailhog
    ports:
      - ${DEV_IP}:1025:1025
      - ${DEV_IP}:8025:8025

  mongo:
      image: mongo:latest
      ports:
        - ${DEV_IP}:27017:27017
      volumes:
        - mongo:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    volumes:
       - rabbit-mq:/var/lib/rabbitmq
    ports:
      - ${DEV_IP}:15672:15672
      - ${DEV_IP}:5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

  mariadb:
      image: mariadb:10.3
      command: "mysqld --innodb_flush_method=nosync"
      environment:
       MYSQL_ROOT_PASSWORD: root
      ports:
       - ${DEV_IP}:3306:3306
      volumes:
       - mariadb:/var/lib/mysql

  sftp:
#      image: rlesouef/alpine-sftp
      image: sjourdan/alpine-sshd
      ports:
          - '${DEV_IP}:2222:22'
      environment:
        - USER=foo
        - PASSWORD=pass
        # Should be the same as the volume mapping of app container
        # - FOLDER=/data
        # Optional: chroot
        # - CHROOT=1
#      volumes:
#        - /var/run/docker.sock:/var/run/docker.sock
#          - ./tests/Manual/upload:/home/foo/upload
#          - ./tests/Manual/download:/home/foo/download
#      command: foo:pass:${DEV_UID}

volumes:
  mongo: {}
  mariadb: {}
  rabbit-mq: {}
