version: '2'
services:
  php-dev:
    image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/srv/project
      - ../:/srv/libs
      - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
      - ./topology:${GENERATOR_PATH}
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - COMPOSER_HOME=/home/dev/.composer
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - GENERATOR_PATH=${GENERATOR_PATH}
      - PROJECT_SOURCE_PATH=${PROJECT_SOURCE_PATH}
    depends_on:
      - mongo
      - rabbitmq
      - smtp
      - redis
    links:
      - mongo
      - rabbitmq
      - smtp

  nginx:
    image: nginx
    ports:
      - ${DEV_IP}:8000:8000
    depends_on:
      - php-dev
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/srv/project

  smtp:
    image: mailhog/mailhog
    ports:
      - ${DEV_IP}:1025:1025
      - ${DEV_IP}:8025:8025

  mongo:
      image: mongo:latest
      ports:
        - ${DEV_IP}:27017:27017
      volumes:
        - mongo:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    volumes:
       - rabbit-mq:/var/lib/rabbitmq
    ports:
      - ${DEV_IP}:15672:15672
      - ${DEV_IP}:5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

  mariadb:
      image: mariadb:10.3
      command: "mysqld --innodb_flush_method=nosync"
      environment:
       MYSQL_ROOT_PASSWORD: root
      ports:
       - ${DEV_IP}:3306:3306
      volumes:
       - mariadb:/var/lib/mysql

  redis:
    image: redis:3.2-alpine
    ports:
      - ${DEV_IP}:6379:6379
    volumes:
      - redis:/data

volumes:
  mongo: {}
  mariadb: {}
  rabbit-mq: {}
  redis: {}
