version: '2.2'
services:
  consumer:
    image: dkr.hanaboso.net/pipes/notification-sender:dev
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /var/www/notification-sender
    environment:
      - APP_ENV=dev
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
    volumes:
      - ./:/var/www/notification-sender
      - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
    command: bash -c 'while ! [ -f vendor/autoload.php ];do sleep 1; echo "sleep 1"; done; bin/console rabbit_mq:consumer:notification'

  app:
    image: dkr.hanaboso.net/pipes/notification-sender:dev
    user: ${DEV_UID}:${DEV_GID}
    ports:
      - ${DEV_IP}:8000:80
    volumes:
      - ./:/var/www
      - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
    environment:
      - APP_ENV=dev
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - ${DEV_IP}:27017:27017
    volumes:
      - mongodb:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${DEV_IP}:15672:15672
      - ${DEV_IP}:5672:5672

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${DEV_IP}:8025:8025

volumes:
  mongodb: {}
