---
version: '3'

services:
  app:
    image: hanabosocom/go-base:1.18
    working_dir: /limiter
    environment:
      - MONGO_HOST=mongodb
      - RABBITMQ_HOST=rabbitmq
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5120
    volumes:
      - ./:/limiter
    command: bash -c 'sleep infinity'

  rabbitmq:
    image: rabbitmq:management-alpine

  mongodb:
      image: mongo:latest
      ports:
        - ${DEV_IP}:27017:27017
      volumes:
        - mongodb:/data/db

  logstash:
    image: kedlas/udplogger:latest

volumes:
    mongodb:
    rabbitmq:

