version: '2'
services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
  redis:
    image: 'redis:alpine'
  influxdb:
    image: 'influxdb:alpine'
  mongo:
    image: 'mongo:3.4'
  # logstash dummy (tests fail on nonexistent hostname)
  logstash:
    image: busybox

  test:
      image: node:14-alpine
      user: ${DEV_UID}:${DEV_GID}
      working_dir: /srv/app
      volumes:
      - ./:/srv/app
      environment:
        - RABBITMQ_HOST=rabbitmq
        - REDIS_HOST=redis
        - MONGO_HOST=mongo
        - METRICS_HOST=influxdb
        - METRICS_PORT=8086
        - NPM_CONFIG_CACHE=/tmp
      depends_on:
        - rabbitmq
        - redis
        - mongo
        - influxdb
        - logstash
      command: sleep infinity
