services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $mapperHandler: '@hbpf.mapper.handler.mapper'

    Hanaboso\PipesFramework\HbPFMapperBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']