services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFMapperBundle\Controller\MapperController:
        class: Hanaboso\PipesFramework\HbPFMapperBundle\Controller\MapperController
        arguments:
            - '@hbpf.mapper.handler.mapper'