services:
    hbpf.mapper.loader.mapper:
        class: Hanaboso\PipesFramework\HbPFMapperBundle\Loader\MapperLoader
        arguments:
            - '@service_container'

    hbpf.mapper.handler.mapper:
        class: Hanaboso\PipesFramework\HbPFMapperBundle\Handler\MapperHandler
        arguments:
            - '@hbpf.mapper.loader.mapper'

    hbpf.mapper.null:
        class: Hanaboso\PipesFramework\Mapper\Impl\NullMapper
        arguments:
