---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipes-secrets
data:
  license: ""
  backend_jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  backend_x_auth_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  crypt_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  email_dsn: "gmail://xxxx@yyyyyy.zz:aaaaaaaaaaaaa@localhost"

  mongodb_database: pipes
  mongodb_auth_and_hosts: pipes-mongodb
  mongodb_db_and_opts: pipes

  # we need at least one "?", because "&..." is being appended in some places
  mongodb_dsn: mongodb://pipes-mongodb/pipes?readPreference=primary

  rabbitmq_dsn: amqp://guest:guest@pipes-rabbitmq:5672/
  rabbitmq_host: pipes-rabbitmq
  rabbitmq_port: "5672"
  rabbitmq_vhost: ""
  rabbitmq_user: guest
  rabbitmq_password: guest

  # this value is currently unchangeable (see chart todos)
  metrics_db: metrics

  elasticsearch_dsn: http://pipes-elasticsearch:9200
