global:
  frontend_url: https://pipes.example.com
  backend_url: https://backend.pipes.example.com
  starting_point_url: http://starting-point.pipes.example.com

  alpha_go_bridge: false # also needs image overrides when enabled
  alpha_legacy: false

  imageRegistry:
    enablePullSecret: false
    server: docker.io
    path: hanaboso
    username: ""
    password: ""
  
  imageOverrides: {}
    # note: you can currently override image used in topologies only by changing images.bridge

  images:
    php-sdk: pipes-pf-bundle:master
    backend: pipes-pf-bundle:master
    status: status-service:dev
    frontend: pipes-frontend:master
    cron-api: pipes-cron:master

    bridge: pipes-pf-bridge:master
    counter: pipes-pf-bridge:master
    repeater: pipes-pf-bridge:master

    limiter: limiter:master
    multi-probe: pipes-multi-probe:master
    notification-sender: pipes-notification-sender:master
    starting-point: pipes-starting-point:master
    stream: stream:dev
    topology-api: pipes-topology-api-v2:master
    logstash: pipes-logstash-mongo:master
    kapacitor: kapacitor:master
    telegraf: pipes-telegraf:master
    logstash-fluentd-google: no-default-image-yet

  # Default global node selector
  nodeSelector: {}
  tolerations: []

  monitoring:
    useInfluxDB: true
    logStorage: elasticsearch

    # Used unly when logStorage is "google"
    # You must also add iam policy binding to that account:
    # gcloud iam service-accounts add-iam-policy-binding \
    #   --role roles/iam.workloadIdentityUser \
    #   --member "serviceAccount:PROJECT-ID.svc.id.goog[NAMESPACE/KSA-NAME]" \
    #   GSA-WITH-LOGS-WRITER-ROLE
    #
    # see https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to
    #
    googleServiceAccount: gsa-with-Logs-Writer-role

  api:
    serviceAnnotations: {}

  backend:
    checkInfinityLoop: true
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 512Mi
        cpu: 25m
      limits:
        memory: 1Gi
        cpu: "2"

  batchConnector:
    enabled: true
    replicaCount: 1
    nodeSelector: {}
    tolerations: []
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 25m
      limits:
        memory: 1Gi
        cpu: "2"

  cronApi:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: "1"

  frontend:
    serviceAnnotations: {}
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 128Mi
        cpu: "2"

  kapacitor:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: "2"

  limiter:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 25m
      limits:
        memory: 512Mi
        cpu: "2"

  logstash:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 1Gi
        cpu: 50m
      limits:
        memory: 1Gi
        cpu: "2"

  longRunningNode:
    enabled: true
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        memory: 1Gi
        cpu: "2"

  multiCounter:
    progressSave: true
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: "2"

  multiProbe:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: "2"

  notificationSender:
    # values for backward compat, will be reset
    apiResources:
      requests:
        memory: 128Mi
        cpu: "25m"
      limits:
        memory: 512Mi
        cpu: "1"
    consumerResources:
      requests:
        memory: 128Mi
        cpu: "25m"
      limits:
        memory: 512Mi
        cpu: "1"

  phpSdk:
    extraEnv: {}
#     FOO:
#       value: bar

  repeater:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 25m
      limits:
        memory: 128Mi
        cpu: "2"

  startingPoint:
    serviceAnnotations: {}
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: "2"

  status:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 25m
      limits:
        memory: 128Gi
        cpu: "2"

  telegraf:
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: "2"

  topologyApi:
    manageServiceAccount: true
    manageRBAC: true
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        memory: 256Mi
        cpu: "1"
    topologiesResources:
      defaultRequestCpu: 100m
      defaultRequestMemory: 128Mi
      defaultLimitCpu: 1000m
      defaultLimitMemory: 512Mi
    topologiesExtraEnv: {}
#     FOO:
#       value: bar

  worker:
    hostPathMounts: []
    nodeSelector: {}
    tolerations: []
    # values for backward compat, will be reset
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 4Gi
        cpu: "4"


nameOverride: ""
fullnameOverride: ""
