global:
  backend_url: https://pipes-api.example.com
  frontend_url: https://pipes-ui.example.com

  imageRegistry:
    enablePullSecret: true
    server: dkr.hanaboso.net
    path: pipes/pipes
    username: ""
    password: ""
  
  imageOverrides: {}
    # note: you can currently override image used in topologies only by changing images.bridge

  images:
    monolith: monolith:master
    frontend: frontend:dev
    cron-api: cron:master
    bridge: pf-bridge:master
    multi-probe: multi-probe:dev
    notification-sender: notification-sender:master
    starting-point: starting-point:master
    stream: stream:dev
    topology-api: topology-api-v2:master
    logstash: logstash:master
    kapacitor: kapacitor:master
    telegraf: rabbitmq-telegraf:master

  monitoring:
    useInfluxDB: true

  api:
    serviceAnnotations: {}

  batch:
    enabled: true

  frontend:
    serviceAnnotations: {}

  logstash:
    enabled: true

  longRunningNode:
    enabled: true

  monolith:
    extraEnv: []

  startingPoint:
    serviceAnnotations: {}

  topology:
    manageServiceAccount: true
    manageRBAC: true

nameOverride: ""
fullnameOverride: ""
