global:
  frontend_url: https://pipes.example.com
  backend_url: https://backend.pipes.example.com
  starting_point_url: http://starting-point.pipes.example.com

  imageRegistry:
    enablePullSecret: false
    server: docker.io
    path: hanaboso
    username: ""
    password: ""
  
  imageOverrides: {}
    # note: you can currently override image used in topologies only by changing images.bridge

  images:
    php-sdk: pipes-pf-bundle:master
    backend: pipes-pf-bundle:master
    frontend: pipes-frontend:master
    cron-api: pipes-cron:master
    bridge: pipes-pf-bridge:master
    limiter: limiter:master
    multi-probe: pipes-multi-probe:master
    notification-sender: pipes-notification-sender:master
    starting-point: pipes-starting-point:master
    stream: stream:dev
    topology-api: pipes-topology-api-v2:master
    logstash: pipes-logstash-mongo:master
    kapacitor: kapacitor:master
    telegraf: pipes-telegraf:master
    logstash-fluentd-google: no-default-image-yet

  monitoring:
    useInfluxDB: true
    logStorage: elasticsearch

    # Used unly when logStorage is "google"
    # You must also add iam policy binding to that account:
    # gcloud iam service-accounts add-iam-policy-binding \
    #   --role roles/iam.workloadIdentityUser \
    #   --member "serviceAccount:PROJECT-ID.svc.id.goog[NAMESPACE/KSA-NAME]" \
    #   GSA-WITH-LOGS-WRITER-ROLE
    #
    # see https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to
    #
    googleServiceAccount: gsa-with-Logs-Writer-role

  api:
    serviceAnnotations: {}

  backend:
    checkInfinityLoop: true

  frontend:
    serviceAnnotations: {}

  longRunningNode:
    enabled: true

  multiCounter:
    progressSave: true

  phpSdk:
    extraEnv: {}
#     FOO:
#       value: bar

  startingPoint:
    serviceAnnotations: {}

  topology:
    manageServiceAccount: true
    manageRBAC: true

  worker:
    hostPathMounts: []


nameOverride: ""
fullnameOverride: ""
