services:

    hbpf.custom_node.user-message-generator:
        class: CleverConnectors\AppBundle\Model\CustomNode\UserMessageGenerator
        arguments:
            - '@jms_serializer'
            - '@clever_connector.async_command_factory'
        calls:
            - [setLogger, ['@monolog.logger.rabbit-mq']]

    hbpf.custom_node.refresh-tokens-message-generator:
        class: CleverConnectors\AppBundle\Model\CustomNode\TokenMessageGenerator
        arguments:
            - '@jms_serializer.serializer'
            - '@clever_connector.async_command_factory'
        calls:
            - [setLogger, ['@monolog.logger.rabbit-mq']]

    hbpf.custom_node.token-refresher:
        class: CleverConnectors\AppBundle\Model\CustomNode\TokenRefresher
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.systems.loader'

    hbpf.custom_node.starting-progress:
        class: CleverConnectors\AppBundle\Model\CustomNode\StartingProgress
        arguments:
            - '@cc.progress_counter.progress_counter_service'


    hbpf.custom_node.progress-incrementer:
        class: CleverConnectors\AppBundle\Model\CustomNode\ProgressIncrementer
        arguments:
            - '@cc.progress_counter.progress_counter_service'

    hbpf.custom_node.cm-event-activator:
        class: CleverConnectors\AppBundle\Model\CMEvents\CMEventActivator
        arguments:
            - '@cc.systems.manager'
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.async_curl_factory'
            - '@rabbit-mq.producer.cm_activator_stream'
