services:

    systems.null.user:
        class: Tests\Integration\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
            - '@hbpf.providers.oauth2_provider'
        tags: ['%systems%', '%systems.dev%', '%systems.user.some_user%']

    systems.null.group:
        class: Tests\Integration\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
            - '@hbpf.providers.oauth2_provider'
        tags: ['%systems%', '%systems.dev%', '%systems.group.some_group%']

    systems.null.user.group:
        class: Tests\Integration\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
            - '@hbpf.providers.oauth2_provider'
        tags: ['%systems%', '%systems.dev%', '%systems.user.some_user%', '%systems.group.some_group%']


    hbpf.connector.test-forward-connector:
        class: CleverConnectors\AppBundle\Model\CM\TestForwardConnector\CMTestForwardConnector

    hbpf.connector.test-repeater-connector:
        class: CleverConnectors\AppBundle\Model\CM\TestRepeaterConnector\CMTestRepeaterConnector
        arguments:
            - '@snc_redis.default'

    hbpf.custom_node.test-notification-connector:
        class: CleverConnectors\AppBundle\Model\CM\TestNotificationConnector\CMTestNotificationConnector
        arguments:
        calls:
            - [setLogger, ['@monolog.logger.notification']]
