services:

    cc.topology.listener:
        class: CleverConnectors\AppBundle\Listeners\TopologyEventListener
        arguments:
            - '@hbpf.configurator.handler.topology'
        tags: ['kernel.event_subscriber']

    cc.progress_counter.listener:
        class: CleverConnectors\AppBundle\Listeners\ProgressCounterListener
        arguments:
            - '@cc.progress_counter.progress_counter_service'
        tags: ['kernel.event_subscriber']

    cc.webhook.security.listener:
        class: CleverConnectors\AppBundle\Listeners\WebhookSecurityListener
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.transport.curl.manager'
            - '@cc.system_limit.manager'
            - '@cc.systems.loader'
        tags: ['kernel.event_subscriber']

    cc.plugins.security.listener:
        class: CleverConnectors\AppBundle\Listeners\PluginsSecurityListener
        arguments:
            - '@cc.plugins.security_manager'
            - '@cc.transport.curl.manager'
        tags: ['kernel.event_subscriber']