services:
    systems.controller:
        class: CleverConnectors\AppBundle\Controller\SystemController
        arguments:
            - '@systems.handler'

    systems.handler:
        class: CleverConnectors\AppBundle\Handler\SystemHandler
        arguments:
            - '@systems.manager'
            - '@doctrine_mongodb.odm.default_document_manager'

    systems.manager:
        class: CleverConnectors\AppBundle\Model\Systems\SystemManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@systems.loader'
            - '@manager.webhook'

    systems.loader:
        class: CleverConnectors\AppBundle\Model\Systems\SystemLoader
        arguments:
            - '@service_container'

    manager.webhook:
        class: CleverConnectors\AppBundle\Model\WebhookManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%webhook.domain%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    cc.controller.webhook:
        class: CleverConnectors\AppBundle\Controller\WebhookController
        arguments:
            - '@hbpf.handler.starting_point'

    listener.controller.security:
        class: CleverConnectors\AppBundle\Listeners\WebhookSecurityListener
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%clevermonitor%'
        tags: ['kernel.event_subscriber']

    hbpf.connector.cleverconnectors-subscriptions-create:
        class: CleverConnectors\AppBundle\Model\CM\SubscriptionConnector\CMCreateSubscriptionConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%clevermonitor%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.connector.cleverconnectors-subscriptions-update:
        class: CleverConnectors\AppBundle\Model\CM\SubscriptionConnector\CMUpdateSubscriptionConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%clevermonitor%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.connector.cleverconnectors-subscriptions-delete:
        class: CleverConnectors\AppBundle\Model\CM\SubscriptionConnector\CMDeleteSubscriptionConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%clevermonitor%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.connector.cleverconnectors-forward-connector:
        class: CleverConnectors\AppBundle\Model\CM\TestForwardConnector\CMTestForwardConnector

    systems.salesforce:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\SalesForce\SalesForceSystem
        arguments:
            - '@hbpf.providers.oauth2_provider'
        tags: ['%systems%']

    systems.shopify:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\Shopify\ShopifySystem
        arguments:
            - '@hbpf.providers.oauth2_provider'
        tags: ['%systems%']

    hbpf.connectors.shopify-customer-create:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\Shopify\ShopifyCreateCustomerConnector
        arguments:

    hbpf.connectors.shopify-customer-update:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\Shopify\ShopifyUpdateCustomerConnector
        arguments:

    hbpf.connectors.shopify-customer-delete:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\Shopify\ShopifyDeleteCustomerConnector
        arguments:

    hbpf.custom_node.shopify-customer-update-mapper:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\Shopify\ShopifyUpdateCustomerMapper
        arguments:

    hbpf.custom_node.shopify-customer-delete-mapper:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\Shopify\ShopifyDeleteCustomerMapper
        arguments:

    hbpf.custom_node.user-message-generator:
        class: CleverConnectors\AppBundle\Model\CustomNode\UserMessageGenerator
        arguments:
            - '@jms_serializer'
            - '%kernel.project_dir%'
        calls:
            - [setLogger, ['@monolog.logger.rabbit-mq']]
