services:
    _defaults:
        public: '%public.services%'

    cc.systems.controller:
        class: CleverConnectors\AppBundle\Controller\SystemController
        arguments:
            - '@cc.systems.handler'

    cc.systems.handler:
        class: CleverConnectors\AppBundle\Handler\SystemHandler
        arguments:
            - '@cc.systems.manager'
            - '@doctrine_mongodb.odm.default_document_manager'

    cc.systems.manager:
        class: CleverConnectors\AppBundle\Model\Systems\SystemManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.systems.loader'
            - '@cc.webhook.manager'
            - '@hbpf.topology_generator.request.request_handler'
            - '@cc.events.manager'
            - '@cc.map_template.manager'
            - '@cc.layout.manager'
            - '@cc.system_metrics.manager'
            - '@cc.system_limit.manager'
            - '@cc.system_topology.runner'

    cc.systems.loader:
        class: CleverConnectors\AppBundle\Model\Systems\SystemLoader
        arguments:
            - '@service_container'

    cc.system_limit.manager:
        class: CleverConnectors\AppBundle\Model\Limits\SystemLimitManager
        arguments:
            - '@cc.systems.loader'
            - '@cc.system_topology.runner'
            - '@doctrine_mongodb.odm.default_document_manager'
            - '%limit_refresh_interval%'

    cc.system_topology.runner:
        class: CleverConnectors\AppBundle\Model\Systems\SystemTopologyRunner
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.starting_point.starting_point'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    cc.last_sync.manager:
        class: CleverConnectors\AppBundle\Model\LastSync\LastSyncManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    cc.events.controller:
        class: CleverConnectors\AppBundle\Controller\CMEventsController
        arguments:
            - "@cc.events.handler"

    cc.events.handler:
        class: CleverConnectors\AppBundle\Handler\CMEventsHandler
        arguments:
            - "@cc.events.manager"

    cc.events.manager:
        class: CleverConnectors\AppBundle\Model\CMEvents\CMEventsManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.systems.loader'
            - '@cc.system_limit.manager'
            - '@cc.system_topology.runner'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    cc.progress_counter.sync_publisher:
        class: CleverConnectors\AppBundle\Model\ProgressCounter\Publisher\SyncPublisher
        arguments:
            - "@rabbit-mq.producer.progress_counter"

    cc.progress_counter.async_publisher:
        class: CleverConnectors\AppBundle\Model\ProgressCounter\Publisher\AsyncPublisher
        arguments:
            - '@rabbit-mq.manager'

    cc.progress_counter.progress_counter_service:
        class: CleverConnectors\AppBundle\Model\ProgressCounter\ProgressCounterService
        arguments:
            - '@snc_redis.default'
            - '@cc.progress_counter.sync_publisher'

    cc.progress_counter.async_progress_counter_service:
        class: CleverConnectors\AppBundle\Model\ProgressCounter\ProgressCounterService
        arguments:
            - '@snc_redis.default'
            - '@cc.progress_counter.async_publisher'

    cc_plugins.plugins.controller:
        class: CleverConnectors\AppBundle\Controller\PluginsController
        arguments:
            - '@cc.plugins.handler'

    cc.plugins.security_manager:
        class: CleverConnectors\AppBundle\Model\Plugins\PluginsSecurityManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    cc.plugins.manager:
        class: CleverConnectors\AppBundle\Model\Plugins\PluginsManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.systems.manager'
            - '@cc.systems.loader'
            - '@hbpf.connector.cleverconnectors-get-distributions-connector'
            - '@cc.system_topology.runner'
            - '@hbpf.connector.cleverconnectors-create-distributionlist-connector'

    cc.plugins.handler:
        class: CleverConnectors\AppBundle\Handler\PluginsHandler
        arguments:
            - '@cc.plugins.manager'
            - '@cc.plugins.security_manager'

    cc.transport.curl.manager:
        class: CleverConnectors\AppBundle\Transport\Curl\CMCurlManager
        arguments:
            - '@hbpf.transport.curl_client_factory'
            - '@hbpf.influxdb_sender_connector'
            - '%clevermonitor%'

    cc.install.manager:
        class: CleverConnectors\AppBundle\Model\Installer\InstallManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@snc_redis.default'
            - '@hbpf.configurator.manager.topology'
            - '@hbpf.topology_generator.request.request_handler'
            - '@cc.category.parser'
            - ['%connectors_topologies%', '%plugins_topologies%', '%service_topologies%']
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    cc.layout.controller:
        class: CleverConnectors\AppBundle\Controller\LayoutController
        arguments:
            - '@cc.layout.handler'

    cc.layout.handler:
        class: CleverConnectors\AppBundle\Handler\LayoutHandler
        arguments:
            - '@cc.layout.manager'
            - '@cc.systems.manager'

    cc.layout.manager:
        class: CleverConnectors\AppBundle\Model\DataLayout\LayoutManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.systems.loader'

    cc.map_template.controller:
        class: CleverConnectors\AppBundle\Controller\MapController
        arguments:
            - '@cc.map_template.handler'

    cc.map_template.handler:
        class: CleverConnectors\AppBundle\Handler\MapHandler
        arguments:
            - '@cc.map_template.manager'
            - '@cc.systems.manager'

    cc.map_template.manager:
        class: CleverConnectors\AppBundle\Model\MapTemplate\MapManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@cc.systems.loader'

    cc.category.parser:
        class: CleverConnectors\AppBundle\Model\Installer\CategoryParser
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.configurator.manager.category'
        calls:
        - ['addRoot',['Systems',"%connectors_topologies%"]]
        - ['addExclude', ['Systems','Topologies']]
        - ['addRoot',['Plugins',"%plugins_topologies%"]]
        - ['addRoot',['Service',"%service_topologies%"]]

    cc.elastica.client:
        class: Elastica\Client
        arguments:
            - { host: '%elastic_host%' }

    cc.system_metrics.manager:
        class: CleverConnectors\AppBundle\Model\SystemMetrics\SystemMetrics
        arguments:
            - '@cc.elastica.client'
            - '%elastic_index%'

    cc.default.controller:
        class: CleverConnectors\AppBundle\Controller\DefaultController