export const NOTIFICATIONS = {
  NAMESPACE: 'notifications',
  ACTIONS: {
    GET_NOTIFICATION_LIST_REQUEST: 'GET_NOTIFICATION_LIST_REQUEST',
    GET_NOTIFICATION_EVENTS_REQUEST: 'GET_NOTIFICATION_EVENTS_REQUEST',
    UPDATE_NOTIFICATIONS_REQUEST: 'UPDATE_NOTIFICATIONS_REQUEST',
  },
  MUTATIONS: {
    RESET: 'RESET',
    GET_NOTIFICATION_LIST_RESPONSE: 'GET_NOTIFICATION_LIST_RESPONSE',
    GET_NOTIFICATION_EVENTS_RESPONSE: 'GET_NOTIFICATION_EVENTS_RESPONSE',
  },
  GETTERS: {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    GET_EVENTS: 'GET_EVENTS',
  },
}

export const NOTIFICATION_TYPES = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
}
