services:
    hbpf.notification.controller.notification:
        class: Hanaboso\PipesFramework\HbPFNotificationBundle\Controller\NotificationController
        arguments:
            - '@hbpf.notification.handler.notification'
