services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $notificationHandler: '@hbpf.notification.handler.notification'

    Hanaboso\PipesFramework\HbPFNotificationBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
