services:
    hbpf.notification.handler.notification:
        class: Hanaboso\PipesFramework\HbPFNotificationBundle\Handler\NotificationHandler
        arguments:
            - '@hbpf.notification.manager.notification'

    hbpf.notification.manager.notification:
        class: Hanaboso\PipesFramework\Notification\Model\NotificationManager
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%notification_host%'
