apiVersion: v2
name: hanaboso1
description: Hanaboso1 Orchesty Implementation
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: orchesty
    version: "~2.1.13"
    repository: "https://orchesty.github.io/helm-charts/"
