---

orchesty:
  # force legacy resource names
  nameOverride: pipes

global:
  backend_url: https://api-hm8rohmtf6.eu1.cloud.orchesty.io
  frontend_url: https://ui-hm8rohmtf6.eu1.cloud.orchesty.io
  starting_point_url: https://start-hm8rohmtf6.eu1.cloud.orchesty.io

  imageOverrides:
    nodejssdk: hanaboso/demo-nodejs:master

  nodejsSdk:
    extraEnv:
      APP_ENV: debug
      AWS_SES_KEY:
        valueFrom:
          secretKeyRef:
            name: pipes-secrets
            key: aws_ses_key
      AWS_SES_SECRET:
        valueFrom:
          secretKeyRef:
            name: pipes-secrets
            key: aws_ses_secret

  backend:
    alpha_instance_id: hm8rohmtf6

