---

orchesty:
  # force legacy resource names
  nameOverride: pipes

  valkey:
    enabled: true

global:
  orchestyVersion: "2.1"
  backend_url: https://api-hm8rohmtf6.eu1.cloud.orchesty.io
  frontend_url: https://ui-hm8rohmtf6.eu1.cloud.orchesty.io
  starting_point_url: https://start-hm8rohmtf6.eu1.cloud.orchesty.io

  imageOverrides:
    applinth-marketplace-ui: dkr.hanaboso.net/pipes/pipes/applinth-marketplace-ui:2.1
    backend: dkr.hanaboso.net/pipes/pipes/applinth:2.1

  workers:
    default:
      sdk: nodejs
      image: hanaboso/demo-nodejs:master
      extraEnv:
        APP_ENV:
          value: debug
        AWS_SES_KEY:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: aws_ses_key
        AWS_SES_SECRET:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: aws_ses_secret
        MONGO_DSN:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: mongodb_dsn

    laborer:
      sdk: nodejs
      image: dkr.hanaboso.net/north-dent/laboratory/orchesty/worker:master
      extraEnv:
        APP_ENV:
          value: debug
        REDIS_DSN:
          value: redis://pipes-valkey

  backend:
    alpha_instance_id: hm8rohmtf6
  
  metricsCollector:
    enabled: true

  applinthMarketplaceUI:
    auth_backlink: https://example.com/foo
