apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "applinth-api.fullname" . }}
  labels:
    {{- include "applinth-api.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gceWorkloadSA }}
