---
version: '3'

services:
  multi-probe:
    image: golang:latest
    working_dir: /go/src/hanaboso.com/multi-probe
    volumes:
      - ../:/go/src/hanaboso.com
    command: bash -c 'sleep infinity'
