version: "3.5"
services:
  console-api:
    image: console-api:tag
    build: ../saas/console-api/docker
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /var/www/saas/console-api
    ports:
      - ${DEV_IP}:3000:3000
    volumes:
      - ../saas/console-api/:/var/www
    environment:
      # Envs for tests are load from .jest/testEnvs.js
      JEST_DOCKER: 1
      NODE_ENV: "debug"
      MONGODB_DSN: mongodb://mongo
      FIREBASE_API_KEY: AIzaSyANIRePUXX1f8fr-IS2ljSU8FgLkC53a0o
      USCCP_URI: 'http://usscp'
      CLOUD_CONTROLLER_URI: 'http://cloud_controller'
    command: sh -c 'pnpm install && pnpm start'

  mongo:
    image: mongo:latest
    ports:
      - ${DEV_IP}:27017:27017
    volumes:
      - mongo:/data/db

  applinth-admin-ui:
    image: hanabosocom/nodejs-build:dev
    working_dir: /var/www/applinth-admin-ui
    environment:
      VUE_APP_BACKEND_URL: http://${DEV_IP}:3000
    ports:
      - ${DEV_IP}:83:8080
      - ${DEV_IP}:4010:4010
    volumes:
      - ./../:/var/www:cached
    command: sh -c 'pnpm install && pnpm start'

volumes:
  mongo: {}
