parameters:
    # FTP
    ftp.host: ''
    ftp.port: 21
    ftp.ssl: false
    ftp.timeout: 15
    ftp.user: ''
    ftp.password: ''

    # SFTP
    sftp.host: ''
    sftp.port: 22
    sftp.timeout: 15
    sftp.user: ''
    sftp.password: ''

    cron_host: "%env(string:CRON_DSN)%"
    starting_point_host: "%env(string:STARTING_POINT_DSN)%"

    env(REDIS_DSN): "redis://redis"
    redis_dsn: '%env(string:REDIS_DSN)%'