security:
    encoders:
        Hanaboso\UserBundle\Document\User:
            algorithm: auto
            cost: 12
    providers:
        user_provider:
            mongodb:
                class: Hanaboso\UserBundle\Document\User
                property: email
        api_provider:
            mongodb:
                class: Hanaboso\UserBundle\Document\User
                property: email
    firewalls:
        unsecured_user_api:
            pattern: ^/(api/user/login|api/user/logout|api/user/\w+/activate|api/user/\w+/set_password|api/user/reset_password|api/user/register)
            security: false
        unsecured_applications:
            pattern: ^/api/applications/.*/(sync|users)/.*
            stateless: true
            provider: api_provider
            guard:
                authenticators:
                    - hbpf.authenticator.api_key
        secured_area:
            pattern: ^/
            security: true
            provider: user_provider
            form_login:
                check_path: /api/user/login
                login_path: /api/user/login
                default_target_path: /

            logout:
                path: /api/user/logout
                target: /
                invalidate_session: true
                success_handler: hbpf.user.handler.user
        main:
            anonymous: ~
