---
version: '3'

services:
    utils:
        image: golang:latest
        working_dir: /go/src/hanaboso.com/utils
        volumes:
          - ../:/go/src/hanaboso.com/
        command: bash -c 'sleep infinity'