---
mongodbBillingDB: "usage-stats"
mongodbCloudDB: "cloud"

firebaseAuthDomain: orchesty.io
# firebaseAuthDomain: orchesty-cloud-prod.firebaseapp.com

usccpUri: https://usccp.cloud.orchesty.io
cloudControllerUri: https://controller.cloud.orchesty.io

image:
  repository: dkr.hanaboso.net/pipes/pipes/cloud-applinth-api
  tag: master

serviceAccount:
  gceWorkloadSA: workload-cc-applinth-api@orchesty-cloud-prod.iam.gserviceaccount.com
