---
mongodbBillingDB: "usage-stats"
mongodbCloudDB: "cloud"

firebaseAuthDomain: orchesty.io
# firebaseAuthDomain: orchesty-cloud-prod.firebaseapp.com

image:
  repository: dkr.hanaboso.net/pipes/pipes/cloud-applinth-api
  tag: master

serviceAccount:
  gceWorkloadSA: workload-cc-applinth-api@orchesty-cloud-prod.iam.gserviceaccount.com
