services:

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - cs_CZ

    doctrine.orm.security.user.provider:
        class: Symfony\Bridge\Doctrine\Security\User\EntityUserProvider
        arguments:
            - "@doctrine_mongodb"


imports:
## Import params
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file