services:
    router:
        class: Symfony\Bundle\FrameworkBundle\Routing\Router
        arguments:

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - cs_CZ

    security.encoder_factory:
        class: Symfony\Component\Security\Core\Encoder\EncoderFactory
        arguments:
            - Hanaboso\PipesFramework\User\Document\User:
                class: Symfony\Component\Translation\Translator
                algorithm: bcrypt
                cost: 12

imports:
## Import params
    - { resource: parameters.yml }

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: mongodb://mongo
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: pipes
    document_managers:
        default:
            mappings:
                UserDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/User/Document"
                    prefix: Hanaboso\PipesFramework\User\Document
                AuthorizationsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/Authorization/Document"
                    prefix: Hanaboso\PipesFramework\Authorization\Document
                MongoFileDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/Commons/FileStorage/Driver"
                    prefix: Hanaboso\PipesFramework\Commons\FileStorage\Driver
            metadata_cache_driver: array
