services:
    router:
        class: Symfony\Bundle\FrameworkBundle\Routing\Router
        arguments:

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - cs_CZ

    security.encoder_factory:
        class: Symfony\Component\Security\Core\Encoder\EncoderFactory
        arguments:
            - Hanaboso\PipesFramework\User\Document\User:
                class: Symfony\Component\Translation\Translator
                algorithm: bcrypt
                cost: 12

imports:
## Import params
    - { resource: parameters.yml }
