services:

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - cs_CZ

    doctrine.orm.security.user.provider:
        class: Symfony\Bridge\Doctrine\Security\User\EntityUserProvider
        arguments:
            - "@doctrine_mongodb"


imports:
## Import params
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: rabbit-mq.yml }

framework:
    #esi: ~
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    csrf_protection:
        enabled: false
    default_locale: "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    fragments: ~
    http_method_override: true
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~

swiftmailer:
    transport: null
    host: smtp
    port: 1025
    username: ''
    password: ''
