services:

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - cs_CZ

    doctrine.orm.security.user.provider:
        class: Symfony\Bridge\Doctrine\Security\User\EntityUserProvider
        arguments:
            - "@doctrine_mongodb"


imports:
## Import params
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi: ~
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    csrf_protection:
        enabled: false
    default_locale: "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    fragments: ~
    http_method_override: true
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~

swiftmailer:
    transport: null
    host: smtp
    port: 1025
    username: ''
    password: ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     'mariadb'
                dbname:   'pipes'
                user:     'root'
                password: 'root'
    orm:
        default_entity_manager: ~
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        connection: default
        mappings:
            HbPFCommonsBundle: ~
        proxy_dir: "%kernel.cache_dir%/doctrine/orm/Proxies"
        proxy_namespace: Proxies

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%mongo_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: pipes
    document_managers:
        default:
            mappings:
                MongoFileDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/Commons/FileStorage/Driver"
                    prefix: Hanaboso\PipesFramework\Commons\FileStorage\Driver
                FileDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/Commons/FileStorage/Document"
                    prefix: Hanaboso\PipesFramework\Commons\FileStorage\Document
                ConfiguratorDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/Configurator/Document"
                    prefix: Hanaboso\PipesFramework\Configurator\Document
            metadata_cache_driver: array
