services:

    router:
        class: Symfony\Bundle\FrameworkBundle\Routing\Router
        arguments:

    translator:
        class: Translator
        arguments:

imports:
## Import params
    - { resource: parameters.yml }

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: mongodb://mongo
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: pipes
    document_managers:
        default:
            mappings:
                UserDocument:
                    type: annotation
                    dir: "%kernel.root_dir%/../src/User/Document"
                    is_bundle: false
                    prefix: Hanaboso\PipesFramework\User\Document
                AuthorizationsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/Authorizations/Document"
                    prefix: Hanaboso\PipesFramework\Authorizations\Document
            metadata_cache_driver: array
