parameters:
    # Base params
    locale: en

    # A secret key that's used to generate certain security-related tokens
    kernel.secret: ThisTokenIsNotSoSecretChangeIt

    logger_handler: syslog

    request_listener.http_port: 80
    request_listener.https_port: 80