parameters:
    # Base params
    locale: en

    # A secret key that's used to generate certain security-related tokens
    secret: ThisTokenIsNotSoSecretChangeIt

    stdout_path: "%kernel.logs_dir%/stdout_%kernel.environment%.log"

    request_listener.http_port: 80
    request_listener.https_port: 80

    # Rabbitmq
    rabbitmq.host: rabbitmq
    rabbitmq.port: 5672
    rabbitmq.vhost: /
    rabbitmq.user: guest
    rabbitmq.password: guest

    # FTP
    ftp.host: ''
    ftp.port: 21
    ftp.ssl: false
    ftp.timeout: 15
    ftp.user: ''
    ftp.password: ''

    # SFTP
    sftp.host: ''
    sftp.port: 22
    sftp.timeout: 15
    sftp.user: ''
    sftp.password: ''

    frontend_host: 127.0.0.1
    backend_host: 127.0.0.2