parameters:
    rabbitmq.host: 127.0.0.1
    rabbitmq.port: 5672
    rabbitmq.vhost: /
    rabbitmq.user: guest
    rabbitmq.password: guest

rabbit-mq:
    host: %rabbitmq.host%          # default: 127.0.0.1
    port: %rabbitmq.port%          # default: 5672
    vhost: %rabbitmq.vhost%        # default: /
    user: %rabbitmq.user%          # default: guest
    password: %rabbitmq.password%  # default: guest

    # make heartbeat as long as longest message processing time in any consumer might take
    heartbeat: 120 # in seconds = 2 minutes, default: 60 seconds

    exchanges:
        change:
            durable: true  # durable means exchange won't be deleted on broker restart
            type: topic    # topic exchanges route messages by given routing key
                     # see https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-topic
                     # other possible types: direct, fanout, headers

        change_done:
            durable: true
            type: topic
            bindings:
                - exchange: change  # RabbitMQ-specific functionality = exchange-to-exchange bindings
                  routing_key: "#"

        test_direct:
            durable: true
            type: direct

    queues:
        product_categorize:
            durable: true
            bindings:
                - exchange: change
                  routing_key: "change.product.#"

        test_consumer:
            durable: true
            bindings:
                - exchange: test_direct
                  routing_key: "*"

    producers:
        demo:
            class: Commons\RabbitMq\Demo\DemoProducer
            exchange: demo
            serializer: Commons\RabbitMq\Demo\DemoSerializer
            routing_key: demo

    consumers:
        demo:
            class: Commons\RabbitMq\Demo\DemoConsumer
            routing_key: '*'
            queue: demo
            no_local: false
            no_ack: false
            exclusive: false
            nowait: false
            arguments:
                 arg: 1
            prefetch_count: null
            prefetch_size: null
            serializer: Commons\RabbitMq\Demo\DemoSerializer
            set_up_method: null
            tick_method: null
            tick_seconds: null
            max_messages: null
            max_seconds: null


