parameters:
    rabbitmq.host: rabbitmq
    rabbitmq.port: 5672
    rabbitmq.vhost: /
    rabbitmq.user: guest
    rabbitmq.password: guest

rabbit-mq:
    host: '%rabbitmq.host%'          # default: 127.0.0.1
    port: '%rabbitmq.port%'          # default: 5672
    vhost: '%rabbitmq.vhost%'        # default: /
    user: '%rabbitmq.user%'          # default: guest
    password: '%rabbitmq.password%'  # default: guest

    # make heartbeat as long as longest message processing time in any consumer might take
    heartbeat: 120 # in seconds = 2 minutes, default: 60 seconds

imports:
    - { resource: rabbit-mq/repeater.yml }
    - { resource: rabbit-mq/demo.yml }
    - { resource: rabbit-mq/starting-point.yml }