hb_pf_mapper:
    resource: "@HbPFMapperBundle"
    type: annotation

hb_pf_joiner:
    resource: "@HbPFJoinerBundle"
    type: annotation

hb_pf_user:
    resource: "@HbPFUserBundle"
    type: annotation