hb_pf_authorization:
    resource: "@HbPFAuthorizationBundle"
    type: annotation

hb_pf_custom_node:
    resource: "@HbPFCustomNodeBundle"
    type: annotation

hb_pf_joiner:
    resource: "@HbPFJoinerBundle"
    type: annotation

hb_pf_mapper:
    resource: "@HbPFMapperBundle"
    type: annotation

hb_pf_table_parser:
    resource: "@HbPFTableParserBundle"
    type: annotation

hb_pf_user:
    resource: "@HbPFUserBundle"
    type: annotation