security:
    encoders:
        Hanaboso\PipesFramework\User\Document\User:
            algorithm: bcrypt
            cost: 15
    providers:
        user_provider:
            entity:
                class: Hanaboso\PipesFramework\User\Document\User
                property: email
    firewalls:
        unsecured_areas:
            pattern: ^/(api/user/login|api/user/logout|api/user/register|api/user/\w+/activate|/api/user/\w+/set_password|/api/user/reset_password)
            security: false
        secured_area:
            pattern: ^/
            security: true
            provider: user_provider
            form_login:
                check_path: /api/user/login
                login_path: /api/user/login
                default_target_path: /
            logout:
                path: /api/user/logout
                target: /
                invalidate_session: true
        main:
            anonymous: ~