export const GRID = {
  ACTIONS: {
    GRID_FETCH: 'GRID_FETCH',
    FETCH_WITH_DATA: 'FETCH_WITH_DATA',
    FETCH_WITH_INITIAL_STATE: 'FETCH_WITH_INITIAL_STATE',
    RESET: 'RESET',
  },
  MUTATIONS: {
    GRID_RESPONSE: 'GRID_RESPONSE',
    RESET: 'RESET',
  },
}
