services:
    app:
        image: hanabosocom/go-base:1.26
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 'true'
            BACKEND_URL: http://backend:80
        volumes:
            - .:/app:cached
            - ${GOPATH}/pkg:/go/pkg
        ports:
            - ${DEV_IP}:80:8080
            - ${DEV_IP}:2345:2345
        command: /run.sh -p cmd/trace.go -l 2345
        security_opt: ['seccomp:unconfined']

    bruno:
        image: ghcr.io/rbnis/bruno-cli
        entrypoint: ["tail", "-f", "/dev/null"]
        volumes:
            - ./bruno:/bruno

    backend:
        image: orchesty/backend:3.0-rc1
        environment:
            MONGODB_DSN: mongodb://mongo/trace
            MONGODB_DB: trace
            METRICS_DSN: mongodb://mongo/metrics
            METRICS_DB: metrics
            RABBITMQ_DSN: amqp://guest:guest@rabbitmq:5672
            BACKEND_URL: http://localhost
            FRONTEND_URL: http://localhost
            STARTING_POINT_URL: http://localhost
            TOPOLOGY_API_DSN: http://localhost
            CRON_DSN: http://localhost
            JWT_KEY: BWoCz4gxw3YHDMkqE5HD1WT2u6zqIAtiJkYVyf6UucL4ZtbhhatQooP5IgTQRwowYR6z8wE3biqZTl37

    mongo:
        image: mongo

    rabbitmq:
        image: rabbitmq:management-alpine
