services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFJoinerBundle\Controller\JoinerController:
        class: Hanaboso\PipesFramework\HbPFJoinerBundle\Controller\JoinerController
        arguments:
            - '@hbpf.handler.joiner'
        calls:
            - ['setContainer', ['@service_container']]
