services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $joinerHandler: '@hbpf.handler.joiner'

    Hanaboso\PipesFramework\HbPFJoinerBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']