services:
    _defaults:
        public: '%public.services%'

    hbpf.loader.joiner:
        class: Hanaboso\PipesFramework\HbPFJoinerBundle\Loader\JoinerLoader
        public: true
        arguments:
            - '@service_container'

    hbpf.joiner.null:
        class: Hanaboso\PipesFramework\Joiner\Impl\NullJoiner
        arguments: