# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.7
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%database_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: '%database_name%'
    document_managers:
        default:
            mappings:
                CCDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/AppBundle/Document"
                    prefix: CleverConnectors\AppBundle\Document
            filters:
                deleted:
                    class: CleverConnectors\AppBundle\Database\DeletedFilter
                    enabled: true