.base-cloud-trace-llm-worker:
  variables:
    DIR: cloud-trace-llm-worker
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}cloud-trace-llm-worker

cloud-trace-llm-worker:test:
  stage: test
  extends:
    - .base-test
    - .base-cloud-trace-llm-worker

cloud-trace-llm-worker:build:
  stage: build
  needs:
    - job: cloud-trace-llm-worker:test
      optional: false
  extends:
    - .base-dind-build
    - .base-cloud-trace-llm-worker
