parameters:
    resource_enum: Hanaboso\PipesFrameworkEnterprise\ResourceEnum
    action_enum: Hanaboso\PipesFrameworkEnterprise\Acl\Enum\ActionEnum
    resource_actions:
        default_actions: ['read']
        resources:
            topology: ['write', 'delete', 'run']
            scheduled_task: ['write']
            application: ['write', 'delete']
            user: ['write', 'delete']
            user_task: ['write']
            settings: ['write', 'delete']

    db_res:
        resources:
            # Add new resources to ResourceEnum class
            user: Hanaboso\UserBundle\Document\User
            tmp_user: Hanaboso\UserBundle\Document\TmpUser
            token: Hanaboso\UserBundle\Document\Token
            file: Hanaboso\CommonsBundle\FileStorage\Document\File
            group: Hanaboso\AclBundle\Document\Group
            rule: Hanaboso\AclBundle\Document\Rule
            node: Hanaboso\PipesFramework\Database\Document\Node
            topology: Hanaboso\PipesFramework\Database\Document\Topology
