parameters:
    resource_enum: Hanaboso\PipesFrameworkEnterprise\ResourceEnum
    action_enum: Hanaboso\AclBundle\Enum\ActionEnum
    resource_actions: []

    db_res:
        resources:
            # Add new resources to ResourceEnum class
            user: Hanaboso\UserBundle\Document\User
            tmp_user: Hanaboso\UserBundle\Document\TmpUser
            token: Hanaboso\UserBundle\Document\Token
            file: Hanaboso\CommonsBundle\FileStorage\Document\File
            group: Hanaboso\AclBundle\Document\Group
            rule: Hanaboso\AclBundle\Document\Rule
            node: Hanaboso\PipesFramework\Database\Document\Node
            topology: Hanaboso\PipesFramework\Database\Document\Topology
