security:
    password_hashers:
        Hanaboso\UserBundle\Document\User:
            algorithm: auto
            cost: 12
    providers:
        user_provider:
            mongodb:
                class: Hanaboso\UserBundle\Document\User
                property: email
    firewalls:
        unsecured_app_api:
            pattern: ^/api/applications/authorize/token
            security: false
        unsecured_user_api:
            pattern: ^/api/(user/login|user/logout|user/\w+/activate|user/\w+/set_password|user/reset_password|user/register|user/exists|user/setup|user/\w+/verify)
            security: false
        unsecured_status_api:
            pattern: ^/api/status
            security: false
        unsecured_cloud_webhook:
            pattern: ^/api/orchesty/webhook/users
            security: false
        unsecured_cloud_handoff:
            pattern: ^/api/cloud/session-handoff
            security: false
        unsecured_cloud_metrics:
            pattern: ^/api/orchesty/metrics
            security: false

        secured_usage_stats_events:
            pattern: ^/api/usage-stats/.*
            stateless: true
            provider: user_provider
            custom_authenticator:
                - Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\ApiKey\EnterpriseApiKeyAuthenticator
        secured_applications:
            pattern: ^/api/applications
            stateless: true
            provider: user_provider
            custom_authenticator:
                - Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\ApiKey\EnterpriseApiKeyAuthenticator
        secured_area:
            pattern: ^/
            security: true
            provider: user_provider
            custom_authenticators:
                - Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\Auth0\Auth0Authenticator
            form_login:
                check_path: /api/user/login
                login_path: /api/user/login
                default_target_path: /

            logout:
                path: /api/user/logout
                target: /
                invalidate_session: true
