services:
    hbpf.command.change_password:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Command\ChangePasswordCommand
        arguments:
            - '@hbpf.database_manager_locator.user'
            - '@hbpf.user.provider.resource'
            - '@security.encoder_factory.generic'
        tags:
            -  { name: console.command }

    hbpf.command.create_user:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Command\CreateUserCommand
        arguments:
            - '@hbpf.database_manager_locator.user'
            - '@hbpf.user.provider.resource'
            - '@security.encoder_factory.generic'
        tags:
            -  { name: console.command }

    hbpf.command.list_user:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Command\ListUsersCommand
        arguments:
            - '@hbpf.database_manager_locator.user'
            - '@hbpf.user.provider.resource'
        tags:
            -  { name: console.command }

    hbpf.command.delete_user:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Command\DeleteUserCommand
        arguments:
            - '@hbpf.database_manager_locator.user'
            - '@hbpf.user.provider.resource'
        tags:
            -  { name: console.command }