doctrine_mongodb:
    document_managers:
        default:
            mappings:
                UserDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/User/Document"
                    prefix: Hanaboso\PipesFramework\User\Document