doctrine_mongodb:
    document_managers:
        default:
            mappings:
                UserDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%src_dir%/User/Document"
                    prefix: Hanaboso\PipesFramework\User\Document