parameters:
    resource_enum: Hanaboso\PipesFramework\User\Enum\ResourceEnum
    database_type:
        - 'ODM'
#        ODM | ORM

    # Swift mailer params
    mailer_transport: '%env(SMTP_TRANSPORT)%'
    mailer_host: '%env(SMTP_HOST)%'
    mailer_port: '%env(SMTP_PORT)%'
    mailer_user: '%env(SMTP_USER)%'
    mailer_password: '%env(SMTP_PASSWORD)%'

    # Mailer service params
    mailer_from: dev@hanaboso.com
    mailer_async: false
    mailer_builder_id: generic