services:
    hbpf.user.handler.user:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Handler\UserHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.manager.user'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.user.session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments:
            - '@session.storage.mock_file'

    hbpf.user.manager.token:
        class: Hanaboso\PipesFramework\User\Model\Token\TokenManager
        arguments:
            - '@hbpf.database_manager_locator'

    hbpf.user.manager.user:
        class: Hanaboso\PipesFramework\User\Model\User\UserManager
        arguments:
            - "@hbpf.database_manager_locator"
            - "@hbpf.user.manager.security"
            - "@hbpf.user.manager.token"
            - "@security.encoder_factory.generic"
            - "@event_dispatcher"

    hbpf.user.manager.security:
        class: Hanaboso\PipesFramework\User\Model\Security\SecurityManager
        arguments:
            - '@hbpf.database_manager_locator.user'
            - '@security.encoder_factory'
            - '@hbpf.user.session'
            - '@security.token_storage'

    hbpf.database_manager_locator.user:
        class: Hanaboso\PipesFramework\User\DatabaseManager\UserDatabaseManagerLocator
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine.orm.default_entity_manager'
            - '%database_type%'
