services:
    _defaults:
        public: '%public.services%'

    hbpf.user.handler.user:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Handler\UserHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.manager.user'
            - '@hbpf.user.provider.resource'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.user.manager.token:
        class: Hanaboso\PipesFramework\User\Model\Token\TokenManager
        arguments:
           - '@hbpf.database_manager_locator'
           - '@hbpf.user.provider.resource'

    hbpf.user.manager.user:
        class: Hanaboso\PipesFramework\User\Model\User\UserManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.manager.security'
            - '@hbpf.user.manager.token'
            - '@security.encoder_factory.generic'
            - '@event_dispatcher'
            - '@hbpf.user.provider.resource'
            - '@hbpf.user.mailer'
            - '%activateLink%'

    hbpf.user.manager.security:
        class: Hanaboso\PipesFramework\User\Model\Security\SecurityManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@security.encoder_factory'
            - '@session'
            - '@security.token_storage'
            - '@hbpf.user.provider.resource'

    hbpf.user.provider.resource:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Provider\ResourceProvider
        arguments:
            - '%db_res%'

    hbpf.user.mailer:
        class: Hanaboso\PipesFramework\User\Model\Mailer\Mailer
        arguments:
            - '@rabbit-mq.producer.pipes.messages'
            - '@EmailServiceBundle\Handler\MailHandler'
            - '%mailer_from%'
            - '%mailer_async%'
            - '%mailer_builder_id%'

    EmailServiceBundle\Transport\Impl\SwiftMailerTransport:
        class: EmailServiceBundle\Transport\Impl\SwiftMailerTransport
        arguments:
            - '@swiftmailer.mailer.default'
        calls:
            - ['setLogger', ['@monolog.logger.mailer']]