---
version: '3'

services:
  mongodb:
    image: mongo

  logstash:
    image: kedlas/udplogger:latest

  workflow:
    image: cmhanaboso.azurecr.io/devtools/go-build:latest
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /go/src/clever-monitor/workflow
    volumes:
      - ../:/go/src/clever-monitor
    command: bash -c 'sleep infinity'
