---
version: '3'

services:
  mongodb:
    image: mongo

  logstash:
    image: kedlas/udplogger:latest

  workflow:
    image: golang:latest
    working_dir: /go/src/clever-monitor/workflow
    volumes:
      - ../:/go/src/clever-monitor
    command: bash -c 'sleep infinity'
