apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cluster-telegraf.fullname" . }}
  labels:
    {{- include "cluster-telegraf.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cluster-telegraf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cluster-telegraf.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ include "cluster-telegraf.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFLUXDB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-telegraf.fullname" . }}
                  key: INFLUXDB_URL
            - name: INFLUXDB_ORG
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-telegraf.fullname" . }}
                  key: INFLUXDB_ORG
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-telegraf.fullname" . }}
                  key: INFLUXDB_TOKEN
          volumeMounts:
            - name: varrunutmp
              mountPath: /var/run/utmp
              readOnly: true
            - name: sys
              mountPath: /rootfs/sys
              readOnly: true
            - name: proc
              mountPath: /rootfs/proc
              readOnly: true
            - name: config
              mountPath: /etc/telegraf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cluster-telegraf.fullname" . }}-ds
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
        - name: varrunutmp
          hostPath:
            path: /var/run/utmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
