.base-pf-bundles:
  variables:
    DIR: pf-bundles
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}backend

backend:test:
  stage: test
  extends:
    - .base-test
    - .base-pf-bundles

backend:build:
  stage: build
  needs:
    - job: backend:test
      optional: false
  extends:
    - .base-dind-build
    - .base-pf-bundles
