services:

    hbpf.factory.mask:
        class: Hanaboso\PipesFramework\Acl\Factory\MaskFactory

    hbpf.acl.provider.database:
        class: Hanaboso\PipesFramework\Acl\Provider\Impl\DatabaseProvider
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
