services:
    hbpf.acl.provider.database:
        class: Hanaboso\PipesFramework\Acl\Provider\Impl\DatabaseProvider
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.acl.provider.resource:
        class: Hanaboso\PipesFramework\HbPFAclBundle\Provider\ResourceProvider
        arguments:
            - '%acl_rule%'

    hbpf.factory.rule:
        class: Hanaboso\PipesFramework\Acl\Factory\RuleFactory
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '%acl_rule%'

    hbpf.listener.acl:
        class: Hanaboso\PipesFramework\Acl\DocumentListener\UserEventSubscriber
        arguments:
        - '@hbpf.factory.rule'
        tags:
        - { name: kernel.event_subscriber }
