services:
    hbpf.acl.provider.database:
        class: Hanaboso\PipesFramework\Acl\Provider\Impl\DatabaseProvider
        arguments:
            - '@hbpf.database_manager_locator.user'

    hbpf.acl.provider.resource:
        class: Hanaboso\PipesFramework\HbPFAclBundle\Provider\ResourceProvider
        arguments:
            - '%acl_res%'

    hbpf.factory.rule:
        class: Hanaboso\PipesFramework\Acl\Factory\RuleFactory
        arguments:
            - '@hbpf.database_manager_locator.user'
            - '%acl_rule%'

    hbpf.access.manager:
        class: Hanaboso\PipesFramework\Acl\Manager\AccessManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.factory.rule'
            - '@hbpf.acl.provider.database'
            - '@hbpf.acl.provider.resource'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.manager.user:
        class: Hanaboso\PipesFramework\Acl\Manager\UserManager
        arguments:
            - '@hbpf.access.manager'
        tags:
            - { name: kernel.event_subscriber }
