---
version: '3'

services:
  app:
    image: dkr.hanaboso.net/pipes/pipes/rabbitmq-telegraf:dev
    environment:
      APP_DEBUG: "true"
    volumes:
      - ./:/rabbitmq-telegraf
    ports:
      - ${DEV_IP}:8080:8080
    command: go run main.go

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${DEV_IP}:15672:15672
      - ${DEV_IP}:5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - ${DEV_IP}:27017:27017
    volumes:
      - mongodb:/data/db

  kapacitor:
    image: dkr.hanaboso.net/pipes/pipes/kapacitor:dev
    hostname: kapacitor

volumes:
  rabbitmq: {}
  mongodb: {}
