parameters:
    installer_dirs: "%env(json:INSTALLER_DIRS)%"
    env(INSTALLER_DIRS): "[]"

    checkInfiniteLoop: "%env(bool:CHECK_INFINITY_LOOP)%"
    env(CHECK_INFINITY_LOOP): true

    docker_registry: "%env(string:DOCKER_REGISTRY)%"
    env(DOCKER_REGISTRY): dkr.hanaboso.net/pipes/pipes
    docker_pf_bridge_image: "%env(string:DOCKER_PF_BRIDGE_IMAGE)%"
    env(DOCKER_PF_BRIDGE_IMAGE): pf-bridge:dev

    env(XML_PARSER_API_DSN): "xml-parser-api"
    xml_parser_api_host: "%env(string:XML_PARSER_API_DSN)%"

    worker_default_port: "%env(int:WORKER_DEFAULT_PORT)%"
    topology_api: "%env(string:TOPOLOGY_API_DSN)%"
    starting_point: "%env(string:STARTING_POINT_DSN)%"
    monolith_api_host: "%env(string:MONOLITH_API_DSN)%"
    metrics_host: "%env(string:METRICS_HOST)%"
    metrics_port: "%env(string:METRICS_PORT)%"

    topology_configs:
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::RABBITMQ_DSN: "%env(string:RABBIT_DSN)%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::DOCKER_REGISTRY: "%docker_registry%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::DOCKER_PF_BRIDGE_IMAGE: "%docker_pf_bridge_image%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::METRICS_HOST: "%metrics_host%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::METRICS_PORT: "%metrics_port%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::METRICS_SERVICE: "%metrics_service%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::WORKER_DEFAULT_PORT: "%worker_default_port%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::MONOLITH_API_HOST: "%monolith_api_host%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::XML_PARSER_API_HOST: "%xml_parser_api_host%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::MONGODB_DSN: "%env(string:MONGODB_DSN)%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::MONGODB_DB: "%env(string:MONGODB_DB)%"

    topology_generator_configs:
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyGenerator\TopologyGeneratorBridge::TOPOLOGY_API: "%topology_api%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyGenerator\TopologyGeneratorBridge::STARTING_POINT: "%starting_point%"
