parameters:
    generator_path: "%env(GENERATOR_PATH)%"
    env(GENERATOR_PATH): "%kernel.project_dir%/topology"
    docker_network: "%env(DOCKER_NETWORK)%"
    env(DOCKER_NETWORK): "demo_default"
    project_source_path: "%env(PROJECT_SOURCE_PATH)%"
    env(PROJECT_SOURCE_PATH): null
    deployment_prefix: "%env(DEPLOYMENT_PREFIX)%"
    env(DEPLOYMENT_PREFIX): demo
    topology_mode: "%env(TOPOLOGY_MODE)%"
    env(TOPOLOGY_MODE): swarm
    docker_registry: "%env(DOCKER_REGISTRY)%"
    env(DOCKER_REGISTRY): dkr.hanaboso.net/pipes/pipes
    docker_pf_bridge_image: "%env(DOCKER_PF_BRIDGE_IMAGE)%"
    env(DOCKER_PF_BRIDGE_IMAGE): pf-bridge:dev
    multi_probe_host: "%env(MULTI_PROBE_HOST)%"
    env(MULTI_PROBE_HOST): multi-probe:8007
    worker_default_port: "%env(WORKER_DEFAULT_PORT)%"
    env(WORKER_DEFAULT_PORT): 8008
    topology_api: "%env(TOPOLOGY_API)%"
    env(TOPOLOGY_API): topology-api:80
    starting_point: "%env(STARTING_POINT)%"
    env(STARTING_POINT): starting-point:80


    topology_configs:
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::RABBITMQ_HOST: "%rabbit_host%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::RABBITMQ_USER: "%rabbit_user%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::RABBITMQ_PASS: "%rabbit_password%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::RABBITMQ_VHOST: "%rabbit_vhost%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::DOCKER_REGISTRY: "%docker_registry%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::DOCKER_PF_BRIDGE_IMAGE: "%docker_pf_bridge_image%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::MULTI_PROBE_HOST: "%multi_probe_host%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::METRICS_HOST: "%kapacitor.host%:%kapacitor.port%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory::WORKER_DEFAULT_PORT: "%worker_default_port%"

    topology_generator_configs:
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyGenerator\TopologyGeneratorBridge::MULTI_PROBE: "%multi_probe_host%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyGenerator\TopologyGeneratorBridge::TOPOLOGY_API: "%topology_api%"
        !php/const Hanaboso\PipesFramework\Configurator\Model\TopologyGenerator\TopologyGeneratorBridge::STARTING_POINT: "%starting_point%"