services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%service_visibility%'

    notification.handler.settings:
        class: Hanaboso\NotificationSender\Handler\NotificationSettingsHandler
        arguments:
            - '@notification.manager.settings'

    hbpf.notification.handler.curl:
        class: Hanaboso\NotificationSender\Model\Notification\Handler\Impl\CurlNotificationHandler
        arguments:
        tags: ['hbpf.notification.handler']

    hbpf.notification.handler.email:
        class: Hanaboso\NotificationSender\Model\Notification\Handler\Impl\EmailNotificationHandler
        arguments:
        tags: ['hbpf.notification.handler']

    hbpf.notification.handler.rabbit:
        class: Hanaboso\NotificationSender\Model\Notification\Handler\Impl\RabbitNotificationHandler
        arguments:
        tags: ['hbpf.notification.handler']
