# Default values for cloud-controller.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: dkr.hanaboso.net/pipes/pipes/saas-cloud-controller
  pullPolicy: Always
  tag: master

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

secret:
  name: cloud-controller
  keys:
    docsSearchToken: docs_search_token
    mongodbDsn: mongodb_dsn
    mongodbHostname: mongodb_hostname
    rabbitHostname: rabbit_hostname
    rabbitManagementPort: rabbit_management_port
    rabbitAdminUser: rabbit_admin_user
    rabbitAdminPass: rabbit_admin_pass
    kongValkeyUser: kong_valkey_user
    kongValkeyPass: kong_valkey_pass

env:
  appDebug: true
  appOrchestyVersion: "3.0.0-rc2"
  helmOrchestyVersion: "3.0.0-rc2"
  helmBridgePoolKey: bridgepool
  docsSearchUrl: https://orchesty-io.stage.hanaboso.net

kong:
  enabled: true
  adminUrl: "http://kong-admin.kong.svc.cluster.local:8001"
  domainSuffix: "eu2.cloud.orchesty.io"
  redisHost: "kong-valkey.kong.svc.cluster.local"

cloud:
  instancePrefix: "prod"
  instance: "orchesty-instance"
  pullSecret: "hanaboso"
  auth0:
    domain: "dev-qsa0lopaqbhr0vmj.eu.auth0.com"
    audience: "https://api.orchesty.cloud"
    clientId: "1XIsyOq2kpTDt4qOlop2rEAQzPcE2Q5p"

gcs:
  enabled: true
  projectId: "orchesty-cloud-prod"
  credentialsSecretName: "gcs-credentials"
  serviceAccountEmail: "cloud-control@orchesty-cloud-prod.iam.gserviceaccount.com"

resources: {}
