apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "applinth-billing-processor.fullname" . }}
  labels:
    {{- include "applinth-billing-processor.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            {{- include "applinth-billing-processor.selectorLabels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: [ "all", "--json-logs" ]
              env:
                - name: MONGODB_DSN
                  valueFrom:
                    secretKeyRef:
                      name: billing
                      key: processorMongodbDsn
              resources:
                  {{- toYaml .Values.resources | nindent 16 }}

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
