---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kapacitor
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      hostname: kapacitor
      containers:
        - name: kapacitor
          image: dkr.hanaboso.net/pipes/pipes/influxdb:dev
          ports:
            - protocol: UDP
              containerPort: 9100
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kapacitor
spec:
  selector:
    app: kapacitor
  ports:
    - protocol: UDP
      port: 9100
