---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-api
  labels:
    app: monolith-api
spec:
  selector:
    matchLabels:
      app: monolith-api
  template:
    metadata:
      labels:
        app: monolith-api
    spec:
      containers:
        - name: php-w-nginx
          image: dkr.hanaboso.net/pipes/demo/php-api:dev
          ports:
            - containerPort: 80
          env:
            - name: __BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  key: backend_url
                  name: pipes-config
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  key: smtp_user
                  name: pipes-config
            - name: SMTP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: smtp_password
                  name: pipes-config
            - name: BACKEND_HOST
              value: "$(__BACKEND_URL)/"
            - name: FRONTEND_HOST
              value: "$(__BACKEND_URL)/"
            - name: ELASTIC_HOST
              value: elasticsearch
            - name: ELASTIC_INDEX
              value: index
            - name: METRICS_HOST
              value: kapacitor
            - name: METRICS_PORT
              value: "9100"
            - name: METRICS_SERVICE
              value: influx
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: monolith-api
spec:
  selector:
    app: monolith-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30349
