---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-probe
  labels:
    app: multi-probe
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: multi-probe
  template:
    metadata:
      labels:
        app: multi-probe
    spec:
      containers:
        - name: multi-probe
          image: dkr.hanaboso.net/pipes/pipes/multi-probe:dev
          ports:
            - containerPort: 8007
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASS
              value: ""
            - name: REDIS_DB
              value: "0"
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: multi-probe
spec:
  selector:
    app: multi-probe
  ports:
    - protocol: TCP
      targetPort: 8007
      port: 80
