---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-sender-consumer
  labels:
    app: notification-sender-consumer
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: notification-sender-consumer
  template:
    metadata:
      labels:
        app: notification-sender-consumer
    spec:
      containers:
        - name: php-worker
          image: dkr.hanaboso.net/pipes/notification-sender:master
          args: [ "bash", "-c", "while ! [ -f vendor/autoload.php ]; do sleep 1; echo 'sleep 1'; done; bin/console rabbit_mq:consumer:notification" ]
          env:
            - name: MONGO_HOST
              value: mongo
          resources:
            requests:
              memory: 128Mi
              cpu: "100m"
            limits:
              memory: 512Mi
              cpu: "500m"
