---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream
  labels:
    app: stream
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
    spec:
      containers:
        - name: stream
          image: dkr.hanaboso.net/pipes/pipes/stream:dev
          ports:
            - name: socket
              containerPort: 80
            - name: internal-api
              containerPort: 3030
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: STREAM_WS_PORT
              value: "80"
            - name: STREAM_HTTP_PORT
              value: "3030"
            - name: STREAM_QUEUE
              value: pipes.stream
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: stream-socket
spec:
  selector:
    app: stream
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30350

---
apiVersion: v1
kind: Service
metadata:
  name: stream-internal-api
spec:
  selector:
    app: stream
  ports:
    - protocol: TCP
      targetPort: 3030
      port: 80
