.base-pipes-php-sdk:
  variables:
    DIR: pipes-php-sdk

pipes-php-sdk:test:
  stage: test
  extends:
    - .base-test
    - .base-pipes-php-sdk

pipes-php-sdk:git-mirror:
  variables:
    MIRROR_REPOSITORY_NAME: orchesty-php-sdk
    MIRROR_TRIGGER_REPO_VAR: hanaboso-pipes-php-sdk

  when: manual
  needs:
    - job: pipes-php-sdk:test
      optional: false

  extends:
    - .base-git-mirror
    - .base-pipes-php-sdk