apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-applinth.fullname" . }}
  labels:
    {{- include "demo-applinth.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo-applinth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-applinth.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "demo-applinth.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_PORT
              value: "{{ .Values.service.port }}"

            - name: APPLINTH_HOST
              value: {{ .Values.global.applinth_marketplace_url }}

            - name: JWE_PUBLIC_KEY
              valueFrom:
                  secretKeyRef:
                      key: applinth_jwe_public_key
                      name: pipes-secrets
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
