.base-cron:
  variables:
    DIR: cron
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}cron

cron:test:
  stage: test
  extends:
    - .base-test
    - .base-cron

cron:build:
  stage: build
  needs:
    - job: cron:test
      optional: false
  extends:
    - .base-dind-build
    - .base-cron
