version: '3.5'

services:
    app:
        image: hanabosocom/go-base:dev
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 'true'
            MONGO_DSN: mongodb://mongodb/cron?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            MONGO_COLLECTION: cron
        volumes:
            - ./:/app
            - ${GOPATH}/pkg:/go/pkg
        ports:
            - ${DEV_IP}:80:8080
        command: /bin/sh -c '
            su-exec root chmod u+s /usr/bin/crontab &&
            su-exec root crond -l 0 -L /var/log/cron.log &&
            go run cmd/cron.go'

    mongodb:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - ${DEV_IP}:8080:8080
        volumes:
            - ./openapi.yaml:/api.yaml
        environment:
            SWAGGER_JSON: /api.yaml

volumes:
    mongodb:
