openapi: 3.0.0

info:
    title: CRON
    description: CRON API
    version: '1.0'

servers:
    -   url: http://127.0.0.49
        description: Docker Localhost

paths:
    /status:
        get:
            tags: [ Status ]
            responses:
                '200':
                    $ref: '#/components/responses/Status'

    /crons:
        get:
            tags: [ CRONs ]
            responses:
                '200':
                    $ref: '#/components/responses/Crons'
                '500':
                    $ref: '#/components/responses/500'

        post:
            tags: [ CRONs ]
            requestBody:
                $ref: '#/components/requestBodies/Cron'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '400':
                    $ref: '#/components/responses/400'
                '500':
                    $ref: '#/components/responses/500'

    /crons/{topology}/{node}:
        put:
            tags: [ CRONs ]
            parameters:
                -   $ref: '#/components/parameters/Topology'
                -   $ref: '#/components/parameters/Node'
            requestBody:
                $ref: '#/components/requestBodies/CronChange'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '400':
                    $ref: '#/components/responses/400'
                '404':
                    $ref: '#/components/responses/404'
                '500':
                    $ref: '#/components/responses/500'

        patch:
            tags: [ CRONs ]
            parameters:
                -   $ref: '#/components/parameters/Topology'
                -   $ref: '#/components/parameters/Node'
            requestBody:
                $ref: '#/components/requestBodies/CronChange'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '400':
                    $ref: '#/components/responses/400'
                '500':
                    $ref: '#/components/responses/500'

        delete:
            tags: [ CRONs ]
            parameters:
                -   $ref: '#/components/parameters/Topology'
                -   $ref: '#/components/parameters/Node'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '500':
                    $ref: '#/components/responses/500'

    /crons-batches:
        post:
            tags: [ Batch CRONs ]
            requestBody:
                $ref: '#/components/requestBodies/Crons'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '400':
                    $ref: '#/components/responses/400'
                '500':
                    $ref: '#/components/responses/500'

        put:
            tags: [ Batch CRONs ]
            requestBody:
                $ref: '#/components/requestBodies/Crons'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '400':
                    $ref: '#/components/responses/400'
                '404':
                    $ref: '#/components/responses/404'
                '500':
                    $ref: '#/components/responses/500'

        patch:
            tags: [ Batch CRONs ]
            requestBody:
                $ref: '#/components/requestBodies/Crons'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '400':
                    $ref: '#/components/responses/400'
                '500':
                    $ref: '#/components/responses/500'

        delete:
            tags: [ Batch CRONs ]
            requestBody:
                $ref: '#/components/requestBodies/CronsDelete'
            responses:
                '200':
                    $ref: '#/components/responses/Empty'
                '500':
                    $ref: '#/components/responses/500'

components:
    requestBodies:
        Empty:
            description: ''
            content:
                application/json:
                    schema:
                        type: object

        Crons:
            description: ''
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/Cron'

        Cron:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Cron'

        CronChange:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/CronChange'

        CronsChange:
            description: ''
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/CronChange'

        CronsDelete:
            description: ''
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/CronDelete'

    responses:
        Empty:
            description: ''
            content:
                application/json:
                    schema:
                        type: object

        Status:
            description: ''
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            database:
                                type: boolean
                                example: true

        Crons:
            description: ''
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    example: 1
                                topology:
                                    type: string
                                    example: topology
                                node:
                                    type: string
                                    example: node
                                time:
                                    type: string
                                    example: '* * * * *'
                                command:
                                    type: string
                                    example: command

        400:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Message'
                    examples:
                        Invalid JSON:
                            value:
                                message: 'Unexpected JSON error: Invalid JSON!'
                        Invalid CRON:
                            value:
                                message: 'Unexpected CRON error: Invalid CRON!'

        404:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Message'
                    example:
                        message: 'Unknown CRON!'

        500:
            description: ''
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Message'
                    example:
                        message: 'Internal Server Error'

    schemas:
        Message:
            type: object
            properties:
                message:
                    type: string

        Cron:
            type: object
            properties:
                topology:
                    type: string
                    example: topology
                node:
                    type: string
                    example: node
                time:
                    type: string
                    example: '* * * * *'
                command:
                    type: string
                    example: command

        CronChange:
            type: object
            properties:
                time:
                    type: string
                    example: '* * * * *'
                command:
                    type: string
                    example: command

        CronDelete:
            type: object
            properties:
                topology:
                    type: string
                    example: topology
                node:
                    type: string
                    example: node

    parameters:
        Topology:
            name: topology
            in: path
            required: true
            example: Topology
            schema:
                type: string

        Node:
            name: node
            in: path
            required: true
            example: Node
            schema:
                type: string
