---
version: '2'

services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
      - ${DEV_IP}:15672:15672

  stream:
    image: 'dkr.hanaboso.net/pipes/pipes/stream:dev'
    environment:
      - RABBITMQ_HOST=rabbitmq
      - STREAM_WS_PORT=80
      - STREAM_HTTP_PORT=3030
      - STREAM_QUEUE=pipes.stream
    ports:
      - ${DEV_IP}:3030:3030
      - ${DEV_IP}:8080:80

  app:
    image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /var/www/html/clients/clever-connectors/cc-api-demo
    volumes:
      - ../../../:/var/www/html
      - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
      - ${HOME}/.composer:/srv/.composer
    environment:
      BASE_URI: https://clever-conn1.stage.hanaboso.net/

  webserver:
    image: nginx
    volumes:
      - ./nginx-site-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${DEV_IP}:80:80
    depends_on:
      - app



  # Storage
  mongodb:
    image: mongo:3.4
    ports:
      - ${DEV_IP}:27017:27017
    volumes:
      - mongodb:/data/db

  mariadb:
    image: mariadb:10.3
    command: "mysqld --innodb_flush_method=nosync"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DEV_IP}:3306:3306
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mongodb: {}
  mariadb: {}
