---
version: '2'

services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
      - ${DEV_IP}:15672:15672

  stream:
    image: 'dkr.hanaboso.net/pipes/pipes/stream:dev'
    environment:
      - RABBITMQ_HOST=rabbitmq
      - STREAM_WS_PORT=80
      - STREAM_HTTP_PORT=3030
      - STREAM_QUEUE=pipes.stream
    ports:
      - ${DEV_IP}:3030:3030
      - ${DEV_IP}:8080:80

  webserver:
    build:
        context: .
        args:
            DEV_USERNAME: ${DEV_USERNAME}
            DEV_UID: ${DEV_UID}
    volumes:
      - ./:/var/www/html
      - ../cc-api-extension/:/var/www/cc-api-extension
      - ../cm-stream/:/var/www/cm-stream
    ports:
      - ${DEV_IP}:80:80
  
