---
version: '2'

services:
  webserver:
    build:
        context: .
        args:
            DEV_USERNAME: ${DEV_USERNAME}
            DEV_UID: ${DEV_UID}
    volumes:
      - ./:/var/www/html
      - ../cc-api-extension/:/var/www/cc-api-extension
    ports:
      - ${DEV_IP}:80:80