server {
	server_name _;
	listen 80 default_server;

	location /socket.io {
		proxy_pass http://stream;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}

	location /api-demo {
		include fastcgi_params;
		fastcgi_param SCRIPT_NAME index.php;
		fastcgi_param SCRIPT_FILENAME /var/www/html/clients/clever-connectors/cc-api-demo/www/index.php;
		fastcgi_param PATH_INFO $request_uri;
		fastcgi_pass app:9000;
	}
}
