.base-frontend:
  variables:
    DIR: app-ui
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}frontend

frontend:test:
  stage: test
  extends:
    - .base-test
    - .base-frontend

frontend:build:
  stage: build
  variables:
    MAKE_TARGET: rebuild
  needs:
    - job: frontend:test
      optional: false
  extends:
    - .base-dind-build
    - .base-frontend
