---

version: '2'

services:
    # Nodes
    batch:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        depends_on:
          - mongo
          - rabbitmq
        command: bash -c 'while ! [ -f vendor/autoload.php ];do sleep 1; echo "sleep 1"; done; bin/console rabbit-mq:async-consumer batch'

    batch-connector:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        depends_on:
          - mongo
          - rabbitmq
        command: bash -c 'while ! [ -f vendor/autoload.php ];do sleep 1; echo "sleep 1"; done; bin/console rabbit-mq:async-consumer batch-connector'

    status-service:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        depends_on:
          - mongo
          - rabbitmq
        command: bash -c 'while ! [ -f vendor/autoload.php ];do sleep 1; echo "sleep 1"; done; bin/console rabbit-mq:consumer status-service'

    repeater:
      image: 'dkr.hanaboso.net/pipes/pipes/pf-bridge:dev'
      user: ${DEV_UID}:${DEV_GID}
      environment:
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: '5672'
        RABBITMQ_USER: guest
        RABBITMQ_PASS: guest
        RABBITMQ_VHOST: /
        MONGO_HOST: mongo
        REPEATER_CHECK_TIMEOUT: '5000'
      depends_on:
        - mongo
        - rabbitmq
      command: './dist/src/bin/pipes.js start repeater'

    # PHP Services monolith
    monolith-fpm:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        depends_on:
          - mongo
          - rabbitmq

    # Services
    topology-fpm:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
          GENERATOR_PATH: ${GENERATOR_PATH}
          DOCKER_NETWORK: ${COMPOSE_PROJECT_NAME}_default
          PROJECT_SOURCE_PATH: ${PROJECT_SOURCE_PATH}
          DOCKER_GID: ${DOCKER_GID}
          DOCKER_SOCKET_PATH: ${DOCKER_SOCKET_PATH}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
          - ./../topology:${GENERATOR_PATH}
          - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
        depends_on:
          - mongo
        group_add:
          - ${DOCKER_GID}

    xml-parser-api:
        image: 'dkr.hanaboso.net/pipes/pipes/python-xml-parser:prod'
        environment:
          PARSER_HOST: xml-parser-api
          PARSER_PORT: '80'
          PARSER_RELOADED: '1'
          METRICS_HOST: influxdb
          METRICS_PORT: '8089'
        ports:
          - ${DEV_IP}:8080:80

    frontend:
    ## BEGIN DEV
        image: dkr.hanaboso.net/pipes/pipes/nodejs-build:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/frontend
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
          PHP_WEBROOT: /var/www/pipes/clients/clever-connectors/pipes-api/web
          NPM_INSTALL: ${NPM_INSTALL}
          NPM_START: "yes" # webpackserver
        ports:
          - ${DEV_IP}:80:80
          - ${DEV_IP}:81:8080
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
    ## END DEV
    ## BEGIN STAGE
    #    image: dkr.hanaboso.net/pipes/pipes/frontend:dev
    #    environment:
    #      BACKEND_URL: https://cleverconn.stage.hanaboso.net/api
    #      PHP_APP_INDEX: app_dev.php
    #      PHP_WEBROOT: /var/www/pipes/clients/clever-connectors/pipes-api/web
    ## END STAGE
        networks:
          default:
            aliases:
              - connector-api
              - mailer-api
              - ftp-api
              - mapper-api
              - monolith-api
              - topology-api
        depends_on:
          - monolith-fpm
          - topology-fpm
          - api-demo-fpm
          - grafana
          - kibana
          - spitter

    stream:
        image: dkr.hanaboso.net/pipes/pipes/stream:dev
        environment:
          - RABBITMQ_HOST=rabbitmq
          - STREAM_WS_PORT=80
          - STREAM_HTTP_PORT=3030
          - STREAM_QUEUE=stream
        ports:
          - ${DEV_IP}:3030:3030
        # - ${DEV_IP}:8080:80

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - ${DEV_IP}:15672:15672
        volumes:
          - rabbitmq:/var/lib/rabbitmq

    # Storage
    mongo:
        image: mongo:3.4
        ports:
          - ${DEV_IP}:27017:27017
        volumes:
          - mongodb:/data/db

    redis:
        image: redis:3.2-alpine
        ports:
        - ${DEV_IP}:6379:6379
        volumes:
        - redis:/data

    # ELK
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
        environment:
          xpack.security.enabled: "false"
        ports:
          - ${DEV_IP}:9200:9200
        volumes:
          - elasticsearch:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:5.6.0
        command: sh -c 'bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker'
        ports:
          - ${DEV_IP}:5601:5601

    logstash:
        image: docker.elastic.co/logstash/logstash:5.6.0
        command: --log.level debug
        volumes:
          - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

    # Metrics

    # Grafana is now accessible on route /grafana of the webserver
    grafana:
        image: grafana/grafana:4.2.0
        environment:
          GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
          GF_SECURITY_ADMIN_PASSWORD: password
        volumes:
          - grafana:/var/lib/grafana

    influxdb:
        image: influxdb:1.2-alpine
        ports:
          - ${DEV_IP}:8083:8083
          - ${DEV_IP}:8086:8086
          - ${DEV_IP}:8089:8089/udp
        volumes:
          - influxdb:/var/lib/influxdb
          - ./influxdb.conf:/etc/influxdb/influxdb.conf
    
    telegraf:
        image: telegraf:1.4.2
        volumes:
          - ./telegraf.conf:/etc/telegraf/telegraf.conf


    # Fake Services
    mailhog:
        image: mailhog/mailhog
        ports:
          - ${DEV_IP}:8025:8025

    # Spitter
    spitter:
      image: dkr.hanaboso.net/hanaboso/spitter/image:dev
      environment:
        SPITTER_PORT: 3000
        SPITTER_HOST: 0.0.0.0
        SPITTER_PREFFIX: /spitter
      ports:
        - ${DEV_IP}:8090:3000

    api-demo-fpm:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/cc-api-demo
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        depends_on:
          - rabbitmq

volumes:
  elasticsearch: {}
  grafana: {}
  influxdb: {}
  mongodb: {}
  rabbitmq: {}
  redis: {}
