---
{{- if .Values.customPersistence }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.customPersistence.pvPrefix }}-influxdb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    type: Directory
    path: {{ .Values.customPersistence.pvDir }}/influxdb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.customPersistence.pvPrefix }}-mongodb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    type: Directory
    path: {{ .Values.customPersistence.pvDir }}/mongodb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.customPersistence.pvPrefix }}-rabbitmq
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    type: Directory
    path: {{ .Values.customPersistence.pvDir }}/rabbitmq


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.customPersistence.pvcPrefix }}-influxdb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.customPersistence.pvPrefix }}-influxdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.customPersistence.pvcPrefix }}-mongodb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.customPersistence.pvPrefix }}-mongodb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.customPersistence.pvcPrefix }}-rabbitmq
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.customPersistence.pvPrefix }}-rabbitmq

{{ end }}
