.base-cloud-usccp:
  variables:
    DIR: saas/usccp
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}cloud-usccp

cloud-usccp:test:
  stage: test
  extends:
    - .base-test
    - .base-cloud-usccp

cloud-usccp:build:
  stage: build
  needs:
    - job: cloud-usccp:test
      optional: false
  when: manual
  extends:
    - .base-dind-build
    - .base-cloud-usccp
