.base-cloud-usccp:
  variables:
    DIR: saas/usccp
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}cloud-usccp

  rules:
    - if: '$FORCE_PIPELINE =~ /ALL/ || $FORCE_PIPELINE =~ /cloud-usccp/'
    - if: '$CI_COMMIT_BEFORE_SHA == $_BANNED_RUN_ALL_SHA'
      when: never
    - changes:
        - ${DIR}/**/*


cloud-usccp:test:
  stage: test
  needs: []

  extends:
    - .base-go-test
    - .base-cloud-usccp

cloud-usccp:build:
  stage: build
  needs: []
  extends:
    - .base-kaniko-build
    - .base-cloud-usccp
