---
openapi: 3.0.0
info:
    title: "USCCP API"
    version: 0.1.0
    description: "Usage Statistics Central Collection Point"

paths:
    /status:
        get:
            description: Service status for health checking
            x-swagger-router-controller: statusController
            operationId: getStatus
            responses:
                '200':
                    description: Healthy
                '500':
                    description: Not healthy

    /:
        put:
            description: Push events from Orchesty instance's event buffer, duplicate events are ignored
            x-swagger-router-controller: eventController
            operationId: putEvent
            requestBody:
                description: USEvent
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - iid
                                - type
                                - version
                                - created
                            properties:
                                iid:
                                    type: string
                                    minLength: 8
                                    maxLength: 32
                                type:
                                    type: string
                                    enum: [applinth_enduser_app_install, applinth_enduser_app_uninstall, cloud_install, cloud_uninstall, applinth_enduser_app_hearthbeat, orchesty_operations]
                                    minLength: 3
                                    maxLength: 64
                                version:
                                    type: integer
                                data:
                                    type: object
                                    description: Required for types applinth_enduser_app_install, applinth_enduser_app_uninstall [aid, euid] and orchesty_operations [total, day]
                                    properties:
                                        aid:
                                            type: string
                                            maxLength: 100
                                        euid:
                                            type: string
                                            maxLength: 100
                                        total:
                                            type: number
                                            maxLength: 100
                                        day:
                                            type: string
                                created:
                                    type: string
                                    format: int64
            responses:
                '200':
                    description: Success
                '500':
                    description: Failed
