parameters:
    rabbit-mq.bunny-manager: RabbitMqBundle\BunnyManager
    rabbit-mq.bunny-channel: Bunny\Channel
    rabbit-mq.bunny-client: Bunny\Client
    rabbit-mq.command.setup: RabbitMqBundle\Command\SetupCommand
    rabbit-mq.command.consumer: RabbitMqBundle\Command\ConsumerCommand
    #rabbit-mq.command.producer: RabbitMqBundle\Command\ProducerCommand
