.base-applinth-billing-processor:
  variables:
    DIR: saas/applinth-billing-processor
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}applinth-billing-processor

applinth-billing-processor:test:
  stage: test
  extends:
    - .base-test
    - .base-applinth-billing-processor

applinth-billing-processor:build:
  stage: build
  needs:
    - job: applinth-billing-processor:test
      optional: false
  when: manual
  extends:
    - .base-dind-build
    - .base-applinth-billing-processor
