services:
    _defaults:
        public: '%public.services%'
        autowire: true
        autoconfigure: true

    Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Controller\NotificationController:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Controller\NotificationController
        arguments:
            - '@hbpf.notification.handler'
