services:
    _defaults:
        public: '%public.services%'

    hbpf.configurator.publish_guard.slot:
        class: Hanaboso\PipesFrameworkEnterprise\Configurator\Model\TopologySlotGate
        arguments:
            - '@hbpf.database_manager_locator'
            - '%limit_topology_slots%'

    hbpf.configurator.handler.topology:
        class: Hanaboso\PipesFrameworkEnterprise\Configurator\Handler\TopologyHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.topology'
            - '@hbpf.configurator.manager.node'
            - '@hbpf.topology_generator.bridge'
            - '@hbpf.user_task.handler.user_task'
            - '@hbpf.topology.tester'
            - 'Hanaboso\PipesFrameworkEnterprise\Database\Document\Topology'
            - '@hbpf.configurator.publish_guard.slot'

    hbpf.notification.handler:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Handler\NotificationHandler
        arguments:
            - '@hbpf.notification.manager'

    hbpf.cloud.metrics_handler:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Handler\CloudMetricsHandler
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine_mongodb.odm.metrics_document_manager'
            - '@hbpf.topology_generator.bridge'
            - '@hbpf.configurator.manager.topology'

    hbpf.cloud.limits_handler:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Handler\CloudLimitsHandler
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine_mongodb.odm.metrics_document_manager'
            - '%limit_messages%'
            - '%limit_storage_gb%'
            - '%limit_topology_slots%'

    hbpf.cloud.events_publisher:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Publisher\CloudEventsPublisher
        arguments:
            - '@rabbit_mq.publisher.cloud-events'

    hbpf.cloud.limits_tick_command:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFEnterpriseConfiguratorBundle\Command\CloudLimitsTickCommand
        arguments:
            - '@hbpf.cloud.limits_handler'
            - '@hbpf.cloud.events_publisher'
        tags:
            - { name: console.command }
