services:
    _defaults:
        public: '%public.services%'

    hbpf.configurator.manager.topology:
        class: Hanaboso\PipesFrameworkEnterprise\Configurator\Model\TopologyManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.cron.manager'
            - '%checkInfiniteLoop%'
            - '@hbpf.transport.curl_manager'
            - '%startingPointHost%'
            - 'Hanaboso\PipesFrameworkEnterprise\Database\Document\Topology'

    hbpf.notification.manager:
        class: Hanaboso\PipesFrameworkEnterprise\Configurator\Notification\NotificationManager
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%notifierHost%'
