parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    public.services: false

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'
