services:
    node-sdk:
        image: node-sdk:tag
        build: node-sdk/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./node-sdk/:/var/www:cached
        environment:
            # Envs for tests are load from node-sdk/.jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: debug
            CRYPT_SECRET: ThisIsNotSoSecret
            BACKEND_URL: ${BACKEND_URL}
            MONGO_DSN: ${MONGO_DSN}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            AWS_SES_KEY: ${AWS_SES_KEY}
            AWS_SES_SECRET: ${AWS_SES_SECRET}
            WORKER_API_HOST: http://worker-api:8080
            ORCHESTY_API_KEY: ${ORCHESTY_API_KEY}
        command: sh -c 'pnpm install && pnpm run start'

    php-sdk:
        image: hanabosocom/php-dev:php-8.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            PHP_WEBROOT: /var/www/pipes/clients/demo/pipes-api/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            BACKEND_DSN: ${BACKEND_URL}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            WORKER_API: http://worker-api:8080
            ORCHESTY_API_KEY: ${ORCHESTY_API_KEY}
        working_dir: /var/www/pipes/clients/demo/pipes-api
        volumes:
            - ../../:/var/www/pipes:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    starting-point:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 'true'
            MONGO_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            RABBIT_DELIVERY_MODE: 2
        volumes:
            - ./../../starting-point/:/app:cached
        ports:
            - ${DEV_IP}:82:8080
        command: go run cmd/starting-point.go

    topology-api:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            DEPLOYMENT_PREFIX: ${MAIN_DB}
            GENERATOR_NETWORK: ${NETWORK_NAME}
            PLATFORM: ${PLATFORM}
            GENERATOR_PATH: /srv/topology
            MONGO_DSN: ${MONGO_DSN}
            PROJECT_SOURCE_PATH: ${PROJECT_SOURCE_PATH}/../topology
        volumes:
            - ./../../topology-generator/:/app:cached
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
            - ../topology:/srv/topology
        command: /bin/sh -c 'su-exec root sh -c "apk add --no-cache docker-compose && chmod 666 /var/run/docker.sock" && go run main.go server'

    cron-api:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 'true'
            MONGO_DSN: ${MONGO_DSN}
            MONGO_COLLECTION: Cron
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
        volumes:
            - ../../cron:/app:cached
        command: /run.sh -p cmd/cron.go -c api -l 2345
        security_opt: ['seccomp:unconfined']

    backend:
        image: hanabosocom/php-dev:php-8.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:8080:80
        environment:
            APP_ENV: dev
            APP_DEBUG: 'true'
            PHP_WEBROOT: /var/www/pipes/pf-bundles-enterprise/public
            #PHP_WEBROOT: /var/www/pipes/pf-bundles/public
            #PHP_WEBROOT: /var/www/pipes/applinth/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            BACKEND_URL: ${BACKEND_URL}/
            FRONTEND_URL: ${FRONTEND_URL}/
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGODB_DSN: ${MONGO_DSN}
            MONGODB_DB: ${MAIN_DB}
            METRICS_DSN: ${METRICS_DSN}
            METRICS_DB: metrics
            CRON_DSN: cron-api:8080
            STARTING_POINT_URL: ${STARTING_POINT_DSN}
            WORKER_API: http://worker-api:8080/
            TOPOLOGY_API_DSN: topology-api:8080
            #DOCKER_PF_BRIDGE_IMAGE: orchesty/bridge:${VERSION}
            DOCKER_PF_BRIDGE_IMAGE: dkr.hanaboso.net/pipes/pipes/pf-bridge:new-ui
            JWT_KEY: BWoCz4gxw3YHDMkqE5HD1WT2u6zqIAtiJkYVyf6UucL4ZtbhhatQooP5IgTQRwowYR6z8wE3biqZTl37
            AUTH0_DOMAIN: dev-qsa0lopaqbhr0vmj.eu.auth0.com
            AUTH0_AUDIENCE: https://api.orchesty.cloud
            EMAIL_DSN: smtp://mailhog:1025
            ALPHA_INSTANCE_ID: 'demo'
            INSTALLER_DIRS: '["/var/www/pipes/clients/demo/node-sdk/src/topology"]'
            JWE_PRIVATE_KEY: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIAGmQ//yMnyMlFAN/E2yfZjzFL1ziTrAbDwa08KEPBq+NUWHvrxrs7
                f8tvm0y+PwcNgdKhSiMN/osY4/iK+vyr9WqgBwYFK4EEACOhgYkDgYYABABnJEkK
                knFnpxumSFk5MFIEYTm2ReaalO4UrCc4QROIchTIZYRb9GeSounARtxnJcfYa+CB
                pXzObmLNvN3u75L2pADOg4p+GkgwtFdfSa5HhMoQD2jEEmL3otvyjf8jF5t8u2YP
                GcXwowJ2vWSQ6pyW17FLVqmUy2ZW5VSowkPp29CvYQ==
                -----END EC PRIVATE KEY-----
        working_dir: /var/www/pipes/pf-bundles-enterprise
        #working_dir: /var/www/pipes/pf-bundles
        #working_dir: /var/www/pipes/applinth
        volumes:
            - ../../:/var/www/pipes:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    backend-enterprise:
        image: hanabosocom/php-dev:php-8.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:8085:80
        environment:
            APP_ENV: dev
            APP_DEBUG: 'true'
            PHP_WEBROOT: /var/www/pipes/pf-bundles-enterprise/public
            #PHP_WEBROOT: /var/www/pipes/pf-bundles/public
            #PHP_WEBROOT: /var/www/pipes/applinth/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            BACKEND_URL: ${BACKEND_ENTERPRISE_URL}/
            FRONTEND_URL: ${FRONTEND_ENTERPRISE_URL}/
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGODB_DSN: ${MONGO_DSN}
            MONGODB_DB: ${MAIN_DB}
            METRICS_DSN: ${METRICS_DSN}
            METRICS_DB: metrics
            CRON_DSN: cron-api:8080
            STARTING_POINT_URL: ${STARTING_POINT_DSN}
            WORKER_API: http://worker-api:8080/
            TOPOLOGY_API_DSN: topology-api:8080
            #DOCKER_PF_BRIDGE_IMAGE: orchesty/bridge:${VERSION}
            DOCKER_PF_BRIDGE_IMAGE: dkr.hanaboso.net/pipes/pipes/pf-bridge:new-ui
            JWT_KEY: BWoCz4gxw3YHDMkqE5HD1WT2u6zqIAtiJkYVyf6UucL4ZtbhhatQooP5IgTQRwowYR6z8wE3biqZTl37
            AUTH0_DOMAIN: dev-qsa0lopaqbhr0vmj.eu.auth0.com
            AUTH0_AUDIENCE: https://api.orchesty.cloud
            ORCHESTY_CLOUD_URL: http://host.docker.internal:3000
            ORCHESTY_CLOUD_FRONTEND_URL: http://localhost:5173
            ORCHESTY_CLOUD_INSTANCE_ID: ${ORCHESTY_CLOUD_INSTANCE_ID:-5d3e1061-5863-4292-8d95-9a238db8b48a}
            ORCHESTY_CLOUD_INSTANCE_SECRET: ${ORCHESTY_CLOUD_INSTANCE_SECRET:-0027c895-2aa1-11f1-872c-0e85bfc47da4}
            EMAIL_DSN: smtp://mailhog:1025
            ALPHA_INSTANCE_ID: 'demo'
            INSTALLER_DIRS: '["/var/www/pipes/clients/demo/node-sdk/src/topology"]'
            JWE_PRIVATE_KEY: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIAGmQ//yMnyMlFAN/E2yfZjzFL1ziTrAbDwa08KEPBq+NUWHvrxrs7
                f8tvm0y+PwcNgdKhSiMN/osY4/iK+vyr9WqgBwYFK4EEACOhgYkDgYYABABnJEkK
                knFnpxumSFk5MFIEYTm2ReaalO4UrCc4QROIchTIZYRb9GeSounARtxnJcfYa+CB
                pXzObmLNvN3u75L2pADOg4p+GkgwtFdfSa5HhMoQD2jEEmL3otvyjf8jF5t8u2YP
                GcXwowJ2vWSQ6pyW17FLVqmUy2ZW5VSowkPp29CvYQ==
                -----END EC PRIVATE KEY-----
        working_dir: /var/www/pipes/pf-bundles-enterprise
        #working_dir: /var/www/pipes/pf-bundles
        #working_dir: /var/www/pipes/applinth
        volumes:
            - ../../:/var/www/pipes:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    worker-api:
        image: worker-api:tag
        build: ./../../worker-api/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        ports:
            - ${DEV_IP}:8081:8080
        volumes:
            - ./../../worker-api:/var/www
        environment:
            APP_ENV: 'debug'
            MONGODB_DSN: ${MONGO_DSN}
            FLUENTD_DSN: 'fluentd:9880'
            METRICS_DB: metrics
            TZ: 'UTC'
        command: sh -c 'pnpm install && pnpm run start'

    fluentd:
        image: dkr.hanaboso.net/pipes/pipes/fluentd:dev
        environment:
            - MONGO_DSN=${MONGO_DSN}
            - MONGO_COLLECTION=Logs

    multi-counter:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        environment:
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGODB_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            UDP_LOGGER_URL: fluentd:5120
        command: go run main.go start
        ports:
            - ${DEV_IP}:8005:8005
        volumes:
            - ./../../counter/:/app:cached

    limiter:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        environment:
            LIMITER_ADDR: 0.0.0.0:3333
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGO_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            UDP_LOGGER_URL: "fluentd:5120"
        command: go run cmd/limiter_app.go
        volumes:
            - ./../../limiter/:/app:cached

    detector:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        environment:
            APP_DEBUG: 'true'
            METRICS_DSN: ${METRICS_DSN}
            MONGO_DSN: ${MONGO_DSN}
            PLATFORM: ${PLATFORM}
            DOCKER_NETWORK: ${NETWORK_NAME}
            RABBITMQ_DSN: ${RABBITMQ_DSN}
        volumes:
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
            - ./../../detector/:/app:cached
        command: /bin/sh -c 'su-exec root chmod 666 /var/run/docker.sock && go run main.go'

    frontend:
        build: ./../../app-ui/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/app-ui
        environment:
            VITE_BACKEND_URL: ${BACKEND_URL}
            VITE_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:80:3000
        volumes:
            - ../../app-ui:/var/www/app-ui:cached
        command: sh -c 'pnpm install && pnpm run start'

    frontend-new:
        build: ./../../app-ui-new/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/app-ui-new
        environment:
            CI: 'true'
            VITE_BACKEND_URL: ${BACKEND_URL}
            VITE_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:84:3000
        volumes:
            - ../../:/var/www/pipes:cached
        command: sh -c 'cd /var/www/pipes && pnpm install --filter @orchesty/ui-core && cd app-ui-new && pnpm run dev'

    frontend-new-enterprise:
        build: ./../../app-ui-new-enterprise/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/app-ui-new-enterprise
        environment:
            CI: 'true'
            VITE_BACKEND_URL: ${BACKEND_ENTERPRISE_URL}
            VITE_STARTINGPONT_URL: ${DEV_IP}:82
            VITE_AUTH0_DOMAIN: dev-qsa0lopaqbhr0vmj.eu.auth0.com
            VITE_AUTH0_CLIENT_ID: 1XIsyOq2kpTDt4qOlop2rEAQzPcE2Q5p
            VITE_AUTH0_AUDIENCE: https://api.orchesty.cloud
            VITE_AUTH0_REDIRECT: 'true'
        ports:
            - ${DEV_IP}:85:3000
        volumes:
            - ../../:/var/www/pipes:cached
        command: sh -c 'cd /var/www/pipes && pnpm install --filter app-ui-new-enterprise... && cd app-ui-new-enterprise && pnpm run dev'

    applinth-marketplace-ui:
        build: ./../../applinth-marketplace-ui/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/applinth-marketplace-ui
        environment:
            VUE_APP_BACKEND_URL: ${BACKEND_URL}
            VUE_APP_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:81:8080
        volumes:
            - ../../applinth-marketplace-ui:/var/www/applinth-marketplace-ui:cached
        command: sh -c 'pnpm install && pnpm start'

    applinth-admin-ui:
        build: ./../../applinth-admin-ui/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/applinth-admin-ui
        environment:
            VUE_APP_BACKEND_URL: ${BACKEND_URL}
            VUE_APP_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:83:8080
        volumes:
            - ../../applinth-admin-ui:/var/www/applinth-admin-ui:cached
        command: sh -c 'pnpm install && pnpm start'

    mailhog:
        image: mailhog/mailhog
        ports:
            - ${DEV_IP}:8025:8025

    mongo:
        image: mongo
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db
#            -   type: tmpfs
#                target: /data/db

    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - ${DEV_IP}:15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq

    wait-for-it:
        image: hanabosocom/wait-for-it:master

    mysql:
        image: mysql:latest
        ports:
            - ${DEV_IP}:3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./node-sdk/test/init-data/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    mongodb:
    rabbitmq:

networks:
    default:
        name: demo_default
