---
version: '3.5'

services:
    php-sdk:
        image: hanabosocom/php-dev:php-8.2-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            PHP_WEBROOT: /var/www/pipes/clients/demo/pipes-api/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            MONGODB_DSN: ${MONGO_DSN}
            MONGODB_DB: ${MAIN_DB}
            METRICS_DSN: ${METRICS_DSN}
            METRICS_DB: metrics
        working_dir: /var/www/pipes/clients/demo/pipes-api
        volumes:
            - ../../:/var/www/pipes:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    multi-counter:
        image: hanabosocom/go-base:1.19
        user: ${DEV_UID}:${DEV_GID}
        environment:
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGODB_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            UDP_LOGGER_URL: fluentd:5120
        command: go run main.go start
        ports:
            - ${DEV_IP}:8005:8005
        volumes:
            - ./../../counter/:/app:cached

    limiter:
        image: orchesty/limiter:${VERSION}
        environment:
            LIMITER_ADDR: 0.0.0.0:3333
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGO_DSN: ${MONGO_DSN}
            UDP_LOGGER_URL: "fluentd:5120"

    detector:
        image: hanabosocom/go-base:1.19
        user: ${DEV_UID}:${DEV_GID}
        environment:
            APP_DEBUG: 'true'
            METRICS_DSN: ${METRICS_DSN}
            MONGO_DSN: ${MONGO_DSN}
            PLATFORM: ${PLATFORM}
            DOCKER_NETWORK: ${NETWORK_NAME}
            RABBITMQ_DSN: ${RABBITMQ_DSN}
        volumes:
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
            - ./../../detector/:/app:cached
        command: go run main.go

    frontend:
        image: hanabosocom/nodejs-build:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/app-ui
        environment:
            VUE_APP_BACKEND_URL: ${BACKEND_URL}
            VUE_APP_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:80:8080
        volumes:
            - ../../app-ui:/var/www/app-ui:cached
        command: sh -c 'pnpm install && pnpm run serve'

    applinth-marketplace-ui:
        image: hanabosocom/nodejs-build:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/applinth-marketplace-ui
        environment:
            VUE_APP_BACKEND_URL: ${BACKEND_URL}
            VUE_APP_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:81:8080
        volumes:
            - ../../applinth-marketplace-ui:/var/www/applinth-marketplace-ui:cached
        command: sh -c 'pnpm install && pnpm start'

    applinth-admin-ui:
        image: hanabosocom/nodejs-build:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/applinth-admin-ui
        environment:
            VUE_APP_BACKEND_URL: ${BACKEND_URL}
            VUE_APP_STARTINGPONT_URL: ${DEV_IP}:82
        ports:
            - ${DEV_IP}:83:8080
        volumes:
            - ../../applinth-admin-ui:/var/www/applinth-admin-ui:cached
        command: sh -c 'pnpm install && pnpm start'

    adminer:
        image: adminer:latest
        ports:
            - ${DEV_IP}:1028:8080

    mailhog:
        image: mailhog/mailhog
        ports:
            - ${DEV_IP}:8025:8025
