---

version: '2'

services:
    # Nodes

    # PHP Services monolith
    monolith-fpm:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/demo/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
          - ${HOME}/.composer:/srv/.composer
        depends_on:
          - mongo
          - rabbitmq
        networks:
          - pipesdemo_default

    # Services
    topology-fpm:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/demo/pipes-api
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
          GENERATOR_PATH: ${GENERATOR_PATH}
          DOCKER_NETWORK: ${DOCKER_NETWORK}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
          - ./../topology:${GENERATOR_PATH}
          - ${HOME}/.composer:/srv/.composer
        depends_on:
          - mongo
        networks:
          - pipesdemo_default

    repeater:
      image: 'dkr.hanaboso.net/pipes/pipes/pf-bridge:dev'
      user: ${DEV_UID}:${DEV_GID}
      environment:
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: '5672'
        RABBITMQ_USER: guest
        RABBITMQ_PASS: guest
        RABBITMQ_VHOST: /
        MONGO_HOST: mongo
        REPEATER_CHECK_TIMEOUT: '5000'
      depends_on:
        - mongo
        - rabbitmq
      command: './dist/src/bin/pipes.js start repeater'

    xml-parser-api:
        image: 'dkr.hanaboso.net/pipes/pipes/python-xml-parser:prod'
        environment:
          PARSER_HOST: xml-parser-api
          PARSER_PORT: '80'
          PARSER_RELOADED: '1'
          METRICS_HOST: metrics
          METRICS_PORT: '5555'
        ports:
          - ${DEV_IP}:8080:80
        networks:
          - pipesdemo_default

    # Frontend
    frontend:
        image: dkr.hanaboso.net/pipes/pipes/nodejs-build:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/frontend
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
          PHP_WEBROOT: /var/www/pipes/clients/demo/pipes-api/web
          NPM_INSTALL: ${NPM_INSTALL}
          NPM_START: "yes" # webpackserver
        ports:
          - ${DEV_IP}:80:80
          - ${DEV_IP}:81:8080
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        networks:
          pipesdemo_default:
            aliases:
              - connector-api
              - mailer-api
              - ftp-api
              - mapper-api
              - monolith-api
              - topology-api
              - stream
              - api-demo-fpm
        depends_on:
          - monolith-fpm
          - topology-fpm
          - api-demo-fpm
          - grafana
          - kibana

    stream:
        image: dkr.hanaboso.net/pipes/pipes/stream:dev
        environment:
          - RABBITMQ_HOST=rabbitmq
          - STREAM_WS_PORT=80
          - STREAM_HTTP_PORT=3030
          - STREAM_QUEUE=pipes.stream
        ports:
          - ${DEV_IP}:3030:3030
        # - ${DEV_IP}:8080:80

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - ${DEV_IP}:15672:15672
        volumes:
          - rabbitmq:/var/lib/rabbitmq
        networks:
          - pipesdemo_default

    # Storage
    mongo:
        image: mongo:3.4
        ports:
          - ${DEV_IP}:27017:27017
        volumes:
          - mongodb:/data/db
        networks:
          - pipesdemo_default

    # ELK
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
        environment:
          xpack.security.enabled: "false"
        ports:
          - ${DEV_IP}:9200:9200
        volumes:
          - elasticsearch:/usr/share/elasticsearch/data
        networks:
          - pipesdemo_default

    kibana:
        image: docker.elastic.co/kibana/kibana:5.6.0
        command: sh -c 'bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker'
        ports:
          - ${DEV_IP}:5601:5601
        networks:
          - pipesdemo_default

    logstash:
        image: docker.elastic.co/logstash/logstash:5.6.0
        command: --log.level debug
        volumes:
          - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        networks:
          - pipesdemo_default

    # Metrics
    grafana:
        image: grafana/grafana:4.2.0
        environment:
          GF_SERVER_ROOT_URL: http://${DEV_IP}:3000
          GF_SECURITY_ADMIN_PASSWORD: password
        ports:
          - ${DEV_IP}:3000:3000
        volumes:
          - grafana:/var/lib/grafana
        networks:
          - pipesdemo_default

    influxdb:
        image: influxdb:1.2-alpine
        ports:
          - ${DEV_IP}:8083:8083
          - ${DEV_IP}:8086:8086
          - ${DEV_IP}:8089:8089/udp
        volumes:
          - influxdb:/var/lib/influxdb
          - ./influxdb.conf:/etc/influxdb/influxdb.conf
        networks:
          - pipesdemo_default

    telegraf:
        image: telegraf:1.4.2
        volumes:
          - telegraf:/var/lib/telegraf
          - ./telegraf.conf:/etc/telegraf/telegraf.conf

    # Fake Services
    mailhog:
        image: mailhog/mailhog
        ports:
          - ${DEV_IP}:8025:8025
        networks:
          - pipesdemo_default

    redis:
        image: redis:3.2-alpine
        ports:
        - ${DEV_IP}:6379:6379
        volumes:
        - redis:/data

    api-demo-fpm:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www/pipes/clients/clever-connectors/cc-api-demo
        environment:
          DEV_UID: ${DEV_UID}
          DEV_GID: ${DEV_GID}
        volumes:
          - ../../:/var/www/pipes
          - ${SSH_AUTH_SOCK}:/ssh-agent
        depends_on:
          - rabbitmq

volumes:
  elasticsearch: {}
  grafana: {}
  influxdb: {}
  mongodb: {}
  rabbitmq: {}
  redis: {}
  telegraf: {}

networks:
  pipesdemo_default:
    external: true
