services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    hbpf.handler.logs:
        class: Hanaboso\PipesFramework\HbPFLogsBundle\Handler\LogsHandler
        arguments:
            - '@mongodb.logs'

    Hanaboso\PipesFramework\Logs\:
        resource: '../../../Logs'

    mongodb.logs:
        alias: Hanaboso\PipesFramework\Logs\MongoDbLogs
        public: true