image: node:alpine

stages:
  - build

script:
  stage: build
  script:
    - export RABBITMQ_HOST=rabbitmq
    - docker-compose down -v
    - docker-compose up -d
    - docker-compose exec app npm install ./usr/src/app
    - docker-compose exec app /usr/src/app/node_modules/eslint/bin/eslint.js /usr/src/app/
    - docker-compose exec app cd /usr/src/app & npm test