version: '2'
services:
  services:
    image: 'node:alpine'
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_VHOST=/
    depends_on:
      - rabbitmq
      - node_1
      - node_2
      - node_3
    command: /usr/src/app/bin/pipes start services
    ports:
      - '8007:8007'
  node_1:
    image: 'node:alpine'
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_VHOST=/
    depends_on:
      - rabbitmq
    command: /usr/src/app/bin/pipes start node --id node_1
    ports:
      - '5001:8007'
      - '5002:3333'
  node_2:
    image: 'node:alpine'
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_VHOST=/
    depends_on:
      - rabbitmq
    command: /usr/src/app/bin/pipes start node --id node_2
    ports:
      - '5003:8007'
  node_3:
    image: 'node:alpine'
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_VHOST=/
    depends_on:
      - rabbitmq
    command: /usr/src/app/bin/pipes start node --id node_3
    ports:
      - '5004:8007'
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
      - '15672:15672'
      - '5672:5672'
