services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFMetricsBundle\Controller\MetricsController:
        class: Hanaboso\PipesFramework\HbPFMetricsBundle\Controller\MetricsController
        arguments:
            - '@hbpf.metrics.handler.metrics'