services:
    _defaults:
        public: '%public.services%'

    hbpf.metrics.handler.metrics:
        class: Hanaboso\PipesFramework\HbPFMetricsBundle\Handler\MetricsHandler
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "@hbpf.metrics.manager.mongo_metrics"

    hbpf.metrics.manager.mongo_metrics:
        class: Hanaboso\PipesFramework\Metrics\Manager\MongoMetricsManager
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%mongodb.node_table%"
            - "%mongodb.monolith_table%"
            - "%mongodb.rabbit_table%"
            - "%mongodb.counter_table%"
            - "%mongodb.connector_table%"
            - '@doctrine_mongodb.odm.metrics_document_manager'
            - '%mongodb.rabbit_consumer_table%'
            - '@hbpf.metric-connector-overview.aggregation-filter'
            - '@hbpf.metric-connector.aggregation-filter'
            - '@hbpf.metric-connector-graph.aggregation-filter'
            - '@hbpf.metric-request.aggregation-filter'
            - '@hbpf.metric-process.aggregation-filter'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.metric-connector-overview.aggregation-filter:
        class: Hanaboso\PipesFramework\Metrics\Model\Filters\MetricConnectorOverviewAggregationFilter
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'

    hbpf.metric-connector.aggregation-filter:
        class: Hanaboso\PipesFramework\Metrics\Model\Filters\MetricConnectorAggregationFilter
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'

    hbpf.metric-connector-graph.aggregation-filter:
        class: Hanaboso\PipesFramework\Metrics\Model\Filters\MetricConnectorGraphAggregationFilter
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'

    hbpf.metric-request.aggregation-filter:
        class: Hanaboso\PipesFramework\Metrics\Model\Filters\MetricRequestAggregationFilter
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'

    hbpf.metric-process.aggregation-filter:
        class: Hanaboso\PipesFramework\Metrics\Model\Filters\MetricProcessAggregationFilter
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'
