services:
    hbpf.metrics.metrics_client:
        class: Hanaboso\PipesFramework\Metrics\Client\MetricsClient
        arguments:
            - "%influx.host%"
            - "%influx.api_port%"
            - "%influx.user%"
            - "%influx.password%"
            - "%influx.database%"

    hbpf.metrics.handler.metrics:
        class: Hanaboso\PipesFramework\HbPFMetricsBundle\Handler\MetricsHandler
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "@hbpf.metrics.manager_loader"

    hbpf.metrics.manager.influx_metrics:
        class: Hanaboso\PipesFramework\Metrics\Manager\InfluxMetricsManager
        arguments:
            - "@hbpf.metrics.metrics_client"
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%influx.node_table%"
            - "%influx.monolith_table%"
            - "%influx.rabbit_table%"
            - "%influx.counter_table%"
            - "%influx.connector_table%"
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.metrics.manager.mongo_metrics:
        class: Hanaboso\PipesFramework\Metrics\Manager\MongoMetricsManager
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%mongodb.node_table%"
            - "%mongodb.monolith_table%"
            - "%mongodb.rabbit_table%"
            - "%mongodb.counter_table%"
            - "%mongodb.connector_table%"
            - '@doctrine_mongodb.odm.metrics_document_manager'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.metrics.manager_loader:
        class: Hanaboso\PipesFramework\Metrics\Manager\MetricsManagerLoader
        arguments:
            - '%metrics_service%'
            - '@hbpf.metrics.manager.influx_metrics'
            - '@hbpf.metrics.manager.mongo_metrics'