services:

    hbpf.metrics.metrics_client:
        class: Hanaboso\PipesFramework\Metrics\Client\MetricsClient
        arguments:
            - "%influx.host%"
            - "%influx.port%"
            - "%influx.user%"
            - "%influx.password%"
            - "%influx.database%"

    hbpf.metrics.handler.metrics:
        class: Hanaboso\PipesFramework\HbPFMetricsBundle\Handler\MetricsHandler

    hbpf.metrics.manager.metrics:
        class: Hanaboso\PipesFramework\Metrics\MetricsManager
        arguments:
            - "@hbpf.metrics.metrics_client"
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%influx.table%"