export const IMPLEMENTATIONS = {
  NAMESPACE: 'implementations',
  ACTIONS: {
    LIST_IMPLEMENTATIONS: 'LIST_IMPLEMENTATIONS',
    SET_FILE_IMPLEMENTATIONS: 'SET_FILE_IMPLEMENTATIONS',
    GET_IMPLEMENTATION_REQUEST: 'GET_IMPLEMENTATION_REQUEST',
    CREATE_IMPLEMENTATIONS_REQUEST: 'LIST_IMPLEMENTATIONS_REQUEST',
    UPDATE_IMPLEMENTATIONS_REQUEST: 'UPDATE_IMPLEMENTATIONS_REQUEST',
    DELETE_IMPLEMENTATIONS_REQUEST: 'DELETE_IMPLEMENTATIONS_REQUEST',
  },
  MUTATIONS: {
    SET_FILE_IMPLEMENTATIONS: 'SET_FILE_IMPLEMENTATIONS',
    LIST_IMPLEMENTATIONS: 'LIST_IMPLEMENTATIONS',
    GET_IMPLEMENTATION_RESPONSE: 'GET_IMPLEMENTATION_RESPONSE',
    RESET: 'RESET',
  },
}
