parameters:

    kernel.root_dir: '%kernel.project_dir%/src'

    # Base params
    locale: en

    # A secret key that's used to generate certain security-related tokens
    secret: ThisTokenIsNotSoSecretChangeIt


services:
    neco:
        alias: rest.decoder.xml