parameters:
  # Base params
  locale: en

  # A secret key that's used to generate certain security-related tokens
  secret: ThisTokenIsNotSoSecretChangeIt

  frontendHost: "%env(string:FRONTEND_URL)%"
  backendHost: "%env(string:BACKEND_URL)%"
  cronHost: "%env(string:CRON_DSN)%"
  startingPointHost: "%env(string:STARTING_POINT_URL)%"
  activateLink: '%backendHost%/user/%s/activate'
  passwordLink: 'restore-password/%s'
