{{- $componentName := "logstash" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
data:
  logstash.conf: |
{{ .Files.Get (printf "files/logstash-%s.conf" .Values.global.monitoring.logStorage) | indent 4 }}
