{{- $componentName := "logstash" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
      containers:
        - name: logstash
          image: {{ include "pipes.imageFullname" (dict "image" $componentName "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: default
              containerPort: 9600
              protocol: TCP
            - name: ingest-tcp
              containerPort: 5120
              protocol: TCP
            - name: ingest-udp
              containerPort: 5120
              protocol: UDP
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: LOG_STORAGE
              value: {{ .Values.global.monitoring.logStorage }}
            - name: MONGO_DSN
              valueFrom:
                configMapKeyRef:
                  key: mongodb_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  key: mongodb_database
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: MONGO_COLLECTION
              value: Logs
          resources:
{{ toYaml .Values.global.logstash.resources | indent 12 }}
{{ if eq .Values.global.monitoring.logStorage "google" }}
        - name: fluentd
          image: {{ include "pipes.imageFullname" (dict "image" "logstash-fluentd-google" "root" .) }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: "1"
{{ end }}

{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
