{{- $componentName := "monolith-api" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: php-w-nginx
          image: {{ include "pipes.imageFullname" (dict "image" "monolith" "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
{{ include "pipes.monolithEnv" . | indent 12 }}
          resources:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: "2"
{{- with .Values.global.monolith.hostPathMounts }}
{{- if .}}
          volumeMounts:
{{- range . }}
            - name: {{ .name }}
              mountPath: {{ .dest }}
              mountPropagation: HostToContainer
{{- end }}
      volumes:
{{- range . }}
        - name: {{ .name }}
          hostPath:
            path: {{ .src }}
{{- end }}
{{- end }}
{{- end }}
