{{- $componentName := "multi-counter" -}}
---
{{- if .Values.global.alpha_go_bridge }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: multi-counter
          args: ["/bin/counter", "start"]
          image: {{ include "pipes.imageFullname" (dict "image" "counter" "root" .) }}
          imagePullPolicy: Always
          ports:
            # just to satisfy the Service, not used
            - name: http
              containerPort: 8005
          env:
            - name: RABBITMQ_DSN
              valueFrom:
                configMapKeyRef:
                  key: rabbitmq_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: MONGODB_DSN
              valueFrom:
                configMapKeyRef:
                  key: mongodb_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            {{- if .Values.global.monitoring.useInfluxDB }}
            - name: METRICS_DSN
              value: influxdb://kapacitor:9100
            {{- else }}
            - name: __MONGODB_AUTH_AND_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: mongodb_auth_and_hosts
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: __METRICS_DB
              valueFrom:
                configMapKeyRef:
                  key: metrics_db
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: METRICS_DSN
              value: "mongodb://$(__MONGODB_AUTH_AND_HOSTS)/$(__METRICS_DB)"
            {{- end }}
          resources:
{{ toYaml .Values.global.multiCounter.resources | indent 12 }}


{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{- end}}
