---
version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${DEV_IP}:15672:15672
      - ${DEV_IP}:5672:5672
  mongodb:
    image: mongo
    ports:
      - ${DEV_IP}:27017:27017

  limiter:
    image: golang:latest
    working_dir: /go/src/hanaboso.com/limiter
    volumes:
      - ../:/go/src/hanaboso.com
    command: bash -c 'sleep infinity'