---
version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${DEV_IP}:15672:15672
      - ${DEV_IP}:5672:5672
  mongodb:
    image: mongo
    ports:
      - ${DEV_IP}:27017:27017

  limiter:
    image: golang:latest
    working_dir: /go/src/hanaboso.com/limiter
    volumes:
      - ../:/go/src/hanaboso.com
    command: bash -c 'sleep infinity'

  # ELK
  #elasticsearch:
      #image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
      #environment:
        #xpack.security.enabled: "false"
      #ports:
        #- ${DEV_IP}:9200:9200
      #volumes:
        #- elasticsearch:/usr/share/elasticsearch/data

  #kibana:
      #image: docker.elastic.co/kibana/kibana:5.6.0
      #command: sh -c 'bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker'
      #ports:
        #- ${DEV_IP}:5601:5601

  #logstash:
      #image: docker.elastic.co/logstash/logstash:5.6.0
      #command: --log.level debug
      #ports:
        #- ${DEV_IP}:5120:5120/udp
      #volumes:
        #- ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

#volumes:
  #elasticsearch: {}
