parameters:
    rabbit-mq.bunny-manager: Hanaboso\PipesFramework\RabbitMq\BunnyManager
    rabbit-mq.bunny-channel: Bunny\Channel
    rabbit-mq.bunny-client: Bunny\Client
    rabbit-mq.command.setup: Hanaboso\PipesFramework\HbPFRabbitMqBundle\Command\SetupCommand
    rabbit-mq.command.consumer: Hanaboso\PipesFramework\HbPFRabbitMqBundle\Command\ConsumerCommand
    rabbit-mq.command.producer: Hanaboso\PipesFramework\HbPFRabbitMqBundle\Command\ProducerCommand
