parameters:
    rabbit-mq.bunny-manager: Hanaboso\PipesFramework\RabbitMqBundle\BunnyManager
    rabbit-mq.bunny-channel: Bunny\Channel
    rabbit-mq.bunny-client: Bunny\Client
    rabbit-mq.command.setup: Hanaboso\PipesFramework\RabbitMqBundle\Command\SetupCommand
    rabbit-mq.command.consumer: Hanaboso\PipesFramework\RabbitMqBundle\Command\ConsumerCommand
    rabbit-mq.command.async-consumer: Hanaboso\PipesFramework\RabbitMqBundle\Command\AsyncConsumerCommand
    rabbit-mq.command.producer: Hanaboso\PipesFramework\RabbitMqBundle\Command\ProducerCommand