services:
    _defaults:
        public: '%public.services%'

    hbpf.command.refresh_cron:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Command\RefreshCronCommand
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.cron.manager'
        tags:
            - { name: console.command }

    hbpf.command.topology_install:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Command\InstallTopologyCommand
        arguments:
            - '@hbpf.install.topology.manager'
        tags:
            - { name: console.command }

    hbpf.command.service_install:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Command\InstallServiceCommand
        arguments:
            - '@hbpf.configurator.manager.sdk'
        tags:
            - { name: console.command }

    hbpf.command.create_indexes:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Command\UpdateMongoIndexesCommand
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine_mongodb.odm.metrics_document_manager'
        tags:
            - { name: console.command }
