parameters:

services:
    _defaults:
        public: '%public.services%'

    hbpf.cron.manager:
        class: Hanaboso\PipesFramework\Configurator\Cron\CronManager
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%cronHost%'

    hbpf.topology.configurator:
        class: Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory
        arguments:
            - '%topology_configs%'
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.topology_generator.bridge:
        class: Hanaboso\PipesFramework\Configurator\Model\TopologyGenerator\TopologyGeneratorBridge
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.transport.curl_manager'
            - '@hbpf.topology.configurator'
            - '%topology_generator_configs%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.install.topology.manager:
        class: Hanaboso\PipesFramework\TopologyInstaller\InstallManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.configurator.manager.topology'
            - '@hbpf.topology_generator.bridge'
            - '@hbpf.category.parser'
            - '@rest.decoder.xml'
            - '@hbpf.install.cache.null'
            - '%installer_dirs%'
            - '%checkInfiniteLoop%'

    hbpf.topology.tester:
        class: Hanaboso\PipesFramework\Configurator\Model\TopologyTester
        arguments:
            - '@hbpf.topology.tester.client'
            - '@hbpf.topology.configurator'
            - '@hbpf.database_manager_locator'

    hbpf.topology.tester.client:
        class: GuzzleHttp\Client
        arguments:
            - { timeout: 30 }

    hbpf.install.cache.null:
        class: Hanaboso\PipesFramework\TopologyInstaller\Cache\NullCache

    hbpf.install.cache.redis:
        class: Hanaboso\PipesFramework\TopologyInstaller\Cache\RedisCache
        arguments:
            - '%env(string:REDIS_DSN)%'

    hbpf.category.parser:
        class: Hanaboso\PipesFramework\TopologyInstaller\CategoryParser
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.configurator.manager.category'
            - '%installer_dirs%'

    hbpf.progress.filter:
        class: Hanaboso\PipesFramework\Configurator\Model\Filters\ProgressFilter
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.api_token.filter:
        class: Hanaboso\PipesFramework\Configurator\Model\Filters\ApiTokenFilter
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
