---

version: '3'

services:
    python_node:
        image: dkr.hanaboso.net/pipes/pipes/python-sdk:dev
        environment:
          FLASK_HOST: 0.0.0.0
          FLASK_PORT: '80'
          FLASK_ENV: development
          FLASK_DEBUG: 0
        ports:
          - 127.0.0.56:8080:80
        volumes:
          - ./:/usr/src/app
        stdin_open: true
        tty: true
