package docker_compose

const (
	RABBITMQ_HOST = "RABBITMQ_HOST"
	RABBITMQ_PORT = "RABBITMQ_PORT"
	RABBITMQ_USER = "RABBITMQ_USER"
	RABBITMQ_PASS = "RABBITMQ_PASS"
	RABBITMQ_VHOST = "RABBITMQ_VHOST"
	MULTI_PROBE_HOST = "MULTI_PROBE_HOST"
	MULTI_PROBE_PORT = "MULTI_PROBE_PORT"
	METRICS_HOST = "METRICS_HOST"
	METRICS_PORT = "METRICS_PORT"
)
