.base-counter:
  variables:
    DIR: counter
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}counter

counter:test:
  stage: test
  extends:
    - .base-test
    - .base-counter

counter:build:
  stage: build
  needs:
    - job: counter:test
      optional: false
  extends:
    - .base-dind-build
    - .base-counter
