apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usccp.fullname" . }}
  labels:
    {{- include "usccp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "usccp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usccp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "usccp.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_DSN
              valueFrom:
                secretKeyRef:
                  name: usccp
                  key: mongodb_dsn
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
          resources:
              {{- toYaml .Values.resources | nindent 12 }}

        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:2
          args: [
            "--listener_port=8081",
            "--backend=127.0.0.1:8080",
            "--service=usccp.cloud.orchesty.io",
            "--rollout_strategy=managed",
            "--healthz=/healthz",
          ]
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
