apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "usccp.fullname" . }}
  labels:
    {{- include "usccp.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gceWorkloadSA }}
