services:
    hbpf.command.run_topology:
        class: Hanaboso\PipesFramework\Commons\Command\RunTopologyCommand
        arguments:
            - '@hbpf.handler.starting_point'
        tags:
            -  { name: console.command }