services:
    app.command.account_active_check:
        class: Hanaboso\PipesFramework\Authorizations\Command\InstallAuthorizationsCommand
        arguments:
            - '@hbpf.loader.authorization'
        tags:
            -  { name: console.command }