services:

    hbpf.redirect:
        class: Hanaboso\PipesFramework\Commons\Redirect\Redirect
        arguments:

    hbpf.node_repository:
        class: Hanaboso\PipesFramework\Commons\Node\NodeRepository
        arguments:
          - '@service_container'

    hbpf.source_service:
        class: Hanaboso\PipesFramework\Commons\Source\SourceService
        arguments:
            - '@hbpf.transport.curl_manager'

    hbpf.file_storage.driver:
        class: Hanaboso\PipesFramework\Commons\FileStorage\Driver\MongoFileDriver
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.path_generator.hash'

    hbpf.file_storage.filetypes:
        class: Hanaboso\PipesFramework\Commons\FileStorage\FileTypes
        arguments:

    hbpf.path_generator.hash:
        class: Hanaboso\PipesFramework\Commons\FileStorage\PathGenerator\HashPathGenerator
        arguments: