services:
    _defaults:
        public: '%public.services%'

    hbpf.system_metrics_listener:
        class: Hanaboso\PipesFramework\Commons\Listener\SystemMetricsListener
        arguments:
            - '@hbpf.influxdb_sender'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber, event: kernel.terminate }
            - { name: kernel.event_subscriber, event: kernel.controller }

    hbpf.redirect:
        class: Hanaboso\PipesFramework\Commons\Redirect\Redirect
        arguments:

    hbpf.file_storage.driver.mongo:
        class: Hanaboso\PipesFramework\Commons\FileStorage\Driver\MongoFileDriver
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.path_generator.hash'

    hbpf.path_generator.hash:
        class: Hanaboso\PipesFramework\Commons\FileStorage\PathGenerator\HashPathGenerator
        arguments:

    hbpf.file_storage.locator:
        class: Hanaboso\PipesFramework\Commons\FileStorage\Driver\FileStorageDriverLocator
        arguments:
            - '@hbpf.file_storage.driver.mongo'
            - '@hbpf.file_storage.driver.mongo'
            - '@hbpf.file_storage.driver.mongo'

    hbpf.file_storage:
        class: Hanaboso\PipesFramework\Commons\FileStorage\FileStorage
        arguments:
            - '@hbpf.file_storage.locator'
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.database_manager_locator:
        class: Hanaboso\PipesFramework\Commons\DatabaseManager\DatabaseManagerLocator
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine.orm.default_entity_manager'

    hbpf.docker.handler.docker_handler:
        class: Hanaboso\PipesFramework\Commons\Docker\Handler\DockerHandler
        arguments: ['@hbpf.docker.docker']

    hbpf.docker.docker:
        class: Hanaboso\PipesFramework\Commons\Docker\Docker
        arguments: ['@hbpf.commons.docker.docker_client']

    hbpf.commons.docker.docker_client:
        class: Hanaboso\PipesFramework\Commons\Docker\DockerClient
        arguments:
            - '%docker.connection.settings%'

    udp_metrics_sender:
        class: Hanaboso\PipesFramework\Commons\Metrics\UDPSender
        arguments:
            - '%influx.host%'
            - '%influx.udp_port%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.influxdb_sender:
        class: Hanaboso\PipesFramework\Commons\Metrics\InfluxDbSender
        arguments:
            - '@udp_metrics_sender'
            - '%influx.fpm_table%'

    hbpf.cron.manager:
        class: Hanaboso\PipesFramework\Commons\Cron\CronManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%monolith_host%'
            - '%cron_host%'
