services:

    hbpf.redirect:
        class: Hanaboso\PipesFramework\Commons\Redirect\Redirect
        arguments:

    hbpf.file_storage.driver.mongo:
        class: Hanaboso\PipesFramework\Commons\FileStorage\Driver\MongoFileDriver
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.path_generator.hash'

    hbpf.path_generator.hash:
        class: Hanaboso\PipesFramework\Commons\FileStorage\PathGenerator\HashPathGenerator
        arguments:

    hbpf.file_storage.locator:
        class: Hanaboso\PipesFramework\Commons\FileStorage\Driver\FileStorageDriverLocator
        arguments:
            - '@hbpf.file_storage.driver.mongo'
            - '@hbpf.file_storage.driver.mongo'
            - '@hbpf.file_storage.driver.mongo'

    hbpf.file_storage:
        class: Hanaboso\PipesFramework\Commons\FileStorage\FileStorage
        arguments:
            - '@hbpf.file_storage.locator'
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.database_manager_locator:
        class: Hanaboso\PipesFramework\Commons\DatabaseManager\DatabaseManagerLocator
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine.orm.default_entity_manager'

    hbpf.progress_counter.progress_counter_service:
        class: Hanaboso\PipesFramework\Commons\ProgressCounter\ProgressCounterService
        arguments:
            - '@snc_redis.default'

    hbpf.progress_counter.listener.progress_counter_listener:
        class: Hanaboso\PipesFramework\Commons\ProgressCounter\Listener\ProgressCounterListener
        arguments: ['@hbpf.progress_counter.progress_counter_service']
        tags:
            - { name: kernel.event_subscriber }
