services:

    hbpf.redirect:
        class: Hanaboso\PipesFramework\Commons\Redirect\Redirect
        arguments:

    hbpf.node_repository:
        class: Hanaboso\PipesFramework\Commons\Node\NodeRepository
        arguments:
          - '@service_container'

    hbpf.source_service:
        class: Hanaboso\PipesFramework\Commons\Source\SourceService
        arguments:
            - '@hbpf.transport.curl_manager'