services:
    hbpf.transport.curl_client_factory:
            class: Hanaboso\PipesFramework\Commons\Transport\Curl\CurlClientFactory
            arguments:

    hbpf.transport.curl_manager:
        class: Hanaboso\PipesFramework\Commons\Transport\Curl\CurlManager
        arguments:
            - "@hbpf.transport.curl_client_factory"

    hbpf.transport.soap_client_factory:
        class: Hanaboso\PipesFramework\Commons\Transport\Soap\SoapClientFactory
        arguments:

    hbpf.transport.soap_manager:
        class: Hanaboso\PipesFramework\Commons\Transport\Soap\SoapManager
        arguments:
            - "@hbpf.transport.soap_client_factory"