services:
    _defaults:
        public: '%public.services%'

    hbpf.transport.curl_client_factory:
        class: Hanaboso\PipesFramework\Commons\Transport\Curl\CurlClientFactory

    hbpf.transport.curl_manager:
        class: Hanaboso\PipesFramework\Commons\Transport\Curl\CurlManager
        arguments:
            - '@hbpf.transport.curl_client_factory'
            - '@hbpf.influxdb_sender_connector'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.transport.soap_client_factory:
        class: Hanaboso\PipesFramework\Commons\Transport\Soap\SoapClientFactory
        arguments:
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.transport.soap_manager:
        class: Hanaboso\PipesFramework\Commons\Transport\Soap\SoapManager
        arguments:
            - '@hbpf.transport.soap_client_factory'
            - '@hbpf.influxdb_sender_connector'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.transport.async_curl_factory:
        class: Hanaboso\PipesFramework\Commons\Transport\AsyncCurl\CurlSenderFactory
        arguments:
            - '@hbpf.influxdb_sender_connector'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]