apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-controller.fullname" . }}
  labels:
    {{- include "cloud-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cloud-controller.selectorLabels" . | nindent 4 }}
