---

## BEGIN DEV
version: '2'
## END DEV
## BEGIN STAGE
#version: '3.3'
## END STAGE

services:
  app:
    image: dkr.hanaboso.net/clever-monitor/cm-ranger:${TAG_RANGER}
    environment:
      - CC_API_BACKEND=monolith-api
      - CC_NOTIFICATION_BACKEND=notification-sender-api
      - SYNCHRONIZATION_BACKEND=monolith-api
      - TEMPLATING_BACKEND=templating-service
      - WORKFLOW_BACKEND=workflow:50051
    depends_on:
      - mariadb
      - redis
      - rabbitmq
  ## BEGIN DEV
    ports:
      - ${DEV_IP}:80:80
  ## END DEV
  ## BEGIN STAGE
  #  secrets:
  #    - source: clevermonitor-ca.pem
  #      target: /var/www/html/var/secret/ca.crt
  #    - source: clevermonitor-hanaboso.pem
  #      target: /var/www/html/var/secret/keypair.pem
  ## END STAGE

  webserver:
    image: tixik/nginx-fake-index:endpoints
    ## BEGIN DEV
    ports:
      - ${DEV_IP}:80:80
    ## END DEV
    ## BEGIN STAGE
    #ports:
    #  - ${PUBLISH_HTTP_PORT}:80
    ## END STAGE
    depends_on:
      - app

  templating-service:
    image: cmhanaboso.azurecr.io/clever-monitor/cm-templating-service:${TAG_TEMPLATING}
    environment:
      - REMOTE_STORAGE_ENABLED=true
      - STORAGE_URL=filestorage
      - MONGO_HOST=mongo
    depends_on:
      - mongo
      - rabbitmq
      - filestorage

  filestorage:
    image: dkr.hanaboso.net/clever-monitor/cm-source/cm-filestorage:${TAG_FILESTORAGE}
    environment:
      - APP_ENV=dev
      - REDIS_HOST=redis
    volumes:
      - filestorage:/var/www/files
    depends_on:
      - redis

  workflow:
    image: dkr.hanaboso.net/pipes/pipes/workflow:${TAG_WORKFLOW}
    environment:
      - MONGO_HOST=mongo
      - LOGSTASH_ENABLED=true
      - LOGSTASH_PORT=5044
    depends_on:
      - mongo
      - logstash

  mariadb:
    image: mariadb:10.3
    command: "mysqld --innodb_flush_method=nosync"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql

## BEGIN DEV
volumes:
  mariadb: {}
  filestorage: {}
## END DEV

## BEGIN STAGE
#volumes:
#  mariadb:
#    external: true
#      name: cm-ranger2-mariadb
#  filestorage:
#    external: true
#      name: cm-ranger2-filestorage
#
#secrets:
#  clevermonitor-ca.pem:
#    external: true
#  clevermonitor-hanaboso.pem:
#    external: true
#
#networks:
#  default:
#    external:
#      name: ${EXTERNAL_NETWORK}
## END STAGE
