---

version: '3.4'

services:
  ## BEGIN DEV
  webserver:
    image: tixik/nginx-fake-index:endpoints
    ports:
      - ${DEV_IP}:81:80
    depends_on:
      - app
  ## END DEV

  app-ui:
    image: cmhanaboso.azurecr.io/hanaboso/ranger-ui:dev
    ## BEGIN DEV
    ports:
      - ${DEV_IP}:80:80
    ## END DEV
    ## BEGIN STAGE
    #ports:
    #  - ${PUBLISH_HTTP_PORT_UI}:80
    ## END STAGE
    depends_on:
      - app

  app:
    image: cmhanaboso.azurecr.io/clever-monitor/cm-ranger:${TAG_RANGER}
    environment:
      - CC_API_BACKEND=monolith-api
      - CC_NOTIFICATION_BACKEND=notification-sender-api # - add correct host
      - SYNCHRONIZATION_BACKEND=monolith-api  # - add correct host
      - TEMPLATING_BACKEND=templating-service:8080
      - WORKFLOW_BACKEND=workflow:50051
      - CC_CLIENT_BACKEND=127.0.0.1 # Client Service API - add correct host
      - APP_ENV=dev
      - OLD_APP=FALSE
    depends_on:
      - mariadb
      - redis
      - rabbitmq
  ## BEGIN STAGE
  #  ports:
  #    - ${PUBLISH_HTTP_PORT}:80
  #  secrets:
  #    - source: clevermonitor-ca.pem
  #      target: /var/www/html/var/secret/ca.crt
  #    - source: clevermonitor-hanaboso.pem
  #      target: /var/www/html/var/secret/keypair.pem
  ## END STAGE

  templating-service:
    image: cmhanaboso.azurecr.io/clever-monitor/cm-templating-service:${TAG_TEMPLATING}
    environment:
      - REMOTE_STORAGE_ENABLED=true
      - STORAGE_URL=filestorage
      - MONGO_HOST=mongo
      - RABBITMQ_HOST=aim-test-we-app-1.ext.cm-dns.cloud
      - STREAM_QUEUE=pipes.stream
    depends_on:
      - mongo
      - rabbitmq
      - filestorage

  preview-generator:
    image: cmhanaboso.azurecr.io/clever-monitor/cm-preview-generator:${TAG_PREVIEW}
    environment:
      - FILE_STORAGE_URL=filestorage/file/
      - PORT=8080

  filestorage:
    image: cmhanaboso.azurecr.io/clever-monitor/filestorage:${TAG_FILESTORAGE}
    environment:
      - APP_ENV=dev
      - REDIS_HOST=redis
    volumes:
      - filestorage:/var/www/files
    depends_on:
      - redis

  workflow:
    image: cmhanaboso.azurecr.io/clever-monitor/workflow-config:${TAG_WORKFLOW}
    environment:
      - MONGO_HOST=mongo
      - LOGSTASH_ENABLED=false
      - LOGSTASH_PORT=5044
    depends_on:
      - mongo

  links-storage:
    image: cmhanaboso.azurecr.io/clever-monitor/links:master
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo

  mariadb:
    image: mariadb:10.3
    command: "mysqld --innodb_flush_method=nosync"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql

## BEGIN DEV
  mongo:
    image: mongo:3.4
    ports:
      - ${DEV_IP}:27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:3.2-alpine
    volumes:
       - redis:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  mariadb: {}
  filestorage: {}
  mongodb: {}
  redis: {}
  rabbitmq: {}
## END DEV

## BEGIN STAGE
#volumes:
#  mariadb:
#    external:
#      name: ${DEPLOYMENT_PREFIX}-mariadb
#  filestorage:
#    external:
#      name: ${DEPLOYMENT_PREFIX}-filestorage
#
#secrets:
#  clevermonitor-ca.pem:
#    external: true
#  clevermonitor-hanaboso.pem:
#    external: true
#
#networks:
#  default:
#    external:
#      name: ${EXTERNAL_NETWORK}
## END STAGE
