import { API } from '../../api'

export const DATA_GRIDS = {
  ADMIN_USERS_LIST: 'ADMIN_USERS_LIST',
  IMPLEMENTATIONS_LIST: 'IMPLEMENTATIONS_LIST',
  SCHEDULED_TASK: 'SCHEDULED_TASK',
  NOTIFICATIONS: 'NOTIFICATIONS',
  EVENTS: 'EVENTS',
  USER_TASK: 'USER_TASK',
  INSTALLED_APPS: 'INSTALLED_APPS',
  AVAILABLE_APPS: 'AVAILABLE_APPS',
  STATISTICS: 'STATISTICS',
  TOPOLOGY_LOGS: 'TOPOLOGY_LOGS',
  LOGS: 'LOGS',
  OVERVIEW: 'OVERVIEW',
  TRASH: 'TRASH',
}

export const GRID_REQUESTS = {
  [DATA_GRIDS.INSTALLED_APPS]: API.appStore.getInstalledApps,
  [DATA_GRIDS.USER_TASK]: API.userTask.grid,
  [DATA_GRIDS.ADMIN_USERS_LIST]: API.admin.getList,
  [DATA_GRIDS.OVERVIEW]: API.overview.grid,
  [DATA_GRIDS.STATISTICS]: API.statistic.grid,
  [DATA_GRIDS.SCHEDULED_TASK]: API.scheduledTask.grid,
  [DATA_GRIDS.IMPLEMENTATIONS_LIST]: API.implementation.grid,
  [DATA_GRIDS.NOTIFICATIONS]: API.notification.grid,
  [DATA_GRIDS.EVENTS]: API.notification.events,
  [DATA_GRIDS.AVAILABLE_APPS]: API.appStore.getAvailableApps,
  [DATA_GRIDS.LOGS]: API.topology.getLogs,
  [DATA_GRIDS.TOPOLOGY_LOGS]: API.topology.getLogsByID,
  [DATA_GRIDS.TRASH]: API.trash.grid,
}
