export const AUTH = {
  NAMESPACE: 'auth',
  GETTERS: {
    IS_LOGGED: 'IS_LOGGED',
    IS_CHECKED: 'IS_CHECKED',
    GET_LOGGED_USER: 'GET_LOGGED_USER',
    GET_LOGGED_USER_ID: 'GET_LOGGED_USER_ID',
  },
  ACTIONS: {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    CHECK_LOGGED_REQUEST: 'CHECK_LOGGED_REQUEST',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    CHECK_TOKEN_REQUEST: 'CHECK_TOKEN_REQUEST',
    CHECK_REGISTER_TOKEN_REQUEST: 'CHECK_REGISTER_TOKEN_REQUEST',
    REGISTER_PASSWORD_REQUEST: 'REGISTER_PASSWORD_REQUEST',
    SET_PASSWORD_REQUEST: 'SET_PASSWORD_REQUEST',
    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    UPDATE_CONTACT_REQUEST: 'UPDATE_CONTACT_REQUEST',
  },
  MUTATIONS: {
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',
    CHECK_LOGGED_RESPONSE: 'CHECK_LOGGED_RESPONSE',
    LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
    CHECK_TOKEN_RESPONSE: 'CHECK_TOKEN_RESPONSE',
    UPDATE_CONTACT_RESPONSE: 'UPDATE_CONTACT_RESPONSE',
    RESET: 'RESET',
  },
}
