services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFApplicationBundle\Controller\ApplicationController:
        class: Hanaboso\PipesFramework\HbPFApplicationBundle\Controller\ApplicationController
        arguments:
            - '@hbpf.application.handler.application'