services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $applicationHandler: '@hbpf.application.handler.application'

    Hanaboso\PipesFramework\HbPFApplicationBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']