services:
    _defaults:
        public: '%public.services%'

    hbpf.loader.authorization:
        class: Hanaboso\PipesFramework\HbPFApplicationBundle\Loader\ApplicationLoader
        public: true
        arguments:
            - '@service_container'

    hbpf._application.manager.application:
        class: Hanaboso\PipesFramework\Application\Model\ApplicationManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.loader.authorization'
            - '@hbpf._application.manager.webhook'

    hbpf._application.handler.application:
        class: Hanaboso\PipesFramework\HbPFApplicationBundle\Handler\ApplicationHandler
        arguments:
            - '@hbpf._application.manager.application'