services:
    _defaults:
        public: '%public.services%'

    hbpf.loader.authorization:
        class: Hanaboso\PipesFramework\HbPFApplicationBundle\Loader\ApplicationLoader
        public: true
        arguments:
            - '@service_container'