export const DIRECTION = {
  ASCENDING: 'ASC',
  DESCENDING: 'DESC',
}

export const FILTER_TYPE = {
  TEXT: 'TEXT',
  NUMBER: 'NUMBER',
  ENUMS: 'ENUMS',
  MULTIPLE_ENUMS: 'MULTIPLE_ENUMS',
  AUTO_COMPLETE: 'AUTO_COMPLETE',
  DATETIME: 'DATETIME',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  DATE_TIME_BETWEEN: 'DATE_TIME_BETWEEN',
  DATE_BETWEEN: 'DATE_BETWEEN',
}

export const FILTER = {
  QUICK_FILTER: 'QUICK_FILTER',
  SIMPLE_FILTER: 'SIMPLE_FILTER',
  ADVANCED_FILTER: 'ADVANCED_FILTER',
}

export const OPERATOR = {
  EQUAL: '`1`',
  NOT_EQUAL: 'NOT_EQUAL',
  LIKE: 'LIKE',
  STARTS_WITH: 'STARTS_WITH',
  ENDS_WITH: 'ENDS_WITH',
  EMPTY: 'EMPTY',
  NEMPTY: 'NEMPTY',
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN',
  GREATER_THAN_OR_EQUAL: 'GREATER_THAN_OR_EQUAL',
  LESS_THAN_OR_EQUAL: 'LESS_THAN_OR_EQUAL',
  BETWEEN: 'BETWEEN',
  IN: 'IN',
  NIN: 'NIN',
}

export const OPERATOR_CHAR = {
  [OPERATOR.EQUAL]: '=',
  [OPERATOR.NOT_EQUAL]: '!=',
  [OPERATOR.LIKE]: '%',
  [OPERATOR.STARTS_WITH]: '*%',
  [OPERATOR.ENDS_WITH]: '%*',
  [OPERATOR.EMPTY]: 'IS NULL',
  [OPERATOR.NEMPTY]: 'NOT NULL',
  [OPERATOR.GREATER_THAN]: '>',
  [OPERATOR.GREATER_THAN_OR_EQUAL]: '>=',
  [OPERATOR.LESS_THAN]: '<=',
  [OPERATOR.LESS_THAN_OR_EQUAL]: '>=',
  [OPERATOR.BETWEEN]: 'BETWEEN',
}
