{
 "title": "Orchesty Cloud Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Orchesty Instances",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"instance\",\n    predicate: (r) => r._measurement == \"orchesty\",\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  { "title": "Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\n// prevent aligning of windows (stolen)\ninstances = ${instances:json}\nevery = 2h\noffset = duration(v: string(v: uint(v: now()) - uint(v:date.truncate(t: now(), unit: every))) + \"ns\")\n\n// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orchesty\")\n  |> filter(fn: (r) => r[\"_field\"] == \"procs_failed\")\n  |> filter(fn: (r) => contains(value: r[\"instance\"], set: instances))\n  |> group(columns: [\"url\"])\n  |> sort(columns: [\"_time\"])\n  |> increase()\n  |> aggregateWindow(every: every, offset: offset, fn: max)\n  |> difference()\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group()\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "instances = ${instances:json}\n\n// v.bucket, v.timeRangeStart, and v.timeRange stop are all variables supported by the flux plugin and influxdb\nfrom(bucket: v.bucket)\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logging.googleapis.com/user\" and r[\"_field\"] == \"no-rabbit-conn-messages\")\n  |> filter(fn: (r) => contains(value: r[\"instance\"], set: instances))\n  |> group(columns: [\"namespace_name\", \"orchesty_service\", \"_field\"])\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Has non-empty queues with no messages consumed last 10min",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 1 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\n\ninstances = ${instances:json}\n  |> array.map(fn: (x) => strings.joinStr(arr: [\"instance\", x], v: \"-\"))\n\n// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"rabbitmq_queue\"\n    and (r[\"_field\"] == \"messages\" or r[\"_field\"] == \"messages_ack\")\n    and contains(value: r[\"vhost\"], set: instances)\n  )\n  |> group(columns: [\"_field\", \"vhost\", \"queue\"])\n\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> difference(columns: [\"messages_ack\"])\n  |> max(column: \"messages_ack\")\n  |> min(column: \"messages\")\n\n  |> map(fn: (r) => ({ r with _value: (\n      if r.messages > 0 and r.messages_ack == 0 then\n       r.messages\n      else\n       0\n    )}))\n  |> drop(columns: [\"messages\", \"messages_ack\", \"_measurement\", \"_time\"])\n\n  |> group(columns: [\"_value\", \"vhost\"], mode: \"except\")\n  |> filter(fn: (r) => r._value > 0)\n"
    }
   ]
  },
  { "title": "Total process stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Failed processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "every = 30m\ninstances = ${instances:json}\n\n// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orchesty\")\n  |> filter(fn: (r) => r[\"_field\"] == \"procs_failed\")\n  |> filter(fn: (r) => contains(value: r[\"instance\"], set: instances))\n  |> group(columns: [\"instance\", \"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> increase()\n  |> aggregateWindow(every: every, fn: last)\n  |> difference()\n  |> keep(columns: [\"_measurement\", \"_field\", \"_value\", \"_time\", \"instance\"])\n"
    }
   ]
  },
  {
   "title": "Successful processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 7 },
   "targets": [
    {
     "query": "every = 30m\ninstances = ${instances:json}\n\n// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orchesty\")\n  |> filter(fn: (r) => r[\"_field\"] == \"procs_succeeded\")\n  |> filter(fn: (r) => contains(value: r[\"instance\"], set: instances))\n  |> group(columns: [\"instance\", \"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> increase()\n  |> aggregateWindow(every: every, fn: last)\n  |> difference()\n  |> keep(columns: [\"_measurement\", \"_field\", \"_value\", \"_time\", \"instance\"])\n"
    }
   ]
  },
  {
   "title": "Limiter stats",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "every = 30m\ninstances = ${instances:json}\n\n// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orchesty\")\n  |> filter(fn: (r) => r[\"_field\"] == \"limiter_count\")\n  |> filter(fn: (r) => contains(value: r[\"instance\"], set: instances))\n  |> group(columns: [\"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> aggregateWindow(every: every, fn: max)\n  |> keep(columns: [\"_measurement\", \"_value\", \"_time\", \"instance\"])\n"
    }
   ]
  },
  {
   "title": "Repeater stats",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 15 },
   "targets": [
    {
     "query": "every = 30m\ninstances = ${instances:json}\n\n// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orchesty\")\n  |> filter(fn: (r) => r[\"_field\"] == \"repeater_count\")\n  |> filter(fn: (r) => contains(value: r[\"instance\"], set: instances))\n  |> group(columns: [\"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> aggregateWindow(every: every, fn: max)\n  |> keep(columns: [\"_measurement\", \"_value\", \"_time\", \"instance\"])\n"
    }
   ]
  },
  {
   "title": "Cloud Logging / Log bytes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logging.googleapis.com/billing\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_ingested\")\n  |> group(columns: [\"resource_type\", \"_field\", \"_measurement\"])\n  |> aggregateWindow(every: 60m, fn: max)\n  |> keep(columns: [\"_value\", \"_time\", \"resource_type\"])\n  |> yield()"
    }
   ]
  }
 ]
}