{
 "title": "RabbitMQ",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Publishes",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rabbitmq_queue\" and r[\"_field\"] == \"messages_publish\")\n  |> keep(columns: [\"_field\", \"_time\", \"_value\", \"queue\", \"vhost\"])\n  |> increase()\n  |> aggregateWindow(every: 30m, fn: max)\n  |> difference()\n  |> group(columns: [\"_time\", \"vhost\"])\n  |> sum()\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")"
    }
   ]
  },
  {
   "title": "Messages sitting in queues",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rabbitmq_queue\" and r[\"_field\"] == \"messages\")\n  |> aggregateWindow(every: 30m, fn: max)\n  |> group(columns: [\"_time\", \"vhost\"])\n  |> sum()\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")"
    }
   ]
  },
  {
   "title": "Non-empty queues with no messages consumed",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: v.bucket)\n  |> range(start: -60m)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"rabbitmq_queue\"\n    and (r[\"_field\"] == \"messages\" or r[\"_field\"] == \"messages_ack\")\n  )\n  |> group(columns: [\"_field\", \"vhost\", \"queue\"])\n\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> difference(columns: [\"messages_ack\"])\n  |> max(column: \"messages_ack\")\n  |> min(column: \"messages\")\n\n  |> map(fn: (r) => ({ r with _value: (\n      if r.messages > 0 and r.messages_ack == 0 then\n       r.messages\n      else\n       0\n    )}))\n  |> drop(columns: [\"messages\", \"messages_ack\", \"_measurement\"])\n\n  |> group(columns: [\"_value\", \"_time\", \"vhost\"], mode: \"except\")\n  |> filter(fn: (r) => r._value > 0)\n"
    }
   ]
  }
 ]
}