---
version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - ${DEV_IP}:27017:27017
  logstash:
    image: kedlas/udplogger:latest
    ports:
      - ${DEV_IP}:5120:4444/udp

  workflow:
    image: golang:latest
    working_dir: /go/src/clever-monitor.com/workflow
    volumes:
      - ../:/go/src/clever-monitor.com
    command: bash -c 'sleep infinity'
