services:
    _defaults:
        public: '%public.services%'

    hbpf.command.refresh_cron:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Command\RefreshCronCommand
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.cron.manager'
        tags:
            - { name: console.command }
