services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\CategoryController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\CategoryController
        arguments:
            - '@hbpf.handler.category'
        calls:
            - ['setContainer', ['@service_container']]

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController
        arguments:
            - '@hbpf.configurator.handler.node'
        calls:
            - ['setContainer', ['@service_container']]

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController
        arguments:
            - '@hbpf.configurator.handler.topology'
        calls:
            - ['setContainer', ['@service_container']]

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\SdkController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\SdkController
        arguments:
            - '@hbpf.configurator.handler.sdk'
        calls:
            - ['setContainer', ['@service_container']]
