services:
    hbpf.configurator.controller.topology:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController
        arguments:

    hbpf.configurator.controller.node:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController
        arguments:
