services:
    _defaults:
        public: '%public.services%'
        autowire: true
        autoconfigure: true

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\CategoryController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\CategoryController
        arguments:
            - '@hbpf.handler.category'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController
        arguments:
            - '@hbpf.configurator.handler.node'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController
        arguments:
            - '@hbpf.configurator.handler.topology'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\SdkController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\SdkController
        arguments:
            - '@hbpf.configurator.handler.sdk'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyProgressController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyProgressController
        arguments:
            - '@hbpf.configurator.handler.topology_progress'