services:
    hbpf.configurator.controller.topology:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController
        arguments:

    hbpf.configurator.controller.node:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController
        arguments:

    hbpf.controller.starting_point:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\StartingPointController
        arguments:

    hbpf.api_gateway.controller.test:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TestController
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@hbpf.handler.starting_point'
            - "%kernel.project_dir%"
            - "@monolog.logger.test"
            - '@hbpf.docker_compose.volume_path_definition_factory'

    hbpf.configurator.generator_controller:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\GeneratorController
        arguments:
            - '@hbpf.handler.generator_handler'
            - '@monolog.logger.security'
