services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\CategoryController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\CategoryController
        arguments:
            - '@hbpf.handler.category'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\NodeController
        arguments:
            - '@hbpf.configurator.handler.node'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\TopologyController
        arguments:
            - '@hbpf.configurator.handler.topology'