services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $topologyHandler: '@hbpf.configurator.handler.topology'
            $nodeHandler: '@hbpf.configurator.handler.node'
            $generatorHandler: '@hbpf.handler.generator_handler'
            $controllingProducer: '@rabbit-mq.producer.topology-destroy'
            $startingPointHandler: '@hbpf.handler.starting_point'
            $categoryHandler: '@hbpf.handler.category'

    Hanaboso\PipesFramework\HbPFConfiguratorBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']