services:
    _defaults:
        public: '%public.services%'

    hbpf.configurator.handler.topology:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\TopologyHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.topology'
            - '@hbpf.configurator.manager.node'
            - '@hbpf.topology_generator.bridge'
            - '@hbpf.user_task.handler.user_task'

    hbpf.configurator.handler.node:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\NodeHandler
        arguments:
            - '@hbpf.configurator.manager.node'

    hbpf.handler.category:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\CategoryHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.category'

    hbpf.handler.api_token:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\ApiTokenHandler
        arguments:
            - '@hbpf.configurator.manager.api_token'

    hbpf.handler.dashboard:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\DashboardHandler
        arguments:
            - '@hbpf.configurator.manager.dashboard'

    hbpf.configurator.handler.sdk:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\SdkHandler
        arguments:
            - '@hbpf.configurator.manager.sdk'

    hbpf.configurator.handler.topology_progress:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\TopologyProgressHandler
        arguments:
            - '@hbpf.configurator.manager.topology_progress'
