services:
    hbpf.configurator.handler.topology:
            class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\TopologyHandler
            arguments:
                - '@hbpf.database_manager_locator'
                - '@hbpf.configurator.manager.topology'

    hbpf.configurator.handler.node:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\NodeHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.node'

    hbpf.handler.starting_point:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\StartingPointHandler
        arguments:
            - "@doctrine.odm.mongodb.document_manager"
            - '@hbpf.starting_point.starting_point'
