services:
    _defaults:
        public: '%public.services%'

    hbpf.configurator.handler.topology:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\TopologyHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.topology'
            - '@hbpf.topology_generator.request.request_handler'

    hbpf.configurator.handler.node:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\NodeHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.node'

    hbpf.handler.category:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\CategoryHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.configurator.manager.category'
