services:
    _defaults:
        public: '%public.services%'

    hbpf.configurator.manager.topology:
        class: Hanaboso\PipesFramework\Configurator\Model\TopologyManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.cron.manager'

    hbpf.configurator.manager.node:
        class: Hanaboso\PipesFramework\Configurator\Model\NodeManager
        arguments:
            - '@hbpf.database_manager_locator'

    hbpf.configurator.manager.category:
        class: Hanaboso\PipesFramework\Configurator\Model\CategoryManager
        arguments:
            - '@hbpf.database_manager_locator'
