services:
    # Starting point
    hbpf.starting_point.starting_point:
        class: Hanaboso\PipesFramework\Configurator\StartingPoint\StartingPoint
        arguments:
            - '@rabbit-mq.manager'
            - '@hbpf.transport.curl_manager'
            - '@hbpf.influxdb_sender'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.docker_compose.volume_path_definition_factory:
        class: Hanaboso\PipesFramework\TopologyGenerator\DockerCompose\VolumePathDefinitionFactory
        arguments:
            - '%project_source_path%'

    hbpf.topology_generator.topology_actions_factory:
        class: Hanaboso\PipesFramework\TopologyGenerator\Actions\TopologyActionsFactory
        arguments:
            - '@hbpf.docker.handler.docker_handler'
            - '@hbpf.rabbit_mq.handler.rabbit_mq_handler'
            - '@hbpf.docker_compose.volume_path_definition_factory'

    hbpf.topology_generator.request.request_handler:
        class: Hanaboso\PipesFramework\TopologyGenerator\Request\RequestHandler
        arguments:
            - '@hbpf.transport.curl_manager'
