parameters:

services:
    _defaults:
        public: '%public.services%'

    hbpf.cron.manager:
        class: Hanaboso\PipesFramework\Configurator\Cron\CronManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%monolith_host%'
            - '%cron_host%'

    hbpf.topology_generator.request.request_handler:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\RequestHandler
        arguments:
            - '@hbpf.transport.curl_manager'
