parameters:

services:
    _defaults:
        public: '%public.services%'

    hbpf.cron.manager:
        class: Hanaboso\PipesFramework\Configurator\Cron\CronManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%starting_point_host%'
            - '%cron_host%'

    hbpf.topology.configurator:
        class: Hanaboso\PipesFramework\Configurator\Model\TopologyConfigFactory
        arguments:
            - '%topology_configs%'