parameters:
    env(PERSISTENT_QUEUES): false
    env(PERSISTENT_MESSAGES): false

services:
    _defaults:
        public: '%public.services%'

    # Starting point
    hbpf.starting_point.starting_point:
        class: Hanaboso\PipesFramework\Configurator\StartingPoint\StartingPoint
        arguments:
            - '@rabbit-mq.manager'
            - '@hbpf.transport.curl_manager'
            - '@hbpf.influxdb_sender_monolith'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
            - ['setDurableQueue', ['%env(bool:PERSISTENT_QUEUES)%']]
            - ['setDurableMessage', ['%env(bool:PERSISTENT_MESSAGES)%']]

    hbpf.cron.manager:
        class: Hanaboso\PipesFramework\Configurator\Cron\CronManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%monolith_host%'
            - '%cron_host%'

    hbpf.topology_generator.request.request_handler:
        class: Hanaboso\PipesFramework\HbPFConfiguratorBundle\Handler\RequestHandler
        arguments:
            - '@hbpf.transport.curl_manager'
