services:
    systems.controller:
        class: CleverConnectors\AppBundle\Controller\SystemController
        arguments:
            - '@systems.handler'

    systems.handler:
        class: CleverConnectors\AppBundle\Handler\SystemHandler
        arguments:
            - '@systems.manager'

    systems.manager:
        class: CleverConnectors\AppBundle\Model\Systems\SystemManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@systems.loader'
            - '@manager.webhook'

    systems.loader:
        class: CleverConnectors\AppBundle\Model\Systems\SystemLoader
        arguments:
            - '@service_container'

    systems.null.user:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
        tags: ['%systems%', '%systems.dev%', '%systems.user.some_user%']

    systems.null.group:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
        tags: ['%systems%', '%systems.dev%', '%systems.group.some_group%']

    systems.null.user.group:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
        tags: ['%systems%', '%systems.dev%', '%systems.user.some_user%', '%systems.group.some_group%']

    manager.webhook:
        class: CleverConnectors\AppBundle\Model\WebhookManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%webhook.domain%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    cc.controller.webhook:
        class: CleverConnectors\AppBundle\Controller\WebhookController
        arguments:
            - '@hbpf.handler.starting_point'

    listener.controller.security:
        class: CleverConnectors\AppBundle\Listeners\WebhookSecurityListener
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        tags: ['kernel.event_subscriber']
