services:
    systems.loader:
        class: CleverConnectors\AppBundle\Model\Systems\SystemLoader
        arguments:
            - '@service_container'

    systems.manager:
        class: CleverConnectors\AppBundle\Model\Systems\SystemManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@systems.loader'

    systems.null.user:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
        tags: ['systems', 'systems.dev', 'systems.user.someUser']

    systems.null.group:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
        tags: ['systems', 'systems.dev', 'systems.group.someGroup']

    systems.null.user.group:
        class: CleverConnectors\AppBundle\Model\Systems\Impl\NullSystem
        arguments:
        tags: ['systems', 'systems.dev', 'systems.user.someUser', 'systems.group.someGroup']

    manager.webhook:
        class: CleverConnectors\AppBundle\Model\WebhookManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    cc.controller.webhook:
        class: CleverConnectors\AppBundle\Controller\WebhookController
        arguments:
            - '@hbpf.handler.starting_point'

    listener.controller.security:
        class: CleverConnectors\AppBundle\Listeners\WebhookSecurityListener
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        tags: ['kernel.event_subscriber']
