export const SELECT_PAGE = 'SELECT_PAGE';
export const SET_PAGE_DATA = 'SET_PAGE_DATA';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const TOGGLE_MAIN_SUB_MENU = 'TOGGLE_MAIN_SUB_MENU';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';

// Process
export const PROCESS_SET_STATE = 'PROCESS_SET_STATE';
export const PROCESS_CLEAR = 'PROCESS_CLEAR';

// Server
export const SERVER_API_GATEWAY_CHANGE = 'SERVER_API_GATEWAY_CHANGE';

// Authorization
export const USER_LOGGED = 'USER_LOGGED';
export const USER_LOGOUT = 'USER_LOGOUT';

// Notifications
export const NOTIFICATION_INCREMENT_ID = 'NOTIFICATION_INCREMENT_ID';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_TIMEOUT = 'NOTIFICATION_TIMEOUT';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

// Topology
export const TOPOLOGY_LIST_CREATE = 'TOPOLOGY/LIST/CREATE';
export const TOPOLOGY_LIST_DELETE = 'TOPOLOGY/LIST/DELETE';
export const TOPOLOGY_LIST_LOADING = 'TOPOLOGY/LIST/LOADING';
export const TOPOLOGY_LIST_RECEIVE = 'TOPOLOGY/LIST/RECEIVE';
export const TOPOLOGY_LIST_ERROR = 'TOPOLOGY/LIST/ERROR';
export const TOPOLOGY_LIST_CHANGE_SORT = 'TOPOLOGY/LIST/CHANGE_SORT';
export const TOPOLOGY_LIST_CHANGE_PAGE = 'TOPOLOGY/LIST/CHANGE_PAGE';

export const TOPOLOGY_RECEIVE = 'TOPOLOGY_RECEIVE';
export const TOPOLOGY_RECEIVE_ITEMS = 'TOPOLOGY_RECEIVE_ITEMS';
export const TOPOLOGY_REMOVE = 'TOPOLOGY_REMOVE';
export const TOPOLOGY_RECEIVE_SCHEMA = 'TOPOLOGY_RECEIVE_SCHEMA';
export const TOPOLOGY_RECEIVE_TEST = 'TOPOLOGY_RECEIVE_TEST';
export const TOPOLOGY_RESET_TEST = 'TOPOLOGY_RESET_TEST';

// Topology Group

export const TOPOLOGY_GROUP_RECEIVE = 'TOPOLOGY_GROUP_RECEIVE';
export const TOPOLOGY_GROUP_RECEIVE_ITEMS = 'TOPOLOGY_GROUP_RECEIVE_ITEMS';
export const TOPOLOGY_GROUP_REMOVE = 'TOPOLOGY_GROUP_REMOVE';

// Node
export const NODE_LIST_CREATE = 'NODE/LIST/CREATE';
export const NODE_LIST_LOADING = 'NODE/LIST/LOADING';
export const NODE_LIST_RECEIVE = 'NODE/LIST/RECEIVE';
export const NODE_LIST_ERROR = 'NODE/LIST/ERROR';

export const NODE_RECEIVE = 'NODE_RECEIVE';
export const NODE_RECEIVE_ITEMS = 'NODE_RECEIVE_ITEMS';

// Connector Authorizations
export const AUTHORIZATION_LIST_CREATE = 'AUTHORIZATION/LIST/CREATE';
export const AUTHORIZATION_LIST_LOADING = 'AUTHORIZATION/LIST/LOADING';
export const AUTHORIZATION_LIST_RECEIVE = 'AUTHORIZATION/LIST/RECEIVE';
export const AUTHORIZATION_LIST_ERROR = 'AUTHORIZATION/LIST/ERROR';

export const AUTHORIZATION_RECEIVE = 'AUTHORIZATION_RECEIVE';
export const AUTHORIZATION_RECEIVE_ITEMS = 'AUTHORIZATION_RECEIVE_ITEMS';
export const AUTHORIZATION_RECEIVE_SETTINGS = 'AUTHORIZATION_RECEIVE_SETTINGS';

// Category
export const CATEGORY_RECEIVE = 'CATEGORY_RECEIVE';
export const CATEGORY_RECEIVE_ITEMS = 'CATEGORY_RECEIVE_ITEMS';
export const CATEGORY_REMOVE = 'CATEGORY_REMOVE';

export const CATEGORY_TREE_SELECT = 'CATEGORY/TREE/SELECT';
export const CATEGORY_TREE_CREATE = 'CATEGORY/TREE/CREATE';
export const CATEGORY_TREE_LOADING = 'CATEGORY/TREE/LOADING';
export const CATEGORY_TREE_RECEIVE = 'CATEGORY/TREE/RECEIVE';
export const CATEGORY_TREE_ERROR = 'CATEGORY/TREE/ERROR';
export const CATEGORY_TREE_INVALIDATE = 'CATEGORY/TREE/INVALIDATE';

// Editable
export const EDITABLE_SWITCH_EDIT = 'EDITABLE_SWITCH_EDIT';
export const EDITABLE_SWITCH_VIEW = 'EDITABLE_SWITCH_VIEW';
export const EDITABLE_CHANGE = 'EDITABLE_CHANGE';
