export const OPEN_PAGE = 'OPEN_PAGE';
export const CLOSE_PAGE = 'CLOSE_PAGE';
export const SELECT_PAGE = 'SELECT_PAGE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const LEFT_SIDEBAR_TOGGLE = 'LEFT_SIDEBAR_TOGGLE';

export const CONTEXT_MENU_OPEN = 'CONTEXT_MENU_OPEN';
export const CONTEXT_MENU_CLOSE = 'CONTEXT_MENU_CLOSE';

// Process
export const PROCESS_SET_STATE = 'PROCESS_SET_STATE';
export const PROCESS_CLEAR = 'PROCESS_CLEAR';

// Server
export const SERVER_API_GATEWAY_CHANGE = 'SERVER_API_GATEWAY_CHANGE';

// Authorization
export const USER_LOGGED = 'USER_LOGGED';
export const USER_LOGOUT = 'USER_LOGOUT';

// Notifications
export const NOTIFICATION_INCREMENT_ID = 'NOTIFICATION_INCREMENT_ID';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_TIMEOUT = 'NOTIFICATION_TIMEOUT';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

// Topology
export const TOPOLOGY_LIST_CREATE = 'TOPOLOGY/LIST/CREATE';
export const TOPOLOGY_LIST_DELETE = 'TOPOLOGY/LIST/DELETE';
export const TOPOLOGY_LIST_LOADING = 'TOPOLOGY/LIST/LOADING';
export const TOPOLOGY_LIST_RECEIVE = 'TOPOLOGY/LIST/RECEIVE';
export const TOPOLOGY_LIST_ERROR = 'TOPOLOGY/LIST/ERROR';
export const TOPOLOGY_LIST_CHANGE_SORT = 'TOPOLOGY/LIST/CHANGE_SORT';
export const TOPOLOGY_LIST_CHANGE_PAGE = 'TOPOLOGY/LIST/CHANGE_PAGE';

export const TOPOLOGY_RECEIVE = 'TOPOLOGY_RECEIVE';
export const TOPOLOGY_RECEIVE_ITEMS = 'TOPOLOGY_RECEIVE_ITEMS';
export const TOPOLOGY_REMOVE = 'TOPOLOGY_REMOVE';
export const TOPOLOGY_RECEIVE_SCHEMA = 'TOPOLOGY_RECEIVE_SCHEMA';
export const TOPOLOGY_RECEIVE_TEST = 'TOPOLOGY_RECEIVE_TEST';
export const TOPOLOGY_RESET_TEST = 'TOPOLOGY_RESET_TEST';

// Topology Group

export const TOPOLOGY_GROUP_RECEIVE = 'TOPOLOGY_GROUP_RECEIVE';
export const TOPOLOGY_GROUP_RECEIVE_ITEMS = 'TOPOLOGY_GROUP_RECEIVE_ITEMS';
export const TOPOLOGY_GROUP_REMOVE = 'TOPOLOGY_GROUP_REMOVE';

// Node
export const NODE_LIST_CREATE = 'NODE/LIST/CREATE';
export const NODE_LIST_LOADING = 'NODE/LIST/LOADING';
export const NODE_LIST_RECEIVE = 'NODE/LIST/RECEIVE';
export const NODE_LIST_ERROR = 'NODE/LIST/ERROR';

export const NODE_RECEIVE = 'NODE_RECEIVE';
export const NODE_RECEIVE_ITEMS = 'NODE_RECEIVE_ITEMS';

// Connector Authorizations
export const AUTHORIZATION_LIST_CREATE = 'AUTHORIZATION/LIST/CREATE';
export const AUTHORIZATION_LIST_LOADING = 'AUTHORIZATION/LIST/LOADING';
export const AUTHORIZATION_LIST_RECEIVE = 'AUTHORIZATION/LIST/RECEIVE';
export const AUTHORIZATION_LIST_ERROR = 'AUTHORIZATION/LIST/ERROR';

export const AUTHORIZATION_RECEIVE = 'AUTHORIZATION_RECEIVE';
export const AUTHORIZATION_RECEIVE_ITEMS = 'AUTHORIZATION_RECEIVE_ITEMS';
export const AUTHORIZATION_RECEIVE_SETTINGS = 'AUTHORIZATION_RECEIVE_SETTINGS';

// Category
export const CATEGORY_RECEIVE = 'CATEGORY_RECEIVE';
export const CATEGORY_RECEIVE_ITEMS = 'CATEGORY_RECEIVE_ITEMS';
export const CATEGORY_REMOVE = 'CATEGORY_REMOVE';

export const CATEGORY_TREE_SELECT = 'CATEGORY/TREE/SELECT';
export const CATEGORY_TREE_TOGGLE = 'CATEGORY/TREE/TOGGLE';
export const CATEGORY_TREE_CREATE = 'CATEGORY/TREE/CREATE';
export const CATEGORY_TREE_LOADING = 'CATEGORY/TREE/LOADING';
export const CATEGORY_TREE_RECEIVE = 'CATEGORY/TREE/RECEIVE';
export const CATEGORY_TREE_ERROR = 'CATEGORY/TREE/ERROR';
export const CATEGORY_TREE_INVALIDATE = 'CATEGORY/TREE/INVALIDATE';

// Editable
export const EDITABLE_SWITCH_EDIT = 'EDITABLE_SWITCH_EDIT';
export const EDITABLE_SWITCH_VIEW = 'EDITABLE_SWITCH_VIEW';
export const EDITABLE_CHANGE = 'EDITABLE_CHANGE';

// Metrics
export const METRICS_TOPOLOGY_SET_STATE = 'METRICS_TOPOLOGY_SET_STATE';
export const METRICS_TOPOLOGY_RECEIVE = 'METRICS_TOPOLOGY_RECEIVE';
export const METRICS_TOPOLOGY_INVALIDATE = 'METRICS_TOPOLOGY_INVALIDATE';
export const METRICS_RECEIVE_ITEMS = 'METRICS_RECEIVE_ITEMS';
export const METRICS_SET_STATE = 'METRICS_SET_STATE';
export const METRICS_RECEIVE = 'METRICS_RECEIVE';

// Notification settings
export const NOTIFICATION_SETTINGS_LOADING = 'NOTIFICATION_SETTINGS_LOADING';
export const NOTIFICATION_SETTINGS_RECEIVE = 'NOTIFICATION_SETTINGS_RECEIVE';
export const NOTIFICATION_SETTINGS_ERROR = 'NOTIFICATION_SETTINGS_ERROR';

// General search
export const GENERAL_SEARCH_START_SEARCH = 'GENERAL_SEARCH_START_SEARCH';
export const GENERAL_SEARCH_FINISH = 'GENERAL_SEARCH_FINISH';
export const GENERAL_SEARCH_CLEAR = 'GENERAL_SEARCH_CLEAR';

// Panel
export const PANEL_TOGGLE = 'PANEL_TOOGLE';

// Log
export const LOG_RECEIVE_ITEMS = 'LOG_RECEIVE_ITEMS';
