---
apiVersion: v1
kind: Secret
metadata:
  name: orchesty-secrets
stringData:
  backend_jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  crypt_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  orchesty_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  oc_user_name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  oc_user_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Please keep /<database> the same as XY_DB=<database>
  mongodb_dsn: mongodb://mongodb/orchesty?authSource=admin
  mongodb_db: orchesty
  metrics_dsn: mongodb://mongodb/orchesty-metrics?authSource=admin
  metrics_db: orchesty-metrics

  rabbitmq_dsn: amqp://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@rabbitmq:5672/
  
  # RabbitMQ connection details (if metrics collection is enabled):
  rabbitmq_url: http://rabbitmq:15672
  rabbitmq_user: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  rabbitmq_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Applinth JWE private key (if Applinth is enabled):
  applinth_jwe_private_key: |
    -----BEGIN EC PRIVATE KEY-----
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    -----END EC PRIVATE KEY-----

  # Grafana credentials (if Grafana is enabled):
  admin-user: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  admin-password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # S3 Storage for Loki (if logs is enabled)
  s3-endpoint: storage.googleapis.com
  s3-bucket: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  s3-access-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  s3-secret-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx