apiVersion: v2
name: pipes-demo
description: Pipes demo chart
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: orchesty
  version: "*"
  repository: "file://../../../helm/charts/orchesty"

- name: mongodb
  version: "*"
  condition: mongodb.enabled

- name: rabbitmq
  version: "*"
  condition: rabbitmq.enabled

