apiVersion: v2
name: pipes-demo
description: Pipes demo chart
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: orchesty
  version: "~2.1.3"
  repository: "https://orchesty.github.io/helm-charts/"

- name: demo-applinth
  version: "*"

- name: mongodb
  version: "*"
  condition: mongodb.enabled

- name: rabbitmq
  version: "*"
  condition: rabbitmq.enabled

