---

global:
  backend_url: https://api-orchesty.stage.hanaboso.net
  frontend_url: https://orchesty.stage.hanaboso.net
  starting_point_url: https://sp-orchesty.stage.hanaboso.net

  imageOverrides:
    bridge: hanaboso/bridge:dev
    counter: hanaboso/counter:dev

    # todo: remove when all other stages are migrated
    nodejssdk: dkr.hanaboso.net/pipes/demo/demo-nodejs:dev2
    
    frontend: hanaboso/pipes-app-ui:dev
    backend: hanaboso/pipes-pf-bundle:dev
    topology-api: hanaboso/pipes-topology-api-v2:dev
    starting-point: hanaboso/pipes-starting-point:dev
    fluentd: hanaboso/fluentd:dev
    cron-api: hanaboso/cron:dev
    limiter: hanaboso/limiter:dev
    detector: hanaboso/detector:dev

  applinthMarketplaceUI:
    auth_backlink: https://applinth-demo-client-page.netlify.app/hanaboso-stage/

  backend:
    alpha_instance_id: hb-stage

  workers:
    default:
      sdk: nodejs
      image: dkr.hanaboso.net/pipes/demo/demo-nodejs:dev2
      extraEnv:
        AWS_SES_KEY:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: aws_ses_key
        AWS_SES_SECRET:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: aws_ses_secret

customPersistence:
  node: node1
  pvDir: /srv/pipes3
  pvPrefix: pipes3
  pvcPrefix: pipes3

mongodb:
  pvcName: pipes3-mongodb
  nodeSelector:
    kubernetes.io/hostname: "node1"

rabbitmq:
  pvcName: pipes3-rabbitmq
  nodeSelector:
    kubernetes.io/hostname: "node1"
