---

orchesty:
  nameOverride: pipes

global:
  orchestyVersion: "2.1"
  backend_url: https://api-orchesty.stage.hanaboso.net
  frontend_url: https://orchesty.stage.hanaboso.net
  starting_point_url: https://sp-orchesty.stage.hanaboso.net
  applinth_marketplace_url: https://applinth-orchesty.stage.hanaboso.net

  imageRegistry:
    enablePullSecret: true
    pullSecret: hanaboso-registry-pull-secret

  imageOverrides:
    applinth-marketplace-ui: dkr.hanaboso.net/pipes/pipes/applinth-marketplace-ui:master
    backend: dkr.hanaboso.net/pipes/pipes/applinth:master

  applinthMarketplaceUI:
    auth_backlink: https://demo-applinth-orchesty.stage.hanaboso.net
    service:
      type: LoadBalancer
      port: 80

  startingPoint:
    service:
      type: LoadBalancer
      port: 80

  backend:
    alpha_instance_id: hb-stage
    service:
      type: LoadBalancer
      nodePort: 80

  frontend:
    service:
      type: LoadBalancer
      nodePort: 80

  workers:
    default:
      sdk: nodejs
      image: hanaboso/demo-nodejs:master
      extraEnv:
        AWS_SES_KEY:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: aws_ses_key
        AWS_SES_SECRET:
          valueFrom:
            secretKeyRef:
              name: pipes-secrets
              key: aws_ses_secret
  
  valkey:
    enabled: false

customPersistence:
  node: k3snode1
  pvDir: /srv/pipes3
  pvPrefix: pipes3
  pvcPrefix: pipes3

mongodb:
  pvcName: pipes3-mongodb
  nodeSelector:
    kubernetes.io/hostname: "k3snode1"

rabbitmq:
  pvcName: pipes3-rabbitmq
  nodeSelector:
    kubernetes.io/hostname: "k3snode1"
