---

orchesty:
  # force legacy resource names
  nameOverride: pipes

global:
  backend_url: https://api-umo5mkl8z6.eu1.cloud.orchesty.io
  frontend_url: https://ui-umo5mkl8z6.eu1.cloud.orchesty.io
  starting_point_url: https://start-umo5mkl8z6.eu1.cloud.orchesty.io
  worker_api_url: https://worker-api-umo5mkl8z6.eu1.cloud.orchesty.io

  imageOverrides:
    nodejssdk: hanaboso/demo-nodejs:dev
    applinth-marketplace-ui: dkr.hanaboso.net/pipes/pipes/applinth-marketplace-ui:1.0.6
    backend: dkr.hanaboso.net/pipes/pipes/applinth:1.0.6

  nodejsSdk:
    extraEnv:
      AWS_SES_KEY:
        value: "foo"
      AWS_SES_SECRET:
        value: "bar"

  monitoring:
    useInfluxDB: false
    logStorage: mongodb

  applinth:
    licenseKeyProvided: true

  backend:
    instanceId: umo5mkl8z6

mongodb:
  enabled: false

rabbitmq:
  enabled: false
