---

global:
  backend_url: https://api-orchesty.stage.hanaboso.net
  frontend_url: https://orchesty.stage.hanaboso.net
  starting_point_url: https://sp-orchesty.stage.hanaboso.net

  imageOverrides:
    bridge: hanaboso/bridge:dev
    counter: hanaboso/counter:dev
    repeater: hanaboso/pipes-pf-bridge:dev
    nodejssdk: hanaboso/demo-nodejs:dev
    frontend: hanaboso/pipes-app-ui:dev
    backend: hanaboso/pipes-pf-bundle:dev
    topology-api: hanaboso/pipes-topology-api-v2:dev
    starting-point: hanaboso/pipes-starting-point:dev
    logstash: hanaboso/pipes-logstash-mongo:dev

  applinthMarketplaceUI:
    auth_backlink: https://applinth-demo-client-page.netlify.app/hanaboso-stage/

  backend:
    alpha_instance_id: hb-stage

customPersistence:
  node: node1
  pvDir: /srv/pipes3
  pvPrefix: pipes3
  pvcPrefix: pipes3

mongodb:
  pvcName: pipes3-mongodb
  nodeSelector:
    kubernetes.io/hostname: "node1"

rabbitmq:
  pvcName: pipes3-rabbitmq
  nodeSelector:
    kubernetes.io/hostname: "node1"
