---
.base-documentation:
  variables:
    DIR: docusaurus/documentation

.deploy-documentation:
  stage: deploy

  rules:
    - when: manual

  needs:
    - job: documentation:build
      optional: false

  before_script:
    - !reference [ .base-dind-build, before_script ]
    - apk add --no-cache findutils aws-cli
    - aws --version

  script:
    - cd docusaurus/documentation
    - make deploy BUCKET=pipes-website-${ENV} PORTAL_API_URL=${PORTAL_API_URL}
    - echo Deployed to http://pipes-website-${ENV}.s3-website-eu-west-1.amazonaws.com/

documentation:build:
  stage: build

  extends:
    - .base-dind-build
    - .base-documentation

  rules:
    - when: always

  script:
    - cd docusaurus/documentation
    - make build PORTAL_API_URL=%PORTAL_API_URL% # placeholder to be replaced by deploy job (Makefile)

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - docusaurus/documentation/node_modules

  artifacts:
    expire_in: 1 day
    paths:
      - docusaurus/documentation/build

documentation:deploy:stage:
  variables:
    ENV: stage
    PORTAL_API_URL: "${PORTAL_API_URL_STAGE}"
  extends:
    - .base-dind-build
    - .base-documentation
    - .deploy-documentation

documentation:deploy:prod:
  variables:
    ENV: prod
    PORTAL_API_URL: "${PORTAL_API_URL_PROD}"
  extends:
    - .base-dind-build
    - .base-documentation
    - .deploy-documentation
