rabbit-mq:
    async_consumers:
        async-cron:
            class: CleverConnectors\AppBundle\Model\Cron\CronConsumer
            queue: async-cron
            serializer:
            callback: clever_connectors.cron.cron_batch_callback
            prefetch_count: 10

services:
    clever_connectors.cron.cron_batch_action_callback:
        class: CleverConnectors\AppBundle\Model\Cron\CronBatchActionCallback
        arguments:
            - '@jms_serializer'
            - '%kernel.project_dir%'
        calls:
            - [setLogger, ['@monolog.logger.rabbit-mq']]

    clever_connectors.cron.cron_batch_callback:
        class: Hanaboso\PipesFramework\RabbitMq\Impl\Batch\BatchCallback
        arguments:
            - '@clever_connectors.cron.cron_batch_action_callback'
        calls:
            - [setLogger, ['@monolog.logger.rabbit-mq']]

    clever_connectors.cron.get_system_callback:
            class: CleverConnectors\AppBundle\Command\GetSystemsCommand
            arguments:
                - '@doctrine.odm.mongodb.document_manager'
            tags:
                -  { name: console.command }