.base-applinth:
  variables:
    DIR: applinth
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}applinth

applinth:test:
  stage: test
  extends:
    - .base-test
    - .base-applinth

applinth:build:
  stage: build
  needs:
    - job: applinth:test
      optional: false
  extends:
    - .base-dind-build
    - .base-applinth
