version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-8.1-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:80:80
        working_dir: /var/www/pipes/applinth
        volumes:
            - ../:/var/www/pipes:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            APP_ENV: dev
            APP_DEBUG: 'true'
            PHP_WEBROOT: /var/www/pipes/applinth/public
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            X_AUTH_KEY: abc-123
            KERNEL_CLASS: Hanaboso\Applinth\Kernel
            COMPOSER_HOME: ${HOME}/dev/.composer
            FRONTEND_DSN: ${DEV_IP}
            BACKEND_DSN: ${DEV_IP}
            MONGODB_DSN: mongodb://mongo
            MONGODB_DB: pipes
            METRICS_DSN: mongodb://mongo
            METRICS_DB: metrics
            METRICS_SERVICE: mongo
            CHECK_INFINITY_LOOP: 'true'
            TOPOLOGY_API_DSN: topology-api:80
            STARTING_POINT_DSN: starting-point:8080
            CRON_DSN: http://cron-api:8080
            RABBITMQ_DSN: amqp://rabbitmq:5672
            WORKER_DEFAULT_PORT: 8008
            JWT_KEY: BWoCz4gxw3YHDMkqE5HD1WT2u6zqIAtiJkYVyf6UucL4ZtbhhatQooP5IgTQRwowYR6z8wE3biqZTl37
            CRYPT_SECRET: ThisTokenIsNotSoSecretChangeIt
            JWE_PRIVATE_KEY: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIAGmQ//yMnyMlFAN/E2yfZjzFL1ziTrAbDwa08KEPBq+NUWHvrxrs7
                f8tvm0y+PwcNgdKhSiMN/osY4/iK+vyr9WqgBwYFK4EEACOhgYkDgYYABABnJEkK
                knFnpxumSFk5MFIEYTm2ReaalO4UrCc4QROIchTIZYRb9GeSounARtxnJcfYa+CB
                pXzObmLNvN3u75L2pADOg4p+GkgwtFdfSa5HhMoQD2jEEmL3otvyjf8jF5t8u2YP
                GcXwowJ2vWSQ6pyW17FLVqmUy2ZW5VSowkPp29CvYQ==
                -----END EC PRIVATE KEY-----

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - ${DEV_IP}:8080:8080
        volumes:
            - ./openapi.yaml:/api.yaml
        environment:
            SWAGGER_JSON: /api.yaml

    mongo:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongo:/data/db

volumes:
    mongo: {}
    influxdb: {}
