services:
    sdk:
        image: node-sdk:tag
        build: ./docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            # Envs for tests are load from .jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: 'debug'
            CRYPT_SECRET: ThisIsNotSoSecret
            BACKEND_URL: ${DEV_IP}:8080
            STARTING_POINT_DSN: ${DEV_IP}:8080
            AWS_SES_KEY: ${AWS_SES_KEY}
            AWS_SES_SECRET: ${AWS_SES_SECRET}
            WORKER_API_HOST: ${DEV_IP}:8080
            ORCHESTY_API_KEY: ThisIsNotSoSecret
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        command: /bin/sh -c 'pnpm i && pnpm run start'

    mongo:
        image: mongo
        ports:
            - ${DEV_IP}:27017:27017

    mysql:
        image: mysql:latest
        ports:
            - ${DEV_IP}:3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./test/init-data/mysql:/docker-entrypoint-initdb.d
