services:
    _defaults:
        public: '%public.services%'
        autowire: true
        autoconfigure: true

    Hanaboso\PipesFrameworkEnterprise\HbPFMcpBundle\Controller\McpController:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFMcpBundle\Controller\McpController
        arguments:
            - '@hbpf.mcp.handler.mcp'

    Hanaboso\PipesFrameworkEnterprise\HbPFMcpBundle\Controller\AuditEntityController:
        class: Hanaboso\PipesFrameworkEnterprise\HbPFMcpBundle\Controller\AuditEntityController
        arguments:
            - '@hbpf.mcp.handler.audit_entity'
