services:
    _defaults:
        public: '%public.services%'

    hbpf.mcp.manager.loki:
        class: Hanaboso\PipesFrameworkEnterprise\Mcp\Model\LokiManager
        arguments:
            - '@hbpf.transport.curl_manager'
            - '%lokiHost%'

    hbpf.mcp.manager.mcp:
        class: Hanaboso\PipesFrameworkEnterprise\Mcp\Model\McpManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.mcp.manager.loki'
            - '@hbpf.mcp.manager.metrics_aggregator'

    hbpf.mcp.manager.metrics_aggregator:
        class: Hanaboso\PipesFrameworkEnterprise\Mcp\Model\MetricsAggregator
        arguments:
            - '@hbpf.configurator.handler.process'
            - '@hbpf.metrics.handler.metrics'
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.mcp.manager.audit_entity:
        class: Hanaboso\PipesFrameworkEnterprise\Mcp\Model\AuditEntityManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
