services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFUserBundle\Controller\UserController:
        class: Hanaboso\PipesFramework\HbPFUserBundle\Controller\UserController
        arguments:
            - '@hbpf.user.handler.users'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]