hb_pf_api_gateway:
    resource: '@HbPFApiGatewayBundle'
    type:     annotation
    prefix:   /api

hb_pf_application:
    resource: "@HbPFApplicationBundle"
    type: annotation

hb_pf_connector:
    resource: "@HbPFConnectorBundle"
    type: annotation

hb_pf_custom_node:
    resource: "@HbPFCustomNodeBundle"
    type: annotation

hb_pf_table_parser:
    resource: "@HbPFTableParserBundle"
    type: annotation

hb_pf_configurator:
    resource: '@HbPFConfiguratorBundle'
    type: annotation

hb_pf_metrics:
    resource: '@HbPFMetricsBundle'
    type: annotation

hb_pf_notification:
    resource: '@HbPFNotificationBundle'
    type: annotation

hb_pf_logs:
    resource: '@HbPFLogsBundle'
    type: annotation

hb_pf_long_running:
    resource: '@HbPFLongRunningNodeBundle'
    type: annotation

hb_pf_users:
    resource: "@HbPFUsersBundle"
    type: annotation