export const GRID = {
  ACTIONS: {
    GRID_FETCH: 'GRID_FETCH',
    FETCH_WITH_DATA: 'FETCH_WITH_DATA',
    FETCH_DATA_WITHOUT_STORE: 'FETCH_DATA_WITHOUT_STORE',
    FETCH_WITH_INITIAL_STATE: 'FETCH_WITH_INITIAL_STATE',
    RESET: 'RESET',
  },
  GETTERS: {
    GET_PAGING: 'GET_PAGING',
    GET_SORTER: 'GET_SORTER',
    GET_FILTER: 'GET_FILTER',
  },
  MUTATIONS: {
    GRID_RESPONSE: 'GRID_RESPONSE',
    RESET: 'RESET',
  },
}
