.base-detector:
  variables:
    DIR: detector
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}detector

detector:test:
  stage: test
  extends:
    - .base-test
    - .base-detector

detector:build:
  stage: build
  needs:
    - job: detector:test
      optional: false
  extends:
    - .base-dind-build
    - .base-detector

