export const USER_TASKS = {
  NAMESPACE: 'userTasks',
  ACTIONS: {
    USER_TASK_UPDATE: 'USER_TASK_UPDATE',
    USER_TASK_ACCEPT: 'USER_TASK_ACCEPT',
    USER_TASK_ACCEPT_LIST: 'USER_TASK_ACCEPT_LIST',
    USER_TASK_REJECT: 'USER_TASK_REJECT',
    USER_TASK_REJECT_LIST: 'USER_TASK_REJECT_LIST',
    USER_TASK_GET: 'USER_TASK_GET',
    USER_TASK_FETCH_TASKS: 'USER_TASK_FETCH_TASKS',
  },
  MUTATIONS: {
    USER_TASK_GET: 'USER_TASK_GET',
    USER_TASK_FETCH_TASKS: 'USER_TASK_FETCH_TASKS',
    RESET: 'RESET',
  },
  GETTERS: {
    GET_USER_TASKS: 'GET_USER_TASKS',
  },
}
