parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    container:
        dumper:
            inline_factories: true

    backendHost: '%env(BACKEND_DSN)%'
    startingPointHost: "%env(string:STARTING_POINT_DSN)%"

    env(UDP_LOGGER_URL): "fluentd:5120"
    udp_logger_url: "%env(string:UDP_LOGGER_URL)%"

    access_token_refresh_interval: 3600
    node_services_dirs:
        - '%kernel.project_dir%/config'
        - '%kernel.project_dir%/vendor/orchesty/php-connectors/src/Resources/config/'

    applications:
        - '%kernel.project_dir%/vendor/orchesty/php-connectors/src/Resources/config/'

    kernel.root_dir: '%kernel.project_dir%/src'

services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: '%public.services%'

    Demo\Controller\DefaultController:
        class: Demo\Controller\DefaultController
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    Demo\Command\DownloaderCommand:
        arguments:
            - 'downloader:run'
            - '@hbpf.transport.curl_manager'
        tags:
            - { name: 'console.command', command: 'downloader:run' }

    mailer:
        class: EmailServiceBundle\Mailer\Mailer
        arguments:
            - '@EmailServiceBundle\Transport\Impl\SymfonyMailerTransport'
