parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt

    backend_host: 127.0.0.66
    cron_host: 'http://cron-api:5000'
    starting_point_host: 'http://starting-point'
    notification_host: 'http://notification-sender-api'
    activateLink: '%backend_host%/user/%s/activate'
    access_token_refresh_interval: 3600
    node_services_dirs: ['%kernel.project_dir%/config']
    applications: ['%kernel.root_dir%/../vendor/hanaboso/pipes-connectors/src/Resources/config/']

services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: '%public.services%'

    Demo\Controller\DefaultController:
        class: Demo\Controller\DefaultController
        calls:
            - ['setContainer', ['@service_container']]


    Demo\Command\DownloaderCommand:
        arguments:
            - 'downloader:run'
        tags:
            - { name: 'console.command', command: 'downloader:run' }

    Demo\Command\KapacitorCommand:
        arguments:
            - 'kapacitor:run'
        tags:
            - { name: 'console.command', command: 'kapacitor:run' }


    # Connector
    hbpf.connector.batch:
        class: Demo\Connector\BatchConnector

    hbpf.connector.pager-duty:
        class: Demo\Connector\PagerDutyConnector
        arguments:
            - '@hbpf.transport.curl_manager'

    # CustomNode
    hbpf.custom_node.batch:
        class: Demo\CustomNode\BatchCustomNode

    hbpf.custom_node.data-generator:
        class: Demo\CustomNode\DataGeneratorConnector

    hbpf.custom_node.package:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.pick-area:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.customer-notify:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.extra-insurance:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.print-label:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.request-carrier:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.fill-in-form:
        class: Demo\CustomNode\DummyConnectorSplit

    hbpf.custom_node.check-insurance:
        class: Demo\CustomNode\DummyConnectorSplit

    hbpf.custom_node.dummy-exception:
        class: Demo\CustomNode\DummyExceptionConnector
        calls:
            - ['setLogger', ['@monolog.logger.connector']]

    hbpf.custom_node.filter-bids:
        class: Demo\CustomNode\FilterStockExchange
        arguments:
            - 'bids'

    hbpf.custom_node.filter-asks:
        class: Demo\CustomNode\FilterStockExchange
        arguments:
            - 'asks'
        calls:
            - ['setLogger', ['@monolog.logger.connector']]

    hbpf.custom_node.idnes:
        class: Demo\CustomNode\IdnesConnector
        arguments:
            - '@hbpf.transport.curl_manager'

    hbpf.custom_node.split-file:
        class: Demo\CustomNode\SplitFileBatch

    hbpf.custom_node.split-file2:
        class: Demo\CustomNode\SplitFileBatch2
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@rabbit_mq.publisher.test_batch'

    # LongRunningNode
    hbpf.long_running.time-stamper:
        class: Demo\LongRunningNode\TimeStamperHumanTask
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.long_running.time-stamper-one:
        class: Demo\LongRunningNode\TimeStamperHumanTask
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.long_running.time-stamper-two:
        class: Demo\LongRunningNode\TimeStamperHumanTask
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.custom_node.send-duty-email:
        class: Demo\CustomNode\SendDutyEmail
        arguments:
            - '@mailer'
            - '@hbpf.connector.pager-duty'

    mailer:
        class: EmailServiceBundle\Mailer\Mailer
        arguments:
            - '@EmailServiceBundle\Transport\Impl\SwiftMailerTransport'
