parameters:
    locale: en
    secret: ThisIsNotSoSecret
    container:
        dumper:
            inline_factories: true

    node_services_dirs:
        - '%kernel.project_dir%/config'
        - '%kernel.project_dir%/vendor/orchesty/php-connectors/src/Resources/config/'

    applications:
        - '%kernel.project_dir%/config'
        - '%kernel.project_dir%/vendor/orchesty/php-connectors/src/Resources/config/'

    kernel.root_dir: '%kernel.project_dir%/src'
services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: '%public.services%'

    Demo\Controller\DefaultController:
        class: Demo\Controller\DefaultController

    mailer:
        class: EmailServiceBundle\Mailer\Mailer
        arguments:
            - '@EmailServiceBundle\Transport\Impl\SymfonyMailerTransport'
