parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    container:
        dumper:
            inline_factories: true

    backendHost: '%env(BACKEND_DSN)%'
    startingPointHost: "%env(string:STARTING_POINT_DSN)%"

    env(UDP_LOGGER_URL): "fluentd:5120"
    udp_logger_url: "%env(string:UDP_LOGGER_URL)%"

    access_token_refresh_interval: 3600
    node_services_dirs:
        - '%kernel.project_dir%/config'
        - '%kernel.project_dir%/vendor/orchesty/php-connectors/src/Resources/config/'

    applications:
        - '%kernel.project_dir%/vendor/orchesty/php-connectors/src/Resources/config/'

    kernel.root_dir: '%kernel.project_dir%/src'

services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: '%public.services%'

    Demo\Controller\DefaultController:
        class: Demo\Controller\DefaultController
        calls:
            - [ 'setContainer', [ '@service_container' ] ]


    Demo\Command\DownloaderCommand:
        arguments:
            - 'downloader:run'
            - '@hbpf.transport.curl_manager'
        tags:
            - { name: 'console.command', command: 'downloader:run' }

    # Connector
    hbpf.connector.pager-duty:
        class: Demo\Connector\PagerDutyConnector
        calls:
            -   setSender: [ '@hbpf.transport.curl_manager' ]

    # CustomNode
    hbpf.custom_node.data-generator:
        class: Demo\CustomNode\DataGeneratorConnector

    hbpf.custom_node.package:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.pick-area:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.customer-notify:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.extra-insurance:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.print-label:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.request-carrier:
        class: Demo\CustomNode\DummyConnector

    hbpf.custom_node.fill-in-form:
        class: Demo\CustomNode\DummyConnectorSplit

    hbpf.custom_node.check-insurance:
        class: Demo\CustomNode\DummyConnectorSplit

    hbpf.custom_node.dummy-exception:
        class: Demo\CustomNode\DummyExceptionConnector
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]

    hbpf.custom_node.filter-bids:
        class: Demo\CustomNode\FilterStockExchange
        arguments:
            - 'bids'

    hbpf.custom_node.filter-asks:
        class: Demo\CustomNode\FilterStockExchange
        arguments:
            - 'asks'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]

    hbpf.idnes-connector:
        class: Demo\Connector\IdnesConnector
        calls:
            -   setSender: [ '@hbpf.transport.curl_manager' ]

    hbpf.custom_node.send-duty-email:
        class: Demo\CustomNode\SendDutyEmail
        arguments:
            - '@mailer'
            - '@hbpf.connector.pager-duty'

    mailer:
        class: EmailServiceBundle\Mailer\Mailer
        arguments:
            - '@EmailServiceBundle\Transport\Impl\SymfonyMailerTransport'

    hbpf.custom_node.hub-spot.create-multiple-contact-mapper:
        class: Demo\CustomNode\HubSpotCreateMultipleContactsMapper

    hbpf.connector.get-users:
        class: Demo\Connector\GetUsersConnector
        calls:
            -   setSender: [ '@hbpf.transport.curl_manager' ]

    hbpf.connector.hub-spot.create-multiple-contact:
        class: Demo\Connector\HubSpotCreateMultipleContactsConnector
        calls:
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
            -   setApplication: [ '@hbpf.application.hub-spot' ]
            -   setLogger: [ '@monolog.logger.commons' ]
