parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt

    backend_host: 127.0.0.66
    cron_host: 'http://cron-api:5000'
    monolith_host: 'http://php-dev'
    notification_host: 'http://notification-sender-api/notification-sender'
    activateLink: '%backend_host%/user/%s/activate'
    access_token_refresh_interval: 3600

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Demo\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Demo\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    hbpf.custom_node.filter-bids:
        class: Demo\CustomNode\FilterStockExchange
        public: true
        arguments:
            - 'bids'

    hbpf.custom_node.filter-asks:
        class: Demo\CustomNode\FilterStockExchange
        public: true
        arguments:
            - 'asks'

    hbpf.custom_node.split-file:
        class: Demo\CustomNode\SplitFileBatch
        public: true

    hbpf.custom_node.split-file2:
        class: Demo\CustomNode\SplitFileBatch2
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@rabbit-mq.producer.test_batch'
        public: true

    hbpf.custom_node.idnes:
        class: Demo\CustomNode\IdnesConnector
        public: true
        arguments:
            - '@hbpf.transport.curl_manager'

    hbpf.custom_node.package:
        class: Demo\CustomNode\DummyConnector
        public: true

    hbpf.custom_node.pick-area:
        class: Demo\CustomNode\DummyConnector
        public: true

    hbpf.custom_node.customer-notify:
        class: Demo\CustomNode\DummyConnector
        public: true

    hbpf.custom_node.check-insurance:
        class: Demo\CustomNode\DummyConnectorSplit
        public: true

    hbpf.custom_node.extra-insurance:
        class: Demo\CustomNode\DummyConnector
        public: true

    hbpf.custom_node.print-label:
        class: Demo\CustomNode\DummyConnector
        public: true

    hbpf.custom_node.fill-in-form:
        class: Demo\CustomNode\DummyConnectorSplit
        public: true

    hbpf.custom_node.request-carrier:
        class: Demo\CustomNode\DummyConnector
        public: true
