// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WorkflowService.proto

/*
Package workflow is a generated protocol buffer package.

It is generated from these files:
	WorkflowService.proto

It has these top-level messages:
	CreateRequest
	UpdateRequest
	DeleteRequest
	ReadRequest
	ReadAllRequest
	WorkflowResponse
	ConfigRequest
	ConfigTypesResponse
	EditorConfig
	WorkflowConfig
*/
package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConditionType int32

const (
	ConditionType_AND  ConditionType = 0
	ConditionType_OR   ConditionType = 1
	ConditionType_ELSE ConditionType = 2
)

var ConditionType_name = map[int32]string{
	0: "AND",
	1: "OR",
	2: "ELSE",
}
var ConditionType_value = map[string]int32{
	"AND":  0,
	"OR":   1,
	"ELSE": 2,
}

func (x ConditionType) String() string {
	return proto.EnumName(ConditionType_name, int32(x))
}
func (ConditionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DistributeType int32

const (
	DistributeType_ADD    DistributeType = 0
	DistributeType_REMOVE DistributeType = 1
)

var DistributeType_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
}
var DistributeType_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
}

func (x DistributeType) String() string {
	return proto.EnumName(DistributeType_name, int32(x))
}
func (DistributeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WorkflowConfig_Step_Recommendation_Type int32

const (
	WorkflowConfig_Step_Recommendation_STANDARD WorkflowConfig_Step_Recommendation_Type = 0
	WorkflowConfig_Step_Recommendation_CUSTOM   WorkflowConfig_Step_Recommendation_Type = 1
)

var WorkflowConfig_Step_Recommendation_Type_name = map[int32]string{
	0: "STANDARD",
	1: "CUSTOM",
}
var WorkflowConfig_Step_Recommendation_Type_value = map[string]int32{
	"STANDARD": 0,
	"CUSTOM":   1,
}

func (x WorkflowConfig_Step_Recommendation_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_Recommendation_Type_name, int32(x))
}
func (WorkflowConfig_Step_Recommendation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 0, 0}
}

type WorkflowConfig_Step_Segmentation_Type int32

const (
	WorkflowConfig_Step_Segmentation_BUSINESS WorkflowConfig_Step_Segmentation_Type = 0
	WorkflowConfig_Step_Segmentation_GRAPHICS WorkflowConfig_Step_Segmentation_Type = 1
	WorkflowConfig_Step_Segmentation_BOTH     WorkflowConfig_Step_Segmentation_Type = 2
)

var WorkflowConfig_Step_Segmentation_Type_name = map[int32]string{
	0: "BUSINESS",
	1: "GRAPHICS",
	2: "BOTH",
}
var WorkflowConfig_Step_Segmentation_Type_value = map[string]int32{
	"BUSINESS": 0,
	"GRAPHICS": 1,
	"BOTH":     2,
}

func (x WorkflowConfig_Step_Segmentation_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_Segmentation_Type_name, int32(x))
}
func (WorkflowConfig_Step_Segmentation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 1, 0}
}

type WorkflowConfig_Step_ChannelMap_Action_Family int32

const (
	WorkflowConfig_Step_ChannelMap_Action_TAG  WorkflowConfig_Step_ChannelMap_Action_Family = 0
	WorkflowConfig_Step_ChannelMap_Action_LIST WorkflowConfig_Step_ChannelMap_Action_Family = 1
)

var WorkflowConfig_Step_ChannelMap_Action_Family_name = map[int32]string{
	0: "TAG",
	1: "LIST",
}
var WorkflowConfig_Step_ChannelMap_Action_Family_value = map[string]int32{
	"TAG":  0,
	"LIST": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Family) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Family_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Family) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 4, 2, 0}
}

type CreateRequest struct {
	Json       string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
	ClientId   int32  `protobuf:"varint,2,opt,name=clientId" json:"clientId,omitempty"`
	ClientGuid string `protobuf:"bytes,3,opt,name=clientGuid" json:"clientGuid,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *CreateRequest) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *CreateRequest) GetClientGuid() string {
	if m != nil {
		return m.ClientGuid
	}
	return ""
}

type UpdateRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Json string `protobuf:"bytes,2,opt,name=json" json:"json,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadAllRequest struct {
	EditorId string `protobuf:"bytes,1,opt,name=editor_id,json=editorId" json:"editor_id,omitempty"`
}

func (m *ReadAllRequest) Reset()                    { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()               {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadAllRequest) GetEditorId() string {
	if m != nil {
		return m.EditorId
	}
	return ""
}

type WorkflowResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Json    string `protobuf:"bytes,4,opt,name=json" json:"json,omitempty"`
}

func (m *WorkflowResponse) Reset()                    { *m = WorkflowResponse{} }
func (m *WorkflowResponse) String() string            { return proto.CompactTextString(m) }
func (*WorkflowResponse) ProtoMessage()               {}
func (*WorkflowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WorkflowResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkflowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WorkflowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

// event manager & collector specific
type ConfigRequest struct {
	ClientId int32 `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (m *ConfigRequest) Reset()                    { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()               {}
func (*ConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ConfigRequest) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

// collector response
type ConfigTypesResponse struct {
	ClientDomain string `protobuf:"bytes,1,opt,name=client_domain,json=clientDomain" json:"client_domain,omitempty"`
	ClientId     int32  `protobuf:"varint,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	EventType    string `protobuf:"bytes,3,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
}

func (m *ConfigTypesResponse) Reset()                    { *m = ConfigTypesResponse{} }
func (m *ConfigTypesResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfigTypesResponse) ProtoMessage()               {}
func (*ConfigTypesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ConfigTypesResponse) GetClientDomain() string {
	if m != nil {
		return m.ClientDomain
	}
	return ""
}

func (m *ConfigTypesResponse) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *ConfigTypesResponse) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type EditorConfig struct {
	Items []*EditorConfig_EditorConfigItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *EditorConfig) Reset()                    { *m = EditorConfig{} }
func (m *EditorConfig) String() string            { return proto.CompactTextString(m) }
func (*EditorConfig) ProtoMessage()               {}
func (*EditorConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EditorConfig) GetItems() []*EditorConfig_EditorConfigItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type EditorConfig_EditorConfigItem struct {
	Id       string                                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ParentId string                                  `protobuf:"bytes,2,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Type     string                                  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Settings *EditorConfig_EditorConfigItem_Settings `protobuf:"bytes,4,opt,name=settings" json:"settings,omitempty"`
}

func (m *EditorConfig_EditorConfigItem) Reset()         { *m = EditorConfig_EditorConfigItem{} }
func (m *EditorConfig_EditorConfigItem) String() string { return proto.CompactTextString(m) }
func (*EditorConfig_EditorConfigItem) ProtoMessage()    {}
func (*EditorConfig_EditorConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *EditorConfig_EditorConfigItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem) GetSettings() *EditorConfig_EditorConfigItem_Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings struct {
	Condition          *EditorConfig_EditorConfigItem_Settings_Condition          `protobuf:"bytes,1,opt,name=condition" json:"condition,omitempty"`
	ConditionBranchYes *EditorConfig_EditorConfigItem_Settings_ConditionBranchYes `protobuf:"bytes,2,opt,name=condition_branch_yes,json=conditionBranchYes" json:"condition_branch_yes,omitempty"`
	ConditionBranchNo  *EditorConfig_EditorConfigItem_Settings_ConditionBranchNo  `protobuf:"bytes,3,opt,name=condition_branch_no,json=conditionBranchNo" json:"condition_branch_no,omitempty"`
	Distribute         *EditorConfig_EditorConfigItem_Settings_Distribute         `protobuf:"bytes,4,opt,name=distribute" json:"distribute,omitempty"`
	Email              *EditorConfig_EditorConfigItem_Settings_Email              `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Empty              *EditorConfig_EditorConfigItem_Settings_Empty              `protobuf:"bytes,6,opt,name=empty" json:"empty,omitempty"`
	End                *EditorConfig_EditorConfigItem_Settings_End                `protobuf:"bytes,7,opt,name=end" json:"end,omitempty"`
	JoinSource         string                                                     `protobuf:"bytes,8,opt,name=join_source,json=joinSource" json:"join_source,omitempty"`
	JoinDestination    string                                                     `protobuf:"bytes,9,opt,name=join_destination,json=joinDestination" json:"join_destination,omitempty"`
	Notify             *EditorConfig_EditorConfigItem_Settings_Notify             `protobuf:"bytes,10,opt,name=notify" json:"notify,omitempty"`
	Trigger            *EditorConfig_EditorConfigItem_Settings_Trigger            `protobuf:"bytes,11,opt,name=trigger" json:"trigger,omitempty"`
	Wait               *EditorConfig_EditorConfigItem_Settings_Wait               `protobuf:"bytes,12,opt,name=wait" json:"wait,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings{}
}
func (m *EditorConfig_EditorConfigItem_Settings) String() string { return proto.CompactTextString(m) }
func (*EditorConfig_EditorConfigItem_Settings) ProtoMessage()    {}
func (*EditorConfig_EditorConfigItem_Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings) GetCondition() *EditorConfig_EditorConfigItem_Settings_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetConditionBranchYes() *EditorConfig_EditorConfigItem_Settings_ConditionBranchYes {
	if m != nil {
		return m.ConditionBranchYes
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetConditionBranchNo() *EditorConfig_EditorConfigItem_Settings_ConditionBranchNo {
	if m != nil {
		return m.ConditionBranchNo
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetDistribute() *EditorConfig_EditorConfigItem_Settings_Distribute {
	if m != nil {
		return m.Distribute
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetEmail() *EditorConfig_EditorConfigItem_Settings_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetEmpty() *EditorConfig_EditorConfigItem_Settings_Empty {
	if m != nil {
		return m.Empty
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetEnd() *EditorConfig_EditorConfigItem_Settings_End {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetJoinSource() string {
	if m != nil {
		return m.JoinSource
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings) GetJoinDestination() string {
	if m != nil {
		return m.JoinDestination
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings) GetNotify() *EditorConfig_EditorConfigItem_Settings_Notify {
	if m != nil {
		return m.Notify
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetTrigger() *EditorConfig_EditorConfigItem_Settings_Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetWait() *EditorConfig_EditorConfigItem_Settings_Wait {
	if m != nil {
		return m.Wait
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings_Condition struct {
	Type       ConditionType                                                 `protobuf:"varint,1,opt,name=type,enum=workflowservice.ConditionType" json:"type,omitempty"`
	Conditions []*EditorConfig_EditorConfigItem_Settings_Condition_Condition `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Condition{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Condition) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Condition) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition) GetType() ConditionType {
	if m != nil {
		return m.Type
	}
	return ConditionType_AND
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition) GetConditions() []*EditorConfig_EditorConfigItem_Settings_Condition_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings_Condition_Condition struct {
	Field    string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Operator string `protobuf:"bytes,2,opt,name=operator" json:"operator,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Condition_Condition{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Condition_Condition) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Condition_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 0, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_ConditionBranchYes struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_ConditionBranchYes) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_ConditionBranchYes{}
}
func (m *EditorConfig_EditorConfigItem_Settings_ConditionBranchYes) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_ConditionBranchYes) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_ConditionBranchYes) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 1}
}

type EditorConfig_EditorConfigItem_Settings_ConditionBranchNo struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_ConditionBranchNo) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_ConditionBranchNo{}
}
func (m *EditorConfig_EditorConfigItem_Settings_ConditionBranchNo) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_ConditionBranchNo) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_ConditionBranchNo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 2}
}

type EditorConfig_EditorConfigItem_Settings_Distribute struct {
	Type   DistributeType `protobuf:"varint,1,opt,name=type,enum=workflowservice.DistributeType" json:"type,omitempty"`
	ListId string         `protobuf:"bytes,2,opt,name=list_id,json=listId" json:"list_id,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Distribute) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Distribute{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Distribute) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Distribute) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Distribute) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 3}
}

func (m *EditorConfig_EditorConfigItem_Settings_Distribute) GetType() DistributeType {
	if m != nil {
		return m.Type
	}
	return DistributeType_ADD
}

func (m *EditorConfig_EditorConfigItem_Settings_Distribute) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_Email struct {
	SenderName  string `protobuf:"bytes,1,opt,name=sender_name,json=senderName" json:"sender_name,omitempty"`
	SenderEmail string `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail" json:"sender_email,omitempty"`
	Subject     string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	TemplateId  string `protobuf:"bytes,4,opt,name=template_id,json=templateId" json:"template_id,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Email{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Email) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Email) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 4}
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetSenderEmail() string {
	if m != nil {
		return m.SenderEmail
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_Empty struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_Empty) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Empty{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Empty) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Empty) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 5}
}

type EditorConfig_EditorConfigItem_Settings_End struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_End) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_End{}
}
func (m *EditorConfig_EditorConfigItem_Settings_End) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_End) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_End) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 6}
}

type EditorConfig_EditorConfigItem_Settings_Notify struct {
	Email bool `protobuf:"varint,1,opt,name=email" json:"email,omitempty"`
	Aim   bool `protobuf:"varint,2,opt,name=aim" json:"aim,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Notify) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Notify{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Notify) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Notify) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 7}
}

func (m *EditorConfig_EditorConfigItem_Settings_Notify) GetEmail() bool {
	if m != nil {
		return m.Email
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Notify) GetAim() bool {
	if m != nil {
		return m.Aim
	}
	return false
}

type EditorConfig_EditorConfigItem_Settings_Trigger struct {
	Lists        []string                                                     `protobuf:"bytes,1,rep,name=lists" json:"lists,omitempty"`
	Segments     []string                                                     `protobuf:"bytes,2,rep,name=segments" json:"segments,omitempty"`
	Event        string                                                       `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	EventOptions *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions `protobuf:"bytes,4,opt,name=event_options,json=eventOptions" json:"event_options,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Trigger{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Trigger) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Trigger) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 8}
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetLists() []string {
	if m != nil {
		return m.Lists
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetSegments() []string {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetEventOptions() *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions {
	if m != nil {
		return m.EventOptions
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions struct {
	Type         string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ClientDomain string   `protobuf:"bytes,2,opt,name=client_domain,json=clientDomain" json:"client_domain,omitempty"`
	Manually     bool     `protobuf:"varint,3,opt,name=manually" json:"manually,omitempty"`
	Batch        bool     `protobuf:"varint,4,opt,name=batch" json:"batch,omitempty"`
	WebServices  bool     `protobuf:"varint,5,opt,name=web_services,json=webServices" json:"web_services,omitempty"`
	DateFields   []string `protobuf:"bytes,6,rep,name=date_fields,json=dateFields" json:"date_fields,omitempty"`
	DateValue    string   `protobuf:"bytes,7,opt,name=date_value,json=dateValue" json:"date_value,omitempty"`
	EventValue   string   `protobuf:"bytes,8,opt,name=event_value,json=eventValue" json:"event_value,omitempty"`
	RssUrl       string   `protobuf:"bytes,9,opt,name=rss_url,json=rssUrl" json:"rss_url,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 8, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetClientDomain() string {
	if m != nil {
		return m.ClientDomain
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetManually() bool {
	if m != nil {
		return m.Manually
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetWebServices() bool {
	if m != nil {
		return m.WebServices
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetDateFields() []string {
	if m != nil {
		return m.DateFields
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetDateValue() string {
	if m != nil {
		return m.DateValue
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetEventValue() string {
	if m != nil {
		return m.EventValue
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetRssUrl() string {
	if m != nil {
		return m.RssUrl
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_Wait struct {
	Duration int32  `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
	Unit     string `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Wait) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Wait{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Wait) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Wait) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Wait) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0, 9}
}

func (m *EditorConfig_EditorConfigItem_Settings_Wait) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *EditorConfig_EditorConfigItem_Settings_Wait) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type WorkflowConfig struct {
	Id           string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientDomain string                 `protobuf:"bytes,2,opt,name=client_domain,json=clientDomain" json:"client_domain,omitempty"`
	Type         string                 `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ClientId     int32                  `protobuf:"varint,4,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientGuid   string                 `protobuf:"bytes,5,opt,name=client_guid,json=clientGuid" json:"client_guid,omitempty"`
	Filter       *WorkflowConfig_Filter `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	Steps        []*WorkflowConfig_Step `protobuf:"bytes,7,rep,name=steps" json:"steps,omitempty"`
	EditorItemId string                 `protobuf:"bytes,8,opt,name=editor_item_id,json=editorItemId" json:"editor_item_id,omitempty"`
}

func (m *WorkflowConfig) Reset()                    { *m = WorkflowConfig{} }
func (m *WorkflowConfig) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig) ProtoMessage()               {}
func (*WorkflowConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *WorkflowConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowConfig) GetClientDomain() string {
	if m != nil {
		return m.ClientDomain
	}
	return ""
}

func (m *WorkflowConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WorkflowConfig) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *WorkflowConfig) GetClientGuid() string {
	if m != nil {
		return m.ClientGuid
	}
	return ""
}

func (m *WorkflowConfig) GetFilter() *WorkflowConfig_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *WorkflowConfig) GetSteps() []*WorkflowConfig_Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *WorkflowConfig) GetEditorItemId() string {
	if m != nil {
		return m.EditorItemId
	}
	return ""
}

type WorkflowConfig_Filter struct {
	InSegments    []string `protobuf:"bytes,1,rep,name=in_segments,json=inSegments" json:"in_segments,omitempty"`
	InLists       []string `protobuf:"bytes,2,rep,name=in_lists,json=inLists" json:"in_lists,omitempty"`
	NotInSegments []string `protobuf:"bytes,3,rep,name=not_in_segments,json=notInSegments" json:"not_in_segments,omitempty"`
	NotInLists    []string `protobuf:"bytes,4,rep,name=not_in_lists,json=notInLists" json:"not_in_lists,omitempty"`
	Priority      int32    `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
}

func (m *WorkflowConfig_Filter) Reset()                    { *m = WorkflowConfig_Filter{} }
func (m *WorkflowConfig_Filter) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Filter) ProtoMessage()               {}
func (*WorkflowConfig_Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *WorkflowConfig_Filter) GetInSegments() []string {
	if m != nil {
		return m.InSegments
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetInLists() []string {
	if m != nil {
		return m.InLists
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetNotInSegments() []string {
	if m != nil {
		return m.NotInSegments
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetNotInLists() []string {
	if m != nil {
		return m.NotInLists
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type WorkflowConfig_Step struct {
	StepId         string                              `protobuf:"bytes,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	Conditions     []*WorkflowConfig_Step_Condition    `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`
	Recommendation *WorkflowConfig_Step_Recommendation `protobuf:"bytes,3,opt,name=recommendation" json:"recommendation,omitempty"`
	Segmentation   *WorkflowConfig_Step_Segmentation   `protobuf:"bytes,4,opt,name=segmentation" json:"segmentation,omitempty"`
	Channels       *WorkflowConfig_Step_ChannelMap     `protobuf:"bytes,5,opt,name=channels" json:"channels,omitempty"`
	NextFlow       *WorkflowConfig_Step_NextFlow       `protobuf:"bytes,6,opt,name=next_flow,json=nextFlow" json:"next_flow,omitempty"`
	Wait           *WorkflowConfig_Step_Wait           `protobuf:"bytes,7,opt,name=wait" json:"wait,omitempty"`
	ConditionOpt   *WorkflowConfig_Step_Option         `protobuf:"bytes,8,opt,name=condition_opt,json=conditionOpt" json:"condition_opt,omitempty"`
}

func (m *WorkflowConfig_Step) Reset()                    { *m = WorkflowConfig_Step{} }
func (m *WorkflowConfig_Step) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step) ProtoMessage()               {}
func (*WorkflowConfig_Step) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 1} }

func (m *WorkflowConfig_Step) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *WorkflowConfig_Step) GetConditions() []*WorkflowConfig_Step_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *WorkflowConfig_Step) GetRecommendation() *WorkflowConfig_Step_Recommendation {
	if m != nil {
		return m.Recommendation
	}
	return nil
}

func (m *WorkflowConfig_Step) GetSegmentation() *WorkflowConfig_Step_Segmentation {
	if m != nil {
		return m.Segmentation
	}
	return nil
}

func (m *WorkflowConfig_Step) GetChannels() *WorkflowConfig_Step_ChannelMap {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *WorkflowConfig_Step) GetNextFlow() *WorkflowConfig_Step_NextFlow {
	if m != nil {
		return m.NextFlow
	}
	return nil
}

func (m *WorkflowConfig_Step) GetWait() *WorkflowConfig_Step_Wait {
	if m != nil {
		return m.Wait
	}
	return nil
}

func (m *WorkflowConfig_Step) GetConditionOpt() *WorkflowConfig_Step_Option {
	if m != nil {
		return m.ConditionOpt
	}
	return nil
}

type WorkflowConfig_Step_Recommendation struct {
	RecommendationType WorkflowConfig_Step_Recommendation_Type `protobuf:"varint,1,opt,name=recommendation_type,json=recommendationType,enum=workflowservice.WorkflowConfig_Step_Recommendation_Type" json:"recommendation_type,omitempty"`
}

func (m *WorkflowConfig_Step_Recommendation) Reset()         { *m = WorkflowConfig_Step_Recommendation{} }
func (m *WorkflowConfig_Step_Recommendation) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Recommendation) ProtoMessage()    {}
func (*WorkflowConfig_Step_Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 0}
}

func (m *WorkflowConfig_Step_Recommendation) GetRecommendationType() WorkflowConfig_Step_Recommendation_Type {
	if m != nil {
		return m.RecommendationType
	}
	return WorkflowConfig_Step_Recommendation_STANDARD
}

type WorkflowConfig_Step_Segmentation struct {
	SegmentationType WorkflowConfig_Step_Segmentation_Type `protobuf:"varint,1,opt,name=segmentation_type,json=segmentationType,enum=workflowservice.WorkflowConfig_Step_Segmentation_Type" json:"segmentation_type,omitempty"`
}

func (m *WorkflowConfig_Step_Segmentation) Reset()         { *m = WorkflowConfig_Step_Segmentation{} }
func (m *WorkflowConfig_Step_Segmentation) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Segmentation) ProtoMessage()    {}
func (*WorkflowConfig_Step_Segmentation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 1}
}

func (m *WorkflowConfig_Step_Segmentation) GetSegmentationType() WorkflowConfig_Step_Segmentation_Type {
	if m != nil {
		return m.SegmentationType
	}
	return WorkflowConfig_Step_Segmentation_BUSINESS
}

type WorkflowConfig_Step_Option struct {
	OptionType ConditionType `protobuf:"varint,1,opt,name=option_type,json=optionType,enum=workflowservice.ConditionType" json:"option_type,omitempty"`
}

func (m *WorkflowConfig_Step_Option) Reset()         { *m = WorkflowConfig_Step_Option{} }
func (m *WorkflowConfig_Step_Option) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Option) ProtoMessage()    {}
func (*WorkflowConfig_Step_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 2}
}

func (m *WorkflowConfig_Step_Option) GetOptionType() ConditionType {
	if m != nil {
		return m.OptionType
	}
	return ConditionType_AND
}

type WorkflowConfig_Step_Condition struct {
	Variable  string `protobuf:"bytes,1,opt,name=variable" json:"variable,omitempty"`
	Condition string `protobuf:"bytes,2,opt,name=condition" json:"condition,omitempty"`
}

func (m *WorkflowConfig_Step_Condition) Reset()         { *m = WorkflowConfig_Step_Condition{} }
func (m *WorkflowConfig_Step_Condition) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Condition) ProtoMessage()    {}
func (*WorkflowConfig_Step_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 3}
}

func (m *WorkflowConfig_Step_Condition) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *WorkflowConfig_Step_Condition) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type WorkflowConfig_Step_ChannelMap struct {
	Email   *WorkflowConfig_Step_ChannelMap_Email    `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Notify  *WorkflowConfig_Step_ChannelMap_Notify   `protobuf:"bytes,2,opt,name=notify" json:"notify,omitempty"`
	Actions []*WorkflowConfig_Step_ChannelMap_Action `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap) Reset()         { *m = WorkflowConfig_Step_ChannelMap{} }
func (m *WorkflowConfig_Step_ChannelMap) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 4}
}

func (m *WorkflowConfig_Step_ChannelMap) GetEmail() *WorkflowConfig_Step_ChannelMap_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *WorkflowConfig_Step_ChannelMap) GetNotify() *WorkflowConfig_Step_ChannelMap_Notify {
	if m != nil {
		return m.Notify
	}
	return nil
}

func (m *WorkflowConfig_Step_ChannelMap) GetActions() []*WorkflowConfig_Step_ChannelMap_Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type WorkflowConfig_Step_ChannelMap_Email struct {
	SenderName  string `protobuf:"bytes,1,opt,name=sender_name,json=senderName" json:"sender_name,omitempty"`
	SenderEmail string `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail" json:"sender_email,omitempty"`
	Subject     string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	TemplateId  string `protobuf:"bytes,4,opt,name=template_id,json=templateId" json:"template_id,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Email) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Email{} }
func (m *WorkflowConfig_Step_ChannelMap_Email) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Email) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 4, 0}
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSenderEmail() string {
	if m != nil {
		return m.SenderEmail
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

type WorkflowConfig_Step_ChannelMap_Notify struct {
	Email bool `protobuf:"varint,1,opt,name=email" json:"email,omitempty"`
	Aim   bool `protobuf:"varint,2,opt,name=aim" json:"aim,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Notify) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Notify{} }
func (m *WorkflowConfig_Step_ChannelMap_Notify) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Notify) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 4, 1}
}

func (m *WorkflowConfig_Step_ChannelMap_Notify) GetEmail() bool {
	if m != nil {
		return m.Email
	}
	return false
}

func (m *WorkflowConfig_Step_ChannelMap_Notify) GetAim() bool {
	if m != nil {
		return m.Aim
	}
	return false
}

type WorkflowConfig_Step_ChannelMap_Action struct {
	ActionFamily  WorkflowConfig_Step_ChannelMap_Action_Family `protobuf:"varint,1,opt,name=action_family,json=actionFamily,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Family" json:"action_family,omitempty"`
	ActionType    DistributeType                               `protobuf:"varint,2,opt,name=action_type,json=actionType,enum=workflowservice.DistributeType" json:"action_type,omitempty"`
	ActionSubject string                                       `protobuf:"bytes,3,opt,name=action_subject,json=actionSubject" json:"action_subject,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Action) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Action{} }
func (m *WorkflowConfig_Step_ChannelMap_Action) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Action) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Action) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 4, 2}
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionFamily() WorkflowConfig_Step_ChannelMap_Action_Family {
	if m != nil {
		return m.ActionFamily
	}
	return WorkflowConfig_Step_ChannelMap_Action_TAG
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionType() DistributeType {
	if m != nil {
		return m.ActionType
	}
	return DistributeType_ADD
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionSubject() string {
	if m != nil {
		return m.ActionSubject
	}
	return ""
}

type WorkflowConfig_Step_NextFlow struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *WorkflowConfig_Step_NextFlow) Reset()         { *m = WorkflowConfig_Step_NextFlow{} }
func (m *WorkflowConfig_Step_NextFlow) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_NextFlow) ProtoMessage()    {}
func (*WorkflowConfig_Step_NextFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 5}
}

func (m *WorkflowConfig_Step_NextFlow) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WorkflowConfig_Step_Wait struct {
	Duration int32 `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
}

func (m *WorkflowConfig_Step_Wait) Reset()                    { *m = WorkflowConfig_Step_Wait{} }
func (m *WorkflowConfig_Step_Wait) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Wait) ProtoMessage()               {}
func (*WorkflowConfig_Step_Wait) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 1, 6} }

func (m *WorkflowConfig_Step_Wait) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "workflowservice.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "workflowservice.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "workflowservice.DeleteRequest")
	proto.RegisterType((*ReadRequest)(nil), "workflowservice.ReadRequest")
	proto.RegisterType((*ReadAllRequest)(nil), "workflowservice.ReadAllRequest")
	proto.RegisterType((*WorkflowResponse)(nil), "workflowservice.WorkflowResponse")
	proto.RegisterType((*ConfigRequest)(nil), "workflowservice.ConfigRequest")
	proto.RegisterType((*ConfigTypesResponse)(nil), "workflowservice.ConfigTypesResponse")
	proto.RegisterType((*EditorConfig)(nil), "workflowservice.EditorConfig")
	proto.RegisterType((*EditorConfig_EditorConfigItem)(nil), "workflowservice.EditorConfig.EditorConfigItem")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Condition)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Condition")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Condition_Condition)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Condition.Condition")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_ConditionBranchYes)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.ConditionBranchYes")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_ConditionBranchNo)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.ConditionBranchNo")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Distribute)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Distribute")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Email)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Email")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Empty)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Empty")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_End)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.End")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Notify)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Notify")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Trigger)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Trigger")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Trigger.EventOptions")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Wait)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Wait")
	proto.RegisterType((*WorkflowConfig)(nil), "workflowservice.WorkflowConfig")
	proto.RegisterType((*WorkflowConfig_Filter)(nil), "workflowservice.WorkflowConfig.Filter")
	proto.RegisterType((*WorkflowConfig_Step)(nil), "workflowservice.WorkflowConfig.Step")
	proto.RegisterType((*WorkflowConfig_Step_Recommendation)(nil), "workflowservice.WorkflowConfig.Step.Recommendation")
	proto.RegisterType((*WorkflowConfig_Step_Segmentation)(nil), "workflowservice.WorkflowConfig.Step.Segmentation")
	proto.RegisterType((*WorkflowConfig_Step_Option)(nil), "workflowservice.WorkflowConfig.Step.Option")
	proto.RegisterType((*WorkflowConfig_Step_Condition)(nil), "workflowservice.WorkflowConfig.Step.Condition")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Email)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Email")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Notify)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Notify")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Action)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Action")
	proto.RegisterType((*WorkflowConfig_Step_NextFlow)(nil), "workflowservice.WorkflowConfig.Step.NextFlow")
	proto.RegisterType((*WorkflowConfig_Step_Wait)(nil), "workflowservice.WorkflowConfig.Step.Wait")
	proto.RegisterEnum("workflowservice.ConditionType", ConditionType_name, ConditionType_value)
	proto.RegisterEnum("workflowservice.DistributeType", DistributeType_name, DistributeType_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_Recommendation_Type", WorkflowConfig_Step_Recommendation_Type_name, WorkflowConfig_Step_Recommendation_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_Segmentation_Type", WorkflowConfig_Step_Segmentation_Type_name, WorkflowConfig_Step_Segmentation_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Family", WorkflowConfig_Step_ChannelMap_Action_Family_name, WorkflowConfig_Step_ChannelMap_Action_Family_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorkflowService service

type WorkflowServiceClient interface {
	CreateWorkflow(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	DeleteWorkflow(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ReadEditorConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	// event manager config loading - streams all active configurations
	ReadAllWorkflowConfigs(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (WorkflowService_ReadAllWorkflowConfigsClient, error)
	// event manager config loading for specific client id - streams all active workflows for a client
	ReadWorkflowConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (WorkflowService_ReadWorkflowConfigClient, error)
	// collector config loading - returns only client_domain: event type pairs of active workflows
	ReadActiveWorkflowConfigTypes(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (WorkflowService_ReadActiveWorkflowConfigTypesClient, error)
}

type workflowServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowServiceClient(cc *grpc.ClientConn) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) CreateWorkflow(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/CreateWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeleteWorkflow(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/DeleteWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadEditorConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/ReadEditorConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadAllWorkflowConfigs(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (WorkflowService_ReadAllWorkflowConfigsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WorkflowService_serviceDesc.Streams[0], c.cc, "/workflowservice.WorkflowService/ReadAllWorkflowConfigs", opts...)
	if err != nil {
		return nil, err
	}
	x := &workflowServiceReadAllWorkflowConfigsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkflowService_ReadAllWorkflowConfigsClient interface {
	Recv() (*WorkflowConfig, error)
	grpc.ClientStream
}

type workflowServiceReadAllWorkflowConfigsClient struct {
	grpc.ClientStream
}

func (x *workflowServiceReadAllWorkflowConfigsClient) Recv() (*WorkflowConfig, error) {
	m := new(WorkflowConfig)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workflowServiceClient) ReadWorkflowConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (WorkflowService_ReadWorkflowConfigClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WorkflowService_serviceDesc.Streams[1], c.cc, "/workflowservice.WorkflowService/ReadWorkflowConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &workflowServiceReadWorkflowConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkflowService_ReadWorkflowConfigClient interface {
	Recv() (*WorkflowConfig, error)
	grpc.ClientStream
}

type workflowServiceReadWorkflowConfigClient struct {
	grpc.ClientStream
}

func (x *workflowServiceReadWorkflowConfigClient) Recv() (*WorkflowConfig, error) {
	m := new(WorkflowConfig)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workflowServiceClient) ReadActiveWorkflowConfigTypes(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (WorkflowService_ReadActiveWorkflowConfigTypesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WorkflowService_serviceDesc.Streams[2], c.cc, "/workflowservice.WorkflowService/ReadActiveWorkflowConfigTypes", opts...)
	if err != nil {
		return nil, err
	}
	x := &workflowServiceReadActiveWorkflowConfigTypesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkflowService_ReadActiveWorkflowConfigTypesClient interface {
	Recv() (*ConfigTypesResponse, error)
	grpc.ClientStream
}

type workflowServiceReadActiveWorkflowConfigTypesClient struct {
	grpc.ClientStream
}

func (x *workflowServiceReadActiveWorkflowConfigTypesClient) Recv() (*ConfigTypesResponse, error) {
	m := new(ConfigTypesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for WorkflowService service

type WorkflowServiceServer interface {
	CreateWorkflow(context.Context, *CreateRequest) (*WorkflowResponse, error)
	DeleteWorkflow(context.Context, *DeleteRequest) (*WorkflowResponse, error)
	ReadEditorConfig(context.Context, *ReadRequest) (*WorkflowResponse, error)
	// event manager config loading - streams all active configurations
	ReadAllWorkflowConfigs(*google_protobuf.Empty, WorkflowService_ReadAllWorkflowConfigsServer) error
	// event manager config loading for specific client id - streams all active workflows for a client
	ReadWorkflowConfig(*ConfigRequest, WorkflowService_ReadWorkflowConfigServer) error
	// collector config loading - returns only client_domain: event type pairs of active workflows
	ReadActiveWorkflowConfigTypes(*google_protobuf.Empty, WorkflowService_ReadActiveWorkflowConfigTypesServer) error
}

func RegisterWorkflowServiceServer(s *grpc.Server, srv WorkflowServiceServer) {
	s.RegisterService(&_WorkflowService_serviceDesc, srv)
}

func _WorkflowService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/CreateWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/DeleteWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeleteWorkflow(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadEditorConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReadEditorConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/ReadEditorConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReadEditorConfig(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadAllWorkflowConfigs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).ReadAllWorkflowConfigs(m, &workflowServiceReadAllWorkflowConfigsServer{stream})
}

type WorkflowService_ReadAllWorkflowConfigsServer interface {
	Send(*WorkflowConfig) error
	grpc.ServerStream
}

type workflowServiceReadAllWorkflowConfigsServer struct {
	grpc.ServerStream
}

func (x *workflowServiceReadAllWorkflowConfigsServer) Send(m *WorkflowConfig) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkflowService_ReadWorkflowConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).ReadWorkflowConfig(m, &workflowServiceReadWorkflowConfigServer{stream})
}

type WorkflowService_ReadWorkflowConfigServer interface {
	Send(*WorkflowConfig) error
	grpc.ServerStream
}

type workflowServiceReadWorkflowConfigServer struct {
	grpc.ServerStream
}

func (x *workflowServiceReadWorkflowConfigServer) Send(m *WorkflowConfig) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkflowService_ReadActiveWorkflowConfigTypes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).ReadActiveWorkflowConfigTypes(m, &workflowServiceReadActiveWorkflowConfigTypesServer{stream})
}

type WorkflowService_ReadActiveWorkflowConfigTypesServer interface {
	Send(*ConfigTypesResponse) error
	grpc.ServerStream
}

type workflowServiceReadActiveWorkflowConfigTypesServer struct {
	grpc.ServerStream
}

func (x *workflowServiceReadActiveWorkflowConfigTypesServer) Send(m *ConfigTypesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _WorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workflowservice.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowService_CreateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _WorkflowService_DeleteWorkflow_Handler,
		},
		{
			MethodName: "ReadEditorConfig",
			Handler:    _WorkflowService_ReadEditorConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadAllWorkflowConfigs",
			Handler:       _WorkflowService_ReadAllWorkflowConfigs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadWorkflowConfig",
			Handler:       _WorkflowService_ReadWorkflowConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadActiveWorkflowConfigTypes",
			Handler:       _WorkflowService_ReadActiveWorkflowConfigTypes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "WorkflowService.proto",
}

func init() { proto.RegisterFile("WorkflowService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x77, 0xdb, 0xc6,
	0x11, 0x37, 0xff, 0x83, 0x43, 0x8a, 0xa6, 0x56, 0x6e, 0xc2, 0xc2, 0x71, 0xa4, 0xb0, 0x4e, 0x6a,
	0xbb, 0x09, 0xe5, 0xd2, 0xaf, 0x6e, 0x5f, 0x5b, 0x27, 0xd5, 0x1f, 0xda, 0x61, 0x2c, 0x4b, 0x7e,
	0x0b, 0xc9, 0x7e, 0x49, 0x0f, 0x7c, 0x20, 0xb1, 0x92, 0xd7, 0x01, 0x01, 0x04, 0x58, 0x4a, 0xe1,
	0x7b, 0x3d, 0xb4, 0x3d, 0xf4, 0xde, 0x4b, 0x6f, 0x7d, 0x7d, 0xbd, 0xd6, 0x9f, 0xa9, 0x5f, 0xa2,
	0xc7, 0x9e, 0xfa, 0x76, 0x67, 0x01, 0x02, 0xa4, 0x54, 0x53, 0x72, 0x0f, 0x3d, 0x11, 0x33, 0x3b,
	0xf3, 0xdb, 0x99, 0xd9, 0x99, 0xd9, 0xe1, 0xc2, 0x0f, 0x5e, 0xfa, 0xe1, 0xb7, 0xc7, 0xae, 0x7f,
	0x66, 0xb1, 0xf0, 0x94, 0x8f, 0x58, 0x27, 0x08, 0x7d, 0xe1, 0x93, 0xeb, 0x67, 0x9a, 0x1d, 0x21,
	0xdb, 0xbc, 0x79, 0xe2, 0xfb, 0x27, 0x2e, 0xdb, 0x54, 0xcb, 0xc3, 0xc9, 0xf1, 0x26, 0x1b, 0x07,
	0x62, 0x8a, 0xd2, 0xed, 0x01, 0xac, 0xec, 0x84, 0xcc, 0x16, 0x8c, 0xb2, 0xef, 0x26, 0x2c, 0x12,
	0x84, 0x40, 0xf1, 0x75, 0xe4, 0x7b, 0xad, 0xdc, 0x46, 0xee, 0x4e, 0x95, 0xaa, 0x6f, 0x62, 0x82,
	0x31, 0x72, 0x39, 0xf3, 0x44, 0xdf, 0x69, 0xe5, 0x37, 0x72, 0x77, 0x4a, 0x34, 0xa1, 0xc9, 0x87,
	0x00, 0xf8, 0xfd, 0x64, 0xc2, 0x9d, 0x56, 0x41, 0x69, 0xa5, 0x38, 0xed, 0x07, 0xb0, 0x72, 0x14,
	0x38, 0xa9, 0x0d, 0x1a, 0x90, 0xe7, 0x8e, 0x86, 0xcf, 0x73, 0x27, 0xd9, 0x30, 0x3f, 0xdb, 0xb0,
	0xbd, 0x0e, 0x2b, 0xbb, 0xcc, 0x65, 0x17, 0x2a, 0xb5, 0x6f, 0x41, 0x8d, 0x32, 0xdb, 0xb9, 0x68,
	0xf9, 0x33, 0x68, 0xc8, 0xe5, 0x2d, 0xd7, 0x8d, 0x25, 0x6e, 0x42, 0x95, 0x39, 0x5c, 0xf8, 0xe1,
	0x20, 0x11, 0x34, 0x90, 0xd1, 0x77, 0xda, 0x0e, 0x34, 0xe3, 0x58, 0x52, 0x16, 0x05, 0xbe, 0x17,
	0x31, 0x69, 0xd6, 0xc8, 0x77, 0x98, 0x92, 0x2d, 0x51, 0xf5, 0x4d, 0x5a, 0x50, 0x19, 0xb3, 0x28,
	0xb2, 0x4f, 0x98, 0xb6, 0x36, 0x26, 0xb5, 0x01, 0x85, 0x05, 0xa7, 0x8a, 0x29, 0xa7, 0x3e, 0x85,
	0x95, 0x1d, 0xdf, 0x3b, 0xe6, 0x27, 0x29, 0x9b, 0x30, 0x50, 0xb1, 0x4d, 0xa9, 0xb8, 0xb6, 0x4f,
	0x61, 0x0d, 0xa5, 0x0f, 0xa7, 0x01, 0x8b, 0x12, 0xb3, 0x7e, 0x04, 0x2b, 0x5a, 0xc7, 0xf1, 0xc7,
	0x36, 0x8f, 0xcf, 0xa9, 0x8e, 0xcc, 0x5d, 0xc5, 0xcb, 0x02, 0xcf, 0x1f, 0xd8, 0x2d, 0x00, 0x76,
	0x2a, 0xd7, 0xc4, 0x34, 0x60, 0xda, 0xe4, 0xaa, 0xe2, 0xc8, 0x9d, 0xda, 0x7f, 0x5c, 0x83, 0x7a,
	0x4f, 0x05, 0x06, 0xb7, 0x27, 0xbb, 0x50, 0xe2, 0x82, 0x8d, 0xa3, 0x56, 0x6e, 0xa3, 0x70, 0xa7,
	0xd6, 0xed, 0x74, 0xe6, 0xf2, 0xab, 0x93, 0x96, 0xce, 0x10, 0x7d, 0xc1, 0xc6, 0x14, 0x95, 0xcd,
	0x37, 0x04, 0x9a, 0xf3, 0x6b, 0x0b, 0xa9, 0x70, 0x13, 0xaa, 0x81, 0x1d, 0xa6, 0xec, 0xae, 0x52,
	0x03, 0x19, 0x7d, 0x15, 0xd2, 0x94, 0xc5, 0xea, 0x9b, 0x58, 0x60, 0x44, 0x4c, 0x08, 0xee, 0x9d,
	0x44, 0x2a, 0xd4, 0xb5, 0xee, 0xcf, 0x2f, 0x67, 0x5e, 0xc7, 0xd2, 0xea, 0x34, 0x01, 0x32, 0x7f,
	0xbf, 0x0a, 0x46, 0xcc, 0x26, 0x03, 0xa8, 0x8e, 0x7c, 0xcf, 0xe1, 0x82, 0xeb, 0x9a, 0xa8, 0x75,
	0xb7, 0xae, 0xb8, 0x45, 0x67, 0x27, 0x06, 0xa2, 0x33, 0x4c, 0xf2, 0x3b, 0xb8, 0x91, 0x10, 0x83,
	0x61, 0x68, 0x7b, 0xa3, 0x57, 0x83, 0x29, 0x8b, 0x94, 0xfb, 0xb5, 0xee, 0x57, 0xef, 0xbc, 0xd7,
	0xb6, 0x82, 0xfc, 0x9a, 0x45, 0x94, 0x8c, 0x16, 0x78, 0x64, 0x0a, 0x6b, 0x0b, 0xbb, 0x7b, 0xbe,
	0x8a, 0x71, 0xad, 0xdb, 0xff, 0x1f, 0x6d, 0xbe, 0xef, 0xd3, 0xd5, 0xd1, 0x3c, 0x8b, 0x0c, 0x01,
	0x1c, 0x1e, 0x89, 0x90, 0x0f, 0x27, 0x82, 0xe9, 0xd3, 0xdb, 0xbe, 0xea, 0x8e, 0xbb, 0x09, 0x12,
	0x4d, 0xa1, 0x12, 0x0b, 0x4a, 0x6c, 0x6c, 0x73, 0xb7, 0x55, 0x52, 0xf0, 0x8f, 0xae, 0x0a, 0xdf,
	0x93, 0x20, 0x14, 0xb1, 0x10, 0x34, 0x10, 0xd3, 0x56, 0xf9, 0x5d, 0x41, 0x03, 0x31, 0xa5, 0x88,
	0x45, 0x9e, 0x41, 0x81, 0x79, 0x4e, 0xab, 0xa2, 0x20, 0x7f, 0x75, 0x65, 0x48, 0xcf, 0xa1, 0x12,
	0x87, 0xac, 0x43, 0xed, 0xb5, 0xcf, 0xbd, 0x41, 0xe4, 0x4f, 0xc2, 0x11, 0x6b, 0x19, 0xd8, 0x96,
	0x25, 0xcb, 0x52, 0x1c, 0x72, 0x17, 0x9a, 0x4a, 0xc0, 0x61, 0x91, 0xe0, 0x9e, 0xad, 0xd2, 0xbb,
	0xaa, 0xa4, 0xae, 0x4b, 0xfe, 0xee, 0x8c, 0x4d, 0x5e, 0x40, 0xd9, 0xf3, 0x05, 0x3f, 0x9e, 0xb6,
	0x40, 0x59, 0xf7, 0xf9, 0x55, 0xad, 0xdb, 0x57, 0x28, 0x54, 0xa3, 0x91, 0xaf, 0xa1, 0x22, 0x42,
	0x7e, 0x72, 0xc2, 0xc2, 0x56, 0x4d, 0x01, 0x7f, 0x71, 0x55, 0xe0, 0x43, 0x84, 0xa1, 0x31, 0x1e,
	0x79, 0x0e, 0xc5, 0x33, 0x9b, 0x8b, 0x56, 0x5d, 0xe1, 0xfe, 0xfa, 0xaa, 0xb8, 0x2f, 0x6d, 0x2e,
	0xa8, 0x42, 0x32, 0xff, 0x90, 0x87, 0x6a, 0x92, 0xd6, 0xa4, 0xab, 0x7b, 0x91, 0x6c, 0x08, 0x8d,
	0xee, 0x87, 0x0b, 0xf8, 0x89, 0xa4, 0x6c, 0xa9, 0xba, 0x57, 0x7d, 0x0b, 0x90, 0x14, 0x81, 0x2c,
	0x6f, 0xd9, 0x4c, 0x9f, 0xbe, 0x73, 0x85, 0xa5, 0x9a, 0x4a, 0x0a, 0xde, 0xb4, 0xd2, 0xd6, 0xde,
	0x80, 0xd2, 0x31, 0x67, 0x6e, 0xdc, 0x69, 0x91, 0x90, 0x97, 0xba, 0x1f, 0xb0, 0xd0, 0x16, 0x7e,
	0x18, 0xf7, 0xda, 0x98, 0x96, 0x1a, 0xa7, 0xb6, 0x3b, 0x89, 0x9b, 0x2d, 0x12, 0xe6, 0x0d, 0x20,
	0x8b, 0x6d, 0xc5, 0x5c, 0x83, 0xd5, 0x85, 0x7a, 0x37, 0xbf, 0x01, 0x98, 0x95, 0x24, 0x79, 0x90,
	0x09, 0xd7, 0xfa, 0x82, 0xd3, 0x33, 0xd1, 0x54, 0xbc, 0xde, 0x87, 0x8a, 0xcb, 0xa3, 0xd4, 0x55,
	0x50, 0x96, 0x64, 0xdf, 0x31, 0xff, 0x94, 0x83, 0x92, 0x2a, 0x48, 0x99, 0xe5, 0x11, 0xf3, 0x1c,
	0x16, 0x0e, 0x3c, 0x7b, 0xcc, 0xb4, 0x7b, 0x80, 0xac, 0x7d, 0x7b, 0xcc, 0xc8, 0x47, 0x50, 0xd7,
	0x02, 0xd8, 0x06, 0x10, 0x48, 0x2b, 0x21, 0x46, 0x0b, 0x2a, 0xd1, 0x64, 0xf8, 0x9a, 0x8d, 0x84,
	0x76, 0x36, 0x26, 0x25, 0xba, 0x60, 0xe3, 0xc0, 0xb5, 0x05, 0x93, 0x46, 0xe0, 0x55, 0x0e, 0x31,
	0xab, 0xef, 0x98, 0x15, 0x69, 0x47, 0x20, 0xa6, 0x66, 0x09, 0x0a, 0x3d, 0xcf, 0x31, 0xef, 0x43,
	0x19, 0x53, 0x5c, 0xc6, 0x0f, 0x37, 0x94, 0x26, 0x19, 0x71, 0xe3, 0x68, 0x42, 0xc1, 0xe6, 0x63,
	0x65, 0x84, 0x41, 0xe5, 0xa7, 0xf9, 0xcf, 0x02, 0x54, 0x74, 0xf2, 0x4a, 0x1d, 0xe9, 0x20, 0xde,
	0xb3, 0x55, 0x8a, 0x84, 0x3c, 0xa5, 0x88, 0x9d, 0x8c, 0x99, 0x27, 0x30, 0x67, 0xaa, 0x34, 0xa1,
	0xd5, 0x2e, 0xf2, 0xde, 0x8e, 0x4f, 0x49, 0x11, 0xe4, 0x3b, 0x58, 0xc1, 0xfb, 0xdd, 0x0f, 0x30,
	0xd5, 0xb0, 0xb5, 0xee, 0xbd, 0x63, 0x71, 0x75, 0x7a, 0x12, 0xf4, 0x00, 0x31, 0x69, 0x9d, 0xa5,
	0x28, 0xf3, 0x2f, 0x79, 0xa8, 0xa7, 0x97, 0x93, 0xbb, 0x3a, 0x97, 0xba, 0xab, 0x17, 0x26, 0x97,
	0xfc, 0x39, 0x93, 0x8b, 0x09, 0xc6, 0xd8, 0xf6, 0x26, 0xb6, 0xeb, 0x4e, 0x95, 0x57, 0x06, 0x4d,
	0x68, 0xe9, 0xee, 0xd0, 0x16, 0xa3, 0x57, 0xca, 0x21, 0x83, 0x22, 0x21, 0x8f, 0xf8, 0x8c, 0x0d,
	0x07, 0xda, 0xa9, 0x48, 0x75, 0x7a, 0x83, 0xd6, 0xce, 0xd8, 0x50, 0x8f, 0xc5, 0x91, 0x3c, 0x48,
	0x39, 0x80, 0x0e, 0x54, 0xde, 0x47, 0xad, 0xb2, 0x0a, 0x23, 0x48, 0xd6, 0x63, 0xc5, 0x91, 0x23,
	0x91, 0x12, 0xc0, 0x9c, 0xaf, 0xe0, 0x48, 0x24, 0x39, 0x2f, 0x24, 0x43, 0xea, 0x63, 0x44, 0x71,
	0x5d, 0x37, 0x53, 0xc5, 0x42, 0x81, 0xf7, 0xa1, 0x12, 0x46, 0xd1, 0x60, 0x12, 0xba, 0xba, 0x87,
	0x96, 0xc3, 0x28, 0x3a, 0x0a, 0x5d, 0xf3, 0x21, 0x14, 0x65, 0x0f, 0x91, 0x6e, 0x39, 0x93, 0xd0,
	0x4e, 0x86, 0x88, 0x12, 0x4d, 0x68, 0x19, 0xab, 0x89, 0xc7, 0x45, 0x3c, 0xff, 0xca, 0xef, 0xf6,
	0xbf, 0x57, 0xa1, 0x11, 0x4f, 0xa4, 0x7a, 0x0c, 0x9b, 0x9f, 0x95, 0x96, 0x0a, 0xe7, 0x79, 0x33,
	0x53, 0x66, 0x38, 0x2c, 0xce, 0x0d, 0x87, 0xeb, 0x50, 0xd3, 0x8b, 0x27, 0x72, 0x9c, 0x2f, 0xcd,
	0x8f, 0xf3, 0xe4, 0x73, 0x28, 0x1f, 0x73, 0x57, 0xb0, 0x50, 0xdf, 0x7e, 0x9f, 0x2c, 0xa4, 0x55,
	0xd6, 0xee, 0xce, 0x63, 0x25, 0x4d, 0xb5, 0x16, 0xf9, 0x25, 0x94, 0x22, 0xc1, 0x82, 0xa8, 0x55,
	0x51, 0x0d, 0xf0, 0xf6, 0xdb, 0xd4, 0x2d, 0xc1, 0x02, 0x8a, 0x2a, 0xe4, 0x36, 0x34, 0xe2, 0x19,
	0x5e, 0xb0, 0xb1, 0x34, 0x1f, 0x8f, 0xa2, 0xae, 0x07, 0x79, 0xc1, 0xc6, 0x7d, 0xc7, 0xfc, 0x47,
	0x0e, 0xca, 0xb8, 0xa9, 0xf4, 0x46, 0xde, 0x81, 0x71, 0xfd, 0x60, 0x61, 0x01, 0xf7, 0xac, 0xb8,
	0x82, 0x7e, 0x08, 0x06, 0xf7, 0x06, 0x58, 0x76, 0x58, 0x5d, 0x15, 0xee, 0xed, 0xa9, 0xc2, 0xfb,
	0x04, 0xae, 0x7b, 0xbe, 0x18, 0xa4, 0xf5, 0x0b, 0x4a, 0x62, 0xc5, 0xf3, 0x45, 0x7f, 0x06, 0xb1,
	0x01, 0x75, 0x2d, 0x87, 0x30, 0x45, 0xdc, 0x44, 0x09, 0xed, 0xc5, 0x25, 0x1c, 0x84, 0xdc, 0x0f,
	0xb9, 0x98, 0xaa, 0x80, 0x96, 0x68, 0x42, 0x9b, 0x7f, 0x6e, 0x40, 0x51, 0xba, 0x28, 0x53, 0x48,
	0x3a, 0x39, 0xfb, 0x77, 0x52, 0x96, 0x64, 0xdf, 0x21, 0xfb, 0xe7, 0x5c, 0x1b, 0x9d, 0x65, 0xa2,
	0x76, 0xfe, 0xcd, 0x40, 0x7e, 0x0b, 0x8d, 0x90, 0x8d, 0xfc, 0xf1, 0x98, 0x79, 0x0e, 0x26, 0x24,
	0x0e, 0x7b, 0x0f, 0x96, 0xc2, 0xa4, 0x19, 0x55, 0x3a, 0x07, 0x45, 0x8e, 0x64, 0xbf, 0x55, 0x81,
	0x41, 0x68, 0x6c, 0x3d, 0x3f, 0x5d, 0x0a, 0xda, 0x4a, 0x29, 0xd2, 0x0c, 0x0c, 0x79, 0x0a, 0xc6,
	0xe8, 0x95, 0xed, 0x79, 0xcc, 0x8d, 0xf4, 0x24, 0xb7, 0xb9, 0x5c, 0x04, 0x50, 0xe9, 0x99, 0x1d,
	0xd0, 0x04, 0x80, 0x7c, 0x05, 0x55, 0x8f, 0x7d, 0x2f, 0x06, 0x52, 0x58, 0x27, 0xf1, 0x67, 0x4b,
	0xa1, 0xed, 0xb3, 0xef, 0xc5, 0x63, 0xf9, 0x17, 0xd1, 0xf0, 0xf4, 0x17, 0x79, 0xa4, 0xe7, 0x0c,
	0x1c, 0xdb, 0xee, 0x2e, 0x05, 0x33, 0x1b, 0x2a, 0xc8, 0x73, 0x58, 0x99, 0x4d, 0xdf, 0x7e, 0x20,
	0x54, 0x3e, 0xd7, 0xba, 0x3f, 0x59, 0x0a, 0x07, 0x7b, 0x2d, 0xad, 0x27, 0x08, 0x07, 0x81, 0x30,
	0xff, 0x9a, 0x93, 0xff, 0x7c, 0x33, 0x67, 0xc2, 0x61, 0x2d, 0x7b, 0x4a, 0x83, 0xd4, 0x5d, 0xfc,
	0x8b, 0x2b, 0x9c, 0x7a, 0x47, 0x5d, 0xd2, 0x24, 0x0b, 0xaa, 0xfe, 0x3b, 0x6e, 0x40, 0x51, 0xfe,
	0x92, 0x3a, 0x18, 0xd6, 0xe1, 0xd6, 0xfe, 0xee, 0x16, 0xdd, 0x6d, 0x5e, 0x23, 0x00, 0xe5, 0x9d,
	0x23, 0xeb, 0xf0, 0xe0, 0x59, 0x33, 0x67, 0xfe, 0x3d, 0x07, 0xf5, 0xf4, 0x41, 0x93, 0x11, 0xac,
	0xa6, 0x8f, 0x3a, 0x6d, 0xdb, 0xc3, 0x4b, 0xa7, 0x0d, 0x5a, 0xd6, 0x4c, 0x03, 0x2a, 0xbb, 0x3e,
	0x9d, 0xd9, 0xb5, 0x7d, 0x64, 0xf5, 0xf7, 0x7b, 0x96, 0xd5, 0xbc, 0x26, 0xa9, 0x27, 0x74, 0xeb,
	0xf9, 0x97, 0xfd, 0x1d, 0xab, 0x99, 0x23, 0x06, 0x14, 0xb7, 0x0f, 0x0e, 0xbf, 0x6c, 0xe6, 0xcd,
	0x3e, 0x94, 0x31, 0xb6, 0xe4, 0x0b, 0xa8, 0xe1, 0x25, 0x3a, 0xb8, 0xc4, 0xb4, 0x07, 0xa8, 0x22,
	0xbf, 0xcd, 0x5e, 0x7a, 0x0c, 0x33, 0xc1, 0x38, 0xb5, 0x43, 0x6e, 0x0f, 0xdd, 0xf8, 0x62, 0x4c,
	0x68, 0xf2, 0x41, 0xfa, 0x6f, 0x26, 0x76, 0xf2, 0x19, 0xc3, 0x7c, 0x53, 0x02, 0x98, 0xe5, 0x32,
	0x79, 0x9a, 0x9e, 0x2e, 0x6a, 0xdd, 0x9f, 0x5d, 0xb2, 0x16, 0xb2, 0xff, 0x66, 0xf6, 0x93, 0xe9,
	0x1e, 0xff, 0x71, 0x3e, 0xbc, 0x2c, 0xda, 0xdc, 0x54, 0xff, 0x1c, 0x2a, 0xf6, 0x08, 0x9b, 0x55,
	0x41, 0x35, 0xab, 0x4b, 0x03, 0x6e, 0x29, 0x75, 0x1a, 0xc3, 0xfc, 0xff, 0xcc, 0x7b, 0x97, 0x9f,
	0xef, 0xfe, 0x95, 0x83, 0x32, 0xba, 0x43, 0x86, 0xb0, 0x82, 0x0e, 0x0d, 0x8e, 0xed, 0x31, 0x77,
	0xa7, 0x3a, 0x9b, 0x1e, 0x5d, 0x2d, 0x3a, 0x9d, 0xc7, 0x0a, 0x84, 0xd6, 0x11, 0x13, 0x29, 0xf2,
	0x1b, 0xa8, 0xe9, 0x3d, 0x54, 0xbe, 0xe6, 0x97, 0x1b, 0xb7, 0x01, 0x75, 0x54, 0x85, 0x7c, 0x0c,
	0x0d, 0x8d, 0x90, 0x0d, 0x92, 0xb6, 0xdd, 0x42, 0x66, 0xfb, 0x26, 0x94, 0xf5, 0x96, 0x15, 0x28,
	0x1c, 0x6e, 0x3d, 0x69, 0x5e, 0x93, 0xf5, 0xb3, 0xd7, 0xb7, 0x0e, 0x9b, 0x39, 0xd3, 0x04, 0x23,
	0x6e, 0x95, 0xf3, 0x53, 0x8b, 0xd9, 0x7e, 0xfb, 0x40, 0x74, 0xef, 0x9e, 0x7a, 0x27, 0x9b, 0x55,
	0x94, 0xdc, 0x63, 0x6b, 0x5f, 0x76, 0x92, 0x32, 0xe4, 0x0f, 0x28, 0xd6, 0x6a, 0x6f, 0xcf, 0xea,
	0x35, 0xf3, 0xf7, 0x3e, 0x86, 0x46, 0xd6, 0x1b, 0x25, 0xbc, 0xab, 0xdb, 0x0e, 0xed, 0x3d, 0x3b,
	0x78, 0xd1, 0x6b, 0xe6, 0xba, 0x7f, 0x2b, 0xc2, 0xf5, 0xb9, 0xd7, 0x52, 0x62, 0x41, 0x03, 0x5f,
	0x3e, 0xe3, 0x05, 0x72, 0x4e, 0x65, 0xa7, 0x9f, 0x46, 0xcd, 0x8f, 0x2e, 0x3c, 0xab, 0xe4, 0x79,
	0xce, 0x82, 0x06, 0x3e, 0x5c, 0xfe, 0x17, 0xd0, 0xcc, 0xcb, 0xe6, 0x72, 0xa0, 0x4d, 0xca, 0x6c,
	0x27, 0xf3, 0x2a, 0xf7, 0xc1, 0x82, 0x5a, 0xea, 0x3d, 0x74, 0x39, 0xd0, 0xf7, 0xf4, 0x13, 0x69,
	0x36, 0xe1, 0x22, 0xf2, 0x5e, 0x07, 0x1f, 0x8c, 0x3b, 0xf1, 0x83, 0x31, 0xbe, 0x54, 0x98, 0xeb,
	0x6f, 0x49, 0xd5, 0xfb, 0x39, 0xf2, 0x12, 0x88, 0x04, 0x9d, 0x1b, 0x5d, 0xcf, 0xed, 0x98, 0xb3,
	0x77, 0xd0, 0x65, 0x80, 0x07, 0x70, 0x4b, 0x59, 0x3b, 0x12, 0xfc, 0x94, 0x65, 0x57, 0xd5, 0xfb,
	0xe8, 0x85, 0x46, 0xdf, 0xbe, 0x60, 0xef, 0xcc, 0xab, 0xea, 0xfd, 0xdc, 0xf6, 0xdd, 0x6f, 0x7e,
	0x3c, 0x72, 0xd9, 0x29, 0x0b, 0xc7, 0xbe, 0x27, 0xc3, 0xbc, 0x69, 0x7b, 0xb6, 0x3b, 0x15, 0x7c,
	0x14, 0xe1, 0xbb, 0x79, 0xb4, 0x19, 0xe3, 0x0c, 0xcb, 0x8a, 0xf1, 0xe0, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xee, 0xf0, 0x82, 0xbc, 0x80, 0x17, 0x00, 0x00,
}
