// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WorkflowService.proto

/*
Package workflow is a generated protocol buffer package.

It is generated from these files:
	WorkflowService.proto

It has these top-level messages:
	CreateRequest
	UpdateRequest
	DeleteRequest
	ReadRequest
	ReadAllRequest
	WorkflowResponse
	EditorConfig
	WorkflowConfig
*/
package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkflowConfig_Step_Recommendation_Type int32

const (
	WorkflowConfig_Step_Recommendation_STANDARD WorkflowConfig_Step_Recommendation_Type = 0
	WorkflowConfig_Step_Recommendation_CUSTOM   WorkflowConfig_Step_Recommendation_Type = 1
)

var WorkflowConfig_Step_Recommendation_Type_name = map[int32]string{
	0: "STANDARD",
	1: "CUSTOM",
}
var WorkflowConfig_Step_Recommendation_Type_value = map[string]int32{
	"STANDARD": 0,
	"CUSTOM":   1,
}

func (x WorkflowConfig_Step_Recommendation_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_Recommendation_Type_name, int32(x))
}
func (WorkflowConfig_Step_Recommendation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 0, 0}
}

type WorkflowConfig_Step_Segmentation_Type int32

const (
	WorkflowConfig_Step_Segmentation_BUSINESS WorkflowConfig_Step_Segmentation_Type = 0
	WorkflowConfig_Step_Segmentation_GRAPHICS WorkflowConfig_Step_Segmentation_Type = 1
	WorkflowConfig_Step_Segmentation_BOTH     WorkflowConfig_Step_Segmentation_Type = 2
)

var WorkflowConfig_Step_Segmentation_Type_name = map[int32]string{
	0: "BUSINESS",
	1: "GRAPHICS",
	2: "BOTH",
}
var WorkflowConfig_Step_Segmentation_Type_value = map[string]int32{
	"BUSINESS": 0,
	"GRAPHICS": 1,
	"BOTH":     2,
}

func (x WorkflowConfig_Step_Segmentation_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_Segmentation_Type_name, int32(x))
}
func (WorkflowConfig_Step_Segmentation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 1, 0}
}

type WorkflowConfig_Step_ChannelMap_Action_Family int32

const (
	WorkflowConfig_Step_ChannelMap_Action_TAG  WorkflowConfig_Step_ChannelMap_Action_Family = 0
	WorkflowConfig_Step_ChannelMap_Action_LIST WorkflowConfig_Step_ChannelMap_Action_Family = 1
)

var WorkflowConfig_Step_ChannelMap_Action_Family_name = map[int32]string{
	0: "TAG",
	1: "LIST",
}
var WorkflowConfig_Step_ChannelMap_Action_Family_value = map[string]int32{
	"TAG":  0,
	"LIST": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Family) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Family_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Family) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 3, 2, 0}
}

type WorkflowConfig_Step_ChannelMap_Action_Type int32

const (
	WorkflowConfig_Step_ChannelMap_Action_ADD    WorkflowConfig_Step_ChannelMap_Action_Type = 0
	WorkflowConfig_Step_ChannelMap_Action_REMOVE WorkflowConfig_Step_ChannelMap_Action_Type = 1
)

var WorkflowConfig_Step_ChannelMap_Action_Type_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
}
var WorkflowConfig_Step_ChannelMap_Action_Type_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
}

func (x WorkflowConfig_Step_ChannelMap_Action_Type) String() string {
	return proto.EnumName(WorkflowConfig_Step_ChannelMap_Action_Type_name, int32(x))
}
func (WorkflowConfig_Step_ChannelMap_Action_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 3, 2, 1}
}

type CreateRequest struct {
	Json       string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
	ClientId   int32  `protobuf:"varint,2,opt,name=clientId" json:"clientId,omitempty"`
	ClientGuid string `protobuf:"bytes,3,opt,name=clientGuid" json:"clientGuid,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *CreateRequest) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *CreateRequest) GetClientGuid() string {
	if m != nil {
		return m.ClientGuid
	}
	return ""
}

type UpdateRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Json string `protobuf:"bytes,2,opt,name=json" json:"json,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadAllRequest struct {
	EditorId string `protobuf:"bytes,1,opt,name=editor_id,json=editorId" json:"editor_id,omitempty"`
}

func (m *ReadAllRequest) Reset()                    { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()               {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadAllRequest) GetEditorId() string {
	if m != nil {
		return m.EditorId
	}
	return ""
}

type WorkflowResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Json    string `protobuf:"bytes,4,opt,name=json" json:"json,omitempty"`
}

func (m *WorkflowResponse) Reset()                    { *m = WorkflowResponse{} }
func (m *WorkflowResponse) String() string            { return proto.CompactTextString(m) }
func (*WorkflowResponse) ProtoMessage()               {}
func (*WorkflowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WorkflowResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkflowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WorkflowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type EditorConfig struct {
	Items []*EditorConfig_EditorConfigItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *EditorConfig) Reset()                    { *m = EditorConfig{} }
func (m *EditorConfig) String() string            { return proto.CompactTextString(m) }
func (*EditorConfig) ProtoMessage()               {}
func (*EditorConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EditorConfig) GetItems() []*EditorConfig_EditorConfigItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type EditorConfig_EditorConfigItem struct {
	Id       string                                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ParentId string                                  `protobuf:"bytes,2,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Type     string                                  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Settings *EditorConfig_EditorConfigItem_Settings `protobuf:"bytes,4,opt,name=settings" json:"settings,omitempty"`
}

func (m *EditorConfig_EditorConfigItem) Reset()         { *m = EditorConfig_EditorConfigItem{} }
func (m *EditorConfig_EditorConfigItem) String() string { return proto.CompactTextString(m) }
func (*EditorConfig_EditorConfigItem) ProtoMessage()    {}
func (*EditorConfig_EditorConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *EditorConfig_EditorConfigItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem) GetSettings() *EditorConfig_EditorConfigItem_Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings struct {
	Condition       *EditorConfig_EditorConfigItem_Settings_Condition       `protobuf:"bytes,1,opt,name=condition" json:"condition,omitempty"`
	ConditionBranch *EditorConfig_EditorConfigItem_Settings_ConditionBranch `protobuf:"bytes,2,opt,name=condition_branch,json=conditionBranch" json:"condition_branch,omitempty"`
	Distribute      *EditorConfig_EditorConfigItem_Settings_Distribute      `protobuf:"bytes,3,opt,name=distribute" json:"distribute,omitempty"`
	Email           *EditorConfig_EditorConfigItem_Settings_Email           `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Empty           *EditorConfig_EditorConfigItem_Settings_Empty           `protobuf:"bytes,5,opt,name=empty" json:"empty,omitempty"`
	End             *EditorConfig_EditorConfigItem_Settings_End             `protobuf:"bytes,6,opt,name=end" json:"end,omitempty"`
	JoinSrc         *EditorConfig_EditorConfigItem_Settings_JoinSrc         `protobuf:"bytes,7,opt,name=join_src,json=joinSrc" json:"join_src,omitempty"`
	JoinDst         *EditorConfig_EditorConfigItem_Settings_JoinDst         `protobuf:"bytes,8,opt,name=join_dst,json=joinDst" json:"join_dst,omitempty"`
	Notify          *EditorConfig_EditorConfigItem_Settings_Notify          `protobuf:"bytes,9,opt,name=notify" json:"notify,omitempty"`
	Trigger         *EditorConfig_EditorConfigItem_Settings_Trigger         `protobuf:"bytes,10,opt,name=trigger" json:"trigger,omitempty"`
	Wait            *EditorConfig_EditorConfigItem_Settings_Wait            `protobuf:"bytes,11,opt,name=wait" json:"wait,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings{}
}
func (m *EditorConfig_EditorConfigItem_Settings) String() string { return proto.CompactTextString(m) }
func (*EditorConfig_EditorConfigItem_Settings) ProtoMessage()    {}
func (*EditorConfig_EditorConfigItem_Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings) GetCondition() *EditorConfig_EditorConfigItem_Settings_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetConditionBranch() *EditorConfig_EditorConfigItem_Settings_ConditionBranch {
	if m != nil {
		return m.ConditionBranch
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetDistribute() *EditorConfig_EditorConfigItem_Settings_Distribute {
	if m != nil {
		return m.Distribute
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetEmail() *EditorConfig_EditorConfigItem_Settings_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetEmpty() *EditorConfig_EditorConfigItem_Settings_Empty {
	if m != nil {
		return m.Empty
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetEnd() *EditorConfig_EditorConfigItem_Settings_End {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetJoinSrc() *EditorConfig_EditorConfigItem_Settings_JoinSrc {
	if m != nil {
		return m.JoinSrc
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetJoinDst() *EditorConfig_EditorConfigItem_Settings_JoinDst {
	if m != nil {
		return m.JoinDst
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetNotify() *EditorConfig_EditorConfigItem_Settings_Notify {
	if m != nil {
		return m.Notify
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetTrigger() *EditorConfig_EditorConfigItem_Settings_Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings) GetWait() *EditorConfig_EditorConfigItem_Settings_Wait {
	if m != nil {
		return m.Wait
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings_Condition struct {
	Type       bool                                                          `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Conditions []*EditorConfig_EditorConfigItem_Settings_Condition_Condition `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Condition{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Condition) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Condition) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition) GetType() bool {
	if m != nil {
		return m.Type
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition) GetConditions() []*EditorConfig_EditorConfigItem_Settings_Condition_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings_Condition_Condition struct {
	Field    string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Operator string `protobuf:"bytes,2,opt,name=operator" json:"operator,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Condition_Condition{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Condition_Condition) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Condition_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 0, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Condition_Condition) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_ConditionBranch struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_ConditionBranch) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_ConditionBranch{}
}
func (m *EditorConfig_EditorConfigItem_Settings_ConditionBranch) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_ConditionBranch) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_ConditionBranch) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 1}
}

type EditorConfig_EditorConfigItem_Settings_Distribute struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_Distribute) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Distribute{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Distribute) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Distribute) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Distribute) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 2}
}

type EditorConfig_EditorConfigItem_Settings_Email struct {
	SenderName  string `protobuf:"bytes,1,opt,name=sender_name,json=senderName" json:"sender_name,omitempty"`
	SenderEmail string `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail" json:"sender_email,omitempty"`
	Subject     string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	TemplateId  string `protobuf:"bytes,4,opt,name=template_id,json=templateId" json:"template_id,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Email{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Email) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Email) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 3}
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetSenderEmail() string {
	if m != nil {
		return m.SenderEmail
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Email) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_Empty struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_Empty) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Empty{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Empty) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Empty) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 4}
}

type EditorConfig_EditorConfigItem_Settings_End struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_End) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_End{}
}
func (m *EditorConfig_EditorConfigItem_Settings_End) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_End) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_End) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 5}
}

type EditorConfig_EditorConfigItem_Settings_JoinSrc struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_JoinSrc) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_JoinSrc{}
}
func (m *EditorConfig_EditorConfigItem_Settings_JoinSrc) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_JoinSrc) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_JoinSrc) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 6}
}

type EditorConfig_EditorConfigItem_Settings_JoinDst struct {
}

func (m *EditorConfig_EditorConfigItem_Settings_JoinDst) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_JoinDst{}
}
func (m *EditorConfig_EditorConfigItem_Settings_JoinDst) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_JoinDst) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_JoinDst) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 7}
}

type EditorConfig_EditorConfigItem_Settings_Notify struct {
	Email bool `protobuf:"varint,1,opt,name=email" json:"email,omitempty"`
	Aim   bool `protobuf:"varint,2,opt,name=aim" json:"aim,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Notify) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Notify{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Notify) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Notify) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 8}
}

func (m *EditorConfig_EditorConfigItem_Settings_Notify) GetEmail() bool {
	if m != nil {
		return m.Email
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Notify) GetAim() bool {
	if m != nil {
		return m.Aim
	}
	return false
}

type EditorConfig_EditorConfigItem_Settings_Trigger struct {
	Lists        []string                                                     `protobuf:"bytes,1,rep,name=lists" json:"lists,omitempty"`
	Segments     []string                                                     `protobuf:"bytes,2,rep,name=segments" json:"segments,omitempty"`
	Event        string                                                       `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	EventOptions *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions `protobuf:"bytes,4,opt,name=event_options,json=eventOptions" json:"event_options,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Trigger{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Trigger) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Trigger) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 9}
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetLists() []string {
	if m != nil {
		return m.Lists
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetSegments() []string {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger) GetEventOptions() *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions {
	if m != nil {
		return m.EventOptions
	}
	return nil
}

type EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions struct {
	Type         string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ClientDomain string   `protobuf:"bytes,2,opt,name=client_domain,json=clientDomain" json:"client_domain,omitempty"`
	Manually     bool     `protobuf:"varint,3,opt,name=manually" json:"manually,omitempty"`
	Batch        bool     `protobuf:"varint,4,opt,name=batch" json:"batch,omitempty"`
	WebServices  bool     `protobuf:"varint,5,opt,name=web_services,json=webServices" json:"web_services,omitempty"`
	DateFields   []string `protobuf:"bytes,6,rep,name=date_fields,json=dateFields" json:"date_fields,omitempty"`
	DateValue    string   `protobuf:"bytes,7,opt,name=date_value,json=dateValue" json:"date_value,omitempty"`
	EventValue   string   `protobuf:"bytes,8,opt,name=event_value,json=eventValue" json:"event_value,omitempty"`
	RssUrl       string   `protobuf:"bytes,9,opt,name=rss_url,json=rssUrl" json:"rss_url,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 9, 0}
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetClientDomain() string {
	if m != nil {
		return m.ClientDomain
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetManually() bool {
	if m != nil {
		return m.Manually
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetWebServices() bool {
	if m != nil {
		return m.WebServices
	}
	return false
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetDateFields() []string {
	if m != nil {
		return m.DateFields
	}
	return nil
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetDateValue() string {
	if m != nil {
		return m.DateValue
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetEventValue() string {
	if m != nil {
		return m.EventValue
	}
	return ""
}

func (m *EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions) GetRssUrl() string {
	if m != nil {
		return m.RssUrl
	}
	return ""
}

type EditorConfig_EditorConfigItem_Settings_Wait struct {
	Duration int32  `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
	Unit     string `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
}

func (m *EditorConfig_EditorConfigItem_Settings_Wait) Reset() {
	*m = EditorConfig_EditorConfigItem_Settings_Wait{}
}
func (m *EditorConfig_EditorConfigItem_Settings_Wait) String() string {
	return proto.CompactTextString(m)
}
func (*EditorConfig_EditorConfigItem_Settings_Wait) ProtoMessage() {}
func (*EditorConfig_EditorConfigItem_Settings_Wait) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0, 0, 10}
}

func (m *EditorConfig_EditorConfigItem_Settings_Wait) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *EditorConfig_EditorConfigItem_Settings_Wait) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type WorkflowConfig struct {
	Id           string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientDomain string                 `protobuf:"bytes,2,opt,name=client_domain,json=clientDomain" json:"client_domain,omitempty"`
	Type         string                 `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ClientId     int32                  `protobuf:"varint,4,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientGuid   string                 `protobuf:"bytes,5,opt,name=client_guid,json=clientGuid" json:"client_guid,omitempty"`
	Filter       *WorkflowConfig_Filter `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	Steps        []*WorkflowConfig_Step `protobuf:"bytes,7,rep,name=steps" json:"steps,omitempty"`
	EditorItemId string                 `protobuf:"bytes,8,opt,name=editor_item_id,json=editorItemId" json:"editor_item_id,omitempty"`
}

func (m *WorkflowConfig) Reset()                    { *m = WorkflowConfig{} }
func (m *WorkflowConfig) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig) ProtoMessage()               {}
func (*WorkflowConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WorkflowConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowConfig) GetClientDomain() string {
	if m != nil {
		return m.ClientDomain
	}
	return ""
}

func (m *WorkflowConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WorkflowConfig) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *WorkflowConfig) GetClientGuid() string {
	if m != nil {
		return m.ClientGuid
	}
	return ""
}

func (m *WorkflowConfig) GetFilter() *WorkflowConfig_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *WorkflowConfig) GetSteps() []*WorkflowConfig_Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *WorkflowConfig) GetEditorItemId() string {
	if m != nil {
		return m.EditorItemId
	}
	return ""
}

type WorkflowConfig_Filter struct {
	InSegments []string `protobuf:"bytes,1,rep,name=in_segments,json=inSegments" json:"in_segments,omitempty"`
	InLists    []string `protobuf:"bytes,2,rep,name=in_lists,json=inLists" json:"in_lists,omitempty"`
}

func (m *WorkflowConfig_Filter) Reset()                    { *m = WorkflowConfig_Filter{} }
func (m *WorkflowConfig_Filter) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Filter) ProtoMessage()               {}
func (*WorkflowConfig_Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *WorkflowConfig_Filter) GetInSegments() []string {
	if m != nil {
		return m.InSegments
	}
	return nil
}

func (m *WorkflowConfig_Filter) GetInLists() []string {
	if m != nil {
		return m.InLists
	}
	return nil
}

type WorkflowConfig_Step struct {
	StepId         string                              `protobuf:"bytes,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	Conditions     []*WorkflowConfig_Step_Condition    `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`
	Recommendation *WorkflowConfig_Step_Recommendation `protobuf:"bytes,3,opt,name=recommendation" json:"recommendation,omitempty"`
	Segmentation   *WorkflowConfig_Step_Segmentation   `protobuf:"bytes,4,opt,name=segmentation" json:"segmentation,omitempty"`
	Channels       *WorkflowConfig_Step_ChannelMap     `protobuf:"bytes,5,opt,name=channels" json:"channels,omitempty"`
	NextFlow       *WorkflowConfig_Step_NextFlow       `protobuf:"bytes,6,opt,name=next_flow,json=nextFlow" json:"next_flow,omitempty"`
	Wait           *WorkflowConfig_Step_Wait           `protobuf:"bytes,7,opt,name=wait" json:"wait,omitempty"`
}

func (m *WorkflowConfig_Step) Reset()                    { *m = WorkflowConfig_Step{} }
func (m *WorkflowConfig_Step) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step) ProtoMessage()               {}
func (*WorkflowConfig_Step) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

func (m *WorkflowConfig_Step) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *WorkflowConfig_Step) GetConditions() []*WorkflowConfig_Step_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *WorkflowConfig_Step) GetRecommendation() *WorkflowConfig_Step_Recommendation {
	if m != nil {
		return m.Recommendation
	}
	return nil
}

func (m *WorkflowConfig_Step) GetSegmentation() *WorkflowConfig_Step_Segmentation {
	if m != nil {
		return m.Segmentation
	}
	return nil
}

func (m *WorkflowConfig_Step) GetChannels() *WorkflowConfig_Step_ChannelMap {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *WorkflowConfig_Step) GetNextFlow() *WorkflowConfig_Step_NextFlow {
	if m != nil {
		return m.NextFlow
	}
	return nil
}

func (m *WorkflowConfig_Step) GetWait() *WorkflowConfig_Step_Wait {
	if m != nil {
		return m.Wait
	}
	return nil
}

type WorkflowConfig_Step_Recommendation struct {
	RecommendationType WorkflowConfig_Step_Recommendation_Type `protobuf:"varint,1,opt,name=recommendation_type,json=recommendationType,enum=workflowservice.WorkflowConfig_Step_Recommendation_Type" json:"recommendation_type,omitempty"`
}

func (m *WorkflowConfig_Step_Recommendation) Reset()         { *m = WorkflowConfig_Step_Recommendation{} }
func (m *WorkflowConfig_Step_Recommendation) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Recommendation) ProtoMessage()    {}
func (*WorkflowConfig_Step_Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 0}
}

func (m *WorkflowConfig_Step_Recommendation) GetRecommendationType() WorkflowConfig_Step_Recommendation_Type {
	if m != nil {
		return m.RecommendationType
	}
	return WorkflowConfig_Step_Recommendation_STANDARD
}

type WorkflowConfig_Step_Segmentation struct {
	SegmentationType WorkflowConfig_Step_Segmentation_Type `protobuf:"varint,1,opt,name=segmentation_type,json=segmentationType,enum=workflowservice.WorkflowConfig_Step_Segmentation_Type" json:"segmentation_type,omitempty"`
}

func (m *WorkflowConfig_Step_Segmentation) Reset()         { *m = WorkflowConfig_Step_Segmentation{} }
func (m *WorkflowConfig_Step_Segmentation) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Segmentation) ProtoMessage()    {}
func (*WorkflowConfig_Step_Segmentation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 1}
}

func (m *WorkflowConfig_Step_Segmentation) GetSegmentationType() WorkflowConfig_Step_Segmentation_Type {
	if m != nil {
		return m.SegmentationType
	}
	return WorkflowConfig_Step_Segmentation_BUSINESS
}

type WorkflowConfig_Step_Condition struct {
	Variable  string `protobuf:"bytes,1,opt,name=variable" json:"variable,omitempty"`
	Condition string `protobuf:"bytes,2,opt,name=condition" json:"condition,omitempty"`
}

func (m *WorkflowConfig_Step_Condition) Reset()         { *m = WorkflowConfig_Step_Condition{} }
func (m *WorkflowConfig_Step_Condition) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Condition) ProtoMessage()    {}
func (*WorkflowConfig_Step_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 2}
}

func (m *WorkflowConfig_Step_Condition) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *WorkflowConfig_Step_Condition) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type WorkflowConfig_Step_ChannelMap struct {
	Email   *WorkflowConfig_Step_ChannelMap_Email    `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Notify  *WorkflowConfig_Step_ChannelMap_Notify   `protobuf:"bytes,2,opt,name=notify" json:"notify,omitempty"`
	Actions []*WorkflowConfig_Step_ChannelMap_Action `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap) Reset()         { *m = WorkflowConfig_Step_ChannelMap{} }
func (m *WorkflowConfig_Step_ChannelMap) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 3}
}

func (m *WorkflowConfig_Step_ChannelMap) GetEmail() *WorkflowConfig_Step_ChannelMap_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *WorkflowConfig_Step_ChannelMap) GetNotify() *WorkflowConfig_Step_ChannelMap_Notify {
	if m != nil {
		return m.Notify
	}
	return nil
}

func (m *WorkflowConfig_Step_ChannelMap) GetActions() []*WorkflowConfig_Step_ChannelMap_Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type WorkflowConfig_Step_ChannelMap_Email struct {
	SenderName  string `protobuf:"bytes,1,opt,name=sender_name,json=senderName" json:"sender_name,omitempty"`
	SenderEmail string `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail" json:"sender_email,omitempty"`
	Subject     string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	TemplateId  string `protobuf:"bytes,4,opt,name=template_id,json=templateId" json:"template_id,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Email) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Email{} }
func (m *WorkflowConfig_Step_ChannelMap_Email) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Email) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 3, 0}
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSenderEmail() string {
	if m != nil {
		return m.SenderEmail
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *WorkflowConfig_Step_ChannelMap_Email) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

type WorkflowConfig_Step_ChannelMap_Notify struct {
	Email bool `protobuf:"varint,1,opt,name=email" json:"email,omitempty"`
	Aim   bool `protobuf:"varint,2,opt,name=aim" json:"aim,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Notify) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Notify{} }
func (m *WorkflowConfig_Step_ChannelMap_Notify) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Notify) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 3, 1}
}

func (m *WorkflowConfig_Step_ChannelMap_Notify) GetEmail() bool {
	if m != nil {
		return m.Email
	}
	return false
}

func (m *WorkflowConfig_Step_ChannelMap_Notify) GetAim() bool {
	if m != nil {
		return m.Aim
	}
	return false
}

type WorkflowConfig_Step_ChannelMap_Action struct {
	ActionFamily  WorkflowConfig_Step_ChannelMap_Action_Family `protobuf:"varint,1,opt,name=action_family,json=actionFamily,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Family" json:"action_family,omitempty"`
	ActionType    WorkflowConfig_Step_ChannelMap_Action_Type   `protobuf:"varint,2,opt,name=action_type,json=actionType,enum=workflowservice.WorkflowConfig_Step_ChannelMap_Action_Type" json:"action_type,omitempty"`
	ActionSubject string                                       `protobuf:"bytes,3,opt,name=action_subject,json=actionSubject" json:"action_subject,omitempty"`
}

func (m *WorkflowConfig_Step_ChannelMap_Action) Reset()         { *m = WorkflowConfig_Step_ChannelMap_Action{} }
func (m *WorkflowConfig_Step_ChannelMap_Action) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_ChannelMap_Action) ProtoMessage()    {}
func (*WorkflowConfig_Step_ChannelMap_Action) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 3, 2}
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionFamily() WorkflowConfig_Step_ChannelMap_Action_Family {
	if m != nil {
		return m.ActionFamily
	}
	return WorkflowConfig_Step_ChannelMap_Action_TAG
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionType() WorkflowConfig_Step_ChannelMap_Action_Type {
	if m != nil {
		return m.ActionType
	}
	return WorkflowConfig_Step_ChannelMap_Action_ADD
}

func (m *WorkflowConfig_Step_ChannelMap_Action) GetActionSubject() string {
	if m != nil {
		return m.ActionSubject
	}
	return ""
}

type WorkflowConfig_Step_NextFlow struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *WorkflowConfig_Step_NextFlow) Reset()         { *m = WorkflowConfig_Step_NextFlow{} }
func (m *WorkflowConfig_Step_NextFlow) String() string { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_NextFlow) ProtoMessage()    {}
func (*WorkflowConfig_Step_NextFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1, 4}
}

func (m *WorkflowConfig_Step_NextFlow) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WorkflowConfig_Step_Wait struct {
	Duration int32 `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
}

func (m *WorkflowConfig_Step_Wait) Reset()                    { *m = WorkflowConfig_Step_Wait{} }
func (m *WorkflowConfig_Step_Wait) String() string            { return proto.CompactTextString(m) }
func (*WorkflowConfig_Step_Wait) ProtoMessage()               {}
func (*WorkflowConfig_Step_Wait) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1, 5} }

func (m *WorkflowConfig_Step_Wait) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "workflowservice.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "workflowservice.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "workflowservice.DeleteRequest")
	proto.RegisterType((*ReadRequest)(nil), "workflowservice.ReadRequest")
	proto.RegisterType((*ReadAllRequest)(nil), "workflowservice.ReadAllRequest")
	proto.RegisterType((*WorkflowResponse)(nil), "workflowservice.WorkflowResponse")
	proto.RegisterType((*EditorConfig)(nil), "workflowservice.EditorConfig")
	proto.RegisterType((*EditorConfig_EditorConfigItem)(nil), "workflowservice.EditorConfig.EditorConfigItem")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Condition)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Condition")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Condition_Condition)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Condition.Condition")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_ConditionBranch)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.ConditionBranch")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Distribute)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Distribute")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Email)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Email")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Empty)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Empty")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_End)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.End")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_JoinSrc)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.JoinSrc")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_JoinDst)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.JoinDst")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Notify)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Notify")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Trigger)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Trigger")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Trigger_EventOptions)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Trigger.EventOptions")
	proto.RegisterType((*EditorConfig_EditorConfigItem_Settings_Wait)(nil), "workflowservice.EditorConfig.EditorConfigItem.Settings.Wait")
	proto.RegisterType((*WorkflowConfig)(nil), "workflowservice.WorkflowConfig")
	proto.RegisterType((*WorkflowConfig_Filter)(nil), "workflowservice.WorkflowConfig.Filter")
	proto.RegisterType((*WorkflowConfig_Step)(nil), "workflowservice.WorkflowConfig.Step")
	proto.RegisterType((*WorkflowConfig_Step_Recommendation)(nil), "workflowservice.WorkflowConfig.Step.Recommendation")
	proto.RegisterType((*WorkflowConfig_Step_Segmentation)(nil), "workflowservice.WorkflowConfig.Step.Segmentation")
	proto.RegisterType((*WorkflowConfig_Step_Condition)(nil), "workflowservice.WorkflowConfig.Step.Condition")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Email)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Email")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Notify)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Notify")
	proto.RegisterType((*WorkflowConfig_Step_ChannelMap_Action)(nil), "workflowservice.WorkflowConfig.Step.ChannelMap.Action")
	proto.RegisterType((*WorkflowConfig_Step_NextFlow)(nil), "workflowservice.WorkflowConfig.Step.NextFlow")
	proto.RegisterType((*WorkflowConfig_Step_Wait)(nil), "workflowservice.WorkflowConfig.Step.Wait")
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_Recommendation_Type", WorkflowConfig_Step_Recommendation_Type_name, WorkflowConfig_Step_Recommendation_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_Segmentation_Type", WorkflowConfig_Step_Segmentation_Type_name, WorkflowConfig_Step_Segmentation_Type_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Family", WorkflowConfig_Step_ChannelMap_Action_Family_name, WorkflowConfig_Step_ChannelMap_Action_Family_value)
	proto.RegisterEnum("workflowservice.WorkflowConfig_Step_ChannelMap_Action_Type", WorkflowConfig_Step_ChannelMap_Action_Type_name, WorkflowConfig_Step_ChannelMap_Action_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorkflowService service

type WorkflowServiceClient interface {
	CreateWorkflow(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	DeleteWorkflow(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ReadEditorConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ReadWorkflowConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ReadAllWorkflowConfigs(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
}

type workflowServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowServiceClient(cc *grpc.ClientConn) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) CreateWorkflow(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/CreateWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeleteWorkflow(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/DeleteWorkflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadEditorConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/ReadEditorConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadWorkflowConfig(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/ReadWorkflowConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReadAllWorkflowConfigs(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	out := new(WorkflowResponse)
	err := grpc.Invoke(ctx, "/workflowservice.WorkflowService/ReadAllWorkflowConfigs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkflowService service

type WorkflowServiceServer interface {
	CreateWorkflow(context.Context, *CreateRequest) (*WorkflowResponse, error)
	DeleteWorkflow(context.Context, *DeleteRequest) (*WorkflowResponse, error)
	ReadEditorConfig(context.Context, *ReadRequest) (*WorkflowResponse, error)
	ReadWorkflowConfig(context.Context, *ReadRequest) (*WorkflowResponse, error)
	ReadAllWorkflowConfigs(context.Context, *ReadAllRequest) (*WorkflowResponse, error)
}

func RegisterWorkflowServiceServer(s *grpc.Server, srv WorkflowServiceServer) {
	s.RegisterService(&_WorkflowService_serviceDesc, srv)
}

func _WorkflowService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/CreateWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/DeleteWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeleteWorkflow(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadEditorConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReadEditorConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/ReadEditorConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReadEditorConfig(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadWorkflowConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReadWorkflowConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/ReadWorkflowConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReadWorkflowConfig(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReadAllWorkflowConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReadAllWorkflowConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowservice.WorkflowService/ReadAllWorkflowConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReadAllWorkflowConfigs(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workflowservice.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowService_CreateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _WorkflowService_DeleteWorkflow_Handler,
		},
		{
			MethodName: "ReadEditorConfig",
			Handler:    _WorkflowService_ReadEditorConfig_Handler,
		},
		{
			MethodName: "ReadWorkflowConfig",
			Handler:    _WorkflowService_ReadWorkflowConfig_Handler,
		},
		{
			MethodName: "ReadAllWorkflowConfigs",
			Handler:    _WorkflowService_ReadAllWorkflowConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "WorkflowService.proto",
}

func init() { proto.RegisterFile("WorkflowService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x72, 0x1b, 0x49,
	0x15, 0x8e, 0x24, 0x4b, 0x1a, 0x1d, 0xc9, 0xb2, 0xdc, 0xfc, 0x0d, 0xe3, 0xdd, 0xb5, 0x57, 0x2c,
	0x90, 0xad, 0x62, 0x65, 0x50, 0x8a, 0x40, 0xb1, 0x64, 0x29, 0xd9, 0x92, 0xbd, 0xda, 0xc4, 0x76,
	0xaa, 0xc7, 0xce, 0x16, 0x4b, 0xaa, 0xa6, 0x46, 0x33, 0x6d, 0xa7, 0x9d, 0xf9, 0x51, 0xa6, 0x5b,
	0x76, 0xf4, 0x02, 0x3c, 0x02, 0x77, 0x5c, 0xc0, 0x2d, 0x45, 0xf1, 0x14, 0x3c, 0x06, 0x17, 0x54,
	0xf1, 0x0e, 0x14, 0x77, 0x54, 0xff, 0xcc, 0x68, 0x24, 0x3b, 0x44, 0x96, 0x6f, 0xb8, 0x52, 0x9f,
	0x33, 0x7d, 0xbe, 0xf3, 0xd3, 0xe7, 0x9c, 0x3e, 0x6a, 0xf8, 0xce, 0xd7, 0x71, 0xf2, 0xfa, 0x3c,
	0x88, 0xaf, 0x6d, 0x92, 0x5c, 0x51, 0x8f, 0x74, 0xc6, 0x49, 0xcc, 0x63, 0xb4, 0x71, 0xad, 0xd9,
	0x4c, 0xb1, 0xdb, 0x0e, 0xac, 0xef, 0x27, 0xc4, 0xe5, 0x04, 0x93, 0x37, 0x13, 0xc2, 0x38, 0x42,
	0xb0, 0x76, 0xc9, 0xe2, 0xc8, 0x2c, 0xec, 0x14, 0x1e, 0xd6, 0xb0, 0x5c, 0x23, 0x0b, 0x0c, 0x2f,
	0xa0, 0x24, 0xe2, 0x43, 0xdf, 0x2c, 0xee, 0x14, 0x1e, 0x96, 0x71, 0x46, 0xa3, 0x8f, 0x00, 0xd4,
	0xfa, 0x70, 0x42, 0x7d, 0xb3, 0x24, 0xa5, 0x72, 0x9c, 0xf6, 0x23, 0x58, 0x3f, 0x1b, 0xfb, 0x39,
	0x05, 0x4d, 0x28, 0x52, 0x5f, 0xc3, 0x17, 0xa9, 0x9f, 0x29, 0x2c, 0xce, 0x14, 0xb6, 0xb7, 0x61,
	0xbd, 0x4f, 0x02, 0xf2, 0x4e, 0xa1, 0xf6, 0x87, 0x50, 0xc7, 0xc4, 0xf5, 0xdf, 0xf5, 0xf9, 0x33,
	0x68, 0x8a, 0xcf, 0xbd, 0x20, 0x48, 0x77, 0x6c, 0x41, 0x8d, 0xf8, 0x94, 0xc7, 0x89, 0x93, 0x6d,
	0x34, 0x14, 0x63, 0xe8, 0xb7, 0x7d, 0x68, 0xa5, 0xe1, 0xc2, 0x84, 0x8d, 0xe3, 0x88, 0x11, 0x61,
	0x96, 0x17, 0xfb, 0x44, 0xee, 0x2d, 0x63, 0xb9, 0x46, 0x26, 0x54, 0x43, 0xc2, 0x98, 0x7b, 0x41,
	0xb4, 0xb5, 0x29, 0xa9, 0x0d, 0x28, 0xdd, 0x70, 0x6a, 0x2d, 0xe7, 0xd4, 0x7f, 0x36, 0xa1, 0x31,
	0x90, 0x2a, 0xf7, 0xe3, 0xe8, 0x9c, 0x5e, 0xa0, 0x3e, 0x94, 0x29, 0x27, 0x21, 0x33, 0x0b, 0x3b,
	0xa5, 0x87, 0xf5, 0x6e, 0xa7, 0xb3, 0x70, 0x38, 0x9d, 0xfc, 0xee, 0x39, 0x62, 0xc8, 0x49, 0x88,
	0x95, 0xb0, 0xf5, 0xe7, 0x4d, 0x68, 0x2d, 0x7e, 0xbb, 0x11, 0xe4, 0x2d, 0xa8, 0x8d, 0xdd, 0x84,
	0x44, 0x5c, 0xb8, 0xaf, 0x6c, 0x37, 0x14, 0x63, 0x28, 0x8d, 0xe5, 0xd3, 0x31, 0xd1, 0xe6, 0xcb,
	0x35, 0xb2, 0xc1, 0x60, 0x84, 0x73, 0x1a, 0x5d, 0x30, 0xe9, 0x44, 0xbd, 0xfb, 0x8b, 0xbb, 0x99,
	0xd7, 0xb1, 0xb5, 0x38, 0xce, 0x80, 0xac, 0x7f, 0x6f, 0x80, 0x91, 0xb2, 0x91, 0x03, 0x35, 0x2f,
	0x8e, 0x7c, 0xca, 0xa9, 0xce, 0xb6, 0x7a, 0xb7, 0xb7, 0xa2, 0x8a, 0xce, 0x7e, 0x0a, 0x84, 0x67,
	0x98, 0x28, 0x81, 0x56, 0x46, 0x38, 0xa3, 0xc4, 0x8d, 0xbc, 0x57, 0xd2, 0xf5, 0x7a, 0xf7, 0xf0,
	0xde, 0x7a, 0xf6, 0x24, 0x1c, 0xde, 0xf0, 0xe6, 0x19, 0x68, 0x04, 0xe0, 0x53, 0xc6, 0x13, 0x3a,
	0x9a, 0x70, 0x15, 0xd0, 0x7a, 0x77, 0x6f, 0x55, 0x6d, 0xfd, 0x0c, 0x09, 0xe7, 0x50, 0x91, 0x0d,
	0x65, 0x12, 0xba, 0x34, 0xd0, 0xe7, 0xf2, 0x64, 0x55, 0xf8, 0x81, 0x00, 0xc1, 0x0a, 0x4b, 0x81,
	0x8e, 0xf9, 0xd4, 0x2c, 0xdf, 0x17, 0x74, 0xcc, 0xa7, 0x58, 0x61, 0xa1, 0x23, 0x28, 0x91, 0xc8,
	0x37, 0x2b, 0x12, 0xf2, 0xf3, 0x95, 0x21, 0x23, 0x1f, 0x0b, 0x1c, 0xf4, 0x0d, 0x18, 0x97, 0x31,
	0x8d, 0x1c, 0x96, 0x78, 0x66, 0x55, 0x62, 0xfe, 0x66, 0x55, 0xcc, 0xaf, 0x62, 0x1a, 0xd9, 0x89,
	0x87, 0xab, 0x97, 0x6a, 0x91, 0x61, 0xfb, 0x8c, 0x9b, 0xc6, 0xfd, 0xb1, 0xfb, 0x8c, 0x2b, 0xec,
	0x3e, 0xe3, 0xe8, 0x05, 0x54, 0xa2, 0x98, 0xd3, 0xf3, 0xa9, 0x59, 0x93, 0xc8, 0x5f, 0xac, 0x8a,
	0x7c, 0x2c, 0x51, 0xb0, 0x46, 0x43, 0xbf, 0x85, 0x2a, 0x4f, 0xe8, 0xc5, 0x05, 0x49, 0x4c, 0xb8,
	0x9f, 0xc9, 0xa7, 0x0a, 0x06, 0xa7, 0x78, 0xe8, 0x39, 0xac, 0x5d, 0xbb, 0x94, 0x9b, 0x75, 0x89,
	0xfb, 0xeb, 0x55, 0x71, 0xbf, 0x76, 0x29, 0xc7, 0x12, 0xc9, 0xfa, 0x67, 0x01, 0x6a, 0x59, 0xf9,
	0x64, 0x2d, 0x47, 0xd4, 0xbd, 0xa1, 0x5b, 0xce, 0x6b, 0x80, 0xac, 0x9c, 0x98, 0x59, 0x94, 0x3d,
	0xf1, 0xe9, 0xbd, 0x2b, 0x35, 0xd7, 0x1b, 0x72, 0xf0, 0x96, 0x9d, 0xb7, 0xe6, 0xdb, 0x50, 0x3e,
	0xa7, 0x24, 0x48, 0x1b, 0xa6, 0x22, 0xc4, 0xad, 0x17, 0x8f, 0x49, 0xe2, 0xf2, 0x38, 0x49, 0x5b,
	0x66, 0x4a, 0x0b, 0x89, 0x2b, 0x37, 0x98, 0xa4, 0x3d, 0x53, 0x11, 0xd6, 0x26, 0x6c, 0x2c, 0x74,
	0x08, 0xab, 0x01, 0x30, 0x2b, 0x63, 0xeb, 0xf7, 0x05, 0x28, 0xcb, 0xb2, 0x43, 0xdb, 0x50, 0x67,
	0x24, 0xf2, 0x49, 0xe2, 0x44, 0x6e, 0x48, 0xb4, 0x62, 0x50, 0xac, 0x63, 0x37, 0x24, 0xe8, 0x63,
	0x68, 0xe8, 0x0d, 0xaa, 0xd8, 0x95, 0x05, 0x5a, 0x48, 0x61, 0x98, 0x50, 0x65, 0x93, 0xd1, 0x25,
	0xf1, 0xb8, 0x36, 0x23, 0x25, 0x05, 0x3a, 0x27, 0xe1, 0x38, 0x70, 0x39, 0x11, 0x0d, 0x5f, 0xdd,
	0x42, 0x90, 0xb2, 0x86, 0xbe, 0x55, 0x15, 0x76, 0x8c, 0xf9, 0xd4, 0x2a, 0x43, 0x69, 0x10, 0xf9,
	0x56, 0x0d, 0xaa, 0xba, 0x24, 0xd2, 0x65, 0x9f, 0x71, 0xeb, 0xa7, 0x50, 0x51, 0x29, 0x27, 0xfc,
	0x55, 0x66, 0xa8, 0x03, 0xd3, 0x4d, 0xa3, 0x05, 0x25, 0x97, 0x86, 0xd2, 0x34, 0x03, 0x8b, 0xa5,
	0xf5, 0x8f, 0x12, 0x54, 0x75, 0x32, 0x09, 0x99, 0x80, 0x32, 0xae, 0xae, 0xb7, 0x1a, 0x56, 0x84,
	0x88, 0x2a, 0x23, 0x17, 0x21, 0x89, 0xb8, 0x3a, 0xe3, 0x1a, 0xce, 0x68, 0xa9, 0xe5, 0x8a, 0x44,
	0xa9, 0x3b, 0x8a, 0x40, 0x6f, 0x60, 0x5d, 0x2e, 0x9c, 0x78, 0xac, 0x52, 0x43, 0xf5, 0xbd, 0x67,
	0xf7, 0x4c, 0xf6, 0xce, 0x40, 0x80, 0x9e, 0x28, 0x4c, 0xdc, 0x20, 0x39, 0xca, 0xfa, 0x43, 0x11,
	0x1a, 0xf9, 0xcf, 0x73, 0xf9, 0x9a, 0x5e, 0x91, 0x3f, 0x80, 0x75, 0x35, 0xe7, 0x38, 0x7e, 0x1c,
	0xba, 0x34, 0x9d, 0x60, 0x1a, 0x8a, 0xd9, 0x97, 0x3c, 0xe1, 0x6e, 0xe8, 0x46, 0x13, 0x37, 0x08,
	0xa6, 0xd2, 0x2b, 0x03, 0x67, 0xb4, 0x70, 0x77, 0xe4, 0x72, 0xef, 0x95, 0x74, 0xc8, 0xc0, 0x8a,
	0x10, 0x07, 0x7f, 0x4d, 0x46, 0x8e, 0x76, 0x8a, 0xc9, 0x86, 0x6c, 0xe0, 0xfa, 0x35, 0x19, 0xe9,
	0x51, 0x8e, 0x89, 0xe3, 0x15, 0x13, 0x95, 0x23, 0xf3, 0x94, 0x99, 0x15, 0x19, 0x46, 0x10, 0xac,
	0x03, 0xc9, 0x41, 0x1f, 0x82, 0xa4, 0x1c, 0x95, 0xa3, 0x55, 0x69, 0x57, 0x4d, 0x70, 0x5e, 0x08,
	0x86, 0x90, 0x57, 0x11, 0x55, 0xdf, 0x0d, 0x95, 0x1e, 0x92, 0xa5, 0x36, 0x7c, 0x0f, 0xaa, 0x09,
	0x63, 0xce, 0x24, 0x09, 0x64, 0xcb, 0xaa, 0xe1, 0x4a, 0xc2, 0xd8, 0x59, 0x12, 0x58, 0x8f, 0x61,
	0x4d, 0xd4, 0xb4, 0x70, 0xcb, 0x9f, 0x24, 0x6e, 0x76, 0x77, 0x97, 0x71, 0x46, 0x8b, 0x58, 0x4d,
	0x22, 0xca, 0xd3, 0x81, 0x4e, 0xac, 0xdb, 0x7f, 0x6b, 0x41, 0x33, 0x1d, 0xb1, 0xf4, 0xf4, 0xb3,
	0x38, 0xa2, 0x2c, 0x15, 0xce, 0xdb, 0x46, 0x95, 0x2d, 0xa8, 0x69, 0x41, 0x9d, 0xea, 0xf9, 0xf1,
	0x74, 0x1b, 0xea, 0xfa, 0xe3, 0x85, 0x98, 0x4f, 0xcb, 0x8b, 0xf3, 0x29, 0xfa, 0x02, 0x2a, 0xe7,
	0x34, 0xe0, 0x24, 0xd1, 0xd7, 0xd4, 0x8f, 0x6e, 0xa4, 0xd5, 0xbc, 0xdd, 0x9d, 0x03, 0xb9, 0x1b,
	0x6b, 0x29, 0xf4, 0x2b, 0x28, 0x33, 0x4e, 0xc6, 0xcc, 0xac, 0xca, 0x86, 0xf5, 0xc9, 0xfb, 0xc4,
	0x6d, 0x4e, 0xc6, 0x58, 0x89, 0xa0, 0x4f, 0xa0, 0x99, 0x0e, 0xa5, 0x9c, 0x84, 0xc2, 0x7c, 0x75,
	0x14, 0x0d, 0x3d, 0x99, 0x72, 0x12, 0x0e, 0x7d, 0xab, 0x0f, 0x15, 0xa5, 0x53, 0x38, 0x23, 0xae,
	0xbf, 0xb4, 0x7c, 0x54, 0x5d, 0x01, 0x8d, 0xec, 0xb4, 0x80, 0xbe, 0x0f, 0x06, 0x8d, 0x1c, 0x55,
	0x75, 0xaa, 0xb8, 0xaa, 0x34, 0x7a, 0x26, 0x48, 0xeb, 0xaf, 0xeb, 0xb0, 0x26, 0x74, 0x8b, 0xb3,
	0x15, 0xda, 0x67, 0x73, 0x70, 0x45, 0x90, 0x43, 0x1f, 0x1d, 0xdf, 0xd2, 0x7f, 0x3b, 0xcb, 0xb8,
	0x73, 0x7b, 0x8b, 0x45, 0xbf, 0x83, 0x66, 0x42, 0xbc, 0x38, 0x0c, 0x49, 0xe4, 0xab, 0x4c, 0x51,
	0xf3, 0xd0, 0xa3, 0xa5, 0x30, 0xf1, 0x9c, 0x28, 0x5e, 0x80, 0x42, 0x67, 0xa2, 0x3d, 0x4a, 0xaf,
	0x15, 0xb4, 0xea, 0x09, 0x3f, 0x5b, 0x0a, 0xda, 0xce, 0x09, 0xe2, 0x39, 0x18, 0xf4, 0x14, 0x0c,
	0xef, 0x95, 0x1b, 0x45, 0x24, 0x60, 0x7a, 0x12, 0xda, 0x5d, 0x2e, 0x02, 0x4a, 0xe8, 0xc8, 0x1d,
	0xe3, 0x0c, 0x00, 0x7d, 0x05, 0xb5, 0x88, 0xbc, 0xe5, 0x8e, 0xd8, 0xac, 0xb3, 0xeb, 0xb3, 0xa5,
	0xd0, 0x8e, 0xc9, 0x5b, 0x7e, 0x20, 0xfe, 0x8c, 0x18, 0x91, 0x5e, 0xa1, 0x27, 0xfa, 0x42, 0x56,
	0x73, 0xcf, 0xa7, 0x4b, 0xc1, 0xe4, 0x6e, 0xdf, 0x3f, 0x16, 0xc4, 0x3f, 0xa2, 0xb9, 0x08, 0x52,
	0xf8, 0xd6, 0x7c, 0x4c, 0x9d, 0xac, 0xc3, 0x35, 0xbb, 0xbf, 0x5c, 0xe1, 0x8c, 0x3a, 0xa7, 0xd3,
	0x31, 0xc1, 0x68, 0x1e, 0x54, 0xf0, 0xda, 0x3b, 0xb0, 0x26, 0x7e, 0x51, 0x03, 0x0c, 0xfb, 0xb4,
	0x77, 0xdc, 0xef, 0xe1, 0x7e, 0xeb, 0x01, 0x02, 0xa8, 0xec, 0x9f, 0xd9, 0xa7, 0x27, 0x47, 0xad,
	0x82, 0xf5, 0xa7, 0x02, 0x34, 0xf2, 0xc7, 0x82, 0x3c, 0xd8, 0xcc, 0x1f, 0x4c, 0xde, 0xb6, 0xc7,
	0x77, 0x3e, 0x64, 0x65, 0x59, 0x2b, 0x0f, 0x28, 0xed, 0xfa, 0xc9, 0xcc, 0xae, 0xbd, 0x33, 0x7b,
	0x78, 0x3c, 0xb0, 0xed, 0xd6, 0x03, 0x41, 0x1d, 0xe2, 0xde, 0xf3, 0x2f, 0x87, 0xfb, 0x76, 0xab,
	0x80, 0x0c, 0x58, 0xdb, 0x3b, 0x39, 0xfd, 0xb2, 0x55, 0xb4, 0x06, 0xf9, 0x91, 0xc1, 0x02, 0xe3,
	0xca, 0x4d, 0xa8, 0x3b, 0x0a, 0xd2, 0x4b, 0x21, 0xa3, 0xd1, 0x07, 0xf9, 0x7f, 0x36, 0xaa, 0x8b,
	0xcd, 0x18, 0xd6, 0xbf, 0xca, 0x00, 0xb3, 0x74, 0x41, 0x4f, 0xf3, 0x37, 0x6b, 0xbd, 0xfb, 0xf3,
	0x3b, 0xa6, 0xdb, 0xfc, 0x14, 0x7f, 0x9c, 0x4d, 0x9a, 0xea, 0x8f, 0xce, 0xe3, 0xbb, 0xa2, 0x2d,
	0x4c, 0x98, 0xcf, 0xa1, 0xea, 0x7a, 0xaa, 0x1f, 0x94, 0x64, 0x3f, 0xb8, 0x33, 0x60, 0x4f, 0x8a,
	0xe3, 0x14, 0xe6, 0xff, 0x67, 0x02, 0xba, 0xfb, 0x6c, 0xf3, 0x97, 0x22, 0x54, 0x94, 0x3b, 0x68,
	0x04, 0xeb, 0xca, 0x21, 0xe7, 0xdc, 0x0d, 0x69, 0x30, 0xd5, 0x99, 0xf9, 0x64, 0xb5, 0xe8, 0x74,
	0x0e, 0x24, 0x08, 0x6e, 0x28, 0x4c, 0x45, 0xa1, 0x97, 0x50, 0xd7, 0x3a, 0x64, 0xee, 0x17, 0xa5,
	0x86, 0xcf, 0x57, 0xd4, 0x20, 0x0b, 0x00, 0x14, 0x9e, 0x4c, 0xf9, 0x1f, 0x42, 0x53, 0xa3, 0xcf,
	0x07, 0x50, 0xfb, 0x65, 0x2b, 0x66, 0x7b, 0x0b, 0x2a, 0xda, 0x9c, 0x2a, 0x94, 0x4e, 0x7b, 0x87,
	0xad, 0x07, 0xa2, 0x20, 0x9e, 0x0d, 0xed, 0xd3, 0x56, 0xa1, 0xbd, 0xa5, 0xcb, 0xa7, 0x0a, 0xa5,
	0x5e, 0x5f, 0x57, 0x34, 0x1e, 0x1c, 0x9d, 0xbc, 0x18, 0xb4, 0x0a, 0x96, 0x05, 0x46, 0xda, 0xc6,
	0x16, 0xaf, 0x7a, 0xab, 0xfd, 0xfe, 0x29, 0xa2, 0xfb, 0xf7, 0x12, 0x6c, 0x2c, 0xbc, 0x61, 0x21,
	0x1b, 0x9a, 0xea, 0xb1, 0x2a, 0xfd, 0x80, 0x3e, 0xba, 0x11, 0x8f, 0xb9, 0xd7, 0x2c, 0xeb, 0xe3,
	0x77, 0xc6, 0x2b, 0x7b, 0xe8, 0xb1, 0xa1, 0xa9, 0xde, 0x9a, 0xfe, 0x07, 0xe8, 0xdc, 0x63, 0xd4,
	0x72, 0xa0, 0x2d, 0x4c, 0x5c, 0x7f, 0xee, 0xb9, 0xe7, 0x83, 0x1b, 0x62, 0xb9, 0x27, 0xac, 0x65,
	0x40, 0xcf, 0x00, 0x09, 0x89, 0x85, 0x39, 0xea, 0xde, 0xb0, 0x2f, 0xe1, 0xbb, 0xfa, 0xb1, 0x6c,
	0x1e, 0x99, 0xa1, 0xed, 0x5b, 0xa1, 0x67, 0xaf, 0x6a, 0x4b, 0xa0, 0xef, 0x7d, 0xfa, 0xcd, 0x8f,
	0xbd, 0x80, 0x5c, 0x91, 0x24, 0x8c, 0x23, 0x11, 0x8c, 0x5d, 0x37, 0x72, 0x83, 0x29, 0xa7, 0x1e,
	0xdb, 0x95, 0x4f, 0x92, 0x6c, 0x37, 0x85, 0x18, 0x55, 0x24, 0xe3, 0xd1, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xbb, 0xdb, 0x17, 0x14, 0xbc, 0x14, 0x00, 0x00,
}
