services:
    _defaults:
        public: '%public.services%'

    # Magento2Old
    hbpf.authorization.magento2.auth:
        class: Hanaboso\PipesFramework\Authorization\Impl\Magento2\Magento2Authorization
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - 'magento2.auth'
            - 'magento2 Authorization'
            - 'magento2 Authorization'

    hbpf.authorization.magento2_oauth:
        class: Hanaboso\PipesFramework\Authorization\Impl\Magento2\Magento2OAuthAuthorization
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.providers.oauth1_provider'
            - 'magento2_oauth'
            - 'magento2 OAuth'
            - 'magento2 OAuth'
            - '%backend_host%'
        calls:
            - ['setLogger', ['@monolog.logger.authorization']]
