services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFAuthorizationBundle\Controller\AuthorizationController:
        class: Hanaboso\PipesFramework\HbPFAuthorizationBundle\Controller\AuthorizationController
        arguments:
            - '@hbpf.handler.authorization'
        calls:
            - ['setContainer', ['@service_container']]
