services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $authorizationHandler: '@hbpf.handler.authorization'

    Hanaboso\PipesFramework\HbPFAuthorizationBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
