doctrine_mongodb:
    document_managers:
        default:
            mappings:
                AuthorizationDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../src/Authorization/Document"
                    prefix: Hanaboso\PipesFramework\Authorization\Document