services:

    hbpf.providers.oauth1_provider:
        class: Hanaboso\PipesFramework\Authorization\Provider\OAuth1Provider
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.redirect'