services:
    hbpf.loader.authorization:
        class: Hanaboso\PipesFramework\HbPFAuthorizationBundle\Loader\AuthorizationLoader
        arguments:
            - '@service_container'
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.handler.authorization:
        class: Hanaboso\PipesFramework\HbPFAuthorizationBundle\Handler\AuthorizationHandler
        arguments:
            - '@hbpf.loader.authorization'