services:

    hbpf.core.listener:
        class: Hanaboso\PipesFramework\HbPFAuthorizationBundle\DocumentListener\DocumentListener
        arguments:
        - '@hbpf.commons.crypt_service'
        tags:
        - { name: doctrine_mongodb.odm.event_listener, event: preFlush, method: preFlush }
        - { name: doctrine_mongodb.odm.event_listener, event: postLoad, method: postLoad }

    hbpf.handler.authorization:
        class: Hanaboso\PipesFramework\HbPFAuthorizationBundle\Handler\AuthorizationHandler
        arguments: