parameters:
  # Base params
  locale: en

  # A secret key that's used to generate certain security-related tokens
  secret: ThisTokenIsNotSoSecretChangeIt

  frontendHost: "%env(string:FRONTEND_URL)%"
  backendHost: "%env(string:BACKEND_URL)%"
  cronHost: "%env(string:CRON_DSN)%"
  startingPointHost: "%env(string:STARTING_POINT_URL)%"
  notifierHost: "%env(string:NOTIFIER_DSN)%"
  lokiHost: "%env(string:LOKI_DSN)%"
  activateLink: '%backendHost%/user/%s/activate'
  passwordLink: 'reset-password/%s'

  env(NOTIFIER_DSN): ''
  env(LOKI_DSN): ''
  env(ORCHESTY_CLOUD_URL): ''
  env(ORCHESTY_CLOUD_FRONTEND_URL): ''
  env(ORCHESTY_CLOUD_INSTANCE_ID): ''
  env(ORCHESTY_CLOUD_INSTANCE_SECRET): ''
  env(ORCHESTY_CLOUD_INSTANCE_NAME): ''
  env(AUTH0_DOMAIN): ''
  env(AUTH0_AUDIENCE): ''
  env(SYSTEM_ORCHESTY_URL): ''
  env(ORCHESTY_FEATURE_ENTERPRISE_DASHBOARDS): 'false'
  env(ORCHESTY_FEATURE_TRACE_AUDITING): 'false'
  env(ORCHESTY_FEATURE_AUDIT_LOGS): 'false'
  env(ORCHESTY_FEATURE_PULSE): 'false'
  orchesty_cloud_url: '%env(string:ORCHESTY_CLOUD_URL)%'
  system_orchesty_url: '%env(string:SYSTEM_ORCHESTY_URL)%'
  orchesty_cloud_frontend_url: '%env(string:ORCHESTY_CLOUD_FRONTEND_URL)%'
  orchesty_cloud_instance_id: '%env(string:ORCHESTY_CLOUD_INSTANCE_ID)%'
  orchesty_cloud_instance_secret: '%env(string:ORCHESTY_CLOUD_INSTANCE_SECRET)%'
  orchesty_cloud_instance_name: '%env(string:ORCHESTY_CLOUD_INSTANCE_NAME)%'
  auth0_domain: '%env(string:AUTH0_DOMAIN)%'
  auth0_audience: '%env(string:AUTH0_AUDIENCE)%'
  feature_enterprise_dashboards: '%env(bool:ORCHESTY_FEATURE_ENTERPRISE_DASHBOARDS)%'
  feature_trace_auditing: '%env(bool:ORCHESTY_FEATURE_TRACE_AUDITING)%'
  feature_audit_logs: '%env(bool:ORCHESTY_FEATURE_AUDIT_LOGS)%'
  feature_pulse: '%env(bool:ORCHESTY_FEATURE_PULSE)%'

services:
    Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\Auth0\Auth0Authenticator:
        arguments:
            $auth0Domain: '%auth0_domain%'
            $auth0Audience: '%auth0_audience%'
            $jwksCacheService: '@hbpf.auth0.jwks_cache'
            $jwtAuthenticator: '@Hanaboso\UserBundle\Model\Security\JWTAuthenticator'
            $dml: '@hbpf.database_manager_locator'
            $resourceProvider: '@hbpf.user.provider.resource'
            $curlManager: '@hbpf.transport.curl_manager'

    Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\ApiKey\EnterpriseApiKeyAuthenticator:
        arguments:
            $auth0Authenticator: '@Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\Auth0\Auth0Authenticator'
            $dml: '@hbpf.database_manager_locator'
