parameters:
  # Base params
  locale: en

  # A secret key that's used to generate certain security-related tokens
  secret: ThisTokenIsNotSoSecretChangeIt

  frontendHost: "%env(string:FRONTEND_URL)%"
  backendHost: "%env(string:BACKEND_URL)%"
  cronHost: "%env(string:CRON_DSN)%"
  startingPointHost: "%env(string:STARTING_POINT_URL)%"
  notifierHost: "%env(string:NOTIFIER_DSN)%"
  lokiHost: "%env(string:LOKI_DSN)%"
  tunnelProxyHost: "%env(string:TUNNEL_PROXY_HOST)%"
  tunnelProxyGrpcUrl: "%env(string:TUNNEL_PROXY_GRPC_URL)%"
  tunnelExtBackendUrl: "%env(string:TUNNEL_EXT_BACKEND_URL)%"
  tunnelExtStartingPointUrl: "%env(string:TUNNEL_EXT_STARTING_POINT_URL)%"
  tunnelExtWorkerApiHost: "%env(string:TUNNEL_EXT_WORKER_API_HOST)%"
  activateLink: '%backendHost%/user/%s/activate'
  passwordLink: 'reset-password/%s'

  env(TUNNEL_PROXY_HOST): ''
  env(TUNNEL_PROXY_GRPC_URL): ''
  env(TUNNEL_EXT_BACKEND_URL): ''
  env(TUNNEL_EXT_STARTING_POINT_URL): ''
  env(TUNNEL_EXT_WORKER_API_HOST): ''
  env(NOTIFIER_DSN): ''
  env(LOKI_DSN): ''
  env(ORCHESTY_CLOUD_BACKEND_URL): ''
  env(ORCHESTY_CLOUD_FRONTEND_URL): ''
  env(ORCHESTY_CLOUD_INSTANCE_ID): ''
  env(ORCHESTY_CLOUD_INSTANCE_SECRET): ''
  env(AUTH0_DOMAIN): ''
  env(AUTH0_AUDIENCE): ''
  env(ORCHESTY_CLOUD_STARTING_POINT_URL): ''
  env(ORCHESTY_FEATURE_ENTERPRISE_DASHBOARDS): 'false'
  env(ORCHESTY_FEATURE_TRACE_AUDITING): 'false'
  env(ORCHESTY_FEATURE_AUDIT_LOGS): 'false'
  env(ORCHESTY_FEATURE_PULSE): 'false'
  env(ORCHESTY_LIMIT_TOPOLOGY_SLOTS): '0'
  env(ORCHESTY_LIMIT_MESSAGES): '0'
  env(ORCHESTY_LIMIT_STORAGE_GB): '0'
  orchesty_cloud_backend_url: '%env(string:ORCHESTY_CLOUD_BACKEND_URL)%'
  orchesty_cloud_starting_point_url: '%env(string:ORCHESTY_CLOUD_STARTING_POINT_URL)%'
  orchesty_cloud_frontend_url: '%env(string:ORCHESTY_CLOUD_FRONTEND_URL)%'
  orchesty_cloud_instance_id: '%env(string:ORCHESTY_CLOUD_INSTANCE_ID)%'
  orchesty_cloud_instance_secret: '%env(string:ORCHESTY_CLOUD_INSTANCE_SECRET)%'
  auth0_domain: '%env(string:AUTH0_DOMAIN)%'
  auth0_audience: '%env(string:AUTH0_AUDIENCE)%'
  feature_enterprise_dashboards: '%env(bool:ORCHESTY_FEATURE_ENTERPRISE_DASHBOARDS)%'
  feature_trace_auditing: '%env(bool:ORCHESTY_FEATURE_TRACE_AUDITING)%'
  feature_audit_logs: '%env(bool:ORCHESTY_FEATURE_AUDIT_LOGS)%'
  feature_pulse: '%env(bool:ORCHESTY_FEATURE_PULSE)%'
  limit_topology_slots: '%env(int:ORCHESTY_LIMIT_TOPOLOGY_SLOTS)%'
  limit_messages: '%env(int:ORCHESTY_LIMIT_MESSAGES)%'
  limit_storage_gb: '%env(int:ORCHESTY_LIMIT_STORAGE_GB)%'
  system_worker_names: ['sys-worker']

services:
    Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\Auth0\Auth0Authenticator:
        arguments:
            $auth0Domain: '%auth0_domain%'
            $auth0Audience: '%auth0_audience%'
            $jwksCacheService: '@hbpf.auth0.jwks_cache'
            $jwtAuthenticator: '@Hanaboso\UserBundle\Model\Security\JWTAuthenticator'
            $dml: '@hbpf.database_manager_locator'
            $resourceProvider: '@hbpf.user.provider.resource'
            $curlManager: '@hbpf.transport.curl_manager'
            $passwordHasherFactory: '@Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface'
            $groupManager: '@hbpf.manager.group'

    Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\ApiKey\EnterpriseApiKeyAuthenticator:
        arguments:
            $auth0Authenticator: '@Hanaboso\PipesFrameworkEnterprise\ApiGateway\Authenticator\Auth0\Auth0Authenticator'
            $dml: '@hbpf.database_manager_locator'
