---
version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
  mongodb:
    image: mongo
  logstash:
    image: kedlas/udplogger:latest

  limiter:
    image: golang:latest
    working_dir: /limiter
    environment:
      - MONGO_HOST=mongodb
      - RABBITMQ_HOST=rabbitmq
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5120
    volumes:
      - ./:/limiter
    command: bash -c 'sleep infinity'
