---
version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${LIMITER_HOST}:15672:15672
      - ${LIMITER_HOST}:5672:5672
  mongodb:
    image: mongo
    ports:
      - ${LIMITER_HOST}:27017:27017

  logstash:
    image: kedlas/udplogger:latest
    ports:
      - ${LIMITER_HOST}:5120:4444/udp

  limiter:
    image: golang:latest
    working_dir: /limiter
    environment:
      - MONGO_HOST=mongodb
      - RABBITMQ_HOST=rabbitmq
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=4444
    volumes:
      - ./:/limiter
    command: bash -c 'sleep infinity'
