---
version: '3'

services:
  app:
    image: hanabosocom/go-base:1.18
    working_dir: /limiter
    environment:
      - RABBITMQ_DSN=amqp://rabbitmq:5672/
      - UDP_LOGGER_URL=logstash:5120
      - MONGO_DSN=${MONGO_DSN}
    volumes:
      - ./:/limiter
    command: bash -c 'sleep infinity'

  rabbitmq:
    image: rabbitmq:management-alpine

  mongodb:
      image: mongo:latest
      ports:
        - ${DEV_IP}:27017:27017
      volumes:
        - mongodb:/data/db

  logstash:
    image: mendhak/udp-listener
    environment:
      UDPPORT: 5120

volumes:
    mongodb:
    rabbitmq:

