services:
    app:
        image: hanabosocom/go-base:1.24
        working_dir: /app
        environment:
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGO_DSN: ${MONGO_DSN}
        ports:
            - ${DEV_IP}:3333:3333
        volumes:
            - ./:/app
            - ${GOPATH}/pkg:/go/pkg
        command: bash -c 'sleep infinity'

    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - ${DEV_IP}:15672:15672
            - ${DEV_IP}:5672:5672

    mongodb:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017

