#DEMO
rabbit-mq:
    exchanges:
        pipes_exchange:
            durable: true
            type: direct

    queues:
        demo_queue:
            durable: true
            bindings:
                - exchange: pipes_exchange
                  routing_key: demo

    producers:
        demo:
            class: Hanaboso\PipesFramework\Commons\RabbitMq\Demo\DemoProducer
            exchange: pipes_exchange
            serializer: Hanaboso\PipesFramework\RabbitMqBundle\Serializers\JsonSerializer
            routing_key: demo

    consumers:
        demo:
            class: Hanaboso\PipesFramework\Commons\RabbitMq\Demo\DemoConsumer
            routing_key: demo
            queue: demo_queue
            serializer: Hanaboso\PipesFramework\RabbitMqBundle\Serializers\JsonSerializer
            callback: hanaboso.pipes_framework.commons.rabbit_mq.demo.demo_callback

    async_consumers:
        async-demo:
            class: Hanaboso\PipesFramework\Commons\RabbitMq\AsyncDemo\DemoConsumer
            queue: async-demo
            serializer:
            callback: hanaboso.pipes_framework.commons.rabbit_mq.async_demo.demo_callback
            prefetch_count: 10

services:
    hanaboso.pipes_framework.commons.rabbit_mq.demo.demo_callback:
        class: Hanaboso\PipesFramework\Commons\RabbitMq\Demo\DemoCallback
        arguments:
            - '@monolog.logger.rabbit-mq'
        calls:
            - [setRepeater, ['@hanaboso.pipes_framework.commons.rabbit_mq.repeater.repeater']]

    hanaboso.pipes_framework.commons.rabbit_mq.async_demo.demo_callback:
        class: Hanaboso\PipesFramework\Commons\RabbitMq\AsyncDemo\DemoCallback
