rabbit-mq:

    exchanges:
        repeater:
            durable: true
            type: direct

    queues:
        repeater:
            durable: true
            bindings:
                - exchange: repeater
                  routing_key: repeater

    producers:
        repeater:
            class: Hanaboso\PipesFramework\Commons\RabbitMq\Demo\DemoProducer
            exchange: demo
            serializer: Hanaboso\PipesFramework\RabbitMqBundle\Serializers\JsonSerializer
            routing_key: repeater

    consumers:
        repeater:
            class: Hanaboso\PipesFramework\Commons\RabbitMq\Demo\DemoConsumer
            routing_key: repeater
            queue: demo
            serializer: Hanaboso\PipesFramework\RabbitMqBundle\Serializers\JsonSerializer
            callback: hanaboso.pipes_framevork.commons.repeater.repeater_callback

services:
    hanaboso.pipes_framevork.commons.repeater.repeater_callback:
        class: Hanaboso\PipesFramevork\Commons\Repeater\RepeaterCallback
        calls:
            - [setRepeater, ['@hanaboso.pipes_framevork.commons.repeater.repeater']]

    hanaboso.pipes_framevork.commons.repeater.repeater:
        class: Hanaboso\PipesFramevork\Commons\Repeater\Repeater
        arguments: ['@hanaboso.pipes_framevork.commons.repeater.repeater_producer', '2']

    hanaboso.pipes_framevork.commons.repeater.repeater_producer:
        class: Hanaboso\PipesFramevork\Commons\Repeater\RepeaterProducer
        calls:
            - [setLogger, ['@monolog.logger.rabbit-mq']]
