parameters:
    database_host: mongo
    database_port: null
    database_name: demo
    database_user: root
    database_password: root

doctrine_mongodb:
    default_document_manager: default
    default_connection: default
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%database_host%"
            options:
                connectTimeoutMS: 60000
                socketTimeoutMS: 60000
        metrics:
            server: "mongodb://%database_host%"
            options:
                connectTimeoutMS: 60000
                socketTimeoutMS: 60000
    default_database: '%database_name%'
    document_managers:
        default:
            mappings:
                HbPFUserBundle: ~
                CommonsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/Database/Document"
                    prefix: Hanaboso\CommonsBundle\Database\Document
                ApplicationDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/pipes-php-sdk/src/Application/Document"
                    prefix: Hanaboso\PipesPhpSdk\Application\Document
                LongRunningNodeDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/pipes-php-sdk/src/LongRunningNode/Document"
                    prefix: Hanaboso\PipesPhpSdk\LongRunningNode\Document
                LogsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/pipes-framework/src/Logs/Document"
                    prefix: Hanaboso\PipesFramework\Logs\Document
                Webhook:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/app-store/src/Document"
                    prefix: Hanaboso\HbPFApplication\Document
        metrics:
            connection: metrics
            database: metrics
            mappings:
                MetricsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/pipes-framework/src/Metrics/Document"
                    prefix: Hanaboso\PipesFramework\Metrics\Document
