doctrine_mongodb:
    default_document_manager: default
    default_connection: default
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: OdmProxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: OdmHydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "%env(string:MONGODB_DSN)%"
            options:
                connectTimeoutMS: 60000
                socketTimeoutMS: 60000
        metrics:
            server: "%env(string:METRICS_ODM_DSN)%"
            options:
                connectTimeoutMS: 60000
                socketTimeoutMS: 60000
    default_database: "%env(string:MONGODB_DB)%"
    document_managers:
        default:
            connection: default
            database: "%env(string:MONGODB_DB)%"
            mappings:
                CommonsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/orchesty/php-sdk/src/Database/Document"
                    prefix: Hanaboso\PipesPhpSdk\Database\Document
                ApplicationDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/orchesty/php-sdk/src/Application/Document"
                    prefix: Hanaboso\PipesPhpSdk\Application\Document
