#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: []
#        allow_headers: []
#        allow_methods: []
#    paths:
#        '^/api/':
#            allow_credentials: true
#            allow_origin: ['*']
#            allow_headers: ['Content-Type', 'filter', 'orderby', 'page', 'limit']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
#            max_age: 3600