parameters:
    rabbit_host: rabbitmq
    rabbit_port: 5672
    rabbit_vhost: /
    rabbit_user: guest
    rabbit_password: guest
    rabbit_persistent: true
    rabbit_path: /

# Repeater
rabbit_mq:
    exchanges:
        repeater:
            durable: true
            type: direct

    queues:
        pipes.batch_connector:
        pipes.batch:
