services:
    _defaults:
        autoconfigure: true
        autowire: false
        public: true

    hbpf.commons.session_handler:
        class: Hanaboso\CommonsBundle\Session\Handler\RedisSessionHandler
        arguments:
            - '@snc_redis.default'