parameters:
    env(SMTP_USER):
    env(SMTP_PASSWORD):
    mailer_user: '%env(SMTP_USER)%'
    mailer_password: '%env(SMTP_PASSWORD)%'

    mailer_from: dev.email.hb@gmail.com
    mailer_async: false
    mailer_builder_id: generic

swiftmailer:
    transport: 'gmail'
    username: '%mailer_user%'
    password: '%mailer_password%'
    host: 'smtp.gmail.com'
    disable_delivery: false
    logging: true