services:
    # Magento2
    hbpf.connector.magento2.orders:
        class: Hanaboso\PipesFramework\Connector\Impl\Magento2\Magento2OrdersConnector
        arguments:
            - '@hbpf.authorization.magento2_oauth'
            - '@hbpf.transport.curl_manager'

    hbpf.connector.magento2.modules:
        class: Hanaboso\PipesFramework\Connector\Impl\Magento2\Magento2ModulesConnector
        arguments:
            - '@hbpf.authorization.magento2_oauth'
            - '@hbpf.transport.curl_manager'

    hbpf.connector.magento2.customers:
        class: Hanaboso\PipesFramework\Connector\Impl\Magento2\Magento2CustomersConnector
        arguments:
            - '@hbpf.authorization.magento2_oauth'
            - '@hbpf.transport.curl_manager'
