services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFConnectorBundle\Controller\ConnectorController:
        class: Hanaboso\PipesFramework\HbPFConnectorBundle\Controller\ConnectorController
        arguments:
            - '@hbpf.handler.connector'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
            - ['setContainer', ['@service_container']]
