services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $connectorHandler: '@hbpf.handler.connector'
            $logger: '@monolog.logger.commons'

    Hanaboso\PipesFramework\HbPFConnectorBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']