services:
    hbpf.loader.connector:
        class: Hanaboso\PipesFramework\HbPFConnectorBundle\Loader\ConnectorLoader
        arguments:
            - "@service_container"

    # --- Provizorní pro test --- #
    hbpf.storage.interface:
        class: Hanaboso\PipesFramework\Commons\ServiceStorage\JSONSingleFileStorage
    # --------------------------- #
