---

portal-api-build:
  stage: stage3
  only:
    changes:
      - portal/**/*
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor
  script:
    - cd portal
    - make build-sls
  artifacts:
    expire_in: 1 week
    paths:
      - portal

.portal-api-deploy:
  stage: stage5
  when: manual
  dependencies:
    - portal-api-build
  script:
    - cd portal
    - make deploy-sls SLS_ENV=${ENV}

portal-api-deploy-stage:
  variables:
    ENV: stage
  extends: .portal-api-deploy

portal-api-deploy-prod:
  variables:
    ENV: prod
  extends: .portal-api-deploy
  only:
    refs:
      - master
