services:
    hbpf.controller.topology:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TopologyController
        arguments:
            - '@hbpf.handler.topology'
    hbpf.controller.node:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NodeController
        arguments:
            - '@hbpf.handler.node'

    hbpf.commons.controller.starting_point:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\StartingPointController
        arguments:
            - '@hbpf.handler.starting_point'
