services:
    _defaults:
        public: '%public.services%'
        autowire: true
        autoconfigure: true

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\ApplicationController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\ApplicationController
        arguments:
            - '@hbpp.service.locator'

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\CategoryController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\CategoryController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\ConnectorController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\ConnectorController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\LogsController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\LogsController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\LongRunningNodeController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\LongRunningNodeController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\MetricsController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\MetricsController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NodeController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NodeController
        arguments:
            - '@hbpp.service.locator'

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NotificationController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NotificationController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TopologyController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TopologyController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\UserController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\UserController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\SdkController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\SdkController

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\WebhookController:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\WebhookController
