services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
