services:
    hbpf.api_gateway.controller.starting_point:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\StartingPointController
        arguments:
            - '@hbpf.handler.starting_point'

    hbpf.api_gateway.controller.test:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TestController
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@hbpf.handler.starting_point'
            - '%kernel.project_dir%'
