services:
    hbpf.api_gateway.controller.node:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NodeController
        arguments:

    hbpf.api_gateway.controller.topology:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TopologyController
        arguments:

    hbpf.api_gateway.controller.user:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\UserController
        arguments:

    hbpf.api_gateway.controller.authorization:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\AuthorizationController
        arguments:

    hbpf.api_gateway.controller.starting_point:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\StartingPointController
        arguments:

    hbpf.api_gateway.controller.connector:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\ConnectorController
        arguments:

    hbpf.api_gateway.controller.generator:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\GeneratorController
        arguments:
