services:
    hbpf.api_gateway.controller.starting_point:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\StartingPointController
        arguments:
            - '@hbpf.handler.starting_point'

    hbpf.api_gateway.controller.test:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TestController
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@hbpf.handler.starting_point'
            - "%kernel.project_dir%"
            - "@monolog.logger.test"

    hbpf.api_gateway.controller.node:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\NodeController
        arguments:

    hbpf.api_gateway.controller.topology:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\TopologyController
        arguments:

    hbpf.api_gateway.controller.user:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\UserController
        arguments:

    hbpf.api_gateway.controller.authorization:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Controller\AuthorizationController
        arguments:
