services:
    _defaults:
        public: '%public.services%'

    listener.controller.exception:
        class: Hanaboso\PipesFramework\ApiGateway\Listener\ControllerExceptionListener
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber }
