services:
    hbpf.handler.topology:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Handler\TopologyHandler
        arguments:
            - "@hbpf.database_manager_locator"
            - '@hbpf.manager.topology'

    hbpf.manager.topology:
        class: Hanaboso\PipesFramework\ApiGateway\Manager\TopologyManager
        arguments:
            - "@hbpf.database_manager_locator"
