services:
    listener.controller.exception:
        class: Hanaboso\PipesFramework\ApiGateway\Listener\ControllerExceptionListener
        arguments:
        class:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber }
