services:
    hbpf.handler.starting_point:
        class: Hanaboso\PipesFramework\HbPFApiGatewayBundle\Handler\StartingPointHandler
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@hbpf.starting_point.starting_point'
