services:
    _defaults:
        public: '%public.services%'

    hbpp.service.locator:
        class: Hanaboso\PipesFramework\ApiGateway\Locator\ServiceLocator
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '@hbpf.redirect'
        calls:
            - ['setLogger',['@monolog.logger.commons']]

    listener.controller.exception:
        class: Hanaboso\PipesFramework\ApiGateway\Listener\ControllerExceptionListener
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber }

    listener.repeater:
        class: Hanaboso\PipesFramework\ApiGateway\Listener\RepeaterListener
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber }
