.base-comparator:
  variables:
    DIR: comparator
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}comparator

comparator:test:
  stage: test
  extends:
    - .base-test
    - .base-comparator

comparator:build:
  stage: build
  needs:
    - job: comparator:test
      optional: false
  extends:
    - .base-dind-build
    - .base-comparator
