---
site build:
  stage: stage3
  only:
    changes:
      - website/**/*
  script:
    - cd website
    - make build PORTAL_API_URL=%PORTAL_API_URL% # placeholder to be replaced by deploy job (Makefile)
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - website/node_modules
  artifacts:
    expire_in: 1 week
    paths:
      - website/build

.site_deploy:
  stage: stage5
  when: manual
  only:
    changes:
      - website/**/*
  dependencies:
    - site build
  script:
    - cd website
    - make deploy BUCKET=pipes-website-${ENV} PORTAL_API_URL=${PORTAL_API_URL}
    - echo Deployed to http://pipes-website-${ENV}.s3-website-eu-west-1.amazonaws.com/

site deploy stage:
  variables:
    ENV: stage
    PORTAL_API_URL: "${PORTAL_API_URL_STAGE}"
  extends: .site_deploy

site deploy prod:
  variables:
    ENV: prod
    PORTAL_API_URL: ${PORTAL_API_URL_PROD}
  extends: .site_deploy
  only:
    refs:
      - master
