export const SELECT_PAGE = 'SELECT_PAGE';
export const SET_PAGE_DATA = 'SET_PAGE_DATA';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const TOGGLE_MAIN_SUB_MENU = 'TOGGLE_MAIN_SUB_MENU';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';

// Process
export const PROCESS_SET_STATE = 'PROCESS_SET_STATE';
export const PROCESS_CLEAR = 'PROCESS_CLEAR';

// Authorization
export const USER_LOGGED = 'USER_LOGGED';
export const USER_LOGOUT = 'USER_LOGOUT';

// Notifications
export const NOTIFICATION_INCREMENT_ID = 'NOTIFICATION_INCREMENT_ID';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_TIMEOUT = 'NOTIFICATION_TIMEOUT';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

// Topology
export const TOPOLOGY_LIST_CREATE = 'TOPOLOGY/LIST/CREATE';
export const TOPOLOGY_LIST_DELETE = 'TOPOLOGY/LIST/DELETE';
export const TOPOLOGY_LIST_LOADING = 'TOPOLOGY/LIST/LOADING';
export const TOPOLOGY_LIST_RECEIVE = 'TOPOLOGY/LIST/RECEIVE';
export const TOPOLOGY_LIST_ERROR = 'TOPOLOGY/LIST/ERROR';
export const TOPOLOGY_LIST_CHANGE_SORT = 'TOPOLOGY/LIST/CHANGE_SORT';
export const TOPOLOGY_LIST_CHANGE_PAGE = 'TOPOLOGY/LIST/CHANGE_PAGE';

export const TOPOLOGY_RECEIVE = 'TOPOLOGY_RECEIVE';
export const TOPOLOGY_RECEIVE_SCHEMA = 'TOPOLOGY_RECEIVE_SCHEMA';

// Node
export const NODE_LIST_CREATE = 'NODE/LIST/CREATE';
export const NODE_LIST_LOADING = 'NODE/LIST/LOADING';
export const NODE_LIST_RECEIVE = 'NODE/LIST/RECEIVE';
export const NODE_LIST_ERROR = 'NODE/LIST/ERROR';

export const NODE_RECEIVE = 'NODE_RECEIVE';

