services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFLongRunningNodeBundle\Controller\LongRunningNodeController:
        class: Hanaboso\PipesFramework\HbPFLongRunningNodeBundle\Controller\LongRunningNodeController
        arguments:
            - '@hbpf.handler.long_running'
        calls:
            - ['setContainer', ['@service_container']]
