services:
    _defaults:
        public: '%public.services%'

    hbpf.loader.long_running:
        class: Hanaboso\PipesFramework\HbPFLongRunningNodeBundle\Loader\LongRunningNodeLoader
        arguments:
            - '@service_container'