export const ADMIN_USERS = {
  NAMESPACE: 'adminUsers',
  ACTIONS: {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  },
  MUTATIONS: {
    UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
    GET_USER_RESPONSE: 'GET_USER_RESPONSE',
    RESET: 'RESET',
  },
}
