export const EVENT_TYPES = {
  MODAL: {
    TOPOLOGY: {
      CREATE: "MODAL_TOPOLOGY_CREATE",
      EDIT: "MODAL_TOPOLOGY_EDIT",
      DELETE: "MODAL_TOPOLOGY_DELETE",
      MOVE: "MODAL_TOPOLOGY_MOVE",
      RUN: "MODAL_TOPOLOGY_RUN",
      IMPORT: "MODAL_TOPOLOGY_IMPORT",
    },
    FOLDER: {
      CREATE: "MODAL_FOLDER_CREATE",
      EDIT: "MODAL_FOLDER_EDIT",
      DELETE: "MODAL_FOLDER_DELETE",
    },
    JWT_TOKEN: {
      CREATE: "MODAL_JWT_TOKEN_CREATE",
    },
  },
  SIDEBAR: {
    TOGGLE: "SIDEBAR_TOGGLE",
    OPEN: "SIDEBAR_OPEN",
  },
  EDITOR: {
    COMPARE_XML: "EDITOR_COMPARE_XML",
  },
}
