.base-influxdb:
  variables:
    DIR: influxdb
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}influxdb
  rules:
    - if: '$FORCE_PIPELINE =~ /ALL/ || $FORCE_PIPELINE =~ /influxdb/'
    - if: '$CI_COMMIT_BEFORE_SHA == $_BANNED_RUN_ALL_SHA'
      when: never
    - changes:
      - ${DIR}/**/*


influxdb:build:
  stage: build
  needs: []
  extends:
    - .base-kaniko-build
    - .base-influxdb
