services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesFramework\HbPFTableParserBundle\Controller\TableParserController:
        class: Hanaboso\PipesFramework\HbPFTableParserBundle\Controller\TableParserController
        arguments:
            - '@hbpf.parser.table.handler'
        calls:
            - ['setContainer', ['@service_container']]
