services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $tableParserHandler: '@hbpf.parser.table.handler'

    Hanaboso\PipesFramework\HbPFTableParserBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
