services:
    hbpf.parser.table.handler:
        class: Hanaboso\PipesFramework\HbPFTableParserBundle\Handler\TableParserHandler
        arguments:
            - Hanaboso\PipesFramework\Parser\TableParser
            - '@hbpf.file_storage'

    hbpf.parser.table.service:
        class: Hanaboso\PipesFramework\Parser\TableParser
        arguments:
