FROM dkr.hanaboso.net/hanaboso/php-base:php-7.3

ENV APP_ENV=prod
ENV APP_DEBUG=0

COPY ./ /var/www

RUN chown -R www-data:www-data /var

WORKDIR /var/www
ENV PHP_FPM_MAX_CHILDREN 10
ENV PHP_FPM_MAX_REQUESTS 500

CMD [ "php-w-nginx.sh" ]
