.base-starting-point:
  variables:
    DIR: starting-point
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}starting-point

starting-point:test:
  stage: test
  extends:
    - .base-test
    - .base-starting-point

starting-point:build:
  stage: build
  needs:
    - job: starting-point:test
      optional: false
  extends:
    - .base-dind-build
    - .base-starting-point
