---

version: '2'

services:
  pipes-api:
    image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /var/www/pipes/clients/demo/pipes-api
    environment:
      DEV_UID: ${DEV_UID}
      DEV_GID: ${DEV_GID}
    volumes:
      - ../../../:/var/www/pipes
      - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
      - ${HOME}/.composer:/srv/.composer
