---

version: '3.5'

services:
    app:
        image: hanabosocom/php-dev:php-8.2-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:8000:80
        working_dir: /var/www/pipes/clients/demo/pipes-api
        environment:
            PHP_WEBROOT: /var/www/pipes/clients/demo/pipes-api
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            MONGODB_DSN: mongodb://mongo
            MONGODB_DB: pipes
            METRICS_DSN: mongodb://mongo
            METRICS_DB: metrics
            COMPOSER_HOME: ${HOME}/dev/.composer
            KERNEL_CLASS: Demo\Kernel
            WORKER_API: https://test.com
            ORCHESTY_API_KEY: ${ORCHESTY_API_KEY}
        volumes:
            - ../../../:/var/www/pipes:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    mongo:
        image: mongo
