.base-applinth-marketplace-ui:
  variables:
    DIR: applinth-marketplace-ui
    IMAGE: ${REGISTRY}/${IMAGE_PREFIX}applinth-marketplace-ui

applinth-marketplace-ui:test:
  stage: test
  extends:
    - .base-test
    - .base-applinth-marketplace-ui

applinth-marketplace-ui:build:
  stage: build
  variables:
    MAKE_TARGET: rebuild
  needs:
    - job: applinth-marketplace-ui:test
      optional: false
  extends:
    - .base-dind-build
    - .base-applinth-marketplace-ui
