version: "3.5"
services:
  app:
    image: hanabosocom/php-dev:php-8.2-alpine
    user: ${DEV_UID}:${DEV_GID}
    ports:
      - ${DEV_IP}:80:80
    working_dir: /var/www/pipes/applinth
    volumes:
      - ../:/var/www/pipes:cached
      - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
    environment:
      APP_ENV: dev
      APP_DEBUG: "true"
      PHP_WEBROOT: /var/www/pipes/applinth/public
      DEV_UID: ${DEV_UID}
      DEV_GID: ${DEV_GID}
      KERNEL_CLASS: Hanaboso\Applinth\Kernel
      COMPOSER_HOME: ${HOME}/dev/.composer
      FRONTEND_URL: ${DEV_IP}
      BACKEND_URL: ${DEV_IP}
      MONGODB_DSN: mongodb://mongo
      MONGODB_DB: pipes
      METRICS_DSN: mongodb://mongo
      METRICS_DB: metrics
      CHECK_INFINITY_LOOP: "true"
      TOPOLOGY_API_DSN: topology-api:80
      STARTING_POINT_URL: starting-point:8080
      CRON_DSN: http://cron-api:8080
      JWT_KEY: BWoCz4gxw3YHDMkqE5HD1WT2u6zqIAtiJkYVyf6UucL4ZtbhhatQooP5IgTQRwowYR6z8wE3biqZTl37
      RABBITMQ_DSN: amqp://rabbitmq:5672
      DOCKER_PF_BRIDGE_IMAGE: orchesty/bridge:2.0.0
      EMAIL_DSN: smtp://mailhog:1025
      ALPHA_INSTANCE_ID: "demo"
      JWE_PRIVATE_KEY: |
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIAGmQ//yMnyMlFAN/E2yfZjzFL1ziTrAbDwa08KEPBq+NUWHvrxrs7
        f8tvm0y+PwcNgdKhSiMN/osY4/iK+vyr9WqgBwYFK4EEACOhgYkDgYYABABnJEkK
        knFnpxumSFk5MFIEYTm2ReaalO4UrCc4QROIchTIZYRb9GeSounARtxnJcfYa+CB
        pXzObmLNvN3u75L2pADOg4p+GkgwtFdfSa5HhMoQD2jEEmL3otvyjf8jF5t8u2YP
        GcXwowJ2vWSQ6pyW17FLVqmUy2ZW5VSowkPp29CvYQ==
        -----END EC PRIVATE KEY-----

  node-sdk:
    image: node-sdk:tag
    build: ../clients/demo/node-sdk/docker
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /var/www
    volumes:
      - ../clients/demo/node-sdk/:/var/www:cached
    environment:
      # Envs for tests are load from node-sdk/.jest/testEnvs.js
      JEST_DOCKER: 1
      APP_ENV: debug
      CRYPT_SECRET: ThisIsNotSoSecret
      BACKEND_URL: ${DEV_IP}
      STARTING_POINT_DSN: starting-point:8080
      WORKER_API_HOST: http://worker-api:8080
      ORCHESTY_API_KEY: ${ORCHESTY_API_KEY}
    command: sh -c 'pnpm run start'

  worker-api:
    image: worker-api:tag
    build: ./../worker-api/docker
    user: ${DEV_UID}:${DEV_GID}
    working_dir: /var/www
    volumes:
      - ./../worker-api:/var/www:cached
    environment:
      APP_ENV: "debug"
      MONGODB_DSN: mongodb://mongo/pipes
      FLUENTD_DSN: "fluentd:9880"
      TZ: "UTC"
    command: sh -c 'pnpm run start'

  mongo:
    image: mongo:latest
    ports:
      - ${DEV_IP}:27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo: {}
