monolog:
    use_microseconds: false
    channels: [commons]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [ "!event" ]