apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "instance-proxy.fullname" . }}
  labels:
    {{- include "instance-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "instance-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config:  {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "instance-proxy.selectorLabels" . | nindent 8 }}
    spec:
      # haproxy forks unprivileged processes
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: status
              containerPort: 8081
              protocol: TCP
            - name: ping
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ping
          readinessProbe:
            httpGet:
              path: /
              port: ping
          volumeMounts:
            - name: config
              subPath: haproxy.cfg
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "instance-proxy.fullname" . }}
