FROM hanabosocom/php-dev:php-7.4

RUN apt-get update && \
    apt-get install -y apt-transport-https && \
    apt-get clean

ENV APP_ENV=prod
ENV APP_DEBUG=0

COPY ./ /var/www/

WORKDIR /var/www
RUN mkdir /srv/topology && \
    chmod 0777 /srv/topology

RUN chown -R www-data:www-data ./var
