FROM hanabosocom/php-dev:php-7.4

ENV APP_ENV=prod
ENV APP_DEBUG=0

COPY ./ /var/www/

# WTF?
RUN mkdir /var/topology && \
    chmod 0777 /var/topology

RUN chown -R www-data:www-data /var
WORKDIR /var/www

ENV PHP_FPM_MAX_CHILDREN 10
ENV PHP_FPM_MAX_REQUESTS 500

CMD [ "php-w-nginx.sh" ]
