.base-docker-build:
  extends:
    - .base-dind

  variables:
    DIR: "PROVIDE-WHEN-EXTENDING"

  before_script:
    - !reference [.base-dind, before_script]
    - apk add --no-cache make
    - cd ${DIR}


.base-kaniko-build:
  needs:
    - collect-tags

  variables:
    DIR: "PROVIDE-WHEN-EXTENDING"
    IMAGE: "PROVIDE-WHEN-EXTENDING"

    # todo: determine default image
    KANIKO_IMAGE: ${REGISTRY}/kaniko-alpine:latest

  image:
    name: ${KANIKO_IMAGE}

    # this is required for :debug image and does not cause problems for our custom image
    entrypoint: ["sh", "-c"]

  before_script:
    - 'cd ${DIR} && echo "Working directory: ${DIR}"'
    - export TAG_BRANCH=${CI_COMMIT_REF_SLUG}
    - '[ -z "${NO_GIT}" ] && export TAG_DIR_CH=$(git log -1 --pretty=%h --abbrev=8 .)'
    - env | egrep "^(TAG_|IMAGE)"

    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{" > /kaniko/.docker/config.json
    - echo "\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}," >> /kaniko/.docker/config.json
    - echo "\"$RELEASE_REGISTRY_HOST\":{\"username\":\"$RELEASE_REGISTRY_USERNAME\",\"password\":\"$RELEASE_REGISTRY_PASSWORD\"}" >> /kaniko/.docker/config.json
    - echo "}}" >> /kaniko/.docker/config.json

  # feel free to override
  script:
    - executor --context . --destination ${IMAGE}:${TAG_DIR_CH} --destination ${IMAGE}:${TAG_BRANCH} --cache=true

  tags:
    - docker

.base-dummy-build:
  image: alpine
  script:
    - ': >>> DUMMY BUILD "OK" <<<'
  tags:
    - docker
