.base-dind-build:
  extends:
    - .base-dind

  variables:
    BUILDX_BUILDER: bob_the_builder
    MAKE_TARGET: build

    DIR: "PROVIDE-WHEN-EXTENDING"
    IMAGE: "PROVIDE-WHEN-EXTENDING"

  rules:
    - if: '$FORCE_PIPELINE == "ALL"'
      when: always

    - if: '$CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always

    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "ci" || $CI_COMMIT_REF_NAME == "app-ui-build"'
      changes:
        - "${DIR}/**/*"

    - when: never

  before_script:
    - !reference [ .base-dind, before_script ]
    - docker context create builders || true
    - docker buildx create --use --name $BUILDX_BUILDER || docker buildx use $BUILDX_BUILDER
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx inspect --bootstrap

  script:
    - 'cd ${DIR} && echo "Working directory: ${DIR}"'
    - make ${MAKE_TARGET} IMAGE=${IMAGE}:${DEFAULT_TAG}