.base-deploy:
  needs: ["collect-tags"]
  stage: deploy
  environment: stage
  image:
    name: alpine/helm
    entrypoint: [""]

  variables:
    HELM_DIR: ./helm

  script:
    - echo "${KUBECONFIG}" > /tmp/kubeconfig
    - chmod 0600 /tmp/kubeconfig

    - . ./export_tags
    - cd ${PROJECT_DIR}
    - helm repo add orchesty https://orchesty.github.io/helm-charts/
    - helm dependencies build ${HELM_DIR}
    - >-
      helm --kubeconfig /tmp/kubeconfig upgrade -i --wait --reset-values -f ${HELM_DIR}/resources.yaml ${HELM_ARGS} ${HELM_ARGS_EXT}
      pipes ${HELM_DIR}

  tags:
    - docker


.base-deploy-current:
  needs: ["collect-tags"]
  stage: deploy
  environment: stage

  image:
    name: alpine/helm
    entrypoint: [""]

  variables:
    HELM_DIR: ./helm

  script:
    - echo "${KUBECONFIG}" > /tmp/kubeconfig
    - chmod 0600 /tmp/kubeconfig

    - . ./export_tags
    - cp -a helm/charts/orchesty ${PROJECT_DIR}/${HELM_DIR}/charts/orchesty
    - cd ${PROJECT_DIR}
    - >-
      helm --kubeconfig /tmp/kubeconfig upgrade -i --wait --reset-values -f ${HELM_DIR}/resources.yaml ${HELM_ARGS}
      --set global.imageOverrides.applinth-marketplace-ui=${REGISTRY}/${IMAGE_PREFIX}applinth-marketplace-ui:${TAG_APPLINTH_MARKETPLACE_UI}
      --set global.imageOverrides.backend=${REGISTRY}/${IMAGE_PREFIX}backend:${TAG_BACKEND}
      --set global.imageOverrides.frontend=${REGISTRY}/${IMAGE_PREFIX}frontend:${TAG_FRONTEND}
      --set global.imageOverrides.cron-api=${REGISTRY}/${IMAGE_PREFIX}cron:${TAG_CRON}
      --set global.imageOverrides.bridge=${REGISTRY}/${IMAGE_PREFIX}bridge:${TAG_BRIDGE}
      --set global.imageOverrides.counter=${REGISTRY}/${IMAGE_PREFIX}counter:${TAG_COUNTER}
      --set global.imageOverrides.limiter=${REGISTRY}/limiter:${TAG_LIMITER}
      --set global.imageOverrides.starting-point=${REGISTRY}/${IMAGE_PREFIX}starting-point:${TAG_STARTING_POINT}
      --set global.imageOverrides.topology-api=${REGISTRY}/${IMAGE_PREFIX}topology-api:${TAG_TOPOLOGY_API}
      --set global.imageOverrides.fluentd=${REGISTRY}/${IMAGE_PREFIX}fluentd:${TAG_FLUENTD}
      --set global.imageOverrides.detector=${REGISTRY}/${IMAGE_PREFIX}detector:${TAG_DETECTOR}
      --set global.imageOverrides.worker-api=${REGISTRY}/${IMAGE_PREFIX}worker-api:${TAG_WORKER_API}
      ${HELM_ARGS_EXT}
      pipes ${HELM_DIR}

  tags:
    - docker


stage:deploy:
  extends: .base-deploy-current
  environment: stage
  variables:
    PROJECT_DIR: clients/demo
    HELM_ARGS: -f helm/values.stage.yaml

  rules:
    - when: manual


demo2:deploy:
  extends: .base-deploy-current
  environment: demo2
  variables:
    PROJECT_DIR: clients/demo
    HELM_ARGS: -f helm/values.demo2.yaml

  rules:
    - if: $DEPLOY_DEMO2_VERSION != ""
      when: always
    - when: manual

  before_script:
    - echo "${DEMO2_VALUES}" > clients/demo/helm/values.demo2.yaml
    - sed -E "s/VERSION_TAG/${DEPLOY_DEMO2_VERSION}/g" -i clients/demo/helm/values.demo2.yaml
