.base-deploy:
  stage: deploy
  environment: stage
  image:
    name: alpine/helm
    entrypoint: [""]

  variables:
    HELM_DIR: ./helm

  script:
    - echo "${KUBECONFIG}" > /tmp/kubeconfig
    - chmod 0600 /tmp/kubeconfig

    - . ./export_tags
    - cd ${PROJECT_DIR}
    - helm repo add orchesty https://orchesty.github.io/helm-charts/
    - helm dependencies build ${HELM_DIR}
    - >-
      helm --kubeconfig /tmp/kubeconfig upgrade -i --wait --reset-values -f ${HELM_DIR}/resources.yaml ${HELM_ARGS} ${HELM_ARGS_EXT}
      pipes ${HELM_DIR}

  tags:
    - docker


.base-deploy-current:
  stage: deploy
  environment: stage

  image:
    name: alpine/helm
    entrypoint: [""]

  variables:
    HELM_DIR: ./helm

  script:
    - echo "${KUBECONFIG}" > /tmp/kubeconfig
    - chmod 0600 /tmp/kubeconfig

    - . ./export_tags
    - cp -a helm/charts/orchesty ${PROJECT_DIR}/${HELM_DIR}/charts/orchesty
    - cd ${PROJECT_DIR}
    - >-
      helm --kubeconfig /tmp/kubeconfig upgrade -i --wait --reset-values -f ${HELM_DIR}/resources.yaml ${HELM_ARGS}
      --set global.imageOverrides.applinth-marketplace-ui=${REGISTRY}/${IMAGE_PREFIX}applinth-marketplace-ui:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.backend=${REGISTRY}/${IMAGE_PREFIX}backend:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.frontend=${REGISTRY}/${IMAGE_PREFIX}frontend:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.cron-api=${REGISTRY}/${IMAGE_PREFIX}cron:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.bridge=${REGISTRY}/${IMAGE_PREFIX}bridge:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.counter=${REGISTRY}/${IMAGE_PREFIX}counter:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.limiter=${REGISTRY}/limiter:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.starting-point=${REGISTRY}/${IMAGE_PREFIX}starting-point:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.topology-api=${REGISTRY}/${IMAGE_PREFIX}topology-api:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.fluentd=${REGISTRY}/${IMAGE_PREFIX}fluentd:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.detector=${REGISTRY}/${IMAGE_PREFIX}detector:${DEPLOY_DEMO_TAG}
      --set global.imageOverrides.worker-api=${REGISTRY}/${IMAGE_PREFIX}worker-api:${DEPLOY_DEMO_TAG}
      ${HELM_ARGS_EXT}
      pipes ${HELM_DIR}

  tags:
    - docker


stage:deploy:
  extends: .base-deploy-current
  environment: stage
  variables:
    PROJECT_DIR: clients/demo
    HELM_ARGS: -f helm/values.stage.yaml

  rules:
    - when: manual
