stages:
  - prepare
  - test
  - build
  - deploy
  - release
  - rel-x.y.z
  - rel-x.y

variables:
  DIND_IMAGE: "docker:28.0-cli"

  REGISTRY: "dkr.hanaboso.net/pipes/pipes"
  REGISTRY_RELEASE: "index.docker.io/orchesty"
  IMAGE_PREFIX: ""
  DEFAULT_TAG: "master"

  FORCE_PIPELINE:
    description: Force running pipeline for a subset of components or ALL of them
    value: ""

  DEPLOY_DEMO_TAG:
    description: Enter tag to deploy it to the demo environment.
    value: "master"

default:
  interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always

    - when: never

.base-dind:
  image: ${DIND_IMAGE}

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  services:
    - docker:28.0-dind

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - echo "$RELEASE_REGISTRY_PASSWORD" | docker login $RELEASE_REGISTRY_HOST --username $RELEASE_REGISTRY_USERNAME --password-stdin
    - mkdir -p apk
    - apk add --cache-dir apk curl bash git make docker-compose

  cache:
    key: "base-${CI_COMMIT_REF_SLUG}"
    paths:
      - apk
      - .pnpm-store

  tags:
    - dind

.base-tooling:
  image: ${REGISTRY}/ci-tooling:latest
  tags:
    - docker