stages:
  - prepare
  - build
  - test
  - review
  - deploy
  - release
  - rel-x.y.z
  - rel-x.y

variables:
  REGISTRY: "dkr.hanaboso.net/pipes/pipes"
  REGISTRY_RELEASE: "index.docker.io/orchesty"
  IMAGE_PREFIX: ""
  FORCE_PIPELINE:
    description: Force running pipeline for a subset of components or ALL of them
    value: ""

  DEPLOY_DEMO1_VERSION:
    description: Enter version [x.y.z] to deploy it to the demo1 environment.
    value: ""

  DEPLOY_DEMO2_VERSION:
    description: Enter version [x.y.z] to deploy it to the demo2 environment.
    value: ""

  DEPLOY_DEMO3_VERSION:
    description: Enter version [x.y.z] to deploy it to the demo3c environment.
    value: ""

  _BANNED_RUN_ALL_SHA: "0000000000000000000000000000000000000000"

default:
  interruptible: true

.base-dind:
  image: docker:28.0.4-alpine3.21

  variables:
    #DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_CERTDIR: ""
    #DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"
    #DOCKER_TLS_VERIFY: 1
    DOCKER_DRIVER: overlay2

  services:
    - docker:28.0.4-alpine3.21

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - echo "$RELEASE_REGISTRY_PASSWORD" | docker login $RELEASE_REGISTRY_HOST --username $RELEASE_REGISTRY_USERNAME --password-stdin

  tags:
    - dind


.base-tooling:
  image: ${REGISTRY}/ci-tooling:latest
  tags:
    - docker


collect-tags:
  stage: prepare
  image:
    name: alpine/git:latest
    entrypoint: ["sh", "-c"]

  script:
    - export TAG_APPLINTH_MARKETPLACE_UI=$(git log -1 --pretty=%h --abbrev=8 ./applinth-marketplace-ui)
    - export TAG_BACKEND=$(git log -1 --pretty=%h --abbrev=8 ./pf-bundles)
    - export TAG_FRONTEND=$(git log -1 --pretty=%h --abbrev=8 ./app-ui)
    - export TAG_CRON=$(git log -1 --pretty=%h --abbrev=8 ./cron)
    - export TAG_BRIDGE=$(git log -1 --pretty=%h --abbrev=8 ./bridge)
    - export TAG_COUNTER=$(git log -1 --pretty=%h --abbrev=8 ./counter)
    - export TAG_LIMITER=$(git log -1 --pretty=%h --abbrev=8 ./limiter)
    - export TAG_STARTING_POINT=$(git log -1 --pretty=%h --abbrev=8 ./starting-point)
    - export TAG_TOPOLOGY_API=$(git log -1 --pretty=%h --abbrev=8 ./topology-generator)
    - export TAG_FLUENTD=$(git log -1 --pretty=%h --abbrev=8 ./fluentd)
    - export TAG_DETECTOR=$(git log -1 --pretty=%h --abbrev=8 ./detector)
    - export TAG_WORKER_API=$(git log -1 --pretty=%h --abbrev=8 ./worker-api)

    - env | grep ^TAG_ | sed 's/.*/export &/' > export_tags
    - cat export_tags

  artifacts:
    expire_in: 1 month
    paths:
      - ./export_tags

  tags:
    - docker
