.base-go-test:
  extends:
    - .base-dind

  variables:
    MAKE_TARGET: ci-test

  before_script:
    - !reference [.base-dind, before_script]
    - mkdir -p /apk
    - apk add --cache-dir /apk git make docker-compose

  cache:
    key: "base-go-test-${CI_COMMIT_REF_SLUG}"
    paths:
      - /apk

  script:
    - 'cd ${DIR} && echo "Working directory: ${DIR}"'
    - export COMPOSE_PROJECT_NAME=$(echo ${CI_JOB_NAME} | tr ":" "-")_${CI_PIPELINE_ID}
    - export COMPOSE_FILE=docker-compose.ci.yml
    - make ${COMPOSE_FILE} ${MAKE_TARGET}
