include:
  - local: "/.gitlab/ci/essentials.gitlab-ci.yml"

workflow:
  rules:
    - when: always

.base-rel-x.y.z:
  stage: rel-x.y.z

  variables:
    RELEASE_IMAGE: OVERRIDE
    SRC_TAG: OVERRIDE
    GIT_STRATEGY: none

  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: ["sh", "-c"]

  script:
    - "DST_TAG=$(echo ${CI_COMMIT_REF_NAME} | sed -nE 's/v([0-9]+)\\.([0-9]+)\\.([0-9]+)/\\1.\\2.\\3/p')"
    - skopeo login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${REGISTRY}"
    - skopeo login --username "${RELEASE_REGISTRY_USERNAME}" --password "${RELEASE_REGISTRY_PASSWORD}" "$(echo $REGISTRY_RELEASE | sed -E 's|([^/]+).*|\1|')"
    - skopeo copy --multi-arch all docker://${REGISTRY}/${RELEASE_IMAGE}:${SRC_TAG} docker://${REGISTRY_RELEASE}/${RELEASE_IMAGE}:${DST_TAG}

  tags:
    - docker

.base-rel-x.y:
  stage: rel-x.y
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: ["sh", "-c"]

  variables:
    RELEASE_IMAGE: OVERRIDE
    SRC_TAG: OVERRIDE
    GIT_STRATEGY: none

  script:
    - "DST_TAG=$(echo ${CI_COMMIT_REF_NAME} | sed -nE 's/v([0-9]+)\\.([0-9]+)\\.[0-9]+/\\1.\\2/p')"
    - skopeo login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${REGISTRY}"
    - skopeo login --username "${RELEASE_REGISTRY_USERNAME}" --password "${RELEASE_REGISTRY_PASSWORD}" "$(echo $REGISTRY_RELEASE | sed -E 's|([^/]+).*|\1|')"
    - skopeo copy --multi-arch all docker://${REGISTRY}/${RELEASE_IMAGE}:${SRC_TAG} docker://${REGISTRY_RELEASE}/${RELEASE_IMAGE}:${DST_TAG}

  tags:
    - docker

## rel-x.y.z

backend:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}backend
    - export SRC_TAG=master

bridge:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}bridge
    - export SRC_TAG=master

counter:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}counter
    - export SRC_TAG=master

cron:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}cron
    - export SRC_TAG=master

detector:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}detector
    - export SRC_TAG=master

frontend:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}frontend
    - export SRC_TAG=master

limiter:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}limiter
    - export SRC_TAG=master

fluentd:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}fluentd
    - export SRC_TAG=master

starting-point:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}starting-point
    - export SRC_TAG=master

topology-api:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}topology-api
    - export SRC_TAG=master

worker-api:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}worker-api
    - export SRC_TAG=master

## rel-x.y

backend:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}backend
    - export SRC_TAG=master

bridge:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}bridge
    - export SRC_TAG=master

counter:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}counter
    - export SRC_TAG=master

cron:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}cron
    - export SRC_TAG=master

detector:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}detector
    - export SRC_TAG=master

frontend:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}frontend
    - export SRC_TAG=master

limiter:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}limiter
    - export SRC_TAG=master

fluentd:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}fluentd
    - export SRC_TAG=master

starting-point:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}starting-point
    - export SRC_TAG=master

topology-api:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}topology-api
    - export SRC_TAG=master

worker-api:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - export RELEASE_IMAGE=${IMAGE_PREFIX}worker-api
    - export SRC_TAG=master
