include:
  - local: "/.gitlab/ci/essentials.gitlab-ci.yml"

.base-rel-x.y.z:
  stage: rel-x.y.z
  needs:
    - collect-tags

  variables:
    RELEASE_IMAGE: OVERRIDE
    SRC_TAG: OVERRIDE
    GIT_STRATEGY: none

  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: ["sh", "-c"]

  script:
    - "DST_TAG=$(echo ${CI_COMMIT_REF_NAME} | sed -nE 's/v([0-9]+)\\.([0-9]+)\\.([0-9]+)/\\1.\\2.\\3/p')"
    - skopeo login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${REGISTRY}"
    - skopeo login --username "${RELEASE_REGISTRY_USERNAME}" --password "${RELEASE_REGISTRY_PASSWORD}" "$(echo $REGISTRY_RELEASE | sed -E 's|([^/]+).*|\1|')"
    - skopeo --multi-arch all copy docker://${REGISTRY}/${RELEASE_IMAGE}:${SRC_TAG} docker://${REGISTRY_RELEASE}/${RELEASE_IMAGE}:${DST_TAG}

  tags:
    - docker

.base-rel-x.y:
  stage: rel-x.y
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: ["sh", "-c"]

  variables:
    RELEASE_IMAGE: OVERRIDE
    SRC_TAG: OVERRIDE
    GIT_STRATEGY: none

  script:
    - "DST_TAG=$(echo ${CI_COMMIT_REF_NAME} | sed -nE 's/v([0-9]+)\\.([0-9]+)\\.[0-9]+/\\1.\\2/p')"
    - skopeo login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${REGISTRY}"
    - skopeo login --username "${RELEASE_REGISTRY_USERNAME}" --password "${RELEASE_REGISTRY_PASSWORD}" "$(echo $REGISTRY_RELEASE | sed -E 's|([^/]+).*|\1|')"
    - skopeo --multi-arch all copy docker://${REGISTRY}/${RELEASE_IMAGE}:${SRC_TAG} docker://${REGISTRY_RELEASE}/${RELEASE_IMAGE}:${DST_TAG}

  tags:
    - docker

## rel-x.y.z

backend:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}backend
    - export SRC_TAG=${TAG_BACKEND}

bridge:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}bridge
    - export SRC_TAG=${TAG_BRIDGE}

counter:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}counter
    - export SRC_TAG=${TAG_COUNTER}

cron:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}cron
    - export SRC_TAG=${TAG_CRON}

detector:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}detector
    - export SRC_TAG=${TAG_DETECTOR}

frontend:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}frontend
    - export SRC_TAG=${TAG_FRONTEND}

limiter:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}limiter
    - export SRC_TAG=${TAG_LIMITER}

fluentd:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}fluentd
    - export SRC_TAG=${TAG_FLUENTD}

starting-point:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}starting-point
    - export SRC_TAG=${TAG_STARTING_POINT}

topology-api:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}topology-api
    - export SRC_TAG=${TAG_TOPOLOGY_API}

worker-api:rel-x.y.z:
  extends: .base-rel-x.y.z
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}worker-api
    - export SRC_TAG=${TAG_WORKER_API}

## rel-x.y

backend:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}backend
    - export SRC_TAG=${TAG_BACKEND}

bridge:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}bridge
    - export SRC_TAG=${TAG_BRIDGE}

counter:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}counter
    - export SRC_TAG=${TAG_COUNTER}

cron:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}cron
    - export SRC_TAG=${TAG_CRON}

detector:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}detector
    - export SRC_TAG=${TAG_DETECTOR}

frontend:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}frontend
    - export SRC_TAG=${TAG_FRONTEND}

limiter:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}limiter
    - export SRC_TAG=${TAG_LIMITER}

fluentd:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}fluentd
    - export SRC_TAG=${TAG_FLUENTD}

starting-point:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}starting-point
    - export SRC_TAG=${TAG_STARTING_POINT}

topology-api:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}topology-api
    - export SRC_TAG=${TAG_TOPOLOGY_API}

worker-api:rel-x.y:
  extends: .base-rel-x.y
  before_script:
    - . ./export_tags
    - export RELEASE_IMAGE=${IMAGE_PREFIX}worker-api
    - export SRC_TAG=${TAG_WORKER_API}
