.base-test:
  extends:
    - .base-dind

  variables:
    MAKE_TARGET: ci-test

  rules:
    - if: '$FORCE_PIPELINE == "ALL"'
      when: always
    - changes:
        - "${DIR}/**/*"

  resource_group: ci-tests

  script:
    - 'cd ${DIR} && echo "Working directory: ${DIR}"'
    - export COMPOSE_PROJECT_NAME=$(echo ${CI_JOB_NAME} | tr ":" "-")_${CI_PIPELINE_ID}
    - export COMPOSE_FILE=docker-compose.ci.yml

    - make ${COMPOSE_FILE} ${MAKE_TARGET}
