export const GRID = {
  ACTIONS: {
    GRID_FETCH: 'GRID_FETCH',
    GRID_SEARCH: 'GRID_SEARCH',
    GRID_FILTER: 'GRID_FILTER',
    GRID_FILTER_RESET: 'GRID_FILTER_RESET',
    GRID_CHANGE_PAGING: 'GRID_CHANGE_PAGING',
    GRID_UPDATE_ROW: 'GRID_UPDATE_ROW',
    GRID_UPDATE_ROW_ITEM: 'GRID_UPDATE_ROW_ITEM',
    GRID_STATE_SAVE: 'GRID_FILTER_SAVE',
    GRID_HEADERS_SAVE: 'GRID_HEADERS_SAVE',
  },
  MUTATIONS: {
    GRID_RESPONSE: 'GRID_RESPONSE',
    GRID_UPDATE_ROW: 'GRID_UPDATE_ROW',
    GRID_UPDATE_ROW_ITEM: 'GRID_UPDATE_ROW_ITEM',
    UPDATE_QUICK_FILTER: 'UPDATE_QUICK_FILTER',
    SAVE_STATE: 'SAVE_STATE',
    SAVE_HEADERS: 'SAVE_HEADERS',
    RESET: 'RESET',
  },
}
