monolog:
    use_microseconds: false
    channels: [webhook_systems]
    handlers:
        webhook_systems:
            type: '%logger_handler%'
            path: '%kernel.logs_dir%/authorization_%kernel.environment%.log'
            level: info
            max_files: 10