services:
    clever_connectors.cron.get_system_callback:
        class: CleverConnectors\AppBundle\Command\GetSystemsCommand
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
        tags:
            -  { name: console.command }

    clever_connector.async_command_factory:
        class: CleverConnectors\AppBundle\Model\Command\AsyncCommandFactory
        arguments:
            - '%kernel.project_dir%'

    clever_connectors.cron.get_topology_callback:
            class: CleverConnectors\AppBundle\Command\GetTopologyCommand
            arguments:
                - '@doctrine.odm.mongodb.document_manager'
            tags:
                -  { name: console.command }